### ISSUE TITLE
Shaft under mushroom

### ISSUE THREAD

**Issue by KoenDG** [crawl/crawl#1000]
When reporting a bug, please include the following:

**PLATFORM:**
web

**VERSION:**
0.23

**DESCRIPTION:**
https://i.imgur.com/jIGWo7U.png

As you can see, in the spot of the bottom mushroom, there's a shaft as well. Seemed abnormal to me so reporting it.

**Comment by ebering** [comment]
This is permitted by dungeon generation, if a bit odd. Just think of it as a mushroom growing out of the side of the shaft.
