### ISSUE TITLE
Mutation potion applied and unapplied the same mutation

### ISSUE THREAD

**Issue by KoenDG** [crawl/crawl#1002]
**PLATFORM:**
webtiles, Paris server

**VERSION:**
0.23

**DESCRIPTION:**
I used a mutation potion and as part of its effects, it applied and unapplied the exact same mutation. Seems like a waste and illogical

https://imgur.com/a/zJWlPPe

So, in the same series of effects from 1 single potion, I was given brown scales and they were taken away again.

Seems like a completely wasted slot.

**Comment by KoenDG** [comment]
Happened again: https://i.imgur.com/au7gyB6.png

**Comment by alexjurkiewicz** [comment]
Currently this is 'as designed', in that a single mutation potion runs the
"mutate player" process several times independently. However I do agree
it's pretty boring.

**Comment by ebering** [comment]
This is working "as designed" but PRs improving mutation will be considered.
