### ISSUE TITLE
New standard game after dying in a seeded game uses that same seed

### ISSUE THREAD

**Issue by hbent** [crawl/crawl#1010]
When reporting a bug, please include the following:

**PLATFORM:**
Linux, local tiles

**VERSION:**
0.24-a0-181-gd121a6d4c0

**DESCRIPTION:**
Start a seeded game (I was using today's seed).  Die.  Go back to the main menu and start a standard game.  The dungeon will be the same as the seeded game.  I was using pregenerated levels in the seeded game, if that matters.

**Comment by rawlins** [comment]
Thanks for the report, I actually just fixed this today: https://github.com/crawl/crawl/commit/c7eaa0789552f2bd8694c2a2d9db22e00f74e243

(But I hadn't gotten any reports on this yet, so I think you are the first one to notice.)

**Comment by hbent** [comment]
Ha, thanks!
