### ISSUE TITLE
LUA api gap: cannot memorise spells

### ISSUE THREAD

**Issue by rudi-cilibrasi** [crawl/crawl#1028]
When using the LUA interface (such as elliptic's "qw" bot), it seems that there is no way to memorise a spell. I have tried using the qw function `magic` as well as crawl builtins but no luck.
```
    magic("May"), magic("MaY"),
    crawl.do_commands({"CMD_MEMORISE_SPELL"})
    crawl.sendkeys("a","y")
```

Can you please provide an example of how to memorise a spell in Lua so that bots can start to access the caster side of the game?

When reporting a bug, please include the following:

**PLATFORM:**
console

**VERSION:**
0.23
**DESCRIPTION:**
Tried to access caster spell memorisation system, pored through LUA docs, eventually gave up.
Wondering if it's an API gap or if it's easy to make an example of how to memorise any spell from a spell book for any caster class.

Thanks for any info you can provide.

**Comment by rawlins** [comment]
When I include the following minimal working example in my rc file, the char tries to memorize the spell on `a` every turn (there is an API for seeing what letter spells are, via `you.mem_spells` and `you.spell_table`):

```
{
-- this is qw's `magic` function
function magic(command)
  crawl.process_keys(command .. string.char(27) .. string.char(27) ..
                     string.char(27))
end
function ready()
    magic("May")
    --crawl.process_keys("May") -- also works, `magic`'s escs are just for safety
end
}
```

So I suspect there might be something else going on your specific lua code.

(It probably would be a good addition to the lua API to do this all by spell name without having to figure out the right letter, though.)

**Comment by rudi-cilibrasi** [comment]
Thank you for the response. Yes I was able to modify elliptic qw to memorise a spell also after 1000 turns however it required me to turn the "automatic" flag off and after that I could never get it to turn back on again so the bot was stuck. I agree considering your working example and my example it seems like it's technically possible. I also agree with your assessment that the API is inconvenient as it stands. I think a spell name based API is a great idea. Another simple hook I think could be highly useful for a lot of this stuff to simply it instead of multiplexing the `ready` hook how would you feel about a new `on_level_up` hook? that way people can easily just try to do the spell memorisation from there what do you think @rawlins  ? in any case i did manage to memorize the spell but i can't seem to get the ready() hook to keep regularly triggering after that one successful memorization. if i keep having trouble after comparing against your example (mine is similar) then I will post the minimize patch against elliptic for further examination.

**Comment by rudi-cilibrasi** [comment]
finally did get it working to make the bot keep going and can now get a Fire Mage to learn + use Fireball or Venom Mage to learn + use Venom Bolt so API is complete but inconvenient as you expected. Thanks for the help. -r
