### ISSUE TITLE
The source code doesn't work!

### ISSUE THREAD

**Issue by TanisTheRed** [crawl/crawl#1056]
When reporting a bug, please include the following:

**PLATFORM:**
crawl and dat.  It claims you can compile with MVS and I have done 2012-2019 and none work. 

**VERSION:**
master branch and any others to be honest (I tried 20 versions)

**DESCRIPTION:**
You download the source code and doesn't matter what you alter or change the code will not compile.  Crawl and dat are missing files to start with I had to find on other repositories.  The code is broken and there are no instructions that actually get it to compile and run at all.  So don't waste your  time with this as it is a piece of junk that is poorly managed and should be deleted!

**Update**
I found the latest INSTALL.txt file and it fails and here are the specific steps for those who claim it works but it doesn't!

  `git submodule update --init` fails to get any files.  I was able to find the files in a old repository or another crawl.

trying to build crawl generates many many many errors:
1.) Some were linking that I had to update the project properties to point to the includes and libraries (but I was able to solve that).
2.) Quite a few files are marked for include but are non-exsistant.  I found a few in the same repository from above.
3.) #include "tiledef-floor.h"
#include "tiledef-wall.h"
#include "tiledef-feat.h"
Those are no where to be found and are currently the main thing that is preventing anything to compile.

as well as these:
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1392	dllexport/dllimport requires external linkage	crawl	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.20.27508\include\xtgmath.h	177	

So even though they say it should work it does not probably because whoever was testing it didn't actually upload all the changes needed.  So once again don't waste your time as it won't actually work.

**Comment by rawlins** [comment]
I'm going to close this as it doesn't seem to be opened with the intention of productively communicating ("a piece of junk that is poorly managed and should be deleted", really?); the MSVC build process is community contributed and we can't really support it, though we will happily take fixes. The officially supported windows build process is via MSYS2 as described in INSTALL.txt.

I'm also just going to mention that if `git submodule update --init` doesn't work, then there's something fairly fundamentally gone wrong from the start, perhaps with the installation of git, or possibly with how the repository was downloaded.

**Comment by TanisTheRed** [comment]
This is why nothing works, people like you just close any complaints or issues at all.  I put in the exact steps and examples and you don't even try to help you just close it and ignore it.  That is exactly why it is poorly managed!!!!!

________________________________

**Comment by rawlins** [comment]
You didn't give remotely enough information to diagnose anything, and you were abusive while doing it. If you continue to behave abusively towards community members or developers, you will be blocked from posting in crawl repositories.
