### ISSUE TITLE
`git submodule update --init` doesn't work

### ISSUE THREAD

**Issue by TanisTheRed** [crawl/crawl#1060]
When reporting a bug, please include the following:

**PLATFORM:**
doesn't matter

**VERSION:**
master or any

**DESCRIPTION:**
command fails.  Any info?

**Comment by rawlins** [comment]
This isn't enough information to diagnose anything, and this also isn't really even a crawl-specific question. I suggest you start with google / github docs: [https://www.google.com/search?q=git+submodule+update+not+working](https://www.google.com/search?q=git+submodule+update+not+working).

**Comment by TanisTheRed** [comment]
Its ins your instructions so yes it is a crawl specific questions because its your specific instructions.

**Comment by rawlins** [comment]
`git submodule update --init` is a standard git command, there's nothing crawl-speecific about our usage of it. This is not a place to get help on git.

**Comment by TanisTheRed** [comment]
yes your right it is if the repository is setup correctly which it isn't!

________________________________

**Comment by alexjurkiewicz** [comment]
Also, there are specific instructions here: https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.txt#L55:

```
And then to get the contributing libraries, enter the newly cloned repository
via 'cd crawl' and type:

    git submodule update --init
```
