### ISSUE TITLE
All subfolders under contrib are empty?

### ISSUE THREAD

**Issue by TanisTheRed** [crawl/crawl#1061]
When reporting a bug, please include the following:

**PLATFORM:**
all

**VERSION:**
master

**DESCRIPTION:**
Where are the files?

**Comment by rawlins** [comment]
This is because git submodule update didn't work. Please stop spamming our repo.

**Comment by TanisTheRed** [comment]
Answer the questions and update your install guide and I won't have to post these questions.

________________________________

**Comment by ebering** [comment]
I've blocked this user for 7 days for consistently opening unhelpful and abusive issues. If at that time they persist the block will be made indefinite.
