### ISSUE TITLE
Invalid json generated in webtiles "ui-stack" object

### ISSUE THREAD

**Issue by golmman** [crawl/crawl#1065]
**PLATFORM:**
webtiles

**VERSION:**
0.24-a0-227-g1a43be2006

**DESCRIPTION:**
https://github.com/crawl/crawl/blob/master/crawl-ref/source/tileweb.cc#L1809
produces invalid json as it always adds an incorrect trailing comma after the last array element.

**Comment by rawlins** [comment]
Thanks for the report!
