### ISSUE TITLE
nemelex twister pulls monsters out of ghost vault

### ISSUE THREAD

**Issue by anderspapitto** [crawl/crawl#1077]
I got a twister from a deck of destruction near an unopened ghost vault, which has a couple transparent stone walls. Through one of those walls I can see that the twister extends into the vault, and the monsters are now outside with me.

The twister should probably be blocked by transparent rock walls.

on webtiles, version is:

```
Game started: 0.24-a0-382-g8e86157
0.24-a0-400-g86696ef
```

**Comment by ebering** [comment]
I can't be 100% sure but I think that this was `ebering_ghost_funeral_grove` which places trees. Tornado destroys trees, cracking open the ghost vault.
