### ISSUE TITLE
Different mutations for DS wanderers vs other backgrounds

### ISSUE THREAD

**Issue by kitchendrink** [crawl/crawl#1085]
When reporting a bug, please include the following:

**PLATFORM:**
console

**VERSION:**
0.24-a0-411-g4df2b1290f

I recall the same thing happening in other versions as well

**DESCRIPTION:**
Demonspawn mutations seem constant based on the seed for all backgrounds except wanderer, which ends up with a different mutation set. Not sure if this is working as intended or a bug

**Comment by rawlins** [comment]
Thanks for the report; this is already fixed in the incremental_pregen branch (https://github.com/crawl/crawl/commit/38f3c1a516ae, though this link won't be stable if the branch gets rebased) and will be fixed in master once this branch is merged.

**Comment by rawlins** [comment]
(this branch is now merged)
