### ISSUE TITLE
Build on macos

### ISSUE THREAD

**Issue by goslingwan** [crawl/crawl#1115]
How to successfully compile in mac? I have encountered a lot of problems and solved one after another.
I think the project is old?

**Comment by rawlins** [comment]
>How to successfully compile in mac? I have encountered a lot of problems and solved one after another.

DCSS compiles out of the box on OS X, but we would need more information than this to know what advice to give. Have you looked at the instructions in [INSTALL.txt](https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.txt)?

**Comment by goslingwan** [comment]
thx, compiled successfully on MSVC.

In the Xcode, some problems:
 like SDL Project path is change to SDL2.
 like SDL_image Project path is change to SDL2_image.

**Comment by rawlins** [comment]
Ok, I see. Building with XCode is not actually supported; DCSS builds at the command line on OS X.
