### ISSUE TITLE
Outdated things in the help

### ISSUE THREAD

**Issue by Wuzzy2** [crawl/crawl#1125]
**PLATFORM:**
"local tiles"

**VERSION:**
0.23.2

**DESCRIPTION:**
I recently re-read the help and noticed a couple of things have become outdated. Probably someone forgot to update the help.

* Wands: The section about wands still claims that wands need to be identified with scrolls of identify. It also claims that “unidentified” wands take more than 1 use. There are some other false (outdated) claims in this section. Best to rewrite the section completely.
* Religion: This section mentions the “p”ray key for Fedhas but I think its no longer used since a while
* Items: The entry on books mentions the “r”ead key but books can not be read with “r” anymore

**Comment by theJollySin** [comment]
Assign this one to me, and I'll take a crack at it?

**Comment by rawlins** [comment]
@theJollySin we don't really bother with the "assignment" feature of github, but PRs are open and documentation ones usually do get merged fairly quickly, so definitely feel free to submit a PR that fixes these.

**Comment by theJollySin** [comment]
@rawlins Actually, all of three of the above issues with the help menu have been fixed already.

https://github.com/crawl/crawl/blob/master/crawl-ref/docs/crawl_manual.rst

This ticket can be closed.

**Comment by Wuzzy2** [comment]
OK, in the linked file, the first 2 issues are indeed fixed, but not the third one.

> : 	spellbooks 	(use 'r'ead and 'M'emorise and 'z'ap)

**Comment by theJollySin** [comment]
@rawlins Ah! It looks like the changes to spellbooks were made in some places, but not others. I removed the "r" for "read spellbook" command from two places in the documentation.

There is a PR open here:

https://github.com/crawl/crawl/pull/1147

**Comment by theJollySin** [comment]
I believe this issue can be closed, as it was solved by Pull Request number 1147.
