### ISSUE TITLE
Incorrect/misleading auto-inscription of Staff of Olgreb

### ISSUE THREAD

**Issue by Wuzzy2** [crawl/crawl#1127]
**PLATFORM:**
"local tiles"

**VERSION:**
0.23.2

**DESCRIPTION:**
The +9 Staff of Olgreb (not sure about its name) is an unrandart that grants you *immunity* to poison and makes poison attacks. However it carries the auto-inscription “rPois”. This is incorrect/misleading as “rPois” is usually used for resistance to poison, not immunity to poison, which are not the same thing.

For a fix, I recommend to change the auto-inscription to “rPois∞”.

I don't know if other artifacts are affected by this as well.

**Comment by ebering** [comment]
Fixed in e7e91ba
