### ISSUE TITLE
Crash when entering Depths from D:27

### ISSUE THREAD

**Issue by ghost** [crawl/crawl#1128]
**PLATFORM:**
local tiles

**VERSION:**
0.23.2

**DESCRIPTION:**
Beginning a save before the Depths were added, but not entering D:27 has a variety of effects. Entering D:27 in any version after 0.13 creates a set of stairs to the Depths. In version 0.14 and 0.15, these stairs are a mimic monster. In 0.16, these stairs are a mimic that vanishes in smoke. In 0.17 and later, these stairs are actual stairs that take the player to the Depths, but doing so causes a crash.

Crash log:
[crash-Tester-20190805-041221.txt](https://github.com/crawl/crawl/files/3465161/crash-Tester-20190805-041221.txt)

Save file:
(github wouldn't let me upload this)
https://gofile.io/?c=y5s2tl

**Comment by rawlins** [comment]
I've tested this bug out on a 0.11 game upgraded to current trunk (0.29), and while I can't say there are no issues at all, this specific crash doesn't happen. So I'm going to go ahead and close this.
