### ISSUE TITLE
0.23.1-2 crashes on start

### ISSUE THREAD

**Issue by wilkowy** [crawl/crawl#1129]
0.23.1-2 crashes on start, 0.23.0 is fine

0.23.1
```
AppName: crawl-tiles.exe	 AppVer: 0.0.0.0	 ModName: crawl-tiles.exe
ModVer: 0.0.0.0	 Offset: 00a2dbab
```
```
AppName: crawl-console.exe	 AppVer: 0.0.0.0	 ModName: crawl-console.exe
ModVer: 0.0.0.0	 Offset: 008ef46b
```
0.23.2
```
AppName: crawl-tiles.exe	 AppVer: 0.0.0.0	 ModName: crawl-tiles.exe
ModVer: 0.0.0.0	 Offset: 00a463f5
```
```
AppName: crawl-console.exe	 AppVer: 0.0.0.0	 ModName: crawl-console.exe
ModVer: 0.0.0.0	 Offset: 0090a035
```

Windows XP SP3 32b with "ancient" CPU. I suspect game was compiled with SSE2.

**Comment by rawlins** [comment]
> I suspect game was compiled with SSE2.

Yes, windows builds since 0.23.1 are compiled with SSE2; x87 is not supported any more. You  can see some of the motivations for this change here: https://github.com/crawl/crawl/commit/49d9ff80d89e

Can you clarify the context in which you are still using XP / x87? I realize there are parts of the world where this is still common but we decided on this change for the official builds given that XP has been end-of-lifed and is quite rare in general -- and all more recent windows versions do entail at least SSE2.

Do you have the capability to build dcss yourself? It is easy to modify it to build without forcing SSE, but seeding will not work.  (Remove the `FORCE_SSE=y` arguments to the build parameters seen in the above commit.)

**Comment by wilkowy** [comment]
I see 0 premises to use SSE2 in this game. This is not a 3D HD 4K xD game and it does not compute millions of calculations per movement (not to mention an idle time). I can run Freespace, Homeworld, Morrowind and tons of other games without problems, but not dcss. ;-)

**Comment by wilkowy** [comment]
BTW. If it is really needed (but it's not or can be fixed by using correct compiling flags) than such breaking changes IMO should be introduced on a new feature branch version (like 0.24 or further) not in the bug fix one.

**Comment by rawlins** [comment]
> I see 0 premises to use SSE2 in this game. 

SSE is needed for stable floating point calculations on x86/amd devices, nothing to do with 3d graphics; there is extensive discussion and several links in the commit I already linked to.

Again, can you clarify the context in which you are still using XP / x87? The install rate for XP in 2019 is reportedly about 1.65%, which provides an *upper* bound for extant windows devices that don't support SSE, so we didn't consider this a breaking change.

**Comment by wilkowy** [comment]
The issues with precision are well known for decades. Using the correct compiler switches or `long double` or `volatile` for specific computations solves the problem of invalid optimizations (the computations are ok, it's the fault of optimizations breaking precision, because internal calculations are always on 80 bits). The given above link links to https://yosefk.com/blog/consistency-how-to-defeat-the-purpose-of-ieee-floating-point.html which describes how to deal with such nuisances.

Maybe the solution could be to deploy modular installer with fancy SSE2 version and second one for older CPUs (plain SSE covers only 32b singles) so both parties can be happy?

Because it still works, until it blows. (btw. WinXP supports processors with SSE2, sadly AthlonXP does not have them)

**Comment by ebering** [comment]
As we've stuck with SSE2 for 0.24 and this is the single user for whom this is a breaking change I'm going to close this issue. If a PR arrives making stable seeding not rely on SSE2 or adding a modular installer to the build process we'll certainly consider it, but at this time we won't be acting on this.

Indeed, the article that you linked to clarify how to work around the issues with x87 consistency says "So you can automatically sanitize all the mess as follows: 1. If you have SSE2, use it and live happily ever after."
