### ISSUE TITLE
Invisible sprites [Webtiles]

### ISSUE THREAD

**Issue by Sumorb** [crawl/crawl#1139]
Version history for game:
Started: 0.24-a0-549-g45f0056
0.24-a0-580-g6a6c3f8

After update, all preexisting and new trunk games no longer display sprites.  The player character, mobs, and loot are all visibly missing from the map, though they functionally still exist.  I can move around and get attacked by mobs, but only the mobs' status symbols appear (eg the question mark on a mob that hasn't noticed me).  I tried turning layers on and off, and restarting my computer and browser, but to no avail.

**Comment by rawlins** [comment]
We will need more information to diagnose this, at the least: What server, what username on the server? Does spectating work / do spectators see the same thing as you? What is your browser / os? Have you tried other browsers?

**Comment by Sumorb** [comment]
Hello,

I have the following accounts on akrasiac: Bromus, Sumorb, and Manihot.
They all experience the same issue.  Manihot I started as a new account/new
game to see if that would clear anything up (still no sprites).  I can
spectate others' trunk games, and while it is clear that other players are
interacting with the map just fine, I still can't see anything.  This is
only an issue for trunk.  Stable versions display correctly. I haven't
tried having someone else spectate my game.  I'm running something like
Windows 7, Firefox.  I just tried logging in on my work computer (MacOSX
10.11.6) with Firefox, and trunk displays correctly.  I'll try switching
browsers when I get home from work this evening.

Thanks for your help.

**Comment by Sumorb** [comment]
Hello,

Wanted to let you know that the most recent update to trunk solved my issue.

Thanks again!

**Comment by rawlins** [comment]
Ok, great, thanks for the update. FWIW I suspect this could have been a browser cache issue -- I asked around in discord on Thursday and it didn't seem like others with similar OS / browser combos were having issues. If it does happen again feel free to reopen but I would recommend first just trying a different browser to eliminate that possibility.
