### ISSUE TITLE
libretro core fails to compile on ARM64

### ISSUE THREAD

**Issue by jet082** [crawl/crawl#1144]
To fix this, do the following:

1) In ``crawl-ref/Makefile.libretro`` (in the ios section obviously)

```
Add

CFLAGS += -Wno-error=implicit-function-declaration

----

Change armv7 to arm64

----

Add -DIOS to COMMONFLAGS
```

2) Edit ``crawl-ref/source/contrib/lua/src/loslib.c`` and comment out the line ``lua_pushinteger(L, system(luaL_optstring(L, 1, NULL)));`` and add a line that says ``lua_pushnil(L);``

3) Copy the version of libco from https://github.com/libretro/libretro-common/tree/master/libco and overwrite the version in ``crawl-ref/libretro/libco/``

4) Copy the files https://github.com/libretro/libretro-common/blob/master/include/retro_common_api.h and https://github.com/libretro/libretro-common/blob/master/include/libco.h into ``crawl-ref/libretro/libco/``

Now, to play, use the instructions here: https://docs.libretro.com/library/stone_soup/ but also ensure you also have the directories ``morgue``, ``saves``, ``saves/db``, ``saves/sprint``, and ``saves/db`` created before you load ``game.crawlrc`` (I started a game on the windows version, then just copied everything over)

**Comment by rawlins** [comment]
This appears to be aimed at some kind of downstream packaging (perhaps https://github.com/libretro/libretro-meta/issues, though I'm not entirely sure), not at this repository.

**Comment by jet082** [comment]
It's actually this github - https://github.com/libretro/crawl-ref

However, I can't submit issues to it. I was kinda hoping you had some connection to the libretro core. Dang... I'll try libretro-meta.

**Comment by rawlins** [comment]
nope, no connection. FWIW current crawl itself should compile fine on ARM64, though I'm not sure how widely tested the result is; [see debian arm64 build](https://buildd.debian.org/status/package.php?p=crawl&suite=unstable).

**Comment by jet082** [comment]
I have updated the build instructions. I can confirm the core works on iOS now. Touch controls work great :)

![IMG_0046](https://user-images.githubusercontent.com/46708077/66638007-2511b600-ec4f-11e9-8ec5-f4d5e716e4bd.PNG)

**Comment by jet082** [comment]
Fixed by https://github.com/libretro/crawl-ref/commit/cc2530f377a3a5d686d4b6a360d88b01de0fbc59
