### ISSUE TITLE
Sporulate - No Description

### ISSUE THREAD

**Issue by Rydian** [crawl/crawl#1170]
**PLATFORM:**
Webtiles

**VERSION:**
0.24-a0-769-g368c164

**DESCRIPTION:**
With the Fedhas rework, use Grow Ballistomycete successfully and then examine the first ability it has.

Screenshot: https://i.imgur.com/yI3nVV4.png

**Comment by gammafunk** [comment]
Fixed in ac51ba0f9b, thanks.
