### ISSUE TITLE
Naga/centuar rolls are (maybe) wrong

### ISSUE THREAD

**Issue by createyourpersonalaccount** [crawl/crawl#1171]
VERSION: latest

I have noticed in `_acquirement_armour_` function of `acquire.cc` that it claims nagas and centaurs acquire bardings more often if they haven't seen them. Inspection of the code makes me think the opposite is true. Witness the following line:

```text
if (one_chance_in(you.seen_armour[bard] ? 4 : 2))
            return EQ_BOOTS;`
```

After that line, the normal roll proceeds. It appears that *if* I have seen the barding, it's a 1/4 chance I get boots in the extra roll. If I have not seen the barding, it's a 1/2 chance I get boots (so, higher chance to get boots if I haven't seen the barding)

Please let me know if asking for this bug is ok here (or what the preferred method is). thank you

**Comment by createyourpersonalaccount** [comment]
Correction, `_acquirement_armour_slot`  is the function.

**Comment by escondida** [comment]
Having a one in two chance to receive the barding (the chance if you haven't seen one) is better than a one in four chance (the chance if you have seen one), which matches the intent to receive bardings more often if you haven't seen them. (Assuming that for nagas and centaurs, "boots" translates to "barding" in the code).

**Comment by createyourpersonalaccount** [comment]
Thank you, of course they are boots! I don't know why I thought bardings were armour.
