### ISSUE TITLE
console -- screen clears immediately on death

### ISSUE THREAD

**Issue by hymie0** [crawl/crawl#1197]
When reporting a bug, please include the following:

**PLATFORM:**
console

**VERSION:**
0.25-a0-73-g9796ba8

**DESCRIPTION:**
As soon as my character dies, the screen immediately clears, before I can even see the "You have died" message.  It was working in 0.25-a0-72-g6cdc7bc , but then broke in 0.25-a0-73-g9796ba8

I'm sorry, I cannot access the new site. I know you prefer bug reports to be submitted there.  This is the best I can do.

**Comment by rawlins** [comment]
> I'm sorry, I cannot access the new site. I know you prefer bug reports to be submitted there. This is the best I can do.

Thanks for the report, submitting bugs here (especially while mantis registration is closed) is fine.

**Comment by rawlins** [comment]
I think this got fixed in 177707934, and it's gone in my testing on mac local console; can you confirm if you're still seeing this?

**Comment by hymie0** [comment]
Yes, this appears to have been fixed.

Thank you to whomever took care of this.

--hymie0

**Comment by rawlins** [comment]
Great, thanks for the update.
