### ISSUE TITLE
[0.24] Crash using step from time on Zot5 (twice)

### ISSUE THREAD

**Issue by ezmonkey4** [crawl/crawl#1205]
webtiles
0.24.0-1-gfbc8707

On Zot 5 I used step from time and the game "froze" after a while it reported 100% CPU and a crash. I explored the level again and did it again. I tried one time later away from enemies and I got not crash.

I was recording at the time, so I have it saved on youtube. 
https://youtu.be/LUZFOOd0SZs

**Comment by rawlins** [comment]
Thanks for the report; this seems to have resulted simply from SfT running very slowly under certain circumstances, and tripping CAO's stuck process detector. There may be exact circumstances that we couldn't replicate (and would need a savefile for), but I did a bunch of profiling + a series of commits that will hopefully speed up SfT (and monster movement) substantially across the board: d1d2e81a, 282e4f85, 166592d, 53d2a09, 94313f71d, ca9b790695f0. Mostly testing in Vaults:5 where it was reliably bad.
