### ISSUE TITLE
Crash clicking to move to a piece of unreachable terrain

### ISSUE THREAD

**Issue by hbent** [crawl/crawl#1210]
When reporting a bug, please include the following:

**PLATFORM:**
local tiles

**VERSION:**
0.25-a0-163-g00f8f0cddd

**DESCRIPTION:**
Had just killed an unreachable orc wizard, was using mouseover to see what he had dropped and accidentally left clicked as if I wanted to move there.

[crash-Bigaheq Xybu-20191122-164040.txt](https://github.com/crawl/crawl/files/3881567/crash-Bigaheq.Xybu-20191122-164040.txt)

[BigaheqXybu.cs.gz](https://github.com/crawl/crawl/files/3881571/BigaheqXybu.cs.gz)

**Comment by rawlins** [comment]
Thanks for the report; I marked this as closed but the bug I fixed wasn't exactly as described -- it seems that local tiles was crashing on *any* right click (...). I couldn't get it to crash on a left click with your save, though. So feel free to reopen if I've gotten it wrong or just failed to replicate a separate bug.
