### ISSUE TITLE
lua console can cause save break

### ISSUE THREAD

**Issue by Highseekerz** [crawl/crawl#1218]
**PLATFORM and OS or BROWSER:**
Chrome Version 78.0.3904.108 (Official Build) (32-bit)
CWZ server webtiles

**DCSS VERSION:**
0.25-a0-57-ga0c9b72

**DESCRIPTION:**
open lua console, press previous page button, wait a sec, refresh the page
then you'll move to lobby and your game will roll back to latest save

**EXTRA FILES:**
i got amulet of faith on the start
![image](https://user-images.githubusercontent.com/24786276/69938404-96b80300-1520-11ea-9334-fb91ee003c22.png)

and then i opened lua console and press previous page button
![image](https://user-images.githubusercontent.com/24786276/69938429-a6374c00-1520-11ea-8d14-61de55e43465.png)

after that i rejoined the game and my saves rolled back to 0 turn
![image](https://user-images.githubusercontent.com/24786276/69938514-dd0d6200-1520-11ea-9d06-03557933a4f4.png)

of course i got amulet of faith again
![image](https://user-images.githubusercontent.com/24786276/69938556-fa423080-1520-11ea-931e-fae52785e8dd.png)

*If this is an online game, see [these instructions](https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup)
for more information on how to make a save backup; you can provide the
resulting link here.*

**Comment by rawlins** [comment]
Thanks for the detailed report; I have hopefully fixed this in https://github.com/crawl/crawl/commit/28950d1e3277c9363f914e90e2e9ef2b59c677d1
