### ISSUE TITLE
Can't bind numpad-zero key

### ISSUE THREAD

**Issue by Lycowolf** [crawl/crawl#1228]
**PLATFORM and OS or BROWSER:**
local tiles, Windows 7 czech language mutation

**DCSS VERSION:**
crawl_tiles-0.25-a0-277-g7044ed1

**DESCRIPTION:**
I have following statements in my init.txt:
```
bindkey = [0] CMD_EXPLORE
#bindkey = [,] CMD_EXPLORE
bindkey = [-] CMD_GO_UPSTAIRS
bindkey = [+] CMD_GO_DOWNSTAIRS
```

When I press zero on my numpad (usual keyboard, nothing fancy), I get "Number of times to repeat, then command key:" prompt instead of autoexplore. 

Startup log shows the config file is parsed. Help screen shows zero as autoexplore key, confirming it.

When I uncomment the comma key inding and press dot on numpad (my locale uses comma to delimit decimal numbers, and Windows un/helpfully map numpad dot to comma), it autoexplores. The plus and minus keys work as intended on numpad too.

This config worked on 0.23 just fine.

If the binding should be defined any other way (unicode characters? escape sequences?), please provide a way to discover correct config stanza. (This could be a good idea anyway - some kind of ingame keymap editor?)

**Comment by rawlins** [comment]
I haven't tried to verify this yet but numpad handling remains a mess, so it seems plausible. (Sometimes toggling numlock can be a workaround for these issues.)

**Comment by Goratrix** [comment]
I remember this being discussed in Discord, and yes, the numpad numbers don't work with bindkey. The actual `bindkey [0]` command works fine for the normal zero key on the keyboard (not numpad). And the non-number numpad keys work fine too. It's only the numpad numbers that don't work. When I try to macro the numpad zero key, the character is `\{-250}`, so maybe doing it via macro instead of keybind could work?

**Comment by Lycowolf** [comment]
Yeah, I am currently working around this using macro, this works (macro.txt):

```
K:\{-250}
A:o
```

but it isn't pretty :-(

**Comment by Goratrix** [comment]
I think the hardcoding happens here? Both SDLK_KP_0 and SDLK_INSERT keycodes are mapped to return CK_INSERT (and same for all the other numpad keys):

https://github.com/crawl/crawl/blob/364e023d31220b1fa73ffd44e17667f6e4dd6003/crawl-ref/source/windowmanager-sdl.cc#L234
