### ISSUE TITLE
landing on a no_tele_into-suspicious vault in pan

### ISSUE THREAD

**Issue by MinticePIU** [crawl/crawl#1231]
**PLATFORM and OS or BROWSER:**
webtiles, Windows 10, Chrome

**DCSS VERSION:**
0.24.0-1-gfbc8707

**DESCRIPTION:**
I took a pandemonium transit gate(a blue one) that links between pans, then landed on the vault that has(or should have) no_tele_into. I think it's **gammafunk_dig_for_victory**?

**EXTRA FILES:**
morgue(note that i did not die in the vault): https://webzook.net/soup/morgue/0.24/Mintice/morgue-Mintice-20191215-212559.txt
screenshot(at the very moment i took the gate and landed inside the vault): https://media.discordapp.net/attachments/205316046230388737/655853352726298644/unknown.png
gammafunk_dig_for_victory: https://github.com/crawl/crawl/blob/master/crawl-ref/source/dat/des/variable/float.des#L9077

**Comment by rawlins** [comment]
I think this was fixed in 603da076d2ba3
