### ISSUE TITLE
Zot 5 vault needs no_tele_into

### ISSUE THREAD

**Issue by JayH2971** [crawl/crawl#1234]
Webtiles 0.25-a0-294-gea9b1ad ([morgue](http://crawl.akrasiac.org/rawdata/djehuti/morgue-djehuti-20191216-220440.txt))

**DESCRIPTION:**
Entered a permanent teleport trap in Zot 5 and was sent into a pond behind hardened glass. The only way out was to teleport again.

**SCREENSHOT:**
https://i.redd.it/z0l6mjycj2541.png

**Comment by theJollySin** [comment]
In the morgue above it shows the unique vaults in Zot:5 are: 

> layout_gridlike, ebering_ghost_xom, st_stairs_1

But when I look at the last two, neither seems like it could possibly be the vault in question.

Unfortunately, I don't grok the level-building logic well enough to be able to track this down.  I will keep reading to see if I can find it.  BUT if anyone has any helpful directions for where to look, I'll happily add the `w = no_tele_into` into the appropriate place.

**Comment by rawlins** [comment]
I'm not going to have a chance to look closely right now but this is probably caused by `layout_gridlike`, which has a longstanding issue with tele closets ([see](https://crawl.develz.org/mantis/view.php?id=7563&nbn=10#bugnotes)). It should be possible to reproduce via the seed + version.

**Comment by theJollySin** [comment]
@rawlins   I was able to reproduce the bug offline with seed + version.  Indeed.

I am still trying to understand the `layout_gridlike` logic.  Though it looks like it would be enough to say `w = no_tele_into` on all of the various `layout_***` routines. BUT I have been hearing crickets on the suggestion, so I will keep looking.

**Comment by gammafunk** [comment]
Putting `no_tele_into` on closets generated by the layout would be fine. Alternately we could just not generate decorative closets as part of the layout. That sort of thing can be handled by decor vaults, just not with quite as much smooth integration into the layout itself.

**Comment by theJollySin** [comment]
@gammafunk I had dropped this task, as some conversation I had on Freenode made me think no one agreed on an approach to fix it.

I can try to pick it back up again.  I found the `layout_gridlike` code to be a little opaque, perhaps it's is a lack of experience with the codebase.  But I will try to grok it again and see if I can implement your change.

Thanks for the response!

**Comment by theJollySin** [comment]
@gammafunk 
Okay, for the purposes of this discussion, let's talk about "layout_gridlike" in this file:

    crawl-ref/source/dat/des/builder/layout_cellular.des

It is perhaps that I don't know my way around the layout code, but I don't see where we purposefully create closet rooms in this code, or the code that reads it.  So, if room closets are, as I suspect, just a random chance when generating a room, it will be very hard to put w=no_tele_into on those closets. We'd have to write code to scan over every room we generate to determine if it is a closet. Doable, but slow and awful.

So, I think there are two possibilities:

1. Somewhere in the code there are places where we generate closets, and if I can find that, I can fix the ticket.
2. We just need to have `no_tele_into` on all water and lava generated by this layout code.

Any suggestions on where I can look next?  (Sorry to bother.)

**Comment by Skrybe** [comment]
I haven't tested this in trunk, but this should fix the issue.

Under `material_pairs`, the long list about 3/4 of the way down, the first 3 entries are the ones that create liquid pools with glass around them.  Change the "inner" glyphs to something arbitrary:
```
{ outer = 'n', inner = 'L', weight = 5 },
{ outer = 'n', inner = 'y', weight = 5 },
{ outer = 'n', inner = 'z', weight = 5 },
```
Then at the bottom, right before `zonify.map_fill_zones`, add `no_tele_into` to those glyphs, then change them to the appropriate liquid glyph:
```
kprop("Lyz = no_tele_into")
kfeat("L = l")
kfeat("y = W")
kfeat("z = w")
```
