### ISSUE TITLE
Webtiles crash on Mac

### ISSUE THREAD

**Issue by derekgr** [crawl/crawl#1246]
I'm running macOS Catalina, version 10.15.2. Webtiles crashes ("Unfortunately your game terminated due to an error. Game saved, see you later!") quite frequently, and seems to be triggered when accessing more complex menus (inventory, spell memorization, find search results, etc). I can reliably cause it to happen by accessing a menu a few times.

I've noticed this behavior over the past few days on CAO and CBRO, in both Safari and Firefox, in both trunk and 0.24. I've tried erasing my rcfile, but it didn't have an effect. If I switch to Firefox on a Windows machine I have available, a Webtiles crash is exceedingly rare. So, the only variable I've found seems to be which OS I'm using.

I'm happy to provide a chardump or save generated via console, but this has happened across several games, so I don't believe it's tied to a particular game.

I'm filing this issue here as I'm unable to register for mantis in order to file an issue there. Please let me know what other information I can provide, or if this happens to be a known issue.

**Comment by derekgr** [comment]
Anyone?

**Comment by alexjurkiewicz** [comment]
What is your username on these servers?

Given there is no known widespread issue right now, and it happens for you
across servers and versions, what happens if you try another browser or
computer?

**Comment by derekgr** [comment]
On the servers it is brae. As stated in the initial issue description, on MacOS another

**Comment by derekgr** [comment]
I'm sure it's probably just something on my end, as you said, since the issue is not widespread. I'll try and figure something out.
