### ISSUE TITLE
Provide an AppImage

### ISSUE THREAD

**Issue by CosmicToast** [crawl/crawl#1256]
[AppImages](https://appimage.org/) are an approach to multi-distro distribution that puts the control in the hands of the developer (as opposed to demi-centralized approaches like flatpak and snapd).
Since Crawl uses Travis CI, the cost of creating an AppImage is relatively low (there is a semi-official [method](https://docs.appimage.org/packaging-guide/travis.html) to generate them inside of Travis).
This would allow users to have a more authentic experience (bypassing distribution maintainers) and remain up to date (assuming publication is automated and update data is embedded as per specification).
This would also simplify the downloads page for linux.

For an example of a high-quality AppImage producer, please take a look at [KeepassXC](https://github.com/keepassxreboot/keepassxc/), though they do not utilize Travis to generate theirs.
The UX of using their official AppImage is great, however.

**Comment by alexjurkiewicz** [comment]
What sort of users use AppImages right now?

**Comment by 5paceToast** [comment]
Anyone on a Linux OS.
The goal of an AppImage is to be analogous to a MacOS .app, and work in a similar way.
I know of people using the KeepassXC image on Arch, Ubuntu, Debian, Gentoo, and multiple others.
That is very much the point and beauty of this new style of distribution method.

The advantages over flatpak and snapd is that the developer (i.e you) has the full control over what's included vs not in the long term, while flatpak and snapd are more like yet another platform you have to target.

If you mean users in terms of consumers (i.e open source projects producing their own appimages), here is a (VERY) incomplete list of the ones I've used personally:
- KeepassXC (the best support I've seen)
- Yubikey Manager (Qt version)
- Balena Etcher
- Beaker (Browser)
- Hyperspace (a fediverse client)
- Inkscape
- LibreOffice
- LMMS
- MuseScore
- Insomnia (a FOSS Postman-like)

**Comment by rawlins** [comment]
We would accept a patch to do this but I think it's unlikely to come from inside the devteam any time soon, as it would be best done by someone who already knows how to build these.

**Comment by 5paceToast** [comment]
I would give it a shot (especially for the console version), but I'm too unfamiliar with travis to grok it enough to modify.
Would it be helpful if I documented the process for building one by hand?

**Comment by alexjurkiewicz** [comment]
Yes! Release builds are built with GitHub Actions anyway, but there's no
reason some can't be built by hand.

**Comment by PhoneixS** [comment]
I don't know if it is useful for you but maybe you can use something like https://github.com/marketplace/actions/build-appimage

**Comment by robertxgray** [comment]
I have performed the first automated release including AppImages. More info in #2188.
https://github.com/robertxgray/crawl/releases/tag/0.0.0
