### ISSUE TITLE
race/class combo recommendations issue

### ISSUE THREAD

**Issue by scalpelenema** [crawl/crawl#1257]
Greetings!
I noticed that some of dcss recommendations for race/class combos differ depending on what (race or class) you choose first.
Example:
class > race - halfling assassin is recommended
race > class - halfling assassin is not recommended ('assassin' is grayed out)

**Comment by alexjurkiewicz** [comment]
This is intentional. The theory is something like "whatever you pick first
is taken as a given, we recommend based on that". So if you're going to
play assassin, a Halfling is good/interesting/whatever. But if you're going
to play Halfling, assassin is not particularly good/interesting/whatever.

**Comment by scalpelenema** [comment]
OK I think get it )

**Comment by scalpelenema** [comment]
closing then
