### ISSUE TITLE
Crash when Force Lance pushes a creature into a Phantom Mirror copy of itself.

### ISSUE THREAD

**Issue by auniqueidentifier** [crawl/crawl#1261]
http://crawl.akrasiac.org:8080/ online version 0.24 Playing on chrome 79.0.3945.117

DCSS version 0.24

I have managed to repeat it a few times on Rupert, I would be travelling through the dungeon and when I encountered Rupert, I would use a Phantom Mirror  and then I would try to use Force Lance to keep the two of them fighting each other. 

The problem occurred when the original Rupert was hit by the Force Lance spell and crashed into the copy of Rupert. The game would then crash and I would be booted from the game. It then reset the game back to when I last entered that level. 

I was able to reproduce the issue a few times, I stopped trying once I confirmed, jic it would ruin my save.

**Comment by rawlins** [comment]
I have the sense there are still some force lance crashes in trunk, not sure if this is the same issue but it seems worth looking at before 0.25

**Comment by rawlins** [comment]
ok this specific crash was fixed in 77f818bfca1f7aa3d (and is also fixed in trunk in Jan) so I will close this issue.
