### ISSUE TITLE
Windows Installer Version Not Correct

### ISSUE THREAD

**Issue by RandomString123** [crawl/crawl#1263]
**Windows Installer**

**24.0**

**DESCRIPTION:**
On the official site the windows installer version of the game is not the same as the zip version and what is available as 24.0 on current web based servers.  There are some small differences the most obvious one is some races and classes are missing.  Not really a game issue but a packaging issue.

**Comment by alexjurkiewicz** [comment]
Can you provide more info, like a screenshot of the issue?

**Comment by RandomString123** [comment]
Closing, checked with the latest installer and everything seems fine and I don't have the one I used from a few weeks ago around.   Sorry about the waste of a cycle.
