### ISSUE TITLE
Game becomes unresponsive after CTRL+f, item selection, then ESC

### ISSUE THREAD

**Issue by GnarledBeach** [crawl/crawl#1270]
UTC date/time: 2020-01-30, 01:50:00

DCSS version: Trunk, as of a very recent change. This is occurring in *all* of the following configurations: webtiles on CAO, SSH ASCII on CAO, offline ASCII, and offline tiles, the last two being built from source on Arch Linux.

When I press CTRL+f to search for items, enter a query, and select an item from the resulting list, the cursor goes to the item on the map, as expected. Then I press ESC to get out of the search mode. After this, the game is completely unresponsive. No input does anything. I have to reload the web page, or kill/restart the crawl process or SSH connection.

**Comment by aidanholm** [comment]
Fixed; thanks!
