### ISSUE TITLE
Foxfire is attracted to enemies in vault behind glass walls, instead of going towards "real" enemies

### ISSUE THREAD

**Issue by joemaro** [crawl/crawl#1276]
Version: Linux Offline Tiles 0.25-a0-479

![2020-02-09 22:00:09](https://user-images.githubusercontent.com/9556944/74109877-c3734100-4b87-11ea-991f-2659b8dee7ad.png)

In this screenshot i have casted Foxfire several times, expecting it to go towards the frog obviously, but none has gone towards him, instead they all stay glued to the glass walls until they expire.

Gameseed is 9342650502460745047, vault is on D:6

**Comment by ebering** [comment]
Fixed in 3851f72
