### ISSUE TITLE
Frozen Ramparts - Recasting bug

### ISSUE THREAD

**Issue by shummie** [crawl/crawl#1280]
Tested on Local tiles (0.25-a0-488-g03579ab) & Webtiles (0.25-a0-489-g9ae84a01e3)
Windows 10 / Chrome

Casting Frozen Ramparts several times in a row (in different locations?) causes future casts to cause those walls to "recast" even when out of LOS (and even in LOS but too far away). An example is shown in attached screenshots.

I've replicated this by casting frozen ramparts near a wall, move a few squares away, and recast frozen ramparts again (before it expires the first time). I move out of LOS (not sure this is required), and then cast Frozen Ramparts again. If I move back into LOS of the original cast (and recast), there are some squares (maybe the ones that overlapped?) that have the icy walls again.

This is most evident when using frozen ramparts and kiting an enemy. I've gotten a majority of the level showing the icy wall when recasting the frozen ramparts. 

The attached screenshots show the position before casting ramparts,
![0 - Before_casting_icy_ramparts](https://user-images.githubusercontent.com/3296707/74199824-e30f7580-4c2a-11ea-89d4-b0b874bf5ef1.JPG)

after casting to show initial effect range, 
![1 - Casting icy ramparts](https://user-images.githubusercontent.com/3296707/74199847-ef93ce00-4c2a-11ea-9392-93bc8420c182.JPG)

and then moving up to reveal additional tiles out of the original LOS cast that now have icy walls. 
![2 - Moving 2 squares north](https://user-images.githubusercontent.com/3296707/74199853-f4f11880-4c2a-11ea-8c74-1cea5a841995.JPG)

These walls DO deal damage as well and is not just a visual effect.

**Comment by gammafunk** [comment]
Should be fixed by a8e59b5 and e77a692. Thanks for the report.
