### ISSUE TITLE
"Animate Dead" doesn't raise corpses that are on tiles with webs

### ISSUE THREAD

**Issue by joemaro** [crawl/crawl#1283]
Linux 64bit Offline Tiles Client version: 0.25-a0-489

I'm not sure whether that's a bug or if the behaviour is wanted like that:
In the following screenshot there is no way to raise the wolf spider corpse (next to thet stairs) with "Animate Dead" (the necromancy spell, i'm not sure how about the Yred ability). I think it would be odd if crawl rewards killing strong enemies (which you'd want as zombies) on tiles without webs.

![2020-02-11 08:14:33](https://user-images.githubusercontent.com/9556944/74245310-157ca980-4ce3-11ea-893d-78b5faeec36b.png)

Feel free to delete if this isn't a bug.

**Comment by auriel-klasovksy** [comment]
Hey devs, I was thinking about this for my first tinker with the code. Can any one confirm that this is in fact a bug and not a balance thing? animate corps is fairly powerful as is

**Comment by rawlins** [comment]
I haven't looked into this closely but this sounds to me like either a bug, or the kind of thing we might want to clean up anyways if it was once upon a time intentional (in that it's spoilery and idiosyncratic, and rewards luring enemies off of webs).
