### ISSUE TITLE
Duplicate Unrandart from Scroll of Acquirement

### ISSUE THREAD

**Issue by tene** [crawl/crawl#1285]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION:**
0.25-a0-504-g768f60d

**DESCRIPTION:**
I got the unrandard Elemental Staff from a scroll of acquirement while in Lair 3 or 4, not sure which, and then found a second Elemental Staff on Lair 5.
<img width="646" alt="Screen Shot 2020-02-13 at 20 48 20" src="https://user-images.githubusercontent.com/2852/74502400-3c350e80-4ea2-11ea-910b-a886e7d55660.png">

**EXTRA FILES:**
[Backup of my save just after picking up the second Elemental Staff](http://crawl.akrasiac.org/saves/sweeks-crawl-git-768f60da87-200213-2352.tar.bz2)

**Comment by gammafunk** [comment]
This was fixed in f66f01b91, so if you update your game to latest trunk, you shouldn't see any more duplicated unrands. Thanks for the report!
