### ISSUE TITLE
Hex wands rarely don't show % success on certain monsters

### ISSUE THREAD

**Issue by shummie** [crawl/crawl#1287]
Webtiles v0.25-a0-521-gb5d5f98535
Chrome

I've noticed that sometimes when I attempt to use a hex wand on certain enemies (uniques? only certain ones?) that the usual % chance of success does not show up. I do not know under what circumstances this happens, but I think I've had it happen with Harold a couple of times. (I wonder if it's the first turn after seeing him?) After a few turns, it then displays correctly again. I'm finally getting around to submitting this issue.

As I cannot currently attach files or save a backup of my online game. I will add a picture when I encounter this again.

**Comment by shummie** [comment]
Here are two screenshots that illustrate the issue. The first is a poly wand targeting Joseph which shows the chance to defeat MR as normal.
![NoSuccess-Joseph](https://user-images.githubusercontent.com/3296707/75201684-bed58d80-572e-11ea-8b56-888bb8194b92.JPG)

The second screenshot shows the same wand targeting Harold. No message is displayed (which seems weird, I think I remember earlier that targeting Harold still showed Harold as the target, but w/o the success chance). 
![NoSuccess-Harold](https://user-images.githubusercontent.com/3296707/75201716-d44ab780-572e-11ea-8d79-9493d4cf153c.JPG)

This is NOT the first turn I have seen Harold. I put an exclusion on him earlier (but I forgot to try to hex him so I do not know if there was a % success shown for him or not.

Save file location for debugging is here:
http://crawl.kelbi.org/saves/shummie-crawl-git-78a2afb0af-200224-2358.tar.bz2

**Comment by shummie** [comment]
Continuing to play through, it looks like it may be related to Harold having throwing nets quivered. I could not get a % success to hex while he still had throwing nets. Only after he ran out of nets, does the normal Aim: dialog box w/ chance to defeat MR show up.

![NoSuccess-Harold-Nonets](https://user-images.githubusercontent.com/3296707/75202073-c8abc080-572f-11ea-9dae-f89177859037.JPG)

**Comment by hittem** [comment]
didnt see this before i filed my own one mantis https://crawl.develz.org/mantis/view.php?id=12215

it has only happened to me with Harold though. not sure if it ever happens for other monsters?

**Comment by wheals** [comment]
I've tried to reproduce this, but it works fine for me now (testing on console, local tiles, and webtiles).
