### ISSUE TITLE
Android window colour bug report

### ISSUE THREAD

**Issue by rkd2003** [crawl/crawl#1305]
**PLATFORM and OS or BROWSER:**
Android 10
DCSS console version

**DCSS VERSION:**
0.24.0b

**DESCRIPTION:**
Bug report) When I used other onscreen keyboard, green window line appears. Hide this line please. Especially, I can't select hi-res font mode...

**EXTRA FILES:**
![Screenshot_20200302-221740_Dungeon Crawl Stone Soup for Android](https://user-images.githubusercontent.com/23100292/75680656-69245680-5cd5-11ea-9eb3-ec3ba95d8b5b.jpg)

![Screenshot_20200302-222711_Dungeon Crawl Stone Soup for Android](https://user-images.githubusercontent.com/23100292/75680676-74778200-5cd5-11ea-9444-e1686f0230b2.jpg)

**Comment by rawlins** [comment]
We don't really support android builds; is this something you are building yourself, or is this coming from a play store app? If the latter, you may need to report it to the app developer.

**Comment by rawlins** [comment]
I'm going to close this up, as android isn't maintained by the core dev team. (If this is an issue in core dcss we'd probably accept a PR to fix it, but there's no one on the dev team who can fix it themselves.)
