### ISSUE TITLE
Why DCSS is the greatest game ever made

### ISSUE THREAD

**Issue by MTyson** [crawl/crawl#1307]
There is an extreme degree of refinement to DCSS, there's no question.  But that is not why it is the greatest.

The reason is what the refinement has exposed, which is something more essential than most games can even dream about.

Observe: What does it take to win this game? What does it demand of you? What traits does it cultivate?

In short, DCSS demands and develops critical qualities of being a human being:

1) persistence
2) patience
3) mastering frustration
4) noticing when you are in deep shit
5) noticing how quiet and calm alternates with crazy and dangerous
6) acceptance of loss

and others.

Thanks guys.

**Comment by ebering** [comment]
Closing this issue as "no change required"
