### ISSUE TITLE
Crash in mega-zigs, 0.24, webtiles

### ISSUE THREAD

**Issue by ViliusP2** [crawl/crawl#1308]
**PLATFORM and OS or BROWSER:**
 "webtiles",

**DCSS VERSION:**
0.24

**DESCRIPTION:**
Crash

**EXTRA FILES:**

https://underhound.eu/crawl/morgue/Winsalot/crash-Winsalot-20200304-182446.txt

**Comment by rawlins** [comment]
Fixed in trunk at 8b148903, and recently backported to 0.24 as a0fcdd1154
