### ISSUE TITLE
tactic-less arrival vault: minmay_arrival_plants_in_alcoves

### ISSUE THREAD

**Issue by anderspapitto** [crawl/crawl#1311]
only one exit, immediate monsters, no pillars/hatches/etc

version 0.25-a0-587-gb4d47b2
example morgue: http://crawl.akrasiac.org/rawdata/drj/morgue-drj-20200308-233506.txt

**Comment by anderspapitto** [comment]
@ByrelMitchell since you've fixed others recently

**Comment by ByrelMitchell** [comment]
I'm currently going through simple.des. I agree that this vault needs some TLC.

**Comment by ByrelMitchell** [comment]
The fix to this has been merged in 7f95dfe86c4be916f1815015388295e6f3114600.
