### ISSUE TITLE
Antimagic randart with MP+9

### ISSUE THREAD

**Issue by b0morris** [crawl/crawl#1322]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION:**
0.25-a0-632-g7713895

**DESCRIPTION:**
Equipped a randart hand axe {antimagic, rPois MP+9 Str+3} and instead of giving me 9 more mana, it reduced it by what appears to be a percentage. When I had 16 mana it reduced it to 8, and when I had 22 mana it reduced it to 10.

**EXTRA FILES:**
Character dump and two screenshots showing before and after equipping it.
[MP Bug Randart.zip](https://github.com/crawl/crawl/files/4357469/MP.Bug.Randart.zip)

**Comment by alexjurkiewicz** [comment]
Antimagic reduces MP by 2/3rds. I guess you could say it's a bug you found
a weapon with antimagic and MP+

**Comment by b0morris** [comment]
Ahhh. Didn't know that about antimagic. Guess I've only used that brand on melee bruisers before and never really paid attention to my mana. :P

**Comment by Goratrix** [comment]
Strange, this should have been eliminated here: https://github.com/crawl/crawl/blob/master/crawl-ref/source/artefact.cc#L570

**Comment by Goratrix** [comment]
Found another one of these. Version **0.25.1** offline windows tiles, seed **15059308085712573611**.

![Screenshot 2020-10-24 140404](https://user-images.githubusercontent.com/54112839/97081327-03892f80-1602-11eb-9265-1f2b3bdca4c3.png)
