### ISSUE TITLE
Frozen Ramparts on Map Edge

### ISSUE THREAD

**Issue by b0morris** [crawl/crawl#1330]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION:**
0.25-a0-665-ga69d640

**DESCRIPTION:**
Unable to use Frozen Ramparts on map tiles that are at the limit of the map. I'm pretty sure that's what's going on anyway. Was able to generate a few different layouts in Lair 6 where the map looked like it hit the limits and got cutoff. Trying to use Frozen Ramparts on these walls gives the error, "There are no walls around you to affect." Couldn't find any vaults associated with this, and couldn't find the layout in the `dat/des/branches/lair.des` file.

**EXTRA FILES:**
![Screen Shot 2020-03-25 at 2 19 39 PM](https://user-images.githubusercontent.com/1136630/77582809-98c61900-6ea5-11ea-8070-af1a620f208f.png)
![Screen Shot 2020-03-25 at 2 26 43 PM](https://user-images.githubusercontent.com/1136630/77582807-982d8280-6ea5-11ea-9408-80092f72983b.png)

**Comment by joemaro** [comment]
Came here to report the same thing: 

Screenshot when on the maps edge:
![2020-04-05 08:25:39](https://user-images.githubusercontent.com/9556944/78468499-f285d900-7718-11ea-8b41-fccaed789d74.png)

Not on the edge:
![2020-04-05 08:35:42](https://user-images.githubusercontent.com/9556944/78468497-f0237f00-7718-11ea-817b-04ecc8fd5e56.png)

**Comment by gammafunk** [comment]
Fixed, thanks for the report.
