### ISSUE TITLE
Character creation 'Tab' select previous weapon doesn't work

### ISSUE THREAD

**Issue by Syneil** [crawl/crawl#1339]
**Crawl version:** webtiles, trunk (post-0.24)
**O/S:** macOS Catalina, 10.15.4
**Browser:** Chrome 80.0.3987.162 (Official Build) (64-bit)

**Steps to reproduce:**
I click "edit rc" (by DCSS Trunk):
```
species = Demonspawn
background = Fighter
```
I click "DCSS Trunk" (under Play now)
I see:
```
Welcome, {username} the Demonspawn Fighter.
You have a choice of weapons.
```
(Having previously played DSFi selecting Axe)
I press Tab (to repeat selection of Axe)

**What happens:**
Nothing

**What I expect to happen:**
The game starts with an axe equipped.

**Comment by rawlins** [comment]
Thanks for the report, I can replicate this. Tab seems to be getting ignored entirely in the weapon selection screen on webtiles in trunk.

**Comment by aidanholm** [comment]
I haven't tried to debug this, but this happens on local tiles as well; it's probably because <tab> is used to cycle focus between widgets.
