### ISSUE TITLE
SDL_image.h: No such file or directory

### ISSUE THREAD

**Issue by lembark** [crawl/crawl#1362]
**PLATFORM and OS or BROWSER:**
*e.g. "local tiles", "webtiles", or "console". Putting this in the labels is
also fine. If this is an offline game or an issue with the build process,
please include your OS and OS version; if this is an online game please
include your browser and version.*

**DCSS VERSION:**
*e.g. "0.18", ""0.19-a0-1891-ge1d1fe8". If you can launch the game, you can
find this information by pressing ?V; the version will be at the top of the
screen. If not, check the changelog in the 'docs' directory.*

**DESCRIPTION:**
*What happened? What went wrong? What else was going on at the time of the
problem? Can you reproduce the issue? If you can provide a specific sequence
of steps that reproduces the issue, that will be extremely helpful to us (and
may also help you in writing the bug report). Screenshots are also very
welcome; you should be able to upload these directly to github.*

**EXTRA FILES:**
*Please include any morgue files, crashlogs, save files here, or extra
screenshots here. If this is a crash bug, the crashlog and save file will be
extremely helpful; the location of these is sytem-specific but if you ask
we can help you find them.*

*To upload a save file directly to github, compress it to a .zip archive, and
then github will accept the upload. (It will not take a .cs file directly.)*

*If this is an online game, see [these instructions](https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup)
for more information on how to make a save backup; you can provide the
resulting link here.*

**Comment by rawlins** [comment]
Closing, looks like this version was an accident.
