### ISSUE TITLE
ui.cc: 'iswalnum' was not declared in this scope

### ISSUE THREAD

**Issue by sagitter** [crawl/crawl#1372]
Hi all.

Another build error on Fedora. 
Full build log: https://kojipkgs.fedoraproject.org//work/tasks/4333/43564333/build.log

**PLATFORM and OS:**
Fedora 33 (devel branch) 64bit (and any others), GCC-10.0.1

**DCSS VERSION:**
0.24.1

**DESCRIPTION:**
```
g++ -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2  -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -std=gnu++11 -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2  -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pipe    -DUSE_SOUND -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized  -Wno-array-bounds -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua-5.1  -Irltiles   -DWIZARD -DASSERTS  -DCLUA_BINDINGS -DSAVE_DIR_PATH=\"~/.crawl\" -DDATA_DIR_PATH=\"/usr/share/crawl/\" -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -MMD -c ui.cc -o ui.o
ui.cc: In member function 'bool ui::TextEntry::LineReader::is_wordchar(char32_t)':
ui.cc:2086:12: error: 'iswalnum' was not declared in this scope; did you mean 'isaalnum'?
 2086 |     return iswalnum(c) || c == '_' || c == '-';
      |            ^~~~~~~~
      |            isaalnum
make: *** [Makefile:1601: ui.o] Error 1
```

**Comment by rawlins** [comment]
Will look into this.

One general comment: dcss builds on linux and the linux build is heavily tested using CI using a set of standard arguments (though this is all on debian-based systems).  So I expect that this could be the same as last time -- something non-standard (and so not well-tested) is being used as a build argument. How did you (or whoever did it) construct the build command? Can you link to some more readable version of what the build configuration actually is for this automated system? Have you tried manually building crawl using some set of these arguments? What patches are you applying if any during the build process?

**Comment by sagitter** [comment]
> How did you (or whoever did it) construct the build command? Can you link to some more readable version of what the build configuration actually is for this automated system?

Build commands are under the [_%build_](https://src.fedoraproject.org/rpms/crawl/blob/master/f/crawl.spec#_130) section.

%optflags = `-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection`

%{__global_ldflags}  = `-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld`

> What patches are you applying if any during the build process?

[Patches are listed here](https://src.fedoraproject.org/rpms/crawl/tree/master). (They do not influence the Make work.)

**Comment by rawlins** [comment]
ok, this isn't to say that we don't want to know what is causing this, but -- that is a *huge* set of changes relative to our supported build process (and both patches do change Makefile). I looked around and couldn't spot anything obvious that would cause this error or allow me to replicate it, though perhaps some of the hardening stuff is impacting utf-8 code somehow. In absence of a very visible cause, I think we need to ask for a MWE that replicates the compile failure, relative to the supported build, in order to be able to address this on our end.

**Comment by sagitter** [comment]
This simple patch fixed the error:
```

--- a/crawl-ref/source/ui.orig.cc	2020-03-22 05:52:08.000000000 +0100
+++ b/crawl-ref/source/ui.cc	2020-04-22 14:56:57.938271318 +0200
@@ -30,6 +30,8 @@
 # include "view.h"
 #endif
 
+#include <cwctype>
+
 #ifdef USE_TILE_WEB
 # include <unordered_map>
 #endif
```

**Comment by rawlins** [comment]
Thanks for the patch, I went ahead and added this header as it seems safe enough to do on our end.
