### ISSUE TITLE
Jorgrun can dig out of the hall of blades.

### ISSUE THREAD

**Issue by ByrelMitchell** [crawl/crawl#1380]
webtiles, 0.25-a0-879-g6bf7129739

Jorgrun dug out of the hall of blades before I opened the runed door.

http://crawl.kelbi.org/saves/pblur-crawl-git-6bf7129739-200501-1241.tar.bz2

**Comment by ebering** [comment]
This is a "feature" of monster digging. I'm going to close this as a non-issue in the same way that the player teleporting or shafting into Hall of Blades is ok. It's mostly closed off, but can be encountered inadvertently in emergent ways.
