### ISSUE TITLE
Tarantella confused my ancestor ghost

### ISSUE THREAD

**Issue by FloBaueregger** [crawl/crawl#1385]
When playing a GnWr^Hep a tarantella was able to confuse my ancestor in the spider nest. I don't think spider poison should have an effect on ghosts.

Bug seen in webtiles on Chrome, trunk version 0.25-a0-934-g041635d5d1

**Comment by Goratrix** [comment]
So the reason why this happens is that the tarantella attack has flavor AF_CONFUSE, which is independent of poison. The ancestor holiness is MH_NONLIVING.

I assume the confusion attack happens here, and there are no exceptions for any target holiness:

https://github.com/crawl/crawl/blob/8a172589296b978a35bc92522c32d84fbb97c332/crawl-ref/source/melee-attack.cc#L2748

Interestingly, there's another place (the chaos melee brand selection), which seems to assume that holiness MH_PLANT and MH_NONLIVING are immune to AF_CONFUSE, and it's considered invalid for them as targets:

https://github.com/crawl/crawl/blob/8a172589296b978a35bc92522c32d84fbb97c332/crawl-ref/source/attack.cc#L769

I suppose a dev needs to decide what the intended targets for AF_CONFUSE are, if all MH_NONLIVING targets should be immune to the flavor (and what about MH_UNDEAD?)
