### ISSUE TITLE
Two missing tiles

### ISSUE THREAD

**Issue by rawlins** [crawl/crawl#1387]
**PLATFORM and OS or BROWSER:** all tiles versions

**DCSS VERSION:** trunk

**DESCRIPTION:**
Missing tiles:

```
No TILE defined for 'hood of the Assassin'
No TILE defined for 'Cigotuvi's embrace'
```

It would be nice to get *something* in these slots for the 0.25 release, even if it's weak; right now it shows a missing tile placeholder image (the `TODO` tile).

**Comment by RojjaCebolla** [comment]
![kindahoodish](https://user-images.githubusercontent.com/62170514/81379257-c2927280-90d6-11ea-8839-4e3d99245b03.png) 🤷

**Comment by EugeneAbramchuk** [comment]
http://crawl.chaosforge.org/Cigotuvi%27s_embrace lists a tile for it

![image](https://user-images.githubusercontent.com/14140360/87158040-ca81b500-c2c7-11ea-85bc-c20ffb9f5f72.png)

**Comment by rawlins** [comment]
ah looks like I never updated this issue, I added that so that we'd have *something* for the release in: 1a081956a10

I didn't close this because it's not very good.

**Comment by amcnicky** [comment]
Wasn't sure from the above if you'd like suggestions for both tiles, or just Cigotuvi's. Hope you find the suggestions useful.

**Comment by Richiemoor** [comment]
If you need any help you can DM

**Comment by PleasingFungus** [comment]
Don't think we need to leave this open - nothing especially terrible about the cigo's tile compared to half the other old tiles we have lying around. :)
