### ISSUE TITLE
Tabbing with a ranged weapon generates error messages

### ISSUE THREAD

**Issue by d-strickland** [crawl/crawl#1395]
**PLATFORM and OS or BROWSER:**
CKO webtiles using Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**DCSS VERSION:**
0.25-a0-884-g76b13fe646

**DESCRIPTION:**
Pressing tab with a ranged weapon equipped results in these error messages getting printed to the log:

 key_to_command(): command 'CMD_NO_CMD' (219:43) wrong for desired context 2
 key_to_command(): command 'CMD_NO_CMD' (184:78) wrong for desired context 2
 key_to_command(): command 'CMD_NO_CMD' (184:78) wrong for desired context 2
 key_to_command(): command 'CMD_NO_CMD' (181:81) wrong for desired context 2
 key_to_command(): command 'CMD_NO_CMD' (181:81) wrong for desired context 2
 key_to_command(): command 'CMD_NO_CMD' (181:81) wrong for desired context 2
 key_to_command(): command 'CMD_NO_CMD' (199:63) wrong for desired context 2

Pressing enter then proceeds with the autofight action. Tabbed combat works as expected with a melee weapon.

The bug must have been merged in the last 24 hours or so. I think this commit looks like it could be related: 5a1f09014c08563d8c75d1e9c4fc5f913b19c311

**EXTRA FILES:**
http://crawl.kelbi.org/crawl/morgue/nonce/nonce.txt

**Comment by d-strickland** [comment]
Also applies to polearm combat at a distance, but not in melee range.

**Comment by ebering** [comment]
Your diagnosis was correct, thanks for the report! CKO rebuilds trunk every 15 minutes, so you should be able to resume tabbing per normal soon.

**Comment by d-strickland** [comment]
Thanks!
