### ISSUE TITLE
Potential overflow error in spell error

### ISSUE THREAD

**Issue by blergsid** [crawl/crawl#1420]
I am currently playing this character on the browser trunk version of crawl, I started it on version 0.25-a0-1133-g93ebf73 and the issue has persisted until version 0.25-a0-1136-gc1285e6.

I was playing a MuCK and got a crystal plate armor with +7 int on it, which I had on when I found the issue. My spells were working perfectly until I started getting severe stat drain, and after some time I discovered that all my spells lower than spell level 7 were at level 0% failure, although their spell power worked at normal. This issue persists for some variation of my stats, but seems to go away after my strength goes above 0, or after I take off my crystal plate armor. 

Morgue: http://crawl.akrasiac.org/rawdata/blergsid/blergsid.txt
Pastebin of morgue: https://pastebin.com/sShydngC

**Comment by rawlins** [comment]
Thanks for the report! There was actually an initial fix in cef5c758032e6977ec2 that failed to link to this issue, and it should now be fully resolved.
