### ISSUE TITLE
Visibility bug in Orc

### ISSUE THREAD

**Issue by riverfiend** [crawl/crawl#1433]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION:**
0.26-a0-33-gae26e8c

**DESCRIPTION:**
Entered Orc:2 and could see a 3x3 area of rock tiles somewhere outside of LOS

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/63566628/83215244-1b7c8600-a12c-11ea-86ea-427614c95a22.png)

(the ogre there is the player tile)

**Comment by alexjurkiewicz** [comment]
Can you post the seed when you finish the game? Do you know if it appeared
while autoexploring or something else? What is your webtiles username?

**Comment by riverfiend** [comment]
iirc it appeared when I first entered the floor, on CAO as ISplatSpriggans. I'll throw you the seed when I splat this particular spriggan.

**Comment by riverfiend** [comment]
Here's the morgue from that run--
http://crawl.akrasiac.org/rawdata/ISplatSpriggans/morgue-ISplatSpriggans-20200529-160639.txt

Seed: 11278617497985654711

I got this bug again today, this time entering Lair:6--Wish I could tell you precisly when it happened, but I wasn't really paying attention:
![image](https://user-images.githubusercontent.com/63566628/83318133-6a432200-a1f7-11ea-9fea-17243c9137aa.png)

**Comment by Goratrix** [comment]
There have been instances of this popping up on discord recently.

Posted by Flugkiller 05/22 (the four squares in the bottom left): https://imgur.com/5yNEE0t
Posted by vt 05/24 (the section in the left upper side): https://imgur.com/VTbSiS2

**Comment by riverfiend** [comment]
I've got a second in the same run (I'm the swamp worm):
![image](https://user-images.githubusercontent.com/63566628/83335923-ad43da80-a275-11ea-838f-0bfd98cceb9a.png)

**Comment by riverfiend** [comment]
Third run in a row:
![image](https://user-images.githubusercontent.com/63566628/83363153-c4112c80-a35c-11ea-9214-e49034f40346.png)

**Comment by rawlins** [comment]
I did try to replicate this based on the seed in the original morgue, and it didn't seem to be something that is triggered by levelgen, so any more ideas about the exact circumstances, or a save file backup, would be helpful.

**Comment by gammafunk** [comment]
![image](https://user-images.githubusercontent.com/6548464/83470988-22b3d480-a449-11ea-8a4d-af3ad33e60e7.png)

I had this bit of exposed area on a depth level completely out of the main level that I noticed in map mode.

**Comment by anderspapitto** [comment]
I've seen this too, as well as variants where it's not a pure chunk of rock that's revealed, but an actual traversable part of the layer, including seeing monsters and items. I don't have any screenshots to share, but each time, it's corresponded exactly to what would be visible from some arbitrary tile (i.e. there is a tile, such that when i put an exclusion on that tile, the red-marked tiles exactly match the incorrectly-revealed tiles).

My theory is that sometimes when taking stairs (maybe only when revisiting a level?) the player location is uninitialized or set to (0,0) or something, and visibility is generated from that location before being updated to the correct location.

**Comment by rawlins** [comment]
Thanks for the reports + discussion! What was happening was that code that updates map knowledge at the player's location could be triggered as a side effect while a different level was being examined in map view, even though the player's location was determined by the level they were actually on. So, los at the player's coordinates on one level get mapped at those coordinates on the other level. Where this position was solid and enclosed, the result was a 3x3 square.
