### ISSUE TITLE
Absolute zero doesn't let Gozag reward killing with gold

### ISSUE THREAD

**Issue by CrawlCycle** [crawl/crawl#1438]
**PLATFORM and OS or BROWSER:**
Webtiles (CBRO)

**DCSS VERSION:**
```
Version history for your current game:
Game started: 0.26-a0-23-g3ae7099
0.26-a0-28-gc929df5
0.26-a0-29-gb080af9
0.26-a0-34-g9e0bf03
0.26-a0-37-g50178cf

Features
--------
* Lua user scripts
* Web Tile support
* Wizard mode
* PCRE regexps
* Milestones
```
**DESCRIPTION:**
- Expected: Worship Gozag. Kill things with "Absolute Zero". Get gold from killing. I would prefer to get the gold without smashing the iceblock.
- Actual: Worship Gozag. Kill things with "Absolute Zero". Don't get gold from killing.

I play SpEn^Gozag. When I use the spell "Absolute Zero" to kill something in pand, I don't get gold.
I get gold from Gozag whenever I kill something by direct damage, incineration, or drowning. Turning the monster into block of ice with "Absolute Zero" should not be an exception.

In webtile, I sometimes see the gold image flash briefly before it is replaced by a block of ice image.

**EXTRA FILES:**

Game backup (from CBRO): 
http://crawl.beRotato.org/crawl/saves/Cycle-crawl-git-50178cf780-200530-2204.tar.bz2

Morgue:
[Cycle.txt](https://github.com/crawl/crawl/files/4706659/Cycle.txt)

rc:
[rc.txt](https://github.com/crawl/crawl/files/4706713/rc.txt)

Screen shots:
- See cacodemon (6693 gold)
![1](https://user-images.githubusercontent.com/66185335/83339955-e6457480-a2a0-11ea-981f-fa361733340d.png)
- Kill with absolute zero (still 6693 gold)
![2](https://user-images.githubusercontent.com/66185335/83339962-fe1cf880-a2a0-11ea-9c4f-ac44287e0e5c.png)
- Smash iceblock (still 6693 gold)
![3](https://user-images.githubusercontent.com/66185335/83339973-168d1300-a2a1-11ea-8071-f5b19501dba9.png)

**Comment by Goratrix** [comment]
I'm pretty sure this is working as intended. The gold you get with Gozag is a 'replacement' for monster corpses, and Absolute Zero does not leave corpses intentionally:
https://github.com/crawl/crawl/blob/master/crawl-ref/source/beam.cc#L4247

**Comment by CrawlCycle** [comment]
Gozag gives gold when I kill monsters that doesn't leave corpse, such as smoke demon.
