### ISSUE TITLE
Statue "shattered" with LRD remains intact

### ISSUE THREAD

**Issue by aaugusta** [crawl/crawl#1440]
Platform: webtiles - crawl.kelbi.org - Chrome 81.0.4044.138

DCSS Version: 0.25

DESCRIPTION:
I cast LRD on an elephant statue in an elephant vault on Lair:6 (to get at the spellbook tucked behind it).
The game reports "The statue shatters!" but the statue is still intact. See screenshot.
Re-casting produces the same result.

<img width="489" alt="Screen Shot 2020-05-31 at 3 42 37 PM" src="https://user-images.githubusercontent.com/4965382/83361264-7fce5e00-a355-11ea-80a7-3d99894367cf.png">

**Comment by aaugusta** [comment]
Uh, that's not what "shatter" means, is it. Oops.

**Comment by alexjurkiewicz** [comment]
I think "shatter" does imply the statue would be destroyed or at least
visibly damaged. A better message might be to talk about the damage effect:
"A spray of fragments erupts from the statue!" (except more elegantly
worded).
