### ISSUE TITLE
Bolt of Fire still available in vault spellbook

### ISSUE THREAD

**Issue by zeunysos** [crawl/crawl#1442]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION:**
0.26-a0-43-g20b394c

**DESCRIPTION:**
Apparent minor bug: noticed Bolt of Fire was in a spellbook in a Zot vault.  I didn't have the skill to cast it to see if it actually still functioned.

I thought the spell was supposed to have been removed.  Didn't see any git commit comments on the subject, but if the spell's been added back in, ignore this report!

**EXTRA FILES:**
Morgue for the game: http://crawl.akrasiac.org/rawdata/zeunysos/morgue-zeunysos-20200602-201557.txt
It was in the "Incunabulum of Fire and Brimstone", turn 99478.

**Comment by rawlins** [comment]
Thanks for the report!
