### ISSUE TITLE
Sometimes can't check which staircase corresponds (in X-mode, levelmap)

### ISSUE THREAD

**Issue by joemaro** [crawl/crawl#1452]
**PLATFORM and OS or BROWSER:**
Manjaro Linux, the bug happens both on console and on local tiles.

**DCSS VERSION:**
Trunk Version, compiled today:   0.26-a0-68

**DESCRIPTION:**
So when pressing `X` then going to a up-staircase in order to find out about the spot of the corresponding down-staircase, and pressing `[` to change to the upper level, the game doesn't show the down-staircase. In the described scenario the stairs have been used in the past, they are "known" so to say.
**This doesn't always happen, but roughly every 3rd time i check.**

**EXTRA FILES:**
[Lojof.cs.zip](https://github.com/crawl/crawl/files/4770037/Lojof.cs.zip)

In this save game, i just went down into Depths and when i now do `X<[` it does NOT show me the downstairs (on D15) into depths as it should. To clarify, this has also happened on the usual stairs, of which there are usually 3 of them on every level, not only on single staircase entrances like this one.

Hope this savegame can reproduce the bug ...
as always: thanks for all your work devs

edit: corrected the keys to the default binding

**Comment by anderspapitto** [comment]
I've noticed this too, and I suspect that it's the cause of the visibility bug in https://github.com/crawl/crawl/issues/1433 - trying to examine the other end of the stairs uses the wrong/an uninitialized location, and this can cause tiles around that incorrect position to be revealed?

**Comment by rawlins** [comment]
Thanks for the report + discussion! This ended up being unrelated to #1433 (fixed in 726680df4) but involving a very close bit of code.
