### ISSUE TITLE
The tile of disarmed Edmund still shows a flail

### ISSUE THREAD

**Issue by LarsH** [crawl/crawl#1453]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION:**
0.24

**DESCRIPTION:**
Casting Tukima's Dance on Edmund still shows him wielding a flail.

![2019-12-17-221106_1366x768_scrot](https://user-images.githubusercontent.com/1294050/84579931-7f60a900-add2-11ea-9298-e917ea93ed9d.png)

Solutions I could think of:
* just accept this visual quirk
* make Edmund immune to Tukimas dance
* replace Edmunds tile with a normal human tile
* add a new tile for disarmed Edmund

**Comment by wheals** [comment]
Fixed in #1568
