### ISSUE TITLE
Nemelex exploration triggers on looking downstairs with X mode

### ISSUE THREAD

**Issue by Rytisgit** [crawl/crawl#1454]
**PLATFORM and OS or BROWSER:**
webtiles 

**DCSS VERSION:**
0.25 tournament

**DESCRIPTION:**
Got cards from nemelex exporation mechanics by looking downstairs with X ], this was after logging out and then back in after some time. wanted to check downstairs, and got cards when i did so.

**EXTRA FILES:**
https://crawl.xtahua.com/crawl/morgue/sentinel/morgue-sentinel-20200614-112757.txt
![image](https://user-images.githubusercontent.com/36188103/84601633-556abd80-ae8a-11ea-8c2a-e50bea99a8db.png)

**Comment by rawlins** [comment]
Thanks for the report! This along with all the related bugs should be fixed in trunk/0.25.1. This particular one was a side effect of the map view bugs that were fixed in 726680df4ae0 and 012c83cef6ad.
