### ISSUE TITLE
Ubuntu 16.04.6 dependences issues

### ISSUE THREAD

**Issue by darcybgoode** [crawl/crawl#1455]
**PLATFORM and OS or BROWSER:**
Ubuntu 16.04.6

**DCSS VERSION:**
0.25

**DESCRIPTION:**
Unable to install DCSS 0.25 from repo due to unmet dependences (see the screenshot below).
0.24 release had the same issues in the beggining, but they were fixed.

**EXTRA FILES:**
![2020-06-16-111820_809x256_scrot](https://user-images.githubusercontent.com/66628107/84750257-b813a480-afc3-11ea-9b24-f5de73554f49.png)

**Comment by gammafunk** [comment]
Unfortunately, Ubuntu 16.04 is just too old for us to support. Even debian oldstable (stretch), only supports a libc6 as old as [2.24-11](https://packages.debian.org/stretch/libc6). We prefer to base the packages on debian stable if possible. I'd recommend either compiling from source or upgrading your Ubuntu OS if you can't and need to use the provided packages.

**Comment by gammafunk** [comment]
I discussed this with @rawlins and he's done some research that points to debian oldstable (Stretch) can be used as the basis for building for packages, which should allow Ubuntu 16.04 to to install them. I'm going to rebuild the packages against Stretch and will update this issue when that's done.

We're probably going to try a policy of building against debian oldstable from now to help support more OSes. We may be able to go back further to building against the oldest debian version that's not past EOL, but we can't do that now as Jessie is too old to work.

**Comment by gammafunk** [comment]
@darcybgoode I've rebuilt the packages against Stretch and installed them into the repository. Please give these a try and let me know if there are still installation problems for your system.

**Comment by darcybgoode** [comment]
@gammafunk  everything seems to work just fine. Both console and tiles versions are installed without any issues. Thank you.

**Comment by gammafunk** [comment]
Great, thanks! From now on, we'll probably build either against oldstable or the oldest LTS version of debian that's not at end of life and that can still build crawl. This should avoid these recurring dependency issues.
