### ISSUE TITLE
Using Nemelex's Stack Five and causing a deck to have a negative count, enables the use of the deck with a negative count and subsequently crashes the game. 

### ISSUE THREAD

**Issue by Zeiin** [crawl/crawl#1457]
**PLATFORM and OS or BROWSER:**
Webtiles, Google Chrome, NY server

**DCSS VERSION:**
0.25

**DESCRIPTION:**
Playing a character that worships Nemelex, both my Destruction and Summoning decks are empty. I cast Stack Five and select cards from the empty decks (I just used 5 destruction). This decrements the card count from 0 to -5. Once I confirm my selections, the Deck with a negative count is lit up so that it looks like you can use it (white instead of greyed out). Trying to use the negative deck crashes the game. 

http://crawl.kelbi.org/crawl/morgue/Zein/Zein.txt

**Comment by rawlins** [comment]
Thanks for the report! This is fixed in 8f6dc4e0a50b, but I forgot to link to this report, sorry.
