### ISSUE TITLE
Screen Write Out of Bounds Crash

### ISSUE THREAD

**Issue by Vitna-1** [crawl/crawl#1460]
**PLATFORM and OS or BROWSER:**
Console on Windows 7 Professional Service Pack 1.

**DCSS VERSION:**
0.25.0

**DESCRIPTION:**
The game crashes when moving the map from D:1 to D:2 back to D:1
Reproduction steps:
1. Shift+X
2. ]
3. [
4. Crash with the following output
![image](https://user-images.githubusercontent.com/67344840/85467615-6f3a8d80-b579-11ea-908f-e2afb178420e.png)

It looks similar to bugs in Mantis ([12260](https://crawl.develz.org/mantis/view.php?id=12260) & [11981](https://crawl.develz.org/mantis/view.php?id=11981)) but since I couldn't register for it and I don't see any related issues on Github I'm adding the info here.

**EXTRA FILES:**
Included save file and crash log.
[save_and_crash_log.zip](https://github.com/crawl/crawl/files/4822145/save_and_crash_log.zip)

**Comment by rawlins** [comment]
Thanks for the report! I believe this should have been fixed by 726680df4a (which was post-0.25.0), though when testing the save I don't get a crash per se on mac in this case, just weird behavior. We'll probably do a bugfix release with this fix among others shortly after the tournament is over.

**Comment by rawlins** [comment]
The fixes for this are in the 0.25.1 release and I'm pretty confident that I got both this and all the related bugs, so I'm going to close this up. Thanks again for the detailed report!
