### ISSUE TITLE
With Gozag, search shows gold pieces in unexplored locations

### ISSUE THREAD

**Issue by dominiquelee** [crawl/crawl#1461]
**PLATFORM and OS or BROWSER:**
Webtiles Xtahua, Firefox 77.0.1

**DCSS VERSION:**
0.25.0-11-g1f837a76a1

**DESCRIPTION:**
Worshipping Gozag, I haven't explored Vaults at all for now. But it was autogenerated when I entered into Elf.
Searching for "vaults" shows gold in V:4, which should not be the case.
![image](https://user-images.githubusercontent.com/1204726/85712239-6ae0b280-b6e8-11ea-908e-ecc57138102e.png)

**Comment by rawlins** [comment]
Thanks for the report! Can you point me to a morgue (ongoing or otherwise) for this game?

**Comment by dominiquelee** [comment]
Should be https://crawl.xtahua.com/crawl/morgue/Canard/morgue-Canard-20200625-113028.txt

**Comment by rawlins** [comment]
Thanks! It's the abyss trip on Elf:3 that is the key to replicating this. Replication steps: on this exact seed (14282963568280432283) in 0.25, wizmode, join gozag,`~` to elf 3, then `~` to abyss 1, then ctrl-f `vault`.
