### ISSUE TITLE
Clouds are invisible

### ISSUE THREAD

**Issue by joemaro** [crawl/crawl#1469]
Offline Linux Tiles Client version 0.26-a0-146 (compiled today)

The following screenshots show that clouds are simply not visible. I've noticed it with a Catoblepas, whos clouds i didn't see, then tried a wand of flame on water: clouds are effective but invisible.

![2020-06-29 17:09:01](https://user-images.githubusercontent.com/9556944/86023326-d352cb00-ba2b-11ea-934f-fdf645dbbb38.png)

![2020-06-29 17:09:25](https://user-images.githubusercontent.com/9556944/86023297-c9c96300-ba2b-11ea-96fc-bbc647278b5e.png)

![2020-06-29 17:10:39](https://user-images.githubusercontent.com/9556944/86023278-c2a25500-ba2b-11ea-94a2-820de2fb439d.png)

**Comment by aidanholm** [comment]
Thanks for reporting! Fixed at 5ef36ef.
