### ISSUE TITLE
mouse cursor position

### ISSUE THREAD

**Issue by scalpelenema** [crawl/crawl#1472]
Hi!

PLATFORM and OS or BROWSER
local tiles, debian linux testing

DCSS VERSION:
latest git

DESCRIPTION
I play with keyboard only and mouse cursor position was far top left when starting the game. now it is on the desktop position somewhere in the middle for me so I have to manually make it 'disappear' moving to the edge not to mess with the game screen. not a big issue though but still..

**Comment by rawlins** [comment]
(I did look at this briefly when I added the label and it doesn't replicate on mac, so I'm guessing it's linux specific.)

**Comment by robertxgray** [comment]
I had a look at this while reviewing old issues and the behaviour seems to be dependent on the window manager. I made two tests:

1. Mate. The cursor moves to top-left when the game starts.
2. Awesome. The cursor stays in the same place when the game starts but moves to top-left on exit.

Also, I didn't find any references to SDL WarpMouse functions in Crawl's code. I think this issue can be closed.

There are workarounds to hide the cursor in this situation, like [Unclutter](https://wiki.archlinux.org/title/unclutter).

**Comment by robertxgray** [comment]
I'm closing the issue. Please feel free to reopen if you need further assistance.
