### ISSUE TITLE
Putting on amulet from ground, crashed the game.

### ISSUE THREAD

**Issue by joemaro** [crawl/crawl#1479]
Linux Local Tiles Trunk, 0.26-a0-224 (compiled today)

The provided zip file contains a savegame, a crash-morgue, and the usual morgue.
[bugreport.zip](https://github.com/crawl/crawl/files/4879998/bugreport.zip)

What I did to crash the game (twice in a row):

- Went downstairs, 
- moved onto the amulet, 
- tried the unidentified ring from inventory,
- read remove curse, 
- dropped the ring, 
- pressed `p`, 
- pressed `,` to select items on ground,
- pressed letter for amulet, 
--> game crashed.

Now after reproducing the crash once in the same manner, i took the amulet into the inventory and put it on, then the game did NOT crash ...

Hope this helps!

**Comment by ebering** [comment]
Fixed in 29f007eb
