### ISSUE TITLE
Font issues in 0.25 tiles (fine in 0.24)

### ISSUE THREAD

**Issue by powerbf** [crawl/crawl#1482]
**PLATFORM and OS or BROWSER:** local tiles 0.25 on Linux Mint

**DCSS VERSION:** 0.25.0.3-gd7cc5688da

**DESCRIPTION:**
Some letters look messed up, specifically: A, K, T, V, W, X, Y.
It looks like they have a little bit of the next letter of the alphabet attached on the right (i.e. A has a little bit of B, K has a bit of L, etc.)
(See attached image)

This issue occurs in game, but not in the start menu.

I built crawl from source, and initially, I thought this was some library or system issue, but I just checked out and built the 0.24 tiles version and it's fine.

**EXTRA FILES:**
![janky-crawl-font](https://user-images.githubusercontent.com/45711639/87000724-1154a980-c1f9-11ea-9977-4fdd83076b92.png)

**Comment by powerbf** [comment]
I just noticed that the issue occurs only in the messages area. The status panel (where AC, EV, etc. are shown) looks fine. The window that comes when you press "%" also looks fine.

**Comment by powerbf** [comment]
Have updated my 0.25 branch from github and rebuilt. Version is now 0.25.0-37-gb73750e0fb.
Issue is still present.

**Comment by rawlins** [comment]
I haven't been able to replicate this exactly on mac but I do seem to be getting some misrendering on `W` specifically, that seems along the same lines, it appears that some bits of `X` are intruding on `W`. Also, I do not see this bug at all on hidpi.

Regular DPI:
![Screen Shot 2020-08-15 at 10 39 42 AM](https://user-images.githubusercontent.com/6290753/90314710-c6a70b00-dee3-11ea-9049-2829e5587435.png)

HiDPI:
<img width="632" alt="Screen Shot 2020-08-15 at 10 42 31 AM" src="https://user-images.githubusercontent.com/6290753/90314757-387f5480-dee4-11ea-9b70-c8eb6ccc4c66.png">

Has anyone been able to replicate on linux or windows? (In case this wasn't clear, for replication purposes use the name `A K T V W X Y` with spaces.)

**Comment by Goratrix** [comment]
I can confirm it replicates in current trunk (1132-ge9770dfcb6) local tiles in Windows 10, non-hidpi 1920x1200, both fullscreen and windowed:

![Screenshot 2020-12-22 115432](https://user-images.githubusercontent.com/54112839/102881213-cea42800-444c-11eb-8a55-9dab352a1d98.png)

**Comment by powerbf** [comment]
When I build 0.25 on Windows, only the W is weird:
![crawl-win](https://user-images.githubusercontent.com/45711639/103730668-1c18bb80-502f-11eb-9912-a18892dc1dc4.png)

All the aforementioned chars (AKTVWXY) are still weird on Linux.

**Comment by powerbf** [comment]
On Linux, the issue first appears for me with commit [943f020|https://github.com/crawl/crawl/commit/943f02021d53d37ccb947fb65e75af4d8f09610b] (i.e. building the immediately previous commit does not show the problem, but building this commit does)

**Comment by powerbf** [comment]
It seems that glyph widths (and consequently max width) can be larger than max advance.
It tried two fixes, both of which fixed my problem, but I'm not sure how they would impact the issue that 943f020 fixed. 

The two fixes were:

a) make charsz.x at least as big as the bigger of max width and max advance in configure_font():
-    while (charsz.x < m_max_advance.x)
+   while (charsz.x < max(m_max_advance.x, m_max_width))

b) Clamp width to charsz.x in render_text_block() as is already done in load_glyph():
-                int this_width = glyph.width;
+               int this_width = min((int)glyph.width, charsz.x);

**Comment by rawlins** [comment]
I've pushed something that is neither of those two fixes but does work for me, as independent of the advance vs glyph width issue, I'm pretty sure there was an off-by-one error in the code that I found by looking at solution (a). It remains to be seen if some version of fix (a) above also needs to be applied. (Fix (b) doesn't work for me, and on mac just results in the upper right corner of the `W` being cut off.)

As noted in that commit, a *huge* thanks for some very timely bisection + debugging to @powerbf. I haven't closed this issue as it would be nice to have more testing.

**Comment by Goratrix** [comment]
Looks good now on windows:

![Screenshot 2021-01-06 204757](https://user-images.githubusercontent.com/54112839/103813550-9150b480-5060-11eb-9b19-d1b4e5b423e2.png)

**Comment by powerbf** [comment]
Thanks @rawlins. Trunk now looks good on Linux:
![trunk-font](https://user-images.githubusercontent.com/45711639/103996426-8e330100-51e5-11eb-8df6-961621e9ed6f.png)

**Comment by rawlins** [comment]
I think this was fully fixed by the commits from January, so I'm going to go ahead and close it up.
