### ISSUE TITLE
Confusing message when trying to enchant max-enchanted unidentified item

### ISSUE THREAD

**Issue by quhsi** [crawl/crawl#1483]
### Repro steps

1. Pick up an unidentified weapon without the "runed" or "glowing" property.
2. Apply 9 scrolls of enchant weapon on it.

   → "scroll scrumbles to dust", "weapon glows red for a moment" displayed

3. Apply another scroll of enchant weapon

   → "scroll scrumbles to dust", "nothing appears to happen" displayed

### Expected behavior

There should be a warning when enchanting an item with unknown enchantment level as the scroll could be wasted.

If it is guaranteed, that unidentified weapons without a "runed" or "glowing" property have enchantment level 0, then the user could always know the enchantment level of the weapon and thus it could be displayed in the name of the weapon. It should then also be considered in the algorithm for choosing a enchantable weapon.

The same reasoning could be applied to armor.

**Comment by ebering** [comment]
No longer an issue due to changes in how item identification works in trunk.
