### ISSUE TITLE
Misleading coloring when firing an arrow

### ISSUE THREAD

**Issue by Klatu1494** [crawl/crawl#1491]
**PLATFORM and OS or BROWSER:**
Browser

**DCSS VERSION:**
0.25.0-11-g1f837a7

**DESCRIPTION:**
When firing an arrow as a Barachi to the top left corner, all tiles outside my 17x17 surroundings where painted yellow, as if they were going to be affected by the shot. This did not happen when targeting other tiles that were 8 tiles from my character, but as you can see in the screenshot I couldn't target other "corner tiles" at that moment so it could be a "barachi corner tile" problem. Note that there is a monster in the tile, that could be a factor.

**EXTRA FILES:**
Morgue:
[dcss-bug.txt](https://github.com/crawl/crawl/files/4939363/dcss-bug.txt)
Screenshot:
![dcss-bug](https://user-images.githubusercontent.com/18044605/87816690-21ded280-c83e-11ea-8e30-d5cd6ddc1101.png)

**Comment by Goratrix** [comment]
Related mantis ticket:
https://crawl.develz.org/mantis/view.php?id=12269
and possible culprit commit:
968d922

**Comment by wheals** [comment]
I'm not sure what fixed this, but I can reproduce this trivially in 0.25 but not in trunk.
