### ISSUE TITLE
game reports floor items at feet every turn, regardless of message.floor setting in rcfile

### ISSUE THREAD

**Issue by Diojeanne** [crawl/crawl#1494]
**PLATFORM and OS or BROWSER:**
Webtiles, Firefox 68.10.0esr (CAO)

**DCSS VERSION:**
Game started: 0.26-a0-394-g0b5ff55
Current version: 0.26-a0-408-g89fe4bc

**DESCRIPTION:**
Very reproducible: simply stand on a tile where an item is on the floor and fight something. After every action, the list of items at your feet will be printed to the message log, even if message.floor = mute or message.floor = off appears in your rcfile. This is not the behavior of .25, so it must be a recent commit that's done it, likely something touching items.cc.

Here are the complete options in my rcfile just in case one or more of them are related:

pickup_thrown = true
hp_warning = 50
hp_colour = 60:yellow, 25:red
autofight_throw = true
default_manual_training=true
autofight_stop = 60
tile_cell_pixels = 48
tile_show_demon_tier = true
stat_colour = 1:lightred, 3:red, 8:yellow
enemy_hp_colour = blue green yellow brown magenta red
message.floor = off

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/12580216/88320371-5c2ef080-ccd2-11ea-9920-94121b5a7f9e.png)

**Comment by crystalsolenoid** [comment]
Happening for me too on CAO, 0.26-a0-415-g2a96157 (webtiles), Firefox 78.0.2.
You don't have to be attacking on the turn for it to happen, either.
```
 You drop a +0 buckler. The ufetubus hits you. x3
_The ufetubus hits you but does no damage.
 You see here a +0 buckler.
_You swing at nothing.
 You see here a +0 buckler.
 The ufetubus hits you.
 The ufetubus hits you but does no damage.
_The ufetubus barely misses you. The ufetubus hits you.
 You see here a +0 buckler.
 You whack the ufetubus!
 You kill the ufetubus!
_Trog accepts your kill.
 You see here a +0 buckler.
_You swing at nothing.
_You swing at nothing.
```
It also happens with a paralyzed monster, skipping a turn waiting for a monster to come towards you, and spellcasting with monsters around.

330158afa59c0df727ea9783b7ae975528344514 was committed 10mins before this issue was opened and touches the "You see here a..." code?

**Comment by Diojeanne** [comment]
10 minutes is cutting it too close to plausibly be the origin. I can't see a precise time on the commit, but I'd noticed the issue on CAO trunk at least a few hours before opening the issue, I had to discuss it with a few other players and fiddle with my options file first.
