### ISSUE TITLE
Palentonga: No confirmation message when rolling into excluded area.

### ISSUE THREAD

**Issue by crystalsolenoid** [crawl/crawl#1496]
**PLATFORM and OS or BROWSER:**
Webtiles, Firefox 78.0.2

**DCSS VERSION:**
0.26-a0-415-g2a96157

**DESCRIPTION:**
Palentonga's Rolling Charge does not ask to confirm when the charge will end in a travel-excluded square.

- When walking from an unexcluded square to an excluded one, I see the message "Really walk into a travel-excluded area?" and have to confirm.
- When charging into a monster from an unexcluded square and landing on an excluded square, there is no confirmation message and the game lets you just roll into danger without a second thought.

I was able to reproduce by excluding the area I was about to charge into.

**Comment by ebering** [comment]
Thanks for the report, fixed!
