### ISSUE TITLE
ASSERT(valid_cursor_pos(pos.x, pos.y, region)) in 'libconsole.h' at line 58

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1497]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console

**DCSS VERSION:**
0.25.1 (using the .deb from http://crawl.develz.org)

**DESCRIPTION:**
I start the game, and load the character up. I select "Maximize vertical". This makes the window about 80x90, but the game crashes with the message:

ASSERT(valid_cursor_pos(pos.x, pos.y, region)) in 'libconsole.h' at line 58 failed. (invalid cursor position 40,-56 in region 1)

If I start the game with an 80x90 window, it opens correctly, but making the window smaller, and then larger again, also makes it crash. If I make the window narrower or wider, even if I make it higher at the same time, it doesn't crash.

**EXTRA FILES:**
[crash.zip](https://github.com/crawl/crawl/files/4976624/crash.zip)
This contains the save file and the crash report.

**Comment by rawlins** [comment]
Thanks for the report! The zip file seems to be empty (I just get directories `home/user/` with nothing in them). Probably just the crash report is all we need, though I expect that this will be easy to replicate for our linux devs. What terminal are you using?

For anyone following up: this bug doesn't seem to replicate as described on mac with Terminal.app, but I can get potentially related crashes where what *seems* to be happening is that multiple resizes in fast sequence can occasionally lead to the the `crawl_view` state being out of sync with the ncurses state. If the curses window is actually smaller than crawlstate thinks it is, the monster list will overwrite onto the next line, and a crash with one of these checks happens. I haven't figured out how the two get out of sync yet.

**Comment by Aliscans** [comment]
Sorry; I didn't think about the directories in the archive. The files should be in home/user/.crawl. I've attached a copy where they're in the base directory, if that makes things easier.

I ran Crawl in xterm 358 in that session. I've also had the same thing happen in urxvt 9.22.
[crash2.zip](https://github.com/crawl/crawl/files/5006120/crash2.zip)

**Comment by robertxgray** [comment]
I think PR #3068 fixes the crash. @Aliscans can you test it please?

**Comment by Aliscans** [comment]
Sadly, I don't think I can. I can no longer reproduce the crash using the same versions of Crawl and XTerm, so I don't know if this would have helped then.

I don't understand the problem well enough to know what else might have been a factor.

**Comment by robertxgray** [comment]
> I can no longer reproduce the crash using the same versions of Crawl and XTerm

That's unexpected. I was able to make it crash easily by using XTerm (version 375 from Fedora) and Crawl trunk. I works okay with other terminal emulators. Anyway, I need to make further tests because rawlins detected a problem in the fix I proposed.

**Comment by robertxgray** [comment]
I was able to make the game crash with the other terminal emulators I tested. They are far more resistant than XTerm but if you keep resizing you get the crash eventually. @Aliscans are you using wayland by chance? I didn't get on that boat yet.

Please @rawlins have a look at c83c593 when you can. It's only supported by the "works for me" seal of quality but it may improve the user experience... at least for some users.

**Comment by robertxgray** [comment]
Just made some tests using a basic Weston installation with same results. The game crashes when using weston-terminal and commit c83c593 stopped the crashes. No differences between X11 and wayland, at least with my nvidia graphics.

**Comment by Aliscans** [comment]
Sorry, it was my mistake. When I was trying to running it from trunk I was actually building the webtiles version and running that from the console. When I build the console version, it does crash when I change the window height from 90 to 24 and back again.

Your change does stop it from doing so, but I'm a bit concerned about the way it does it. In trunk, the `save_cursor_pos` ensures the position is the same at the start and end of the `clrscr()` function. With your change, the position is saved and immediately forgotten.

You could stop this by making `save` a pointer which was freed at the end of the function.

I don't know what assumptions the game makes about the cursor, so I don't know if any of this matters.

**Comment by robertxgray** [comment]
> Your change does stop it from doing so, but I'm a bit concerned about the way it does it.

I must admit it's the first time I see a RAII object and I didn't understand it's purpose (thanks rawlins). Please check the new solution proposal in commit c83c593 (no PR yet).

With the new solution save_cursor_pos' lifecycle doesn't change. Instead, if the cursor position is invalid, it does nothing. I made test with different terminals and didn't detect any drawbacks.

**Comment by Aliscans** [comment]
Your change made everything work in my original scenario. I've found a similar one where it still crashes. I don't know if it would be better to keep that separate.

If I make Crawl repeat a command (typing 0500s, for example) and then shrink the window, Crawl crashes in `wrapcprint_skipping()`. I can prevent this crash by having `wrapcprint_skipping()` return when the cursor is invalid instead of crashing, but that means that the screen looks odd until it gets redrawn properly.

I've attached a crash log, and a patch which stops it from crashing, but doesn't fix the screen until I press a key.
[crash.txt](https://github.com/crawl/crawl/files/11163876/crash.txt)
[dif.txt](https://github.com/crawl/crawl/files/11163806/dif.txt)

Crawl also crashes if I shrink the screen while it is generating levels. I'd try other things, but I can't think of anything else which keeps Crawl busy for long enough.

**Comment by rawlins** [comment]
The trick with fixing this report by removing the `ASSERT` is: the cursor position should never be invalid. So if it is, at any point, then there's a bug, and it is likely to cause problems somehow, sooner or later; IIRC I added a bunch of these `ASSERT`s for cursor position by region to head off such issues earlier rather than later. If removing this particular `ASSERT` were to let console handle resizing without crashing, that might be worth it, but I'd worry that it doesn't fix the underlying problem. Removing more `ASSERT`s like this would probably be the wrong solution for sure.

Also, it seems I never wrote this in this issue (maybe just in crawl-dev), but on a mac after originally looking at this bug in 2020 I was able to replicate it pretty reliably by rapidly resizing a terminal window back and forth for a while.

**Comment by robertxgray** [comment]
I found another bug while testing. After resizing the window, the mouse is disabled until you press a key. This is fixed if you remove libunix.cc, line 888: `set_mouse_enabled(false);`

About the crashes, it seems that ncurses' getcury function can return negative values while running clrscr() after the window is vertically resized. Not every terminal behaves the same but I would say the chances of crashing increase with the window size's change speed. I didn't find anything related in the [bug-ncurses Archives](https://lists.gnu.org/archive/html/bug-ncurses/), but maybe I didn't use the right terms.

**Comment by robertxgray** [comment]
After some debugging I confirmed the cursor position is okay. The problem is, when the screen is resized, the cursor is usually at the end of the message area. A big change in the screen size leaves the cursor out of that area.

Another possible workaround could be d3fefc9. It resets the cursor position before clearing the screen for the first time after resizing. Can you provide feedback please? Thank you.

**Comment by Aliscans** [comment]
> Another possible workaround could be [d3fefc9](https://github.com/crawl/crawl/commit/d3fefc9ab6ad90b9a40b305438d13af0a99d5971). It resets the cursor position before clearing the screen for the first time after resizing. Can you provide feedback please? Thank you.

That fixes the original problem here, too. The cursor isn't in a predictable location as the game waits for input, so it shouldn't matter that this moves it.

**Comment by Aliscans** [comment]
> The trick with fixing this report by removing the `ASSERT` is: the cursor position should never be invalid.

I'm not that familiar with curses, but I think you may need to use a pad or something to do that. With stdscr (at least, on my system), resizing the game window moves the cursor immediately if it needs to to keep it on screen. The regions are Crawl structures, so they may not be adjusted until much later.

For a pad, I'm thinking of using one which is normally the same size as the window. The cursor and output functions all use the pad, and the game then uses `prefresh()` instead of `refresh()` to display things.

That way, any failures caused by screen resizes will happen at the `prefresh()`, and any cursor problems will be due to something else.

> Also, it seems I never wrote this in this issue (maybe just in crawl-dev), but on a mac after originally looking at this bug in 2020 I was able to replicate it pretty reliably by rapidly resizing a terminal window back and forth for a while. Edit: or rather, I did write it, but just not very clearly...

From what you are saying, it sounds as though your system handles this in a different way to mine.

With the default configuration, it crashes on my system if I load a game in an 80x25 terminal, and then enlarge, shrink and enlarge it again, however long I wait between changes. Doing this quickly may be able to trigger other problems, but it isn't needed.

**Comment by robertxgray** [comment]
I made a PR with the latest fix and some other related ones, please have a look.

**Comment by robertxgray** [comment]
> If I make Crawl repeat a command (typing 0500s, for example) and then shrink the window, Crawl crashes in `wrapcprint_skipping()`

It still crashes with the fixes but at a different function. If I can find a solution for this use case the patch is probably good to go.
