### ISSUE TITLE
0.26 Enchant dancing weapons (like elf:2) not leaving the item

### ISSUE THREAD

**Issue by ezmonkey4** [crawl/crawl#1498]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION:**
0.26-a0-438-g4b1dca4f87

**DESCRIPTION:**
enchanted weapons in elf:2 are not leaving the weapon that they were. I'm worshiping gozag, I don't know if that makes a difference. They simply leave a pile of gold. I would expect the weapon that I killed to be there for me to pick up.

**Comment by wheals** [comment]
This is intended behavior. Like all monsters, dancing weapons leave gold when they die if you worship Gozag, and like fleshy monsters, the gold is instead of their "corpse".
