### ISSUE TITLE
Hated By All Wizlab Spam

### ISSUE THREAD

**Issue by crystalsolenoid** [crawl/crawl#1501]
**PLATFORM and OS or BROWSER:**
Webtiles, but could replicate on Console.

**DCSS VERSION:**
0.26-a0-430-ge2a07e3 and 0.26-a0-438-g4b1dca4f87

**DESCRIPTION:**
In the Roulette of Golubria Wizlab, a character who has chosen Ru's "Sacrifice Love" gets multiple messages every turn that something hates them. It interrupts attempts to rest. I didn't even move past the entry chamber.

I replicated it by adding the "hated by all" mutation by Wizard command (no need to worship Ru) and then teleporting to the WizLab branch (and restarting until I rolled Golubria). On version 0.26-a0-438-g4b1dca4f87 (with some unrelated UI code tweaks that shouldn't? touch the seed), seed 3626463608052015758 gave me the right WizLab.

Here's a typical debug-enabled output for one turn attempting to wait.
> _Something feels only hate for you!
 You start waiting.
 Granting xp for non-damage kill. x3
 pathing failed, target 38 34
 Placing eldritch tentacle segment at 35,34
 Created an eldritch tentacle segment.
 Activity interrupt: message
 Something feels only hate for you!
 Placing eldritch tentacle segment at 36,33
 Created an eldritch tentacle segment.
 Something feels only hate for you!
 Placing eldritch tentacle segment at 37,34
 Created an eldritch tentacle segment.
 Something feels only hate for you!
 Placing eldritch tentacle segment at 38,34
 Created an eldritch tentacle segment.
 Something feels only hate for you!

**EXTRA FILES:**
![Screenshot from 2020-07-27 14-15-48](https://user-images.githubusercontent.com/8132415/88599511-cd4b0c80-d020-11ea-84b1-55a2e6ed4e88.png)
I don't FEEL very welcome, Golubria!

**Comment by rawlins** [comment]
Thanks! This was happening because tentacled monster parts are implemented as disposable fake monsters that get generated and destroyed as the monster shrinks and grows, and the sac love check was basically treating them as real monsters.
