### ISSUE TITLE
Can't use https://crawl.develz.org/mantis/ to submit bug reports.

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1506]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using xterm(358) & Firefox 68.0.2

**DCSS VERSION:**
0.25.1 (using the .deb from http://crawl.develz.org)

**DESCRIPTION:**
When Crawl crashes, it prints a message asking the user to submit a bug report at https://crawl.develz.org/mantis/.

The same URL appears in the in-game help.

The "report it as a new bug here" link on that page goes to an "Access Denied." page. I do not have an account on that web site, and could not find a way to submit a bug report on it.

I would prefer it if the game gave clear instructions on how anyone can submit a bug report, either directly or by reference to a URL.

**Comment by rawlins** [comment]
Thanks for the report, new signups on mantis are locked for reasons largely not under the overall team's control, so we have been slowly shifting to using the github issue tracker. I've updated the main documentation points accordingly.

**Comment by Aliscans** [comment]
On Sun, 02 Aug 2020 19:29:37 +0000 (UTC)
Kyle Rawlins <notifications@github.com> wrote:

> Thanks for the report, new signups on mantis are locked for reasons
> largely not under the overall team's control, so we have been slowly
> shifting to using the github issue tracker. I've updated the main
> documentation points accordingly.
> 

Hi

Thanks for changing that. I did wonder if it could be a browser
issue or something like that when I first looked at the mantis page.

Kieron

--
