### ISSUE TITLE
regression: Barachi can hop without delay on trunk

### ISSUE THREAD

**Issue by 1player** [crawl/crawl#1517]
**PLATFORM and OS or BROWSER:** Browser, CXC

**DCSS VERSION:** 0.26-a0-386-g8013e45:

**DESCRIPTION:**

On this commit a Barachi character can do consecutive hops without having to wait for the -Hop status to disappear.

**STEPS TO REPRODUCE:**

1. Create a Barachi character
2. Hop
3. Note the -Hop status
4. Hop again

**Comment by 1player** [comment]
Fixed on current HEAD by commit 7d7832473c

**Comment by rawlins** [comment]
Thanks for the report!
