### ISSUE TITLE
Searing Ray follows movement of enemy

### ISSUE THREAD

**Issue by 1player** [crawl/crawl#1521]
**PLATFORM and OS or BROWSER:** Browser

**DCSS VERSION:** 0.26-a0-466-g989023bd0d

**DESCRIPTION:**

Used Searing Ray in the open, on an enemy that was blinded. The enemy moved after the first ray, and the next rays were cast towards the new position of the enemy. I would assume the ray's direction to be constant.

Sorry, I don't have any way of reproducing it but it just happened before my eyes and thought it might be a bug.

**Comment by ebering** [comment]
This is the intended behavior of the spell.
