### ISSUE TITLE
A ghost with a nonexistent spell

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1522]
PLATFORM and OS or BROWSER:
Linux 3.16.0 console using XTerm(358)

DCSS VERSION:
Crawl version 0.25.1 (using the .deb from http://crawl.develz.org)

**DESCRIPTION:**
A ghost was created on Lair 1, "Kaece the Destroyer" (which wasn't the ghost of a character played locally). It had 5 spells listed, one of which was "d - nonexistent spell". When I saved the game and loaded it again, that spell had gone.

I think the save/load code must do some sort of clean up on ghost powers, but the "place ghost in dungeon" code doesn't do this. 

I've attached a file with the save game, and a screenshot of the monster description from before I saved it.
[game.zip](https://github.com/crawl/crawl/files/5065890/game.zip)

**Comment by ebering** [comment]
I believe @rawlins fixed this in trunk but I can't find the commit 601c79e3d but I'm not currently able to double check.

**Comment by Aliscans** [comment]
Thanks. I didn't look at trunk, as I couldn't find a way to create a specific ghost.
