### ISSUE TITLE
Dithmenos shadow cuts off hydra heads (that regrow regardless of weapon brand).

### ISSUE THREAD

**Issue by AlexanderPosch** [crawl/crawl#1529]
**DCSS VERSION:**
Webtiles 0.26-a0

**DESCRIPTION:**
Dithmenos shadow cuts off hydra heads. Also two heads regrow even when the wielded weapon has the fire brand. 

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/49498206/90966787-1b93e400-e4d7-11ea-9058-d0a3214d55e3.png)

**Comment by ebering** [comment]
This is working as intended. Your shadow uses a +0 unbranded shadow mimic of the weapon you're using. The messaging could maybe be clarified here but it's not clear where the needed messaging should go.

**Comment by AlexanderPosch** [comment]
I know that this is not a bug, but I think preventing the shadow from cutting of hydra heads would be quite reasonable. 
It is similar to riposte in the sense that the player has no control over it. (Riposte does not cut of hydra heads).
