### ISSUE TITLE
Rampage does not interact well with Wu Jian

### ISSUE THREAD

**Issue by AlexanderPosch** [crawl/crawl#1531]
**DCSS VERSION:**
Webtiles 0.26-a0 (there was a new trunk update since i spotted this so I'm not sure if it is still relevant)

**DESCRIPTION:**
Rampage does not interact well with Wu Jian, I'm not sure how it should interact but here's what i noticed: Serpents-lash is not triggered during movement towards enemies (even when moving only one tile). Lunge attack does not work after moving two tiles and I believe the attacking of adjacent creatures is also not handled as intended.

**Comment by ebering** [comment]
This is working as intended, per the Wu Jian powers description, Wu Jian abilities do not work with rampaging:

```
Martial techniques are incompatible with more elaborate
methods of moving, and do not combine with charging, digging, hopping, or
rampaging.
```
