### ISSUE TITLE
spectral weapon stops travel when behind runed translucent gates

### ISSUE THREAD

**Issue by michaelastclair** [crawl/crawl#1559]
**PLATFORM and OS or BROWSER:**
Webtiles; Firefox Developer Edition 81.0b7 (64-bit)

**DCSS VERSION:**
0.26-a0-612-gd4d190f45e

**DESCRIPTION:**
A spectral weapon in a 'runed translucent gate' vault stops travel as if it were a monster _not_ in such a vault.

**EXTRA FILES:**

![image](https://user-images.githubusercontent.com/12725654/92552196-9a1ab080-f24f-11ea-8dd6-1c23b6119d15.png)

**Comment by ebering** [comment]
I've been unable to reproduce this (and after discovering the geometry dependence of #1670 I've tried a broad array of test conditions), I believe one of the changes to `i_feel_safe` since this ticket resolved the issue. If you find it happening again please create a save backup if possible.
