### ISSUE TITLE
Game crushed on undefined wand on the ground

### ISSUE THREAD

**Issue by kevasesk** [crawl/crawl#1575]
local tiles. Windows 10

0.26-a0-631-ged93497179

Auto explore pick up some wand (not all) game crashed. If i mouse over on tile with it, it also crushed. So any action with this wand will go crush and the game start from last save or just from level of the current dungeon.

[crash-openai-20200920-225454.txt](https://github.com/crawl/crawl/files/5252670/crash-openai-20200920-225454.txt)

**Comment by wheals** [comment]
I believe this was already fixed in 72c467432.
