### ISSUE TITLE
Identified unrands do not correctly write notes

### ISSUE THREAD

**Issue by magus** [crawl/crawl#1580]
**PLATFORM and OS or BROWSER:**
webtiles
Chrome 85.0.4183.102
http://crawl.akrasiac.org:8080/#play-seeded-0.25

**DCSS VERSION:**
0.25.1-2-g60ff931

**DESCRIPTION:**
When encountering artefact items, there is an automatic note that is taken
https://github.com/crawl/crawl/blob/ed93497179af4b028d739b0e3213d459c628818c/crawl-ref/source/notes.cc#L256

This line runs fine for randarts but does not seem to run for unrands
I've observed this twice now in two separate runs and the common factor seems to be unrands, randarts write this message just fine.

#### Repro: Wyrmbane
```
Seed: 12134159514649495260
Version: 0.25
```

On `D:8` `Maggie` is wielding a `Wyrmbane`, when she comes into view you will see it in the logs but it will not be identified in the notes, like normal artefacts and will never show up in the players morgue file.

#### Repro: Amulet of the Four Winds
```
Seed: 11054727056997975547
Version: 0.25
```

In `E:3` there is a chamber with a `deep elf annihilator` wearing the `amulet of the four winds`, again the item is written in the logs but never identified in the notes. This one is especially obvious because he is in the same pack as a `deep elf elementalist` wearing `+1 leather armour "Gaoloj" {*Corrode rN++ SInv}` which properly shows up in the morgue notes as

```
 47307 | Elf:3    | Entered Level 3 of the Elven Halls
 47628 | Elf:3    | Reached skill level 19 in Armour
 47671 | Elf:3    | a deep elf annihilator comes into view. It is wielding a +0
                  | short sword and wearing the amulet of the Four Winds {rN+
                  | MR+++ Clar}.
 47724 | Elf:3    | Identified the cursed +1 leather armour "Gaoloj" {*Corrode
                  | rN++ SInv}
 47724 | Elf:3    | a deep elf elementalist comes into view. It is wielding a
                  | +1 scythe of protection and wearing the cursed +1 leather
                  | armour "Gaoloj" {*Corrode rN++ SInv}.
```
[magusnn.txt.zip](https://github.com/crawl/crawl/files/5322736/magusnn.txt.zip)

#### Not Repro: Spriggan's Knife
http://crawl.akrasiac.org/rawdata/magusnn/morgue-magusnn-20200926-221631.txt

This one is interesting, `Spriggan's Knife` is found on the ground, not wielded or worn by an enemy. This does properly get logged as a note.

```
  7905 | Lair:2   | Noticed a six-headed hydra
  7922 | Lair:3   | Found the +7 Spriggan's Knife {stab, EV+4 Stlth+}
  8025 | Lair:1   | Reached skill level 9 in Stealth
```

Given the above three repro scenarios, I think it seems to be the edge case of unrands, worn or wielded, but not found on the ground.

**Comment by Goratrix** [comment]
I suppose the reason why this happens (and maybe is intended as such) is that unrands are always pre-identified. The NOTE_ID_ITEM case (which results in 'Identified...' note) is called when an item gets identified (in this situation by being worn by a monster), but that path is not taken for unrands, because they are always already identified (known). The other case you mention is from a different code path (NOTE_FOUND_UNRAND case), which probably would not make sense in the first situation as the item was not 'Found'.

**Comment by magus** [comment]
Thanks that explanation makes sense and confirms what I am seeing. Do you think it would be reasonable to note these items by either changing how they are identified or by creating a new event for this situation? The current behavior feels inconsistent since there is a very specific scenario where artifacts are not noted because they are technically not identified but to a player that feels unclear. The documentation says all artifacts are noted when identified which while correct in this scenario is again maybe not clear to a player. 

https://github.com/crawl/crawl/blob/c07710193ceeb6264850a6cc0b0e5fddc497e847/crawl-ref/docs/options_guide.txt

I would love to make this contribution by the way, if someone is willing to guide me a bit on where to look or the best way they think it would be to go about this change.
