### ISSUE TITLE
Rollback crash when webtiles connection breaks while having 0 skills trained.

### ISSUE THREAD

**Issue by Midn8** [crawl/crawl#1600]
**PLATFORM and OS or BROWSER:**
Windows 10, playing on Firefox Webtiles.

**DCSS VERSION:**
0.26-a0-708-g17f3b190f9

**DESCRIPTION:**
When you have no skills trained due to having hit a skill target, and the game crashes or your connection breaks, it rolls you back to your last save. I can only assume that this is not intended. You can trigger it by refreshing the page or just by having your computer go to sleep or whatever so the connection breaks. This bug has been around since at least the .25 tournament.

**EXTRA FILES:**
https://pastebin.com/vUnyHTms

**Comment by Goratrix** [comment]
This is a known issue since 270f1c6 but seems quite hard to fix, mentioned by advil in ##crawl-dev:

> 11:34:53 <advil> wheals there's a crash originating in 0.25-a (from the patch that does exact skill targeting) where if you close the skill target menu after hitting a skill target during world_reacts, the game crashes; the fix for this is rather complicated because basically no UI should be happening during world_reacts (as it is impossible to save in the middle of, and interactive UI should only happen at points when you can save)
11:37:05 <advil> this is that crash, the signature is that after the disconnect skill menu code repeats "You need to enable at least one skill for training." in a tight loop

**Comment by rawlins** [comment]
I believe this has been fixed as of: https://github.com/crawl/crawl/commit/e0c665c49dfa
