### ISSUE TITLE
Gnolls say that they resume training invocations when changing religions despite training it anyway

### ISSUE THREAD

**Issue by Midn8** [crawl/crawl#1601]
**PLATFORM and OS or BROWSER:**
Online Webtiles

**DCSS VERSION:**
0.26-a0-708-g17f3b190f9

**DESCRIPTION:**
I shouldn't resume training invocations, I was training it the whole time! (abandoned Ru for Yred and got this message).

**EXTRA FILES:**

![image](https://user-images.githubusercontent.com/36286364/97451110-6976ff00-1901-11eb-9800-afb448bb5858.png)

**Comment by Cureja** [comment]
Solved by this pull request where they remove needing relevant items, worship, etc for training. So the resume training text is just removed. https://github.com/crawl/crawl/commit/69557b85ccbad668db97273aa0c4b6d08e918ea7

**Comment by rawlins** [comment]
Yes, looks like this is no longer an issue.
