### ISSUE TITLE
apt packages missing?

### ISSUE THREAD

**Issue by wintersteiger** [crawl/crawl#1625]
More of a question than a bug report: my apt tells me that there is no package with name `crawl` at `deb https://crawl.develz.org/debian crawl 0.25`. It claims there's only `crawl-common` and `crawl-tiles-data` (and then complains because the Ubuntu crawl package is 0.23). Is that package really missing or did I screw up my apt cache somehow?

**Comment by wintersteiger** [comment]
Forgot to mention that I tried to install it on my Raspberry Pi, so this is for armhf. I think the amd64/x86 packages are ok, only armhf is missing; see

https://crawl.develz.org/debian/dists/crawl/0.25/binary-amd64/Packages
vs
https://crawl.develz.org/debian/dists/crawl/0.25/binary-armhf/Packages

**Comment by rawlins** [comment]
We don't currently distribute any arm debs unfortunately, I believe some time in the past we did but no one currently has the resources to do the builds.

Debian itself in both sid and bulseye has armhf debs: https://packages.debian.org/search?keywords=crawl

If you are already ok doing debian on a pi It's not going to be too hard to build, either. We don't test it ourselves but as that link shows you debian does, and IIRC one of the fork servers (for stoat soup) is actually running on a raspberry pi, so it should work without incident.
