### ISSUE TITLE
Absolute Zero destroys gold with gozag

### ISSUE THREAD

**Issue by EugeneJudo** [crawl/crawl#1631]
**PLATFORM and OS or BROWSER:**
webtiles, chrome

**DCSS VERSION:**
0.25

**DESCRIPTION:**
If a monster steps on uncollected gold, then you use absolute zero on them, both the gold they would yield with gozag, and the gold they were standing on disappear. Note that it doesn't get added to your total gold reserves either, as it would with deep water.

**Comment by shummie** [comment]
I believe this was fixed in https://github.com/crawl/crawl/commit/b271ac0e069b9b0f8c97b970a75cab801e8ade7f

**Comment by EugeneJudo** [comment]
Is this just something that remains in 0.25? It definitely still
occurs in 0.25.1-8-g42b30a86e7,
which is used on kelbi (perhaps that's not the most up to date version?)

**Comment by rawlins** [comment]
Yes, it's currently fixed in trunk only; it's possible this would get backported for a hypothetical 0.25.2 bugfix release.

**Comment by gabosandbox** [comment]
Normally, absolute zero creates a block of ice from a monster. However, if I worship Gozag, I don't get the block of ice.

**Comment by wheals** [comment]
> 
> 
> Normally, absolute zero creates a block of ice from a monster. However, if I worship Gozag, I don't get the block of ice.

This is correct and intentional. A monster can't turn into both ice and gold.
