### ISSUE TITLE
Enchant weapon not applying to spectral brand

### ISSUE THREAD

**Issue by oktalk** [crawl/crawl#1633]
**PLATFORM and OS or BROWSER:**
Webtiles: Mac Catalina, Chrome browser 87

**DCSS VERSION:**
DCSS trunk on https://cbro.berotato.org:8443/

**DESCRIPTION:**
I added the spectral brand to my weapon then used a few enchant weapon scrolls. None of them applied.

![Screen Shot 2020-12-10 at 9 34 06 AM](https://user-images.githubusercontent.com/158135/101793621-9eaf6900-3acb-11eb-8a6c-0d3643e0bc61.png)

![Screen Shot 2020-12-10 at 9 34 34 AM](https://user-images.githubusercontent.com/158135/101793633-a1aa5980-3acb-11eb-8d67-f97626e52327.png)

**EXTRA FILES:**
*Please include any morgue files, crashlogs, save files here, or extra
screenshots here. If this is a crash bug, the crashlog and save file will be
extremely helpful; the location of these is sytem-specific but if you ask
we can help you find them.*

*To upload a save file directly to github, compress it to a .zip archive, and
then github will accept the upload. (It will not take a .cs file directly.)*

*If this is an online game, see [these instructions](https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup)
for more information on how to make a save backup; you can provide the
resulting link here.*

**Comment by shummie** [comment]
It looks like you may not have identified the weapon yet. The enchantment value will be revealed once you identify or wield the weapon.

**Comment by rawlins** [comment]
I tested this out and I think @shummie is exactly right -- a partially id'd weapon can happen if you brand an un-id'd floor weapon. If you now read id on it (or just wield it) you will see the effect of your enchant weapon scrolls. This is in some sense not a bug, though it's pretty odd for a partially id'd weapon to still be possible.
