### ISSUE TITLE
Explore doesn't search the map boundary

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1636]
**PLATFORM and OS or BROWSER:**
Linux 3.16 using XTerm(358)

**DCSS VERSION:**
0.26-a0-1049-g242049e08c

**DESCRIPTION:**

If I load the below save file and press o, it says "Done exploring.".

There's a tile not far above the @ which is in the explore horizon, and a second at the bottom of the map. I would expect it to search for these.

Having looked into it, the problem seems to be that Crawl doesn't consider exploring the map boundary.

The patch below (dif.txt) seems to make it act as I'd expect, but it will need testing.
**EXTRA FILES:**
[Cthoga.cs.gz](https://github.com/crawl/crawl/files/5682167/Cthoga.cs.gz)

[dif.txt](https://github.com/crawl/crawl/files/5682168/dif.txt)

**Comment by wheals** [comment]
This is working as intended -- the map boundary can never contain anything interesting, so there's no reason to autoexplore there.
