### ISSUE TITLE
Spellbook lists don't show Vehumet's gifts as being known

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1638]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 using XTerm(358) console

**DCSS VERSION:**
0.26-a0-1057-g5b34608550

**DESCRIPTION:**
If Vehumet is offering you a spell, which you haven't memorised, then the game treats it like a spell which wasn't in your library in a couple of situations:

1. If you look at the information for a spellbook containing the spell (e.g. through help, or in a shop), it shows the spell as not being known.

2. If you pick up a spellbook which contains the spell, it tells you that you add that spell to your library.

Something is changing with the spell in the second case, so it may be worth mentioning something about the spell. It was already in the spell list, though.

I've enclosed a copy of a save file in which Vehumet is offering Shock, and the @ is standing on a Book of the Air. If you look at the help for the book,  it says Shock isn't known, and if you pick the Book of the Air up, it includes Shock in the list of spells you add to your library.

**EXTRA FILES:**

[test.cs.zip](https://github.com/crawl/crawl/files/5683951/test.cs.zip)

**Comment by wheals** [comment]
This is intentional. You might not have the spell slots to learn the spell before Vehumet changes to a different one, for example. It's a bit of an edge case, but it's better than a book with that spell being marked useless when it might still come in handy.
