### ISSUE TITLE
Absolute Zero indicates the location of invisible monster without Sinv

### ISSUE THREAD

**Issue by ukdong90** [crawl/crawl#1641]
**DCSS VERSION AND GAME INFORMATION:**
0.26-a0-1080-g4c0aae810e

**DESCRIPTION:**
When your character has no Sinv, you have to find an invisible foe with random detection(white phantom image). However, if you cast Absolute Zero with 'Z', you can specify its location. This bug has occurred since new spell casting and aim system had been updated.

**EXTRA FILES:**

![캡처](https://user-images.githubusercontent.com/65288602/102081521-b97b3800-3e53-11eb-9d7a-aaf3ad4703d0.PNG)
![캡처2](https://user-images.githubusercontent.com/65288602/102081524-baac6500-3e53-11eb-8e21-420ecd3b182a.PNG)
![캡처3](https://user-images.githubusercontent.com/65288602/102081525-baac6500-3e53-11eb-8761-af7009c27c55.PNG)

**Comment by rawlins** [comment]
Thanks for the report! As you can see from the fix commit, this was a very general issue.
