### ISSUE TITLE
New drain and transformation together cause bug

### ISSUE THREAD

**Issue by gabosandbox** [crawl/crawl#1644]
**PLATFORM and OS or BROWSER:**
Browser

**DCSS VERSION AND GAME INFORMATION:**
Version history for your current game:
Game started: 0.26-a0-660-gc07710193c
0.26-a0-661-g406de6ba63
0.26-a0-662-g8b9c6dab81
0.26-a0-663-g36e8fdb655
0.26-a0-665-gefeb406119
0.26-a0-668-gd58323b419
0.26-a0-682-g294304f6e8
0.26-a0-683-g5206c1d7ac
0.26-a0-690-gcb57259078
0.26-a0-695-g987792ac36
0.26-a0-707-g31817bcca1
0.26-a0-708-g17f3b190f9
0.26-a0-712-ga5a9c9c9d0
0.26-a0-720-g2a1d101370
0.26-a0-737-g4e9f4955e2
0.26-a0-757-g626ac9e51a
0.26-a0-771-g060e6a62af
0.26-a0-778-g3fe0686644
0.26-a0-818-g75db068ed4
0.26-a0-835-g8259106e14
0.26-a0-844-g3dd439832f
0.26-a0-846-gcc8f1ee719
0.26-a0-952-g76694b35de
0.26-a0-958-gf3041fb45f
0.26-a0-966-gd078a86f14
0.26-a0-1021-gda264ca44c
0.26-a0-1026-g544776af23
0.26-a0-1033-gd598b01645
0.26-a0-1040-gbe3abf3417
0.26-a0-1053-gaff5f71418
0.26-a0-1060-g086102a3f0
0.26-a0-1086-g9010512d90

**DESCRIPTION:**
1. Don't use any transmutation
2. Wield a *drain weapon
3. Cast necromutation (maybe 1-4 times. i am not sure.)
4. Unwield weapon
5. Kill monsters t get rid of drain status
6. Now I have about 3 times max hp than I should. For example, originally I have something like 200/200 hp. Now I have 200/600 hp.
7. Wait for the transformation to end. Somehow I only have about 50% hp. For example, when I have 200/600 hp in lich form. When the transformation ends, I have about 100/200 hp. This is quite dangerous in zig.

**Comment by rawlins** [comment]
Thanks for the report! I believe this is fixed by db0aba6ef. If you see it again definitely feel free to reopen.
