### ISSUE TITLE
Demonic guardian defense protocalls are overkill

### ISSUE THREAD

**Issue by Midn8** [crawl/crawl#1646]
**PLATFORM and OS or BROWSER:**
Webtiles (CBRO2)

**DCSS VERSION AND GAME INFORMATION:**
0.26-a0-1107-g6118521029

**DESCRIPTION:**
Several things are prompting for a "Really attack your @foo@?" message for demonic guardians that don't harm them at all. In this run so far I've found that Disaster Area (but not upheaval) and pproj damnation bolt AoEs will both prompt this message, though the demonic guardian is immune.

**Comment by ebering** [comment]
If you could report any further inconsistencies that you've noticed that would be great. The dg should be immune but these prompts are not all sent through stop_attack_prompt in the right way...

**Comment by ebering** [comment]
There has been a lot of work in the subsequent 6 months cleaning up these checks, please re-open if there are new issues.
