### ISSUE TITLE
Game crash report

### ISSUE THREAD

**Issue by ukdong90** [crawl/crawl#1650]
**PLATFORM and OS or BROWSER:**
Webtiles on CWZ server

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.26-a0-937-g67df3f2

**DESCRIPTION:**
https://webzook.net/soup/morgue/trunk/cortm/crash-cortm-20201220-085642.txt
https://webzook.net/soup/morgue/trunk/cortm/crash-cortm-20201220-090628.txt
https://webzook.net/soup/morgue/trunk/cortm/crash-cortm-20201220-101808.txt
https://webzook.net/soup/morgue/trunk/cortm/crash-cortm-20201220-103735.txt

ERROR in 'mon-util.cc' at line 686: bogus mc (no monster data): invalid monster_type 1000 (1000)

**Comment by wheals** [comment]
Looks like this was fixed in https://github.com/crawl/crawl/commit/52035dc9a5b8
