### ISSUE TITLE
Local mac tiles trunk selection cursor not visible

### ISSUE THREAD

**Issue by liammcd** [crawl/crawl#1658]
Trunk version 0.26-a0-1184-g95e395e029, mac local tiles. 

The selection/targeting cursor when firing with 'f', examining with 'x', and evoking wands is not visible when moving target with keyboard keys

Trying to e'x'amine a monster, can't move selection with keyboard commands. Selection is visible when the mouse is moved to it, but making keyboard movements doesn't move the cursor but does change what is being examined. For firing and evoking the trajectory is highlighted by the selection cursor is not visible

**Comment by Goratrix** [comment]
Same issue on windows, mantis ticket here: https://crawl.develz.org/mantis/view.php?id=12424

Commit which has caused this: 1cd98bb

**Comment by wheals** [comment]
Fixed in https://github.com/crawl/crawl/commit/98a0ced1662f21ddcde53023d722fcd2efd3f7e6
