### ISSUE TITLE
_Unknown command Infinite lua loop detected

### ISSUE THREAD

**Issue by 4d30** [crawl/crawl#1661]
$ crawl -version
Crawl version 0.25.1
Save file version 34.219
Compiled with GCC 7.5.0
Build platform: i486--netbsdelf
Platform: i486--netbsdelf
CFLAGS: -O2 -pipe -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/pkg/include/lua-5.1 -DWIZARD -DASSERTS -DCLUA_BINDINGS -DSAVE_DIR_PATH="~/.crawl" -DDATA_DIR_PATH="/usr/pkg/share/stone-soup/"
LDFLAGS: -rdynamic -fuse-ld=gold -O2 

$ uname -a
NetBSD carbon 9.99.77 NetBSD 9.99.77 (CARBON) #8: Sun Dec 27 16:28:10 UTC 2020  joey@hydrogen:/usr/obj/sys/arch/i386/compile/CARBON i386

Once the dungeon is drawn and you're in 'the game,' the console is spammed with _Unknown Command. If I add a macro for {\27} I am able to change the spam message to another command so I think there is some loop which spams the ESC key. Eventually there is a Infinite Lua Loop detected message.

The game process registers keystrokes like movement/battle interspersed with {\27} spam.

The process consumes the entire CPU and lags the whole machine.

**Comment by rawlins** [comment]
This seems like it might be platform-specific. If this came from a netbsd package, it would be worth reporting it to whoever built it. Also, can you confirm that your `init.txt` file is empty / default?

**Comment by rawlins** [comment]
It occurs to me that this could also be `TERM` related (if somehow an escape code is being let through to the game), what value do you have set for that?

**Comment by 4d30** [comment]
Some details for you:
$ echo $TERM
xterm

init.txt is the default one that's all commented out. 

I'll open a PR at pkgsrc as well.

**Comment by niacat** [comment]
I'm pretty sure this is a compatibility issue between crawl and NetBSD's libcurses.

For testing, a [portable version of netbsd curses](https://github.com/sabotage-linux/netbsd-curses) is available.

For now I'll roll back the pkgsrc package to use ncurses. This is what I get for only testing the tiles version...
