### ISSUE TITLE
Conveying which gods don't use invocations

### ISSUE THREAD

**Issue by MIC132** [crawl/crawl#1662]
With the recent changes to skill training that allow training all skills at all times, it is now possible to train Invocations while worshipping a god that doesn't use them (or when worshipping no god). While for an experienced player this is a non-issue, newer players might (reasonably, I think) assume that Invocations work for all gods, since the information that they don't for some isn't clearly conveyed. Some, like Ashenzari, have explicit statements about this ("Ashenzari's powers are based on piety instead of Invocations") but some, like Vehumet, don't.

Since using Invocations is generally the default I think it would make sense for all the non-invo gods to have a line in the powers screen similar to the Ashenzari one, to make it clear they don't benefit from Invocations.

**Comment by rawlins** [comment]
Thanks for the report, this definitely needed a revisit!
