### ISSUE TITLE
Orange Statue through clear wall prevents autoexplore

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#1670]
**PLATFORM and OS or BROWSER:**
webtile .26

**DESCRIPTION:**
If you can see an orange crystal statue through a clear wall it prevents autoexploring even though there is no way for it to harm you. This happened after entering the tower shield of ignorance vault. Gfunk said that it should be in the "I feel safe stuff"

**EXTRA FILES:**

![image](https://user-images.githubusercontent.com/70080435/103496643-05931a00-4e0d-11eb-86e8-75c97b8333f4.png)

**Comment by ebering** [comment]
Can you provide your RC settings and a chardump with the version string? I can't replicate this in 0.26-b1-32-g5d43845318 (my current tournament game on cxc also spawned the vault).

**Comment by ardl** [comment]
The main rc file is https://cbro.berotato.org/rcfiles/crawl-0.26/ardl.rc with forcemores included from this rc https://cbro.berotato.org/rcfiles/crawl-0.26/ardlmore.rc and message coloring from https://cbro.berotato.org/rcfiles/crawl-0.26/ardlcolors.rc

The version string is 0.26-b1-32-g5d43845318

Chardump is https://cbro.berotato.org/morgue/ardl/morgue-ardl-20210104-204318.txt

I had entered the vault and closed the door again to prevent the summons from chasing me, that might've had something to do with it.
