### ISSUE TITLE
Ctrl+Direction Allows directional melee while confused

### ISSUE THREAD

**Issue by nikheizen** [crawl/crawl#1676]
**PLATFORM and OS or BROWSER:**
*All platforms.*

**DCSS VERSION AND GAME INFORMATION:**
*0.26, 0.27a*

**DESCRIPTION:**
Ctrl+direction allows you to melee in the chosen direction while standing still instead of printing a "You are too confused!" message.

**Comment by rawlins** [comment]
Thanks this was already fixed in 838eb4c31eb7d / b5863c6483, but some servers may still need a manual rebuild.
