### ISSUE TITLE
auto_item_letters isn't checked if you buy something which merges with an existing item and identifies it.

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1684]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-77-gd04b7445b5

**DESCRIPTION:**
Start the game in the attached save file with 

gunzip test.cs.gz
crawl -extra-opt-last save_dir=. -extra-opt-last item_slot=noise:n -name test

If you read item **b**, it's identified and it becomes item **n**.
If you drop item **b**, and buy a scroll of noise from the shop on your square, that's item **n**, and the scrolls at your feet are identified.
If you buy a scroll of noise from the shop without dropping your scrolls, you have 13 identified scrolls of noise in slot **b**.

I would expect the objects to be reassigned when you identify them, however you do this. _merge_stackable_item_into_inv() doesn't do it, though.

**EXTRA FILES:**
[test.cs.gz](https://github.com/crawl/crawl/files/5811110/test.cs.gz)

**Comment by ebering** [comment]
Duplicates #1685
