### ISSUE TITLE
Unequiping armour with W and equip_unequip = true ignores !T

### ISSUE THREAD

**Issue by Rytisgit** [crawl/crawl#1688]
**PLATFORM and OS or BROWSER:**
webtiles opera

**DCSS VERSION AND GAME INFORMATION:**
0.26.0-10-g1f06aea511

**DESCRIPTION:**
Unequiping armour with W and equip_unequip = true ignores !T
Works when unequiping currently worn items, not when switching to a new armour

**Comment by PleasingFungus** [comment]
Can no longer replicate this - seems to work fine now. Thanks for reporting, and sorry for the delay!
