### ISSUE TITLE
Scores only load after dying

### ISSUE THREAD

**Issue by slifty** [crawl/crawl#1694]
**PLATFORM and OS or BROWSER:**
I'm running local tiles on OSX 10.14.6

**DCSS VERSION AND GAME INFORMATION:**
0.26.0

**DESCRIPTION:**
I'm trying to move my morgue and saves in a dropbox folder instead of the default location (hoping to sync across devices eventually but that's another story).  I've been attempting to do this using the following `init.txt` settings:

```
crawl_dir = /Users/slifty/Dropbox/Apps/dcss
morgue_dir = /Users/slifty/Dropbox/Apps/dcss/morgue
save_dir = /Users/slifty/Dropbox/Apps/dcss/saves
```

Saves and morgue files are showing up in the right place, but high scores are not being loaded when I first open dungeon crawl.  The high scores *are* however loaded when a character dies, and then the high score list option works from the menu.  Gif attached to show this behavior.

![dcss_bug](https://user-images.githubusercontent.com/208884/105532138-6b5e1d80-5cb8-11eb-941b-c850cfc293aa.gif)

Note: I originally had not populated the `crawl_dir` setting but added it because I was getting the following error on death:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/208884/105531999-2f2abd00-5cb8-11eb-8750-95422ada3921.png">

I appreciate that the most likely root cause here is user error, but I wanted to raise it in case something else is going on.

Here is the contents of the saves directory in case it is useful:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/208884/105532386-c132c580-5cb8-11eb-9a77-0de099f3aa61.png">

**Comment by ebering** [comment]
If you are amenable to building your own crawl, you can use the makefile option `SAVEDIR` to build crawl binaries pointed at the right place.

Otherwise, this is indeed a bug and not user error! A fix will be applied to trunk soon and shipped in the forthcoming 0.26.1 bug fix release.
