### ISSUE TITLE
Beastly Appendage melds Octopode's hat without giving horns.

### ISSUE THREAD

**Issue by dillytin** [crawl/crawl#1699]
**DCSS VERSION AND GAME INFORMATION:**
0.26 released version 

**DESCRIPTION:**
![캡처](https://user-images.githubusercontent.com/65288602/105675621-b5e7d000-5f2c-11eb-8e69-ca600511d6cd.PNG)

I think it doesn't need to meld a hat if it give spikes, not horns. 
Save poor little octopus plz

**Comment by amulder87** [comment]
I noticed this too, seemed weird when they don't get a headbutt attack.

**Comment by semitonal** [comment]
This is intended behaviour, as per 0fb1eaa16f (so that Op don't just get to cast Appendage with no downside at all).
