### ISSUE TITLE
Unable to set fractional skill targets when using non-english system locale

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#1704]
**DCSS VERSION AND GAME INFORMATION:**
Crawl version 0.27-a0-163-ge9b1cf51b5

**DESCRIPTION:**
I want to set fractional numbers as a skill target, e.g 4.5. If you try to do this in the current trunk of DCSS, the target is floor'd to the integral number 4.

The bug here is that if my current skill points are let's say 4.4 and i set the target to 4.5, it's set to 4 instead, not training the skill anymore despite i wanted the extra 0.1.

Edit: Sorry for the insufficient report, see my next comments for more information.

**Comment by ebering** [comment]
Can you provide details about what ui version (console, local tiles, or  webtiles) and what platform (os and browser) you're using?

This does not replicate in console on OS X.

**Comment by randomMesh** [comment]
I am playing local tiles:

```bash
Crawl version 0.27-a0-169-gd3d0dda1a4
Save file version 34.227
Compiled with GCC 8.3.0
Build platform: i686-linux-gnu
Platform: i686-linux-gnu
CFLAGS: -O2 -pipe -DUSE_TILE -DUSE_TILE_LOCAL -DUSE_SDL -DUSE_GL -DUSE_FT -D_REENTRANT -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua5.1 -isystem /usr/include/freetype2 -I/usr/include/libpng16 -isystem /usr/include/SDL2 -DWIZARD -DASSERTS -DPROPORTIONAL_FONT="/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf" -DMONOSPACED_FONT="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf" -D_REENTRANT -DCLUA_BINDINGS
LDFLAGS: -rdynamic -fuse-ld=gold -O2
```

**Comment by randomMesh** [comment]
I think the problem here is that DCSS uses the comma as a fractional separator on german locales despite the game is in english.

**Comment by randomMesh** [comment]
As a workaround i made a bash script which exports the correct locale before starting crawl
```bash
# <snip>
export LC_NUMERIC="C.UTF-8"
./crawl
# <snip>
```

**Comment by randomMesh** [comment]
Mhm... Thinkinkg about it, the above solution might not be the best. It would be cleaner to leave this as it is but to allow entering fractional separators depending on the system locale.

**Comment by rawlins** [comment]
Thanks for the debugging work -- yes, I agree that it's better to just be locale sensitive in this respect as long as the output and parsing use locale sensitive standard library code.

**Comment by rawlins** [comment]
This is fixed in https://github.com/crawl/crawl/commit/486a53e33331661535c28001dd06c11be61c948a by using a locale-sensitive check for the decimal marker rather than hardcoded `.` during text input. This commit also displays skill targets using the correct decimal operator (which the rest of the skill menu already used).

**Comment by randomMesh** [comment]
Thank you for the quick fix. Works like a charm.
