### ISSUE TITLE
Gnoll has no spell at all with any background

### ISSUE THREAD

**Issue by ukdong90** [crawl/crawl#1707]
**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-170-g607d9e9d85 (latest git version, image below) has this bug.

0.27-a0-163-ge9b1cf51b5 on CWZ also has this bug.

0.27-a0-158-g36630e8 on CAO does **NOT** have this bug

**DESCRIPTION:**
Gnoll has no spell at all with any background.

**EXTRA FILES:**
![캡처](https://user-images.githubusercontent.com/65288602/106108142-360b7100-618b-11eb-8694-4445ca89f481.PNG)
![캡처2](https://user-images.githubusercontent.com/65288602/106108154-39066180-618b-11eb-91dc-f3756f345997.PNG)

![캡처3](https://user-images.githubusercontent.com/65288602/106110004-8388dd80-618d-11eb-8e49-b29a2bb118b7.PNG)

One of those commits caused it, I suppose.

**Comment by ebering** [comment]
Thanks or the detailed report!
