### ISSUE TITLE
Unable to stop flying in dragon form

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#1726]
**PLATFORM and OS or BROWSER:**
webtiles trunk

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-277-g024f7ef292

**DESCRIPTION:**
If you are in dragon form and attempt to stop flying you continue to fly and it also takes a turn.

**Comment by rawlins** [comment]
Resolved by https://github.com/crawl/crawl/commit/cb349572af90, thanks!
