### ISSUE TITLE
Ice dragon scales from hobgoblin on D:2 normal?

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#1729]
**PLATFORM and OS or BROWSER:**
Local tiles

**DCSS VERSION AND GAME INFORMATION:**
Latest master branch (0.27-a0-287-gd4424db430 at the time)

**DESCRIPTION:**
A hobgoblin just dropped me some ice dragon scales on D:2. Is this normal?
I would expect that this type of armour is only dropped by ice dragons on deeper floors.

**EXTRA FILES:**
![scales](https://user-images.githubusercontent.com/32773707/107172170-f7648a80-69c4-11eb-8eaf-7f40fc61e598.png)

**Comment by rawlins** [comment]
It is possible but very rare for armour like this to generate as a regular object in a place like D:2 (just about anything can, but with low probability); generating via killing ice dragons late in the game is indeed a more common way to get it.

**Comment by randomMesh** [comment]
> It is possible

This feels wrong. I would prefer to have items a minimum depth or hit dice they can spawn in.
