### ISSUE TITLE
Ash worshiper cannot read id scroll

### ISSUE THREAD

**Issue by ukdong90** [crawl/crawl#1735]
**DCSS VERSION AND GAME INFORMATION:**
81d27af2d4b107c800646382b6b992708a8b1b34
Lastest version

**DESCRIPTION:**

![캡처](https://user-images.githubusercontent.com/65288602/107476856-095b4e80-6bba-11eb-81e8-fc68a316cc47.PNG)

You can't read id scrolls at all for idetifying.

**Comment by rawlins** [comment]
Thanks for the report, this should be fixed in the referenced commit (barring special cases that I'll leave for ash experts). If an item is in your inventory, saving and reloading on the new version should fix it.
