### ISSUE TITLE
##crawl :Cannot join channel (+r) - you need to be identified with services

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#1741]
Felt bored, wanted to chat a bit in ##crawl over at Freenode but it tells me that i have to register with an email address.

Unfortunately, i cannot use disposable email addresses for Freenode:
`Sorry, we do not accept registrations with email addresses from that domain. Use another address.`

Using my private email is not an option (nor is creating another "real" one).

Do you plan to remove that restriction or am i doomed to not able to chat with you guys?

**Comment by semitonal** [comment]
I don't think there's any plan to remove the +r flag from ##crawl, the channel had major spam issues in the past without it. The channel isn't very active these days anyway though, and the #dcss channel in the /r/roguelikes discord is probably a more active place for general chat.
