### ISSUE TITLE
Ozo's Armour blocks dispersal traps

### ISSUE THREAD

**Issue by shummie** [crawl/crawl#1743]
0.27-a0-334-g52645efa06

Probably due to the change in trying to break ozo's (and ramparts?) after forced movement.

If you have Ozo's armour on, and a disperal trap is hit, the prompt "_Your icy armour will break if you move. Continue?" comes up. Pressing N then keeps you in your spot while the dispersal trap is resolved. See attached for a sample screenshot of this happening.

![0-initial_state](https://user-images.githubusercontent.com/3296707/107844571-15056b80-6d9a-11eb-81ee-928587229bfe.JPG)
![1-trap w armour](https://user-images.githubusercontent.com/3296707/107844572-1767c580-6d9a-11eb-9806-556867389134.JPG)
![2-after trap and no](https://user-images.githubusercontent.com/3296707/107844573-1898f280-6d9a-11eb-9baa-e8393ba98131.JPG)

**Comment by randomMesh** [comment]
Maybe the armour melted a bit and freezed again so you are glued to the ground. May be a bug or a feature. :wink:
