### ISSUE TITLE
Ubuntu package for 0.26.1

### ISSUE THREAD

**Issue by jv84** [crawl/crawl#1763]

**Comment by ebering** [comment]
Could you please elaborate on this ticket? Is something not working? A package missing? From which package repository?

**Comment by jv84** [comment]
It's not updated to the latest version.

**Comment by randomMesh** [comment]
The Crawl version in Debian Stable is 0.23, don't know about Sid.
If you have questions about the Debian packages, you should contact its maintainer: Guus Sliepen <guus@debian.org>
```bash
xxx@xxx:~$ apt show crawl-tiles
Package: crawl-tiles
Version: 2:0.23.0-1
Priority: optional
Section: games
Source: crawl
Maintainer: Guus Sliepen <guus@debian.org>
Installed-Size: 10,5 MB
Depends: libc6 (>= 2.28), libfreetype6 (>= 2.2.1), libgcc1 (>= 1:7), libgl1, libglu1-mesa | libglu1, liblua5.1-0, libsdl2-2.0-0 (>= 2.0.9), libsdl2-image-2.0-0 (>= 2.0.2), libsqlite3-0 (>= 3.5.9), libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4), crawl-common (= 2:0.23.0-1), crawl-tiles-data (= 2:0.23.0-1), fonts-dejavu-core
Homepage: http://crawl.develz.org/
Tag: game::rpg:rogue, implemented-in::c++, implemented-in::lua,
 interface::graphical, interface::x11, role::program, uitoolkit::sdl,
 use::gameplaying, x11::application
Download-Size: 3.465 kB
APT-Sources: http://deb.debian.org/debian buster/main i386 Packages
Description: Dungeon Crawl, a roguelike game, tiles version
 Crawl is a fun game in the grand tradition of games like Rogue, Hack, and
 Moria. Your objective is to travel deep into a subterranean cave complex and
 retrieve the Orb of Zot, which is guarded by many horrible and hideous
 creatures.
 .
 This is the graphical (tiles) version.
 .
 This is the Stone Soup version of Dungeon Crawl.
```

**Comment by rawlins** [comment]
I'm pretty sure this request is about the official crawl deb repository we maintain -- I'm not sure anyone ever did build our 0.26.1 debs.

Debian itself does separately package crawl, and both bullseye and sid already have [0.26.1 releases](https://packages.debian.org/search?keywords=crawl).

**Comment by jv84** [comment]
> I'm pretty sure this request is about the official crawl deb repository we maintain -- I'm not sure anyone ever did build our 0.26.1 debs.
> 
> Debian itself does separately package crawl, and both bullseye and sid already have [0.26.1 releases](https://packages.debian.org/search?keywords=crawl).

Yes, that's what I mean. I haven't got the bugfix release after updating package list so it hasn't been built.

**Comment by randomMesh** [comment]
> Yes, that's what I mean.

Ah, ok. I got confused by 'official Debian repository' then. Sorry for that. :grinning:

**Comment by jv84** [comment]
I assume there won't be an update to the package mentioned on the official download page. Ubuntu doesn't matter to you.

**Comment by gammafunk** [comment]
The Debian packages do matter, but I haven't had time to build these. This is an open source project, and volunteers have limited time and variable schedules, so please keep that in mind and have patience in general.

I should be able to get the 0.26.1 debs built by this Saturday.

**Comment by jv84** [comment]
> The Debian packages do matter, but I haven't had time to build these. This is an open source project, and volunteers have limited time and variable schedules, so please keep that in mind and have patience in general.
> 
> I should be able to get the 0.26.1 debs built by this Saturday.

Great.
