### ISSUE TITLE
Travel says "Done exploring." prematurely if there are exclusions by the unexplored area.

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1766]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-404-g4390dbc5be

**DESCRIPTION:**
A couple of problems with explore and excluded squares:

1 (see Adwydric_Done.cs): There are unexplored parts of the level, but I would need to pass through an excluded area to reach them. If I press o to explore after loading this save, however, it says "Done exploring.", when I haven't explored everywhere.

If I change it _is_travelsafe_square() so that it doesn't reject excluded squares if ignore_hostile is set, it says "Partly explored, can't reach some places". This is better, but it would be nice if it also mentioned the items. 

The change also means that non-excluded floor squares which can't be reached because of the exclusions are highlighted, but I'm ambivalent about that.

2 (see Adwydric_Partly_explored.cs): There are no unexplored parts of the level, but there is an excluded area which reaches the edge of the known area (or possibly stretch beyond it - I haven't checked the range). If I press o to explore after loading the save (with autopickup off), however, it says "Partly explored, can't reach some places.", when I have explored everywhere.

I've edited this after looking into it further.

**EXTRA FILES:**
[dif.txt](https://github.com/crawl/crawl/files/6018685/dif.txt)
[save.zip](https://github.com/crawl/crawl/files/6019041/save.zip)

**Comment by ebering** [comment]
Fixed in #1787
