### ISSUE TITLE
Bus Error (SIGBUS) when starting binary built on FreeBSD 12.2

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#1768]
**PLATFORM and OS or BROWSER:**
Local tiles, built with GCC 10.2.0 on FreeBSD 12.2

**DCSS VERSION AND GAME INFORMATION:**
Latest master branch

**DESCRIPTION:**
The binary built from the latest master branch on FreeBSD crashes with a bus error (SIGBUS) when started.
Do you guys support FreeBSD or should i ask elsewhere?

**EXTRA FILES:**
gdb output from binary compiled with `gmake debug TILES=y`:
```bash
(gdb) r
Starting program: /usr/home/xxx/development/crawl/crawl-ref/source/crawl 

Program received signal SIGBUS, Bus error.
0x2b6adace in vtable for __cxxabiv1::__si_class_type_info () from /lib/libcxxrt.so.1
(gdb) where
#0  0x2b6adace in vtable for __cxxabiv1::__si_class_type_info () from /lib/libcxxrt.so.1
#1  0x2ae450b7 in __dynamic_cast () from /usr/local/lib/gcc10/libstdc++.so.6
#2  0x2aece21a in bool std::has_facet<std::ctype<char> >(std::locale const&) () from /usr/local/lib/gcc10/libstdc++.so.6
#3  0x2aebf6e0 in std::basic_ios<char, std::char_traits<char> >::_M_cache_locale(std::locale const&) () from /usr/local/lib/gcc10/libstdc++.so.6
#4  0x2aebfbbc in std::basic_ios<char, std::char_traits<char> >::init(std::basic_streambuf<char, std::char_traits<char> >*) ()
   from /usr/local/lib/gcc10/libstdc++.so.6
#5  0x2ae59c3d in std::ios_base::Init::Init() () from /usr/local/lib/gcc10/libstdc++.so.6
#6  0x0882f909 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /usr/local/lib/gcc10/include/c++/iostream:74
#7  0x08834cb1 in _GLOBAL__sub_I__Z10invo_skill8god_type () at ability.cc:3911
#8  0x2a8e1c8f in ?? () from /libexec/ld-elf.so.1
#9  0x2a8e0a76 in ?? () from /libexec/ld-elf.so.1
#10 0x2a8de4ae in ?? () from /libexec/ld-elf.so.1
(gdb) 
```
Makefile diff:
```diff
diff --git a/crawl-ref/source/Makefile b/crawl-ref/source/Makefile
index f0d9a00ef4..944ebe8d0d 100644
--- a/crawl-ref/source/Makefile
+++ b/crawl-ref/source/Makefile
@@ -1045,7 +1045,7 @@ ifneq ($(LINKER_LDFLAG),)
 LDFLAGS += $(LINKER_LDFLAG)
 endif
 
-LDFLAGS += $(CFOPTIMIZE) $(CFOPTIMIZE_L) $(EXTERNAL_LDFLAGS)
+LDFLAGS += $(CFOPTIMIZE) $(CFOPTIMIZE_L) $(EXTERNAL_LDFLAGS) -Wl,-rpath=/usr/local/lib/gcc10
 
 ifdef REPORT
 CFOTHERS += -ftime-report
```

**Comment by rawlins** [comment]
> Do you guys support FreeBSD or should i ask elsewhere?

We don't in the sense that no one on the devteam has experience with freebsd or can test patches. However, we will merge fixes.

From some googling for this specific error, I don't think it's likely to be a crawl issue; rather, this seems to be something that arises when trying to build with g++ on freebsd. Can you use clang instead? There has been official packaging for freebsd, though it doesn't look very up to date; but I would still check what they do: https://www.freshports.org/games/stonesoup/

**Comment by randomMesh** [comment]
Thanks for looking into this. :+1: 

I'll check out the FreeBSD package and see what they do.
