### ISSUE TITLE
Xom should snigger (BrE), not snicker (AmE)

### ISSUE THREAD

**Issue by powerbf** [crawl/crawl#1775]
Version 0.26, any platform

Since DCSS is supposed to speak British/Australian English....

There are a couple of messages containing the word snicker: "Xom snickers.", "Xom snickers loudly."

Snicker is American English:
https://dictionary.cambridge.org/dictionary/english/snicker

The British/Australian equivalent is snigger:
https://dictionary.cambridge.org/dictionary/english/snigger

(As an Australian myself, this stands out like a sore thumb!)

**Comment by leleleSDX** [comment]
uh oh

**Comment by noobanidus** [comment]
As an Australian myself, Americanisation has potentially led to cross-pollination. But I'd honestly say that I've heard more people around my say "snickering" in the past few years than I've heard "sniggering".

**Comment by ebering** [comment]
Gonna close this as won't do; both spellings appear in OED snippets back to the first appearances of the word in the language, though the American spelling was a rare variant in British works during the 1800s.
