### ISSUE TITLE
End of Vitalisation interrupts memorising spells

### ISSUE THREAD

**Issue by MinticePIU** [crawl/crawl#1796]
**PLATFORM and OS or BROWSER:**
webtiles: Latest stable Chrome
local tiles: Windows 10

**DCSS VERSION AND GAME INFORMATION:**
webtiles: 0.27-a0-362-g8331d791d5
local tiles: 0.26-b1

**DESCRIPTION:**
By the end of Vitalisation, if you are memorising a spell, you would not complete memorising it. (Same happens with spells that Zin does not hate.)

**EXTRA FILES:**

![image](https://user-images.githubusercontent.com/58921073/109917157-2fc36400-7cf8-11eb-88a3-67fbb5d0e47d.png)

**Comment by ebering** [comment]
This does not replicate on current trunk with default RC, and the activity interrupt code all looks correct. Please re-open if the problem still persists, and include your RC file if any, particularly if you have set any `interrupt_*` options.
