### ISSUE TITLE
Food.des vaults don't appear to spawn.

### ISSUE THREAD

**Issue by kippig** [crawl/crawl#1799]
I'm not sure why this isn't the case but I've won 60+ games since 0.26 and I haven't seen the_bakery, hangedman_fish_farm, hangedman_little_slice_of_home, hangedman_ranch, grunt_ogre_cave, grunt_livestock. I'm pretty sure this is a bug because I should have seen one of them if they were still in the game. I'm happy to take this bug, I'd just move all the vaults in food.des over to float.des.

**Comment by kippig** [comment]
!lg * kmap=grunt_livestock recent s=v
Yiufbot: 322 games for * (kmap=grunt_livestock recent): 166x 0.25.1, 91x 0.25.0, 59x 0.26.0-a0, 3x 0.26.0, 0.26.0-b1, 0.27.0-a0, 0.26.1


!lg * kmap=the_bakery recent s=v
Yiufbot: 36 games for * (kmap=the_bakery recent): 15x 0.25.1, 14x 0.25.0, 6x 0.26.0-a0, 0.27.0-a0

**Comment by rawlins** [comment]
Probably the vaults are fairly underweighted since their food weighting code was removed in 0550c0020ce without other adjustment to these vaults' weights. It's ok if they are rarer than they used to be though.
