### ISSUE TITLE
Encountered a randomly generated ghost with a nonexistent spell

### ISSUE THREAD

**Issue by ididnaaaaht** [crawl/crawl#1804]
**PLATFORM and OS or BROWSER:**
Local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.26.0

**DESCRIPTION:**
Upon exploring Snake Pit:4, I encountered a ghost vault with a randomly generated ghost of a gnoll hedge wizard. I examined it to see its characteristics, and one of its mastered spells was "nonexistent spell." The description of this spell encouraged a bug report to be filed, so here we are.

**EXTRA FILES:**
![DCSS 0,26 bug report 1](https://user-images.githubusercontent.com/80198833/110237193-8e4a3700-7ede-11eb-85d5-11fe3d79e1b8.jpg)
![DCSS 0,26 bug report 2](https://user-images.githubusercontent.com/80198833/110237197-91ddbe00-7ede-11eb-9e6a-8b1b333463e7.jpg)

**Comment by semitonal** [comment]
Fixed by 776b58c23f948e.
