### ISSUE TITLE
Pandemonium Entering Floor Bug

### ISSUE THREAD

**Issue by kleiner-fisch** [crawl/crawl#1812]
In my current game (morgue attached) I entered a Pandemoneum floor twice in a position that seems undesired. I play trunk version 0.27-a0-553-ge0ab5a2769.

First, next to a sleeping Lom Lobon, and some floors later in a Vault (screenshot attached).

I would assume that there are some restrictions on where a floor may be entered.

![Screenshot_2021-03-08 Dungeon Crawl Stone Soup 0 27-a0-553-ge0ab5a2769](https://user-images.githubusercontent.com/1914470/110382849-c5922280-805b-11eb-9092-a459556c84eb.png)

[morgue.txt](https://github.com/crawl/crawl/files/6104195/morgue.txt)

**Comment by ebering** [comment]
This is a bug, but not for the reasons you think. In general Pan arrival placement on a level is completely random and right next to Lom Lobon is fine.

However, `gammafunk_dig_for_victory` marks the cell you arrived in as `no_tele_into`, which is the only explicit designation for not having the player start in that particular position.
