### ISSUE TITLE
Stealth brand on gloves doesn't seem to work.

### ISSUE THREAD

**Issue by Rekkone** [crawl/crawl#1815]
**PLATFORM and OS or BROWSER:**
Webtiles
Firefox 84

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-577-ge2a43ba0c9

**DESCRIPTION:**
Equipping "a +0 pair of gloves of stealth" {Stlth+} doesn't seem to change the Stlth value(displayed?).
Should add at least 1 pip(or 2 with Dithmenos).
![324673251](https://user-images.githubusercontent.com/46382134/110452822-35d98c00-80ce-11eb-82b0-24695e614874.png)

**Comment by Goratrix** [comment]
I suppose hats (added with commit a82526b) and cloaks (added earlier with 8388af8) don't work either? If I understand this correctly, the check for stealth on aux armor is hardcoded for boots only, this needs be generalized to any aux armor:

https://github.com/crawl/crawl/blob/master/crawl-ref/source/player.cc#L2972

https://github.com/crawl/crawl/blob/master/crawl-ref/source/player.cc#L3031

**Comment by PleasingFungus** [comment]
Great catch! Thanks for pointing this out - should be fixed now. :)
