### ISSUE TITLE
Resting in poison clouds with form-given rPois not allowed

### ISSUE THREAD

**Issue by Midn8** [crawl/crawl#1817]
**PLATFORM and OS or BROWSER:**
Webtiles, firefox

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-577-ge2a43ba0c9

**DESCRIPTION:**
I get the "you're standing in a cloud of poison gas" message when trying to rest in a poison cloud while in dragon form, which has rPois. Not sure if this is intended.

**EXTRA FILES:**
https://pastebin.com/TZReSGmS

morgue

**Comment by ebering** [comment]
This is intended behavior.
