### ISSUE TITLE
Ring removal prompt shows rings backwards

### ISSUE THREAD

**Issue by liammcd** [crawl/crawl#1819]
Latest Trunk

![image](https://user-images.githubusercontent.com/11138182/110558213-14998f80-8110-11eb-92c7-18ea9b6ef6dd.png)

**Comment by Goratrix** [comment]
Fixed with a16a6a3.

**Comment by rawlins** [comment]
Sorry, yeah, should have tagged this issue too. Should be fixed, thanks for the report!
