### ISSUE TITLE
Can not compile on Void Linux, missing "lua/src" directory

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#1829]
**PLATFORM and OS or BROWSER:**
Local tiles, Void Linux

**DCSS VERSION AND GAME INFORMATION:**
Latest master branch.

**DESCRIPTION:**
I am trying to compile DCSS (local tiles) on Void Linux but i get an error saying:
```bash
[xxx@xxx source]$ make TILES=y
  * If you experience any problems building Crawl, please take a second look
  * at INSTALL.txt: the solution to your problem just might be in there!
    * Need to build contribs: lua/src
make[1]: Verzeichnis „/home/xxx/development/crawl/crawl-ref/source/contrib“ wird betreten
**********************************************************

The 'lua/src' directory is missing. Have you run
   'git submodule update --init'?
(It's probably better to install all native dependencies instead.)

**********************************************************
make[1]: *** [Makefile:22: lua/src] Fehler 1
make[1]: Verzeichnis „/home/xxx/development/crawl/crawl-ref/source/contrib“ wird verlassen
make: *** [Makefile:1713: .contrib-libs] Fehler 2
```
Apparently it's missing a "lua/src" directory.
I have installed the following packages regarding LUA with the package manager:
```bash
[xxx@xxx source]$ xbps-query -s lua
[*] LuaJIT-2.1.0beta3_1       Just-In-Time Compiler for Lua
[*] LuaJIT-devel-2.1.0beta3_1 Just-In-Time Compiler for Lua - development files
[*] lua-devel-5.3.5_6         Powerful, fast, lightweight, embeddable scripting language (5.3.x) - development files (transitional...
[*] lua53-5.3.5_6             Powerful, fast, lightweight, embeddable scripting language (5.3.x)
[*] lua53-devel-5.3.5_6       Powerful, fast, lightweight, embeddable scripting language (5.3.x) - development files
```
Are there more LUA packages i need to install?

PS: I want to avoid the `git submodule update --init` procedure and use packages native to my system.

**Comment by rawlins** [comment]
dcss needs lua 5.1; it isn't compatible with lua 5.3 (lua 5.1, 5.2, 5.3 are generally not inter-compatible). Because pkg-config hasn't found lua 5.1, the build system is looking for the submodule, leading to the error you see. For a full list of dependencies, please see: https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md#other-linux--unix

**Comment by randomMesh** [comment]
Thanks, i'll install lua 5.1 then. :+1:
