### ISSUE TITLE
Inputs doubled on arch linux. Compiled from source

### ISSUE THREAD

**Issue by ksladowski** [crawl/crawl#1842]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-695-gb4952372f7
Fresh install, compiled from source on Arch Linux

**DESCRIPTION:**
Certain inputs, such as "enter" or the arrow keys, but notably not alphanumeric keys, duplicate the input.
For example, in the main menu, up/down move two items in the list, not just one. If I move using the arrow keys, my character moves two spaces instead of one. I can live with these issues. My problem is that when I try to cast a spell, I select my spell, hit enter, skip through the target selection/confirmation, and therefore can only attack the nearest target.

**EXTRA FILES:**
n/a

**Comment by ksladowski** [comment]
I use EXWM (Emacs X Window Manager) and the issue was with the way keys were being passed through emacs into X windows. Idk why it never showed up as an issue before crawl but regardless, issue solved

**Comment by rawlins** [comment]
Thanks for the update!
