### ISSUE TITLE
Kobold + scarf of shadows + 6* with Ashenzari = LOS bug

### ISSUE THREAD

**Issue by DevastatorOne** [crawl/crawl#1844]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-512-g57cc695410

**DESCRIPTION:**
You can perfectly see everything in your LOS with scarf of shadows on kobold and 5* piety while worshipping Ashenzari, but at 6* it become confusing that enemies/items disappear at the edge of your LOS.
Small example, Elf on the left and Zombie on the right disappear when i come closer and they are at the edge of my line of astral sight:
https://clips.twitch.tv/GrossCaringJaguarGivePLZ-ZYFfNRhUCEKcjdIf

**EXTRA FILES:**
![1 fov](https://user-images.githubusercontent.com/81159762/111983308-0b022580-8b1b-11eb-85a8-fae207e7c33f.jpg)
![2 fov](https://user-images.githubusercontent.com/81159762/111983350-15bcba80-8b1b-11eb-9292-4b81f72df819.jpg)

**Comment by rawlins** [comment]
Thanks for the detailed bug report + video!
