### ISSUE TITLE
Can't use automagic with Djinni

### ISSUE THREAD

**Issue by cmanfre4** [crawl/crawl#1851]
**PLATFORM and OS or BROWSER:**
console

**DCSS VERSION AND GAME INFORMATION:**
 0.27-a0-765-ge4d627d

**DESCRIPTION:**
Can not use automagic with Djinni race. Using the following options in the rc:

automagic_enable = true
automagic_slot = a
automagic_stop = 10

Get the following error when trying to tab:
_You don't have enough magic to cast Magic Dart!

**Comment by rawlins** [comment]
Dj have no MP at all (the gimmick on the current version is that they cast from HP), so try setting `automagic_stop` to 0 instead. I believe (but couldn't swear) that automagic will also respect autofight_stop.

automagic is generally deprecated in favor of quivering. However, `automagic_stop` is used for quivers as well and it might be more intuitive to have it use MP for Dj in particular.

**Comment by cmanfre4** [comment]
I actually didn't consider trying to set `automagic_stop = 0`. I just tested it, however, and unfortunately I'm still getting the same error.
