### ISSUE TITLE
Flight over deep/shallow water is slow

### ISSUE THREAD

**Issue by shummie** [crawl/crawl#1854]
0.27-a0-805-g913bf40136

As a Djinn w/ perma flight, moving over deep/shallow water confers a movement penalty that's the same as not flying.

![image](https://user-images.githubusercontent.com/3296707/112739807-0b485980-8f3d-11eb-8ce5-8ad94eaeddaa.png)

**Comment by rawlins** [comment]
Resolved by 60bc5d92e6a2, thanks!
