### ISSUE TITLE
Blinding certain monsters increases their chance to hit you

### ISSUE THREAD

**Issue by G-E-C** [crawl/crawl#1862]
**PLATFORM and OS or BROWSER:**
Webtiles. Chrome Versión 89.0.4389.114

**DCSS VERSION AND GAME INFORMATION:**
Stone Soup 0.27-a0 (through 0.27-a0-737-g0a99b99)

**DESCRIPTION:**
Blinding monsters with dazzling flash sometimes increases their hit chance shown in the xv menu. This doesn't happen with all monsters, the ones I noticed were hydras and elephants. To reproduce simply check the monster hit chance before and after being blinded.

**EXTRA FILES:**
1 head hydra before being blinded
![image](https://user-images.githubusercontent.com/47680997/113162213-792ea280-9215-11eb-93a4-45a174f8dddf.png)
Same 1 head hydra, after being blinded
![image](https://user-images.githubusercontent.com/47680997/113162312-8e0b3600-9215-11eb-8d2f-8743648a30b4.png)

**Comment by rawlins** [comment]
I haven't been able to replicate this on just the information provided, so it would be useful to know exactly what character stats this was tested on. The relevant code hasn't changed since being merged and I can't see any way in which this would have been fixed, though.

**Comment by G-E-C** [comment]
> I haven't been able to replicate this on just the information provided, so it would be useful to know exactly what character stats this was tested on. The relevant code hasn't changed since being merged and I can't see any way in which this would have been fixed, though.

I believe this was the character: https://cbro.berotato.org/morgue/GEC/morgue-GEC-20210331-201855.txt

**Comment by G-E-C** [comment]
Oh my god I'm dumb. I had an amulet of the acrobat. Nevermind.
