### ISSUE TITLE
Wizard mode can't make ironbound beastmasters

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1869]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-404-g4390dbc5be

**DESCRIPTION:**
If I try to create an ironbound beastmaster using & m in wizard mode, it doesn't create anything, but instead gives the message:

Unable to place monster.

Trying to create one in the arena also fails, giving the message:

Fatal error:

Failed to create monster at (45,34) env.grid: floor

I don't know if the game can generate these monsters in the normal way.

**Comment by ebering** [comment]
Wizard mode could probably give a better message, but beast masters refuse to place unless MF_PERMIT_BAND is set in the monster generation data; this happens naturally for random monster placement. In level building MONS: specifications you need `ironbound beastmaster band`

The game does indeed generate them the normal way, they've even snagged a few kills in online play.

**Comment by Aliscans** [comment]
Thanks. It's a bit more than a cryptic message, as it did actually crash when it said "Fatal error", but it's good to know what does work.
