### ISSUE TITLE
Feature Request: Add [A]lways option to "Could not pick up an item here; shall I ignore it?"

### ISSUE THREAD

**Issue by EugeneJudo** [crawl/crawl#1873]
When autoexploring, items in autopickup are automatically picked up, unless there's not enough inventory space. In this case it yields the prompt:

```
Could not pick up an item here; shall I ignore it? 
[Y]es or [N]o only, please.
```

Late in the game this most often occurs with random rings, which in my experience are 9/10 times useless by that point. Selecting No doesn't remove this item from autopickup (which is what you do next to minimize the amount of such stops.) Instead there should be a third option as follows to remove the item from autopickup:

```
Could not pick up an item here; shall I ignore it? 
[Y]es [N]o or [A]lways, please.
```

**Comment by sefie1** [comment]
How should it be treated, when there are multiple items that could not be picked up? @EugeneJudo 

For the given use case ignore all would make sense I guess. Though personally, I would be concerned because such a pile could have many items...

**Comment by EugeneJudo** [comment]
Good point, it seems there's a few options for such a case.

One is to just blanket apply 'Always' the same way 'Yes' would ignore
everything in the stack. This has the nicety of at worst halting
autoexplore for a single action regardless of stack size, but the downside
that for multiple items they would need to handled manually with \.

Another is to break up the prompt to act on each offending item in the
stack, e.g. Could not pick a Ring of Fire; shall I ignore it? This has the
opposite pros and cons and would be a bigger change.

Ideally I think the (g)rab or (v)iew menu for multiple items could go into
autopickup toggle mode when pressing \ (for all items available to pick
up), similar to how dropping items has a similar toggle. This would
complement the first solution, and would in general be very helpful (I've
always found the \ menu very clunky to use for anything other than
pre-emptively ignoring items (not looking for specific things), or figuring
out what I haven't picked up yet (usually a small list.)

Regardless I think the former option is the better way to handle such cases.

**Comment by ebering** [comment]
The fancier musings didn't get implemented, but a basic `A` answer is now available.
