### ISSUE TITLE
Can't bind AOE version of Animate Dead to the key if a single target version was bound to that key

### ISSUE THREAD

**Issue by radio-gra** [crawl/crawl#1886]
**PLATFORM and OS or BROWSER:**
online console

**DCSS VERSION AND GAME INFORMATION:**
dcss-0.26 (CUE server)

**DESCRIPTION:**
If you bind Yred's Animate Dead to a different key via =a, then once you reach *** piety and the ability is replaced with the AOE version, you can't then bind it to the same key, unless you first bind something different to that key, after which you can rebind as normal.

Reproduction:
1) Convert to Yred
2) Bind Animate Dead to q
3) Reach *** piety
4) Try to bind Animate Dead (AOE) to q <- fails
5) Bind another ability (e.g. Dig) to q
6) Bind Animate Dead (AOE) to q <- succeeds

**EXTRA FILES:**
https://underhound.eu/crawl/saves/dreux-crawl-0.26-210409-0819.tar.bz2

**Edit**: The binding doesn't seem to be working properly after doing (6), either. If you try to rebind stuff further, abilities will sometimes be bound to the keys that make no sense.

**Comment by ebering** [comment]
These abilities were removed in the latest iteration of Yred so this is no longer an issue.
