### ISSUE TITLE
Odd "comes into view" messages in the Arena of Blood.

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1887]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-926-g0e6d9124c6

**DESCRIPTION:**>  
In the Arena of Blood, monsters have different names. When the game creates a "x comes into view" message it sometimes forgets. Examples include:

> 3 orcs come into view.
 The bag of meat shouts! x2; You hear a shout! x4

and:

>  The Servant appears out of thin air!
 Harold the Weathered comes into view. He is wielding a +9 glaive of flaming.
 The Servant shouts! You hear a shout! x2

The easiest way to resolve these would probably be to add the Sprint monsters to mondata[], but "make the game use monster::mname here" would also work.

I don't know how useful this is, but I've attached save files here from just after each message.

**EXTRA FILES:**
[Harold.cs.gz](https://github.com/crawl/crawl/files/6285386/Harold.cs.gz)
[orcs.cs.gz](https://github.com/crawl/crawl/files/6285388/orcs.cs.gz)

**Comment by ebering** [comment]
These were fixed when I merged your patch fixing them.
