### ISSUE TITLE
Disable prompt for attacking with staff of conjuration

### ISSUE THREAD

**Issue by AliastheContributor** [crawl/crawl#1891]
Now staff of conjuration deals additional damage scaling with conj skill, 
the prompt "Really attack while wielding" is seems no longer needed.
...and for consistency with other staffs.

**Comment by semitonal** [comment]
Do you have your staves of conjuration inscribed with !a in your config? By default there's not currently any prompt for attacking with them.

**Comment by AliastheContributor** [comment]
> Do you have your staves of conjuration inscribed with !a in your config? By default there's not currently any prompt for attacking with them.

You're right, I've autoinscribed /conj with '!a'. Sorry for wrong issue!
