### ISSUE TITLE
Lua spells.range reports wrong range for IMB, Iceblast

### ISSUE THREAD

**Issue by mgdelmonte** [crawl/crawl#1911]
Platform: Windows 10
DCSS 0.27-a0-990-ga6c6c90667 local tiles

The Lua `spells.range` function returns 6 for Iceblast (which has a range of 5) and 3 for Iskenderun's Mystic Blast, which has a range of 0.

Possibly it's adding the radius of the blast to the range?  But it reports the correct range (not including the blast radius) for Fireball.  And IMB has a radius of 2, so reporting a range of 3 is just completely inexplicable.

**Comment by ebering** [comment]
This fails to replicate on current trunk, can you provide a save and demonstration rc or lua sequence?

**Comment by ebering** [comment]
Feel free to re-open if you can replicate this
