### ISSUE TITLE
killing in hydra form doesn't reward gozag gold

### ISSUE THREAD

**Issue by Mac-au** [crawl/crawl#1918]
**PLATFORM and OS or BROWSER:**
Local tiles, Windows

**DCSS VERSION AND GAME INFORMATION:**
crawl_tiles-0.27-a0-961-g825125a692

**DESCRIPTION:**
Title. I haven't used spider form this game and I haven't gotten statue form online yet but it seems plausible that other transformations have this problem.

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/52499665/115304137-308a4b00-a12a-11eb-8686-ddee74220dea.png)
![image](https://user-images.githubusercontent.com/52499665/115304184-3f70fd80-a12a-11eb-929b-9636a3bf8387.png)

**Comment by RojjaCebolla** [comment]
Well, you _devoured_ the bullfrog, so there's no bullfrog corpse to convert into a pile of gold.  Shouldn't happen with your other forms.

**Comment by rawlins** [comment]
As @RojjaCebolla is getting at, this is expected behavior: hydraform devours enemies on death (for HP gain), and when this happens no corpse is left behind. So, nothing to turn into gold.
