### ISSUE TITLE
Casting IMB near hepl ancestor gives warning prompts

### ISSUE THREAD

**Issue by Gilette-dcss** [crawl/crawl#1925]
**PLATFORM and OS or BROWSER:**
Webtiles, Chrome
**DESCRIPTION:**
When casting iskendruns mystic blast near hepl ancestor, you get a warning message even tho it doesnt affect it 
**EXTRA FILES:**
![Screenshot_20210424_163939](https://user-images.githubusercontent.com/83128264/115962872-a6712680-a51d-11eb-85b9-2d455fab1ab1.jpg)
![Screenshot_20210424_164323](https://user-images.githubusercontent.com/83128264/115962873-abce7100-a51d-11eb-969c-a8ebc703de68.jpg)

**Comment by optorun** [comment]
Piggybacking on this one; please tell me if I need to open a separate request.

- OoD is reflected by knight hep ancestor's shield, so it often doesn't pass through them, and sometimes blow up in my face if I'm too close
- Ozocubo's refrigeration deals damage to ancestor, which is weird given that I can blast them with fireballs all day long and they don't get a scratch :D. I'm also prompted by a warn message.

**Comment by rawlins** [comment]
That commit doesn't resolve the OoD issue, so feel free to open a new issue for that (I'm not actually sure what the right behavior is, so it may or may not be a bug at this point). Otherwise, the cases mentioned in this issue should be fixed.
