### ISSUE TITLE
Djinn cause less damage than other species when they hit things with magic staves

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#1940]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-926-g0e6d9124c6

**DESCRIPTION:**
This may be intended, but melee_attack::staff_damage() reads as follows:

`int melee_attack::staff_damage(skill_type skill)
{
    if (x_chance_in_y(attacker->skill(SK_EVOCATIONS, 200)
                    + attacker->skill(skill, 100), 3000))
    {
        return random2((attacker->skill(skill, 100)
                      + attacker->skill(SK_EVOCATIONS, 50)) / 80);
    }
    return 0;
}

`

"skill" is always a spell school here. For a djinni, this means it is always a useless skill, and so that they only get the smaller bonus from their evocations skill.

**Comment by ebering** [comment]
This is intentional behavior.
