### ISSUE TITLE
Hep Ancestor 'avoiding' Invisibility cast from player

### ISSUE THREAD

**Issue by wvartech** [crawl/crawl#1950]
**PLATFORM and OS or BROWSER:**

PC / Windows 10

**DCSS VERSION AND GAME INFORMATION:**

Crawl Tiles 0.27-a0-1071

**DESCRIPTION:**

Hep's Ancestor avoids Invisibility cast over it as if it were an offensive spell, if there is another target in the path beyond it, it will actually affect that instead of Hep's ancestor.
![crawl_CYGEEVUqfB](https://user-images.githubusercontent.com/41836450/118152497-6691b680-b3da-11eb-95fa-6c23139567af.png)

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/41836450/118152560-77dac300-b3da-11eb-94ce-a6614f769361.png)

**Comment by DreamDustDCSS** [comment]
Invisibility was very recently changed to be self-targeted only, see: 6385558a29ec6c50e0cb932773d3f5008517a42f

I _think_ Invisibility was the last "helpful" / buff spell in the game with a targeter, so this issue of the Hep ancestor dodging buffs should no longer exist... unless another spell like this is created in the future.

**Comment by ebering** [comment]
This issue indeed no longer exists.
