### ISSUE TITLE
You focus your inner power and blind INVALID YOU FAULTLESS in retribution!

### ISSUE THREAD

**Issue by camdenbuzard** [crawl/crawl#1960]
**PLATFORM AND BROWSER**
webtiles and Firefox 78.10.1 esr 64-bit:

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-1193-g8631133539

**DESCRIPTION:**
My guardian golem blew up with inner fire, and I was caught in the explosion. Then, I believe, my Ru power tried to retaliate but the monster was already dead?

**EXTRA FILES:**
Morgue File: [https://cbro.berotato.org/morgue/Drazool/morgue-Drazool-20210525-074800.txt](url) 
I also attached a snippet I took.
![image](https://user-images.githubusercontent.com/6893276/119572080-b10e1e00-bd5e-11eb-8cd3-3e58ed7600d8.png)

**Comment by ebering** [comment]
Fixed by
