### ISSUE TITLE
Possible Bug! Spellforged Servitor not firing through Hep ancestor

### ISSUE THREAD

**Issue by Shapermc** [crawl/crawl#1962]
Windows Chrome Browser version 0.27-a0-1193-g8631133539 (webtiles) Player name is Shapermc on the CKO Server

Current game in progress, playing DjEE^Hep and just got spell forged servitor. It refuses to shoot through the ancestor (i.e. hallways usually). I am unsure if this behavior should be adapted to that of the player (to allow it to shoot through), or if this is working as intended, so I am writing up the report for the dev team to decide if bug or not.

**Comment by ebering** [comment]
This is working as intended. The servitor is a construct and does not have the ancestral bond or blessing of hepliaklqana.
