### ISSUE TITLE
Hatch up into an inescapable room

### ISSUE THREAD

**Issue by PhazeonPhoenix** [crawl/crawl#1973]
**PLATFORM and OS or BROWSER:**
webtiles Chrome Windows

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-1202-ge72e49191c

**DESCRIPTION:**
Took a hatch up and landed in this inescapable room in a vault. Sadly no teleports.

**EXTRA FILES:**

![chrome_20210603-010911](https://user-images.githubusercontent.com/18453/120612718-56359000-c40a-11eb-92da-c1825c5f59a8.png)

https://cbro.berotato.org/morgue/cobaltphoenix/morgue-cobaltphoenix-20210603-081628.txt

Attempt to retrieve backup from CBRO2 failed with the following message:

```
/bin/savegame-backup.sh: line 124: SAVE_MATCHES[0]: unbound variable
```

**Comment by DreamDustDCSS** [comment]
```
NAME:   heliophobic_arrival_ceremonial_halls
TAGS:   arrival no_monster_gen no_trap_gen
ORIENT: float
TILE:   c = wall_marble
FTILE:  '+{cG = floor_marble
COLOUR: 'cG = white
SUBST:  ' = .
MAP
.....ccc+ccc.....
.....cG'''Gc.....
..c..cc'c'cc..c..
.ccc.cG'c'Gc.ccc.
.ccc.cc'c'cc.ccc.
..c..cG'c'Gc..c..
.....cc'c'cc.....
ccccccG'''Gcccccc
cGcGcGc'''cGcGcGc
c'''''''''''''''c
+'ccc'''{'''ccc'+
c'''''''''''''''c
cGcGcGc'''cGcGcGc
ccccccG'''Gcccccc
.....cc'c'cc.....
..c..cG'c'Gc..c..
.ccc.cc'c'cc.ccc.
.ccc.cG'c'Gc.ccc.
..c..cc'c'cc..c..
.....cG'''Gc.....
.....ccc+ccc.....
ENDMAP
```
There are probably multiple ways (and better ones) to fix this problem, but one quick fix would be to tweak the map so there's always a path between the little quadrants and the doors. Something like this:
```
MAP
    .... ....
.....ccc+ccc.....
.....cG'''Gc.....
..c..cc'c'cc..c..
.ccc.cG'c'Gc.ccc.
.ccc.cc'c'cc.ccc.
..c..cG'c'Gc..c..
.....cc'c'cc.....
ccccccG'''Gcccccc
cGcGcGc'''cGcGcGc
c'''''''''''''''c
+'ccc'''{'''ccc'+
c'''''''''''''''c
cGcGcGc'''cGcGcGc
ccccccG'''Gcccccc
.....cc'c'cc.....
..c..cG'c'Gc..c..
.ccc.cc'c'cc.ccc.
.ccc.cG'c'Gc.ccc.
..c..cc'c'cc..c..
.....cG'''Gc.....
.....ccc+ccc.....
    .... ....
ENDMAP
```
I'll open a PR later. Thanks for reporting this - thankfully it happened at the start of the run, lol.
