### ISSUE TITLE
Shattering near ood asks for confirmation

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#1976]
**PLATFORM and OS or BROWSER:**
webtiles trunk 0.27-a0-1217-g8a41f320e8

**DESCRIPTION:**
Shattering with an ood in los asks "Really attack near your ood?" which is unnecessary since oods cant be damaged

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/70080435/120906138-f961f180-c624-11eb-8ecd-bc5dd0280099.png)

**Comment by ebering** [comment]
Fixed in 2ff873f9304
