### ISSUE TITLE
Melee AI stares at archer that it can reach and does nothing, while a couple of steps aside would help

### ISSUE THREAD

**Issue by apollovy** [crawl/crawl#1977]
**PLATFORM and OS or BROWSER:**
macOS Big Sur 11.3.1 (20E241), local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.27-dev-latest

**DESCRIPTION:**
My character is standing in 4-5 tiles from the melee-only monster. There's deep water between us, that can be walked around in a couple of moves. The AI doesn't try to go around — it just stands there and stares while I kill it. The process in in the video.

**EXTRA FILES:**
https://user-images.githubusercontent.com/1671727/121077303-260e3880-c7e0-11eb-96e5-2b85f50419b1.mov

**Comment by ebering** [comment]
The crawl monster AI is intentionally not "too smart", and while edge situations like this are glaring they're also sufficiently rare. There is a "retreat if taking damage and we can't path" behavior that monsters can take on a chance in a situation like this.
