### ISSUE TITLE
Odd chain lightning behavior wrt statues

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#1989]
**PLATFORM and OS or BROWSER:**
webtiles trunk 0.27-a0-1301-g128193abf8

**DESCRIPTION:**
If there's a statue between you and the monster, when you cast chain lightning the monster isnt hit, mp/hp is consumed, and there's not a failure message like it grounding out or something else. 

**EXTRA FILES:**
position it occured in:
![image](https://user-images.githubusercontent.com/70080435/122481413-a2510a80-cf9c-11eb-90e5-5a867dee9fad.png)

**Comment by kuniqsX** [comment]
CL used to treat statues as a non-obstructive tile (like floor) when chaining to NPCs during my July 12th game. (0.27-a0-1277-g3808f8b1c9 (webtiles)). Don't remember when statues started to block CL, half a week ago?

**Comment by ardl** [comment]
Fixed by 2fbb07c
