### ISSUE TITLE
Bug/silly behavior: TSO penance from Kirke and Hogs

### ISSUE THREAD

**Issue by riverfiend** [crawl/crawl#1990]
**PLATFORM and OS or BROWSER:**
CAO webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-1302-g7736ffe

**DESCRIPTION:**
Killing Kirke and her hogs in the same turn causes TSO penance, if the hog dies after Kirke releases it from its spell. Submitted upon request from Gammafunk.

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/63566628/122507687-400cff80-cfc6-11eb-93f9-7f5afb7af2e4.png)

**Comment by ebering** [comment]
Should be fixed by 4e304d
