### ISSUE TITLE
Branch entrance disappears from nav after Xom move

### ISSUE THREAD

**Issue by jtroyer** [crawl/crawl#1995]
**PLATFORM and OS or BROWSER:**
webtiles
Mac OS 11.3.1 Safari 14.1 (16611.1.21.161.6)

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-1325-g58a489a
akraisic.org

**DESCRIPTION:**
Xom moved the entrance to Spider Nest
I entered and left several times.

Result:
Ctrl-O lists it as Spider (visited) 
Nest no longer appears  G navigation, G N results in "Okay, then."
Nest entrance is still on Lair:2 and works as normal.

**EXTRA FILES:**

**Comment by rawlins** [comment]
Thanks for the report! This is a long-standing issue; I will clsoe and merge with #1331.
