### ISSUE TITLE
Fo^goz gets empty pot pet sets

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#1996]
**PLATFORM and OS or BROWSER:**
webtiles 0.27-a0-1325-g58a489ad9e

**DESCRIPTION:**
fo^goz gets offered empty sets of potions for pot pet.

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/70080435/123335830-03d02680-d513-11eb-9071-1681ed2f0d02.png)

*To upload a save file directly to github, compress it to a .zip archive, and
then github will accept the upload. (It will not take a .cs file directly.)*

*If this is an online game, see [these instructions](https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup)
for more information on how to make a save backup; you can provide the
resulting link here.*

**Comment by ebering** [comment]
Fixed in 9ca5906e5d
