### ISSUE TITLE
Trog ^ missing some info

### ISSUE THREAD

**Issue by maxrightgame** [crawl/crawl#2004]
**PLATFORM and OS or BROWSER:**
webtiles cxc, Yandex Browser 21.5.0.582

**DCSS VERSION AND GAME INFORMATION:**
Stone Soup 0.27-a0 (through 0.27-a0-1333-gcdc07c3)

**DESCRIPTION:**
Trog learndb entry says he can prolong your berserk however ^ menu doesn't have info about that aspect at all.
Example of Trog prolonging berserk: " You feel the power of Trog in you as your rage grows."

**Comment by ebering** [comment]
Fixed in 8a2cd6d854
