### ISSUE TITLE
Text ordering / State, Stairs + Dispersal Trap

### ISSUE THREAD

**Issue by shummie** [crawl/crawl#2005]
0.27-a0-1378-gdefffd1ff6

Sorry, no screenshot to verify, but I went upstairs to Zot 2 and dragged a draconian with me. The draconian landed on a dispersal trap next to the downstairs on the level above. I was able to successfully go upstairs to Zot 2, the draconian hit the trap, then dispersed me. The log below has an error in that it says "You stop ascending the stairs" when I'm already upstairs.

I guess you could argue that I'm partly up the stairs still so I stop ascending the stairs and get dispersed upstairs =D.

 You climb upwards.
 The purple draconian enters a dispersal trap!
 You blink.
_You stop ascending the stairs.

**Comment by ebering** [comment]
Knowing the sequencing code here changing this message order is going to be a real pain for basically zero gain, so I'm going to go with the flavour explanation: you stop climbing because you've been dispersed to level ground.
