### ISSUE TITLE
Crash on level up to 25

### ISSUE THREAD

**Issue by phlounder221** [crawl/crawl#2008]
**PLATFORM and OS or BROWSER:**
Webtiles
Windows 10 Pro version 20H2
Firefox version 89.0.2 (64-bit)

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-1416-g941b2bd30b
cbro.berotato.org
Username: phlounder

**DESCRIPTION:**
I'm playing a Djinni Wanderer, at XL 24 and 99%, and as soon as I kill one more thing I get, "You have reached level 25!" then the game crashes. It is reproducible, doesn't seem to matter where I am, it happens as soon as I gain experience. When it crashes I get the message, "Unfortunately your game crashed. range check error (21 / 21)".

https://cbro.berotato.org//Phlounder-crawl-git-941b2bd30b-210701-1913.tar.bz2

**Comment by ebering** [comment]
This is because your DjWn started wit so many spells that at XL 25 you learn more spells than the hard cap on spells.

We're working on a fix, thanks for the report!

**Comment by ebering** [comment]
Fixed by 2b06128
