### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by eyeoftheoverseer** [crawl/crawl#2010]
offline tiles and console, Windows 10

First noticed on 
crawl-0.27-a0-1384-g1422d76b99
no problems on 0.27-a0-1359-ga2a4dfd6fd

Game opens and closes immediately

0.27-a0-1430-g28b6d0f915 the window lasts long enough to show "loading maps"

0.27-a0-1384-g1422d76b99 on console crashes, but console shows 

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

before it closes

**Comment by ebering** [comment]
Can you report if the problem persists in the latest trunk build? This does not replicate on macOS with the latest trunk

**Comment by eyeoftheoverseer** [comment]
Working fine in the one on the newest

**Comment by rawlins** [comment]
for the record: I suspect this was only fixed in 56f7456 (but hopefully *was* fixed); static initialization order bugs are pretty random in terms of when they actually cause problems.
