### ISSUE TITLE
Mangrove awoken by ally indistinguishable from one awoken by foe

### ISSUE THREAD

**Issue by Syneil** [crawl/crawl#2015]
**PLATFORM and OS or BROWSER:**
webtiles, CAO

**DCSS VERSION AND GAME INFORMATION:**
Trunk at 2021-07-05 08:00 UTC

**DESCRIPTION:**
In the swamp, player casts Shadow Creatures which creates a Spriggan Druid who uses Awaken Forest turning nearby Mangroves aggressive. They were (I believe) not aggressive to myself, but I didn't see any way to tell in the UI if they were allied to me or against me. If there were an enemy Spriggan Druid present, I would like a way to see, or inspect, if they're dangerous.

**EXTRA FILES:**
Screenshot of the combat and the inspection of such a mangrove.
<img width="820" alt="Screenshot of the combat and the inspection of such a mangrove" src="https://user-images.githubusercontent.com/7725171/124441723-e18ca300-dd73-11eb-8126-e0e6b557df23.png">

**Comment by rawlins** [comment]
Seems reasonable, we do this for regular monsters.  Alignment of the casting monster is checked, so trees shouldn't attack the player / should attack enemies.

**Comment by ebering** [comment]
Fixed by the PR which was merged as 0997d3a1
