### ISSUE TITLE
Potion of lignification is regarded as useless for Vampire

### ISSUE THREAD

**Issue by dillytin** [crawl/crawl#2017]
Versions: 0.27-a0-1442-g87b6fcb595

![캡처](https://user-images.githubusercontent.com/65288602/124761888-3a735b80-df6d-11eb-8abe-e04875979ecb.PNG)

Vamp can use this potion while alive but it's marked as useless

**Comment by rawlins** [comment]
This seems to be specific to the recognized items menu, it works correctly in other cases that I've tested.

**Comment by robertxgray** [comment]
I have been looking into this issue and I think you should consider not returning true for is_lifeless_undead(false) when playing as a vampire. These are the side effects I found:

- Rage and lignification potions are tagged as useless.
- Wanderers can't receive such potions.
- Poison ring tagged as useless while bloddless and other poison related side effects.
- Kikubaaqudgha does not grant Sublimation of Blood.
