### ISSUE TITLE
CDI has old Freenode information.

### ISSUE THREAD

**Issue by nojaa3** [crawl/crawl#2020]
![Näyttökuva 2021-7-8 kello 12 15 21](https://user-images.githubusercontent.com/82903954/124896612-464f3400-dfe6-11eb-8d3f-a3247a73eb95.png)

CDI information should be probably redirect to #crawl-dev on Libera instead.

**Comment by rawlins** [comment]
@gammafunk can edit this I think

**Comment by gammafunk** [comment]
Fixed, thanks for the report!
