### ISSUE TITLE
Lost ~8k turns

### ISSUE THREAD

**Issue by particleface** [crawl/crawl#2023]
**webtiles firefox 89.0.2 (64-bit)**

**Dungeon Crawl Stone Soup version 0.27-a0-1529-g1e82c303ef
Game seed: 16879724400776533345
Depths: 2
https://crawl.kelbi.org/crawl/morgue/particleface/morgue-particleface-20210711-051359.txt**

**I took an escape hatch from Depths:3 to Depths:2 and entered the new village vault that I had not yet explored. After a few hundred turns the game was unresponsive. I restarted a few times and it was still unresponsive. Waited a while and tried again and when I logged in I had lost ~7-8k turns. I was worshipping Hep with BM ancestor.**

**Comment by rawlins** [comment]
Thanks for the report, I've copied this info into an earlier report (#1757) that looks like the same bug. I'll go ahead and close this in order to consolidate.
