### ISSUE TITLE
Spectral Weapon description doesn't include any indicator that you share damage with the spectral weapon. 

### ISSUE THREAD

**Issue by Shapermc** [crawl/crawl#2028]
Windows, Chrome Browser, 0.27-a0-1548-gf8a67e7463 (webtiles)

I don't use spectral weapon much, so I never noticed that you share damage with the spectral weapon. This was creating extra damage on my character in a confusing way until I noticed that I was sharing damage. I read the description and there's no information that you share damage, and this information is likely important when making decisions on how to use the weapon. 

![specwep1](https://user-images.githubusercontent.com/80350699/125714108-94b25a89-4a45-4349-9fb9-2fc9e26056d8.png)
![specwep2](https://user-images.githubusercontent.com/80350699/125714111-1baa6234-44c4-4b1e-bb22-dc2c886b1e04.png)

**Comment by ebering** [comment]
Resolved by 2387c0671f5
