### ISSUE TITLE
Missing Tiles for Stormform and Blinkbolt

### ISSUE THREAD

**Issue by AlexanderPosch** [crawl/crawl#2032]
The tiles for Stormform and Blinkbolt are still missing in trunk. 
I tried coming up with some options for stormform: 
![image](https://user-images.githubusercontent.com/49498206/125805322-d659af3c-1755-4ce0-95ff-228b49a33088.png)
 (my personal favourite of those is the one in the middle at the bottom)
But it would maybe/(very probably😃) still be better if someone with more experience in making tiles decided to create them.

**Comment by AlexanderPosch** [comment]
Btw heres also something I came up with for blinkbolt [lol I felt bad asking someone else to do it when not giving it a shot myself :)]
![image](https://user-images.githubusercontent.com/49498206/125960371-96ac556c-96a1-4fad-b6e6-debe541c3a1a.png)

**Comment by ebering** [comment]
Merged by @PleasingFungus in 29e9f9e103
