### ISSUE TITLE
Preventing leaving a portal accidentally

### ISSUE THREAD

**Issue by jv84** [crawl/crawl#2047]
I was in a portal and my intention was to enter a transporter. I accidentally pressed a wrong button on a wrong tile and left the portal. This ruined the whole playing flow and I just killed the character.

I want a script which asks a confirmation before leaving a portal. Is this possible?

**Comment by sefie1** [comment]
How would this be done?

My first thought was to add an appropriate option in the rc file and a check in the code, perhaps movement.cc. However, the comment mentions a script, so this indicates a lua script?

**Comment by semitonal** [comment]
There's an easily-adaptable Lua function for exactly this in `settings/advanced_optioneering.txt`.
