### ISSUE TITLE
High CPU usage and lag when a character dies

### ISSUE THREAD

**Issue by jv84** [crawl/crawl#2048]
I have had this behavior on Linux tiles version as long as I remember.
It only happens if a character has collected enough experience.
Keyboard input gets unresponsive and the death screen is skipped, returning straight to main menu.
Seems like it's flushing some cache. Bad garbage collection?

**Comment by jv84** [comment]
I have to say the game gets more unresponsive in general the more it progresses.

**Comment by randomMesh** [comment]
Maybe compile in debug mode and [check for memory leaks with valgrind](https://stackoverflow.com/questions/5134891/how-do-i-use-valgrind-to-find-memory-leaks#44989219).

**Comment by jv84** [comment]
Maybe. It's easy to say. :)

**Comment by randomMesh** [comment]
It's easy to say

> Bad garbage collection?

without checking first. ;)

**Comment by jv84** [comment]
So you claim Valgrind is that easy to use? I don't have debugging skills. And replicating the situation is another thing. I would have to play for equally long with Valgrind slowing down everything.

**Comment by ebering** [comment]
Hi, a gentle reminder that when you comment on these issues it generates notifications for a large number of team members. Please keep the conversations 1) productive and 2) collegial.

Suggesting valgrind as a stab in the dark isn't completely unhelpful, but it doesn't contribute much to the conversation. The subsequent comments were unhelpful and I've deleted them.

**Comment by jv84** [comment]
It's close to impossible for me to specify the issue better or debug it. I'll close this.

**Comment by rawlins** [comment]
For what it's worth, lag on ending a game is a known issue and I have attempted to profile it before, but not with any success.
