### ISSUE TITLE
Online now unsupported for Android?

### ISSUE THREAD

**Issue by Tempus123** [crawl/crawl#2051]
Almost immediately after 0.27 moved from trunk to live, Hackers Keyboard (I play via Android) stopped responding for me, but only once I started a game. It worked fine for logging in, for example.

I therefore deleted both hackers keyboard and the dcss tiles app in order to download and install the latest versions in case that helped. However, I can no longer find dcss online in Google Play? Only offline apps?  Is this something Devs are aware of?

**Comment by rawlins** [comment]
"dcss online" was a third-party app, so I'm afraid we don't have any insight into what happened to it, though I have heard it is out of the store for a while. I would try to contact the developer ("Newtz Games") if possible, but I'm unfortunately not sure how easy that is, his web presence seems to have dropped. It may still be possible to download an apk from various places.

We should probably remove the link from the download page. There's also a newer port of local tiles that's under active development.
