### ISSUE TITLE
Redundant display of spectral weapons text labels

### ISSUE THREAD

**Issue by borekl** [crawl/crawl#2053]
**PLATFORM and OS or BROWSER:**
on-line console (CUE)

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.27.0-1-g7a089689b8

**DESCRIPTION:**
Redundant display of spectral weapon: "Your spectral +8 spectral giant spiked club hits the redback!!!", also see this screenshot:
https://i.imgur.com/79uZ5kf.png

**Comment by ebering** [comment]
Fixed by 25d27de915
