### ISSUE TITLE
Several commands abort at item selection

### ISSUE THREAD

**Issue by Frenoss** [crawl/crawl#2060]
**PLATFORM and OS or BROWSER:**
webtiles
Firefox 91.0 and Edge 92.0.902.73

**DCSS VERSION AND GAME INFORMATION:**
Game started: 0.28-a0-115-g169bfb5
0.28-a0-122-gfd0ec89
akrasiac.org, username Frenoss

**DESCRIPTION:**
Commands 'r', 'w', 'W', and 'P' (but not 'd' or 'T') abort with the message "Okay, then." after pressing an inventory letter. The commands can be accessed and work by visiting the item description in inventory first. The identify scroll hits the same abort condition when reading it from the inventory and then having to choose which item to identify.

I resumed a game from yesterday, which prompted to upgrade to a new version. I accepted.

**EXTRA FILES:**
http://crawl.akrasiac.org/saves/Frenoss-crawl-git-fd0ec89410-210813-1841.tar.bz2

**Comment by rawlins** [comment]
Thanks for the report; I've reverted the commit that seems to have caused this problem. CAO will rebuild within the next 30 minutes or so.
