### ISSUE TITLE
Can't memorize spells in Trunk

### ISSUE THREAD

**Issue by Sekuso** [crawl/crawl#2066]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
Current Trunk

**DESCRIPTION:**
You can't memorize spells in Trunk atm, it just says "okay then" regardless of your actions.

https://www.reddit.com/r/dcss/comments/p3sioi/in_trunk_at_the_moment_you_cant_memorize_spells/

**Comment by ebering** [comment]
This has been fixed already
