### ISSUE TITLE
ERROR in 'rltiles/tiledef-main.cc' at line 7905: ASSERT failed: idx of ... out of range TILE_FEAT_MAX (2871) .. TILE_MAIN_MAX (4178)

### ISSUE THREAD

**Issue by hbent** [crawl/crawl#2070]
I have had two effectively identical crashes today on an up to date trunk build.  One in Lair:6:
ERROR in 'rltiles/tiledef-main.cc' at line 7905: ASSERT failed: idx of 6906 out of range TILE_FEAT_MAX (2871) .. TILE_MAIN_MAX (4178)

and one in D:15:
ERROR in 'rltiles/tiledef-main.cc' at line 7905: ASSERT failed: idx of 6596 out of range TILE_FEAT_MAX (2871) .. TILE_MAIN_MAX (4178)

Attached are crash logs for both crashes, and the savefile for the D:15 crash.  As always, please let me know if any more info or testing is needed.

[crash-Woph-20210816-124550.txt](https://github.com/crawl/crawl/files/6994235/crash-Woph-20210816-124550.txt)
[crash-Woph-20210816-130455.txt](https://github.com/crawl/crawl/files/6994236/crash-Woph-20210816-130455.txt)
[Woph.cs.gz](https://github.com/crawl/crawl/files/6994255/Woph.cs.gz)

**Comment by ebering** [comment]
Can you say what you did to cause the crash? Because you have a release build the stack trace is not the easiest to read.
