### ISSUE TITLE
The (q)uiver command behaves oddly with missile weapons.

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2084]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.28-a0-234-gc3c367e0a5

**DESCRIPTION:**
I start a game using the default configuration.

I create a human hunter with a shortbow (starting with a shortbow, arrows, a short sword and some armour). I pick up some stones and quiver them (typing "Qa"). The arrows move to a different quiver.

I go into the description for the shortbow ("ia"), and select the "(q)uiver" command. My quiver is now empty, and the "f" command does nothing.

I drop my short sword ("db"), and the stones are back in my quiver.

If I quiver the shortbow ("Q**a"), I can then throw it with "f".

1. The "(q)uiver" command doesn't seem to do anything useful with a shortbow, and it clearly doesn't emulate the "Q" command. Should it be offered at all?

2. Should dropping the short sword (which wasn't in my quiver or wielded) have any effect on my quiver?

**Comment by rawlins** [comment]
This was fixed in e74157ce7a5cd120d by just completely removing evoke wielded as a UI feature (the describe UI was reading a shortbow as evokable because of this, but it couldn't actually be quivered because wielded items are unquiverable).
