### ISSUE TITLE
Tile local mapper buttons are functionless

### ISSUE THREAD

**Issue by perryprog** [crawl/crawl#2087]
**PLATFORM and OS or BROWSER:**
Local tiles on macOS.

**DCSS VERSION AND GAME INFORMATION:**
0.28-a0-239-g68911e0c57 (tiles)

<details>
<summary>Previous issue description before I realized all navigation buttons didn't work.</summary>
**DESCRIPTION:**
When using the "Navigation" set of buttons to find a feature that doesn't yet exist on the map, the map cursor is placed at the extreme edges of the known area instead of gracefully failing and doing nothing the same way the key commands do.

Steps to reproduce (assuming default config):
1) Start a new game
2) Press `X`
3) Press "Find travel exclusion". For me, this causes the map cursor to go to the extreme bottom-right of the currently discovered area.
4) Press `up`
5) Press "Find travel exclusion" (or similar such as "Find waypoint") and observe the same behavior
6) Press `esc` and `X` again
7) Repeat steps 3–5 and observe the map cursor instead going to the extreme top-left. (I've sometimes had to do step six a second time as well to get the bad position the map cursor goes to to change.)
</details>

**DESCRIPTION:**
The tiles local navigation buttons appear to be functionless. The expected behavior would be that using any of these buttons would translate to the direct equivalents of using the keyboard commands (such as `E`). I suspect the map buttons specifically are implemented in a different way to the rest of the command-based buttons—none of the map buttons have a tooltip that shows the keyboard shortcut for the command that button runs (aside: the lack of tooltips only occurs while in the map view—outside of the map view, they do have a tooltip showing their keyboard shortcut, but they are also disabled).

Various bits of code that are likely related to this issue.
https://github.com/crawl/crawl/blob/68911e0c57671d97a9fd6346bc2c5f3daa4a86d8/crawl-ref/source/tilereg-cmd.cc#L73-L76
https://github.com/crawl/crawl/blob/68911e0c57671d97a9fd6346bc2c5f3daa4a86d8/crawl-ref/source/viewmap.cc#L233-L269

Another odd bit is that the buttons seem to often move the map cursor to unexpected locations—usually either the top-leftmost corner or the bottom-rightmost corner of the seen area.
![image](https://user-images.githubusercontent.com/12972285/130524700-b7e19f13-61e5-42c0-a305-9ef14d340ffc.png)

**Comment by perryprog** [comment]
I've now realized that this seems to affect all of the map navigation buttons, and have updated (and condensed) my original comment accordingly.

**Comment by robertxgray** [comment]
All the ports I tested (Linux and Android) are also affected. I guess this bug passes unnoticed to experienced players.
