### ISSUE TITLE
Ironbound convoker can recall the audience in the Arena

### ISSUE THREAD

**Issue by dillytin** [crawl/crawl#2088]
Version: 0.28-a0-239-g68911e0c57

![image](https://user-images.githubusercontent.com/65288602/130603039-7c5767c8-9822-4be3-9cf5-c41e897a85f5.png)

![image](https://user-images.githubusercontent.com/65288602/130603004-0f0f3f2f-ebf8-4d67-af59-6202222e63a9.png)

I think these screenshots are self-explanatory.

**Comment by nicolae-carpathia** [comment]
agreed. we gotta give that audience weapons

**Comment by semitonal** [comment]
Fixed (sadly) in 34f850c0d.
