### ISSUE TITLE
preferred background/species differs between species and background selection

### ISSUE THREAD

**Issue by Krisselack** [crawl/crawl#2089]
**PLATFORM and OS or BROWSER:**
*"local tiles", "Windows 10"*

**DCSS VERSION AND GAME INFORMATION:**
*"0.26.1"*

**DESCRIPTION:**
*If starting a new game and switching between background or species (spacebar), the selection for the preferred background does not always match the preferred species. e.g. Ghoul Ice Elementalist: when selecting Ghoul, Ice Elementalist is highlighted, when selecting Ice Elementalist, Ghoul is not. IMHO, this should match.*

**Comment by ebering** [comment]
This asymmetry is intentional. Recommendations after selecting a Ghoul are for what would make a good or fun Ghoul; recommendations after selecting the Ice Elementals background are for what would make a good or fun IE.
