### ISSUE TITLE
Throwing does too much damage

### ISSUE THREAD

**Issue by 10ld3** [crawl/crawl#2099]
**PLATFORM and OS or BROWSER:**
Local tiles, Windows

**DCSS VERSION AND GAME INFORMATION:**
0.27.1

**DESCRIPTION:**
Throwing skill appears to do way too much damage. For example, javelins have a base damage of only 10, but on a character with all skills at 27, **javelins do more damage per turn than a +9 vorpal triple crossbow** (which has a base damage of 22 plus brand and enchantment)! 

To be consistent with other weapons, javelins should be doing the amount of damage closer to a +0 fustibalus firing rocks (base damage 10)!

It's the same issue with all throwing weapons, not just javelins.

I've tested this in Wizard mode using &f simulation as well as just creating monsters with &M and seeing how much damage they take.

**Comment by Nasst** [comment]
Throwing damage functions similarly to unarmed combat. The skill gets added to the base damage. A javelin at 27 skill has effectively 37 base damage.

**Comment by ebering** [comment]
This is working as intended in the code. We use GitHub issues for true bugs, discussion of game balance among the team happens in #crawl-dev on libera.chat, and you're also welcome to discuss balance issues on both official and unofficial forums for the game.
