### ISSUE TITLE
Invisibility results in silly targeting

### ISSUE THREAD

**Issue by greentaquitos** [crawl/crawl#2101]
**PLATFORM and OS or BROWSER:**
webtiles chrome92

**DCSS VERSION AND GAME INFORMATION:**
0.27.1

**DESCRIPTION:**
While I was invisible in the position pictured below, an orc wizard tried to target me with a confuse spell and hit an adjacent (to itself) orc sorceror. No creatures moved between my previous turn and the turn pictured.

I don't know if this is intended behavior or not, but this means a wizard trying to hit me was aiming their spell in a direction that could only have hit an ally.

**EXTRA FILES:**
<img width="1680" alt="confus" src="https://user-images.githubusercontent.com/7853076/131392271-d20cd2f1-cfff-4919-9fd8-e06f3aaebfad.png">

**Comment by ebering** [comment]
This is intentional.
