### ISSUE TITLE
Crawl crashes when opening the manual on Fedora 34

### ISSUE THREAD

**Issue by Nasst** [crawl/crawl#2109]
**PLATFORM and OS or BROWSER:**
Local Tiles - Fedora Workstation 34

**DCSS VERSION AND GAME INFORMATION:**
0.27.1, the version in Fedora's repo, more info in the included file.

**DESCRIPTION:**
The game crashes when trying to open the manual in-game. Probably something to do with how packages are build in Fedora's repo? No idea. I know they use a bunch of hardening flags that make it easier for benign errors to crash everything. Compilation info is included in the crash file.

**EXTRA FILES:**
[crash-Spike I-20210901-191502.txt](https://github.com/crawl/crawl/files/7094900/crash-Spike.I-20210901-191502.txt)

**Comment by rawlins** [comment]
This is probably a downstream packaging issue; could you report it here: https://src.fedoraproject.org/rpms/crawl

The Fedora maintainer for crawl is usually pretty responsive.

**Comment by Nasst** [comment]
> This is probably a downstream packaging issue; could you report it here: https://src.fedoraproject.org/rpms/crawl
> 
> The Fedora maintainer for crawl is usually pretty responsive.

Done! https://bugzilla.redhat.com/show_bug.cgi?id=2002086

**Comment by rawlins** [comment]
From https://bugzilla.redhat.com/show_bug.cgi?id=2002086 it looks to me like this has been resolved in Fedora, I can reopen if this is incorrect.
