### ISSUE TITLE
Silly cause of death: "Collided with the open sea"

### ISSUE THREAD

**Issue by nagdon** [crawl/crawl#2114]
**PLATFORM and OS or BROWSER:**
*local console ubuntu*

**DCSS VERSION AND GAME INFORMATION:**
*0.28-a0-385-g79de503ca0*

**DESCRIPTION:**
The "open sea" dungeon feature (outer border of shoals levels) is handled as an impassable wall by the game and when spells with knockback effects (e.g. the Primal Wave of elemental wellsprings) push a creature onto this tile, the game generates silly-sounding messages/death causes. Of course this is not very common so I don't think that a mechanical difference (e.g. no damage on collision) would be justified, but maybe a special-cased message (e.g. "Collided with the *waves of the* open sea" or something even better) would be a nice touch here. 

**EXTRA FILES:**
Morgue file of an affected character:
[morgue-Wihy-20210903-181824.txt](https://github.com/crawl/crawl/files/7107357/morgue-Wihy-20210903-181824.txt)

**Comment by ebering** [comment]
Fortunately English is a flexible enough language that while "Collided with the open sea" might seem a little weird, it's also correct. Adding the requested special case isn't worth the benefit since anyone who has done a belly flop knows that it can hurt quite a bit to collide with the sea!
