### ISSUE TITLE
Error compiling on arm64 - Waiting for unfinished jobs

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2115]
**PLATFORM and OS or BROWSER:**
Local tiles. Ubuntu 21.04 arm64, Raspberry Pi 400

**DCSS VERSION AND GAME INFORMATION:**
Latest master branch.

**DESCRIPTION:**
I cloned the master branch and tried to compile it on a Raspberry Pi 400 running the arm64 version of Ubuntu 21.04.
The build doesn't finish but ends with two errors.

One error states that the file `util/release_ver` is missing. This is correct, this file is not there.
It seems like [the code in gen_ver.pl](https://github.com/crawl/crawl/blob/e240ad9e2944889bcfd9ff7707219ff910244ab5/crawl-ref/source/util/gen_ver.pl#L16) is failing to create that file.

The other error is about `make` waiting for unfinished jobs, which i believe is a consequential failure.

Command used `make -j$(nproc) TILES=y`

**EXTRA FILES:**

Original message:
```
    CXX main.o
    CXX util/levcomp.tab.o
    CXX util/levcomp.lex.o
    GEN build.h
No Git, and util/release_ver doesn't exist.
make: *** [Makefile:1414: build.h] Fehler 2
make: *** Auf noch nicht beendete Prozesse wird gewartet …
```

Message translated by me:
```
    CXX main.o
    CXX util/levcomp.tab.o
    CXX util/levcomp.lex.o
    GEN build.h
No Git, and util/release_ver doesn't exist.
make: *** [Makefile:1414: build.h] Error 2
make: *** Waiting for unfinished jobs …
```

**Comment by rawlins** [comment]
This looks like you were trying to build it outside of a git repository but with a copy of the repository (perhaps by downloading github-generated source files). To build outside of the repo you do need to somehow generate `release_ver` yourself; you can look at the `source` target in `Makefile` to see how this is done when constructing the source tarbells for distribution. There may be a few other steps in that build target that would be necessary as well, not sure. If you are just downloading the source, I'd recommend either checking out the git repository or using one of our source packages, which should be buildable (e.g. debian packages use these).

Source tarbells for 0.27.1 that already have this step done:
* https://github.com/crawl/crawl/releases/download/0.27.1/stone_soup-0.27.1-nodeps.tar.xz
* https://github.com/crawl/crawl/releases/download/0.27.1/stone_soup-0.27.1.tar.xz

**Comment by randomMesh** [comment]
> This looks like you were trying to build it outside of a git repository but with a copy of the repository

No, this is not the case. I am IN the repository i cloned.
```
xxx@xxx:~/development/crawl/crawl-ref/source$ git remote show origin
* Remote-Repository origin
  URL zum Abholen: https://github.com/crawl/crawl.git
  URL zum Versenden: https://github.com/crawl/crawl.git
  Hauptbranch: master
  Remote-Branch:
    master gefolgt
  Lokaler Branch konfiguriert für 'git pull':
    master führt mit Remote-Branch master zusammen
  Lokale Referenz konfiguriert für 'git push':
    master versendet nach master (aktuell)

```

**Comment by rawlins** [comment]
What happens when you run `git describe --tags`?

**Comment by randomMesh** [comment]
```
xxx@xxx:~/development/crawl/crawl-ref/source$ git describe --tags
fatal: Keine Namen gefunden, kann nichts beschreiben.
```

**Comment by rawlins** [comment]
Is it possible this is a shallow checkout rather than a full checkout? It looks like there are no tags in the repository, which prevents `git describe` from working properly. You should be able to do something like `git fetch --tags` or `git fetch --prune --unshallow` to get the tags.

**Comment by randomMesh** [comment]
Yes, i used `git clone --depth=1 https://github.com/crawl/crawl.git` to clone the repositoy.

**Comment by rawlins** [comment]
Yeah, that won't work as-is (although you could still generate `util/release_ver` yourself by hand -- it is just a text file with a git describe output in it (e.g. `0.28-a0-401-ge240ad9e29` for current trunk). To go from a depth 1 clone to something with tags IIRC just `fetch --tags` won't work. But the unshallow one might, and if you search around SE for the Eng. version of the "names" error you can find other invocations.

If you want a depth 1 pull with tags the recipe we use on CI to get things to build is: `git fetch --depth=1 origin +refs/tags/*:refs/tags/*`. I *think* this might work in your current repo?

**Comment by randomMesh** [comment]
Ok, thanks for clarifying.

I removed the repository and cloned it again, omitting the `--depth=1`.
Having a commit history isn't that bad and my HD isn't full yet. ;)

**Comment by rawlins** [comment]
Probably the safest. I did just test out the suggestions I made up above, and the only two that work from a depth 1 clone are:
* `git fetch --prune --unshallow` (but this gets you to an equivalent state to just cloning the whole repository in the first place)
* hand-generating `util/release_ver` -- a safe value to put it in it something like `0.28-a`

Fetching the tags alone doesn't work because there's still no commit history back to the most recent version tag.

**Comment by randomMesh** [comment]
Thanks for the commit, this should prevent others from a headache.

**Comment by cirosantilli** [comment]
I would recommend patching to just use a default value like `0.0-master` is tags are not found and `util/release_ver` is not present.
