### ISSUE TITLE
There's a Potential Teleport Closet/Go to Another Area of Pan Closet in regret_index_pan_draining_boxed.

### ISSUE THREAD

**Issue by Bcadren** [crawl/crawl#2139]
**PLATFORM and OS or BROWSER:** All Both

**DCSS VERSION AND GAME INFORMATION:** Current and several old . . . 

**DESCRIPTION:**
If the player has no digging/sacrificed artifice to Ru and runs out of teleport scrolls; they can be stuck in the little grated areas with the eyes of draining in regret_index_pan_draining_boxed. (Teleport where the eye was, the eye gets displaced outside).

It's a one-line fix; my fork commit for it is here: https://github.com/Bcadren/crawl/commit/11694f2719c6aab7a89eaa5ea9895c06e92ce967

**Comment by rawlins** [comment]
This is closed via https://github.com/crawl/crawl/commit/de44f11507e36e3f65bc540dd530bcd9ae4bb47b from #2149
