### ISSUE TITLE
Should a character in Storm Form be able to be caught in nets?

### ISSUE THREAD

**Issue by shedivesin** [crawl/crawl#2143]
**PLATFORM and OS or BROWSER:**
console

**DCSS VERSION AND GAME INFORMATION:**
0.27.1-1-g398f816
crawl.akrasiac.org, username "Acceptance"
Shoals:1

**DESCRIPTION:**
I am playing an Octopode Transmuter and have Storm Form online. While gleefully zapping my way through Shoals, one of the merfolk tossed a net at me and entangled me. The message log for this was:

```
_A merfolk comes into view. It is wielding a +0 trident of protection.
 You feel a strong surge of power!
 You turn into a lightning-filled tempest!
 Your staff of air melds into your body.
_The merfolk shouts! You hear an angry hiss.
 The merfolk throws a throwing net. The throwing net hits you.
_You become entangled in the net!
 You are held in a net!
_You struggle against the net. The merfolk completely misses you.
_You struggle against the net. The merfolk completely misses you.
 You struggle against the net. The merfolk completely misses you.
_You rip the net and break free! The merfolk barely misses you.
_The merfolk hits you with a +0 trident of protection!
 You blast the merfolk!!!
 You kill the merfolk!
```

As far as gameplay goes, this is all well and good... but I'm "a raging, lightning-filled tempest!" How can one possibly catch a tempest in a net? So this was a rather unexpected occurrence.

**EXTRA FILES:**
http://crawl.akrasiac.org/saves/Acceptance-crawl-0.27-210918-1921.tar.bz2

**Comment by shedivesin** [comment]
I'll also note that manticore barbs can stick you. This strikes me as reasonable from a gameplay perspective, but if you try to move while this occurs, the game says, "The barbs in your skin will harm you if you move. Continue?"

...do I still even have skin in this form?

**Comment by randomMesh** [comment]
I am not a developer so my opinion doesn't matter, but i think if Storm Form renders you invulnerable to barbs and imune to nets it will be overpowered. It's a matter of balance.

**Comment by ebering** [comment]
While you are a storm in storm form you are a sufficiently dense storm to be corporeal enough for nets and have a well defined boundary layer that might as well be called skin.

Pictured: storm form user chasing Greg

![](https://i.imgur.com/kEjvE4D.gif)
