### ISSUE TITLE
+Inv appears on ring randart

### ISSUE THREAD

**Issue by dillytin** [crawl/crawl#2155]
Ver: 0.28-a0-479-g5baa6b73be

According to bf8bb431c4fd50ed5cbcb834d2b4b4d121d16f3a, +Invis can now only appear on armour and amulets, to limit
swapping to activate it. 

![image](https://user-images.githubusercontent.com/65288602/134510398-de55bf9c-f4c3-4423-aaf1-9523f63a5c90.png)

https://webzook.net/soup/morgue/trunk/qyongq/morgue-qyongq-20210923-125312.txt

but somehow now randart rings have it.

**Comment by v-chirkov** [comment]
I'll work on it today, once I get crawl to compile.

**Comment by strategineer** [comment]
Looking at the morgue file, it seems like you started playing this character more than a month before this change was committed 

"Began as a Troll Gladiator on Mar 5, 2021.": but the change was committed in April 12, 2021).

Then you came back, to finish playing many months later: "... on level 2 of the Depths on Sept 23, 2021."

I'm guessing that the ring was generated before the change was made+released?

**Comment by dillytin** [comment]
Seems right. Close this issue.
