### ISSUE TITLE
crawl_dir option not working as expected

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2192]
Hello,

everytime i want to play Crawl (local tiles), i start the executable in a terminal emulator
```bash
cd ~/development/crawl/crawl-ref/source/
./crawl
```
I wanted to make this easier and created a [Desktop Entry](https://specifications.freedesktop.org/desktop-entry-spec/latest/) file which looks like this
```bash
[Desktop Entry]
Name=Crawl
Exec=/home/xxx/development/crawl/crawl-ref/source/crawl
Path=/home/xxx/development/crawl/crawl-ref/source
Icon=/home/xxx/development/crawl/crawl-ref/source/android-project/res/drawable-hdpi/ic_launcher.png
Terminal=false
Type=Application
StartupNotify=false
Categories=Game;
```

Starting Crawl using this file works, but it seems that the `Path` variable is not respected and Crawl creates new `morgue` and `saves` directories in my home directory rather than using the existing ones in the cloned repository.

So i thought it was a good idea to use the `crawl_dir` option in my init.txt and added
`crawl_dir = ~/development/crawl/crawl-ref/source` to it.

Unfortunately, this doesn't help, the saves and morgue directories are again created in my home.

In addition, the option guide says that `crawl_dir` "Defaults to the directory that contains the Crawl executable."
Seem like this not the case when using a Desktop Entry file.

What am i missing?

**Comment by randomMesh** [comment]
Can i get feedback please? Is this a bug in Crawl or did i do something wrong?

**Comment by rawlins** [comment]
I'm not sure what exactly `crawl_dir` is supposed to do, but the save/morgue directory is not relative to `crawl_dir` as set in the rc file; to change this in a an rc file use `save_dir`. It may be better to change this through build options or environment variables. E.g. `CRAWL_DIR=/path/to/wherever ./crawl` probably does what you want.

**Comment by randomMesh** [comment]
Thanks for the commit, works like a charm.

**Comment by randomMesh** [comment]
Ok, i confirmed too fast. It works for the `saves` directory but the `morgue` directory is still created in the home directory.

**Comment by rawlins** [comment]
I think that commit will probably fix it, though I didn't replicate exactly that behavior on a mac.

**Comment by randomMesh** [comment]
> I think that commit will probably fix it

For me, it does. Thank you!
