### ISSUE TITLE
Redraw issue after going fullscreen from welcome screen

### ISSUE THREAD

**Issue by erf** [crawl/crawl#2218]
**PLATFORM and OS or BROWSER:**
macOS (12.0.1 (21A559)), tiles version

**DCSS VERSION AND GAME INFORMATION:**
68644deec8

**DESCRIPTION:**
If i go to fullscreen by pressing CMD+CTRL+f in the welcome screen, i enter the menu page, but there is some drawing issues (see screenshot).

After i press a button in the menu, it is rendered correctly.

<img width="929" alt="Screenshot 2021-11-08 at 20 04 36" src="https://user-images.githubusercontent.com/1562523/140802337-441841ad-1776-4e91-84ee-a97c6679b141.png">

**Comment by rawlins** [comment]
Thanks for the report. Is this on a retina device (or a monitor with scaling enabled)?

**Comment by erf** [comment]
This is on a retina device. A macbook air 13" m1

**Comment by mikeayer** [comment]
FWIW, I have the same machine/OS combo and it does not display that behavior.

**Comment by rawlins** [comment]
I can't replicate this on a retina 13" MBP on Mojave either. I'm not surprised though as Monterey definitely changes some full screen logic for computers with notches, and maybe our version of SDL isn't handling that correctly. I would expect it to replicate on Monterey, though. Followup questions:

* @erf do you have any relevant rc settings? Is your scaling on "default for display" or something else? Do you see it attempt to resize once it goes full screen? (It should noticeably adjust the font sizes after the window goes full screen or out of full screen.)

* @mikeayer were you checking on a trunk build, or on 0.27.1? (It's possible this could be a trunk x monterey interaction.)

**Comment by erf** [comment]
@rawlins  

This was an issue before upgrading to Monterey also.

No special settings. It is set to "Default for display".

Note that this only happen when going full screen in the "Splash/Welcome" which takes you to the "Menu screen" and displays the error. When you press any button, the display error in the menu screen disappears.

**Comment by rawlins** [comment]
> Note that this only happen when going full screen in the "Splash/Welcome" which takes you to the "Menu screen" and displays the error. 

Aha! I hadn't parsed this correctly in the original report. I can replicate it by doing this on my 13" MBP / Mojave.

In fact on my M1 mac mini / big sur if I hit fullscreen with the keybarod shortcut at the splash screen, it is *way* buggier than in the screenshot here, it's not even readable. Oddly, it works just fine with the fullscreen button on big sur.

**Comment by erf** [comment]
Great you were able to replicate! It's just a small annoyance, but maybe there is a simple redraw call that could be added to fix this.

**Comment by mikeayer** [comment]
Ah, yes, using the keyboard shortcut I can repro this now as well, in 0.27.1.  As with others, I was using the window-top control at first which worked.
