### ISSUE TITLE
Feature request: webtiles: bring up the on-screen keyboard on iPadOS, iOS

### ISSUE THREAD

**Issue by Walther** [crawl/crawl#2221]
**PLATFORM and OS or BROWSER:**
- `webtiles`, on https://underhound.eu:8080
- Firefox for iPad 38.1
- Safari for iPad 15.0 (605.1.15)
- Firefox for iOS 39.0
- Safari for iOS 15.0 (604.1)

**DCSS VERSION AND GAME INFORMATION:**
- 0.27

**DESCRIPTION:**

It could be fun to be able to play DCSS on the iPad (and possibly iPhone).

Modern browsers seem to do a decent job at rendering the webtile game, and you can even poke at tiles to move to locations, which is nice! However, there is no input field, visible or hidden/virtual, that would bring up the on-screen keyboard on these devices. Additionally, there is no operating-system-provided way for the user to force bringing up an on-screen keyboard on these devices. This means that any commands apart from "move to this tile" cannot be made in the browser on iPad or iPhone, without connecting an external physical keyboard. Of course it is possible to e.g. click the chat box at the bottom right, and you will get the on-screen keyboard for typing comments, but it will disappear immediately when you click outside the chat box.

It would be nice if the webtiles web UI had some mechanism of requesting the on-screen keyboard to be present. 

Thanks!

**Comment by robertxgray** [comment]
Challenge accepted. My proposal is available on #2332. Could you test it on iOS please?
