### ISSUE TITLE
webtiles: UI papercut when reading unknown identify scroll from inventory

### ISSUE THREAD

**Issue by Walther** [crawl/crawl#2232]
**PLATFORM and OS or BROWSER:**
`webtiles`

**DCSS VERSION AND GAME INFORMATION:**
`0.27`

**DESCRIPTION:**
1. Early game, pick up various unidentified scrolls
2. Open inventory with `i`, use a letter to select a scroll, and then `r` read it
3. The big inventory modal will stay visible, with everything behind it darkened
4. There will be a text almost hidden in the darkened background, saying "it was a scroll of identify --more--"
5. The UI requires the user to press <kbd>Enter</kbd> in order to proceed, while giving very little indication towards it
6. After pressing <kbd>Enter</kbd>, you'll get a second modal on top for actually selecting which item to identify. (Sidenote: background gets darkened further, duplicate darkens?)

In short: in early game, reading your first identify scroll from your inventory will require the player to press <kbd>Enter</kbd> at a time where there's very little indication for it. This happens fairly often due to the nature of the setup - you have to read your first identify scroll without knowing it. While the impact perhaps isn't large - after all, a simple keypress solves it - it can be a bit confusing and a slight UI papercut /  a small but repetitive annoyance.

Possible suggestion: when reading the scroll, immediately close the inventory modal, returning to the normal map + text view, and open the pick-what-to-identify modal after the <kbd>Enter</kbd> keypress on the now more visible "--more--" text. Of course, feel free to figure out other options too.

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/2943750/142262406-4bf87e14-308e-4877-92eb-227d62c09217.png)
![image](https://user-images.githubusercontent.com/2943750/142263186-8bed7ce4-588c-484b-a1cf-e3a1ac9ad053.png)

**Comment by sparkchaser** [comment]
I'll add that this is a much larger issue when you have a fairly full inventory and a small screen area.  The main inventory window can grow large enough to hide the message area completely.

In this particular case, the "more" message makes sense when playing on the console but seems like an unnecessary hoop to jump through for tiles.  The user-friendly solution would be to skip the "more" prompt entirely and add the "It was a scroll of identify" message to the top of the text in the "identify which item" dialog.  I'm not sure if that's worth creating a tiles/console inconsistency over, though.

**Comment by ebering** [comment]
I can't replicate this in either the latest 0.27.1 or current trunk. Could you provide more information: browser, public web tiles server (if applicable), rc file, and the `?v` in-game version string where you see this behavior?

**Comment by rawlins** [comment]
>I think the proposed solution is probably the best way to go

Actually, on looking into it I think what we need to do for the bugfix is just suppress the more, unfortunately because the inventory is also open it's extremely hard to clear the UI stack before triggering the action, would require some major refactoring.
