### ISSUE TITLE
Crashing in Slime - trunk CBRO

### ISSUE THREAD

**Issue by jeremysacco** [crawl/crawl#2240]
- webtiles - trunk on CBRO, Windows, Chrome
- started just after I got to Slime, having gotten three runes so far - crashed at several different points in Slime but all pretty quickly
- also just bought amulet of four winds, if that is causing problems with eyes trying to confuse me? 
- can't get a proper save backup right now but crash reports are in my morgue https://cbro.berotato.org/morgue/snackwell/ 

Not sure what else would be helpful, but there you go. Thanks.

**Comment by semitonal** [comment]
Thanks for the report, should hopefully be fixed now!
