### ISSUE TITLE
[Question] Is the save file format documented?

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2242]
**DESCRIPTION:**
I want to write an application which messes with the save files of a local tiles install. I've looked for documentation on the file format but didn't find any.

Is there documentation or do i need to browse the source?

**Comment by ebering** [comment]
To the extent that there is documentation it is in `docs/develop/` see in particular `docs/develop/save_compatibility.txt`.

Please don't use the issues system for questions like this (which are not bugs or ui feature requests). This is what the development IRC channel (#crawl-dev on libera.chat) is for.
