### ISSUE TITLE
"Where" information usually not shown in game list via SSH on CAO & CKO servers

### ISSUE THREAD

**Issue by smbhax** [crawl/crawl#2252]
**PLATFORM and OS or BROWSER:**
SSH - PuTTY 0.76 64-bit x86 Windows

**DCSS VERSION AND GAME INFORMATION:**
0.28-a0-938-gbc3f381ebc

**DESCRIPTION:**
The "Where" column for games being played on the crawl.akrasiac.org ("CAO") and crawl.kelbi.org ("CKO") servers is almost always blank when viewed over SSH.

"Where," when viewed on certain other servers over SSH, or when viewed on any of the eight public servers over WebTiles, typically shows the game character's level, type, and location.

(The game lists on two other servers I tried, CBR2 and CDO, *did* show "Where" info for almost all games when viewed over SSH.)

1) Log in to crawl.akrasiac.org or crawl.kelbi.org via SSH--I did so using the PuTTY client, following the instructions here: http://crawl.develz.org/wordpress/howto

2) Press "w" to view games in progress

    ==> Almost all games show no information in the "Where" column

**EXTRA FILES:**
Screenshot from CAO (early PST 11/28/21) where one game--which looked to be hosted by SSH--did show "Where" info, but it turned out to be out of date; other games, including my own that I tried later, hosted in a separate SSH PuTTY client--showed no "Where" info:
![crawl_where](https://user-images.githubusercontent.com/91744319/143777466-b83fca0e-19f5-4ffa-a2ea-8f1026486490.jpg)

**Comment by rawlins** [comment]
To show webtiles games' where info in dgl, there's an extra daemon that needs to be started by the server admin, that breaks every once in a while. I've started it back up on cao, and pinged the cko admin.

**Comment by smbhax** [comment]
Ah yes I see the Where info on CAO now, excellent! Thanks! : D

**Comment by smbhax** [comment]
If I see this at some future point while on CAO again, is there a better way to let the server admin know?

**Comment by rawlins** [comment]
The CKO daemon has also now been restarted, so I'll close this up.

As for letting server admins know stuff like this, contacting them via email, on discord, or on irc would be more direct for some cases -- depends on the server. But an issue here is fine.
