### ISSUE TITLE
Boldface font does not display for "bold" text (PuTTY SSH) unless extended colors are disabled

### ISSUE THREAD

**Issue by smbhax** [crawl/crawl#2253]
**PLATFORM and OS or BROWSER:**
SSH - PuTTY 0.76 64-bit x86 Windows

**DCSS VERSION AND GAME INFORMATION:**
0.28-a0-938-gbc3f381ebc

**DESCRIPTION:**
The PuTTY SSH client has an option to make "bold" text use a boldface font, as well as a brighter color. The brighter color shows up in Crawl played over SSH in PuTTY, but the boldface font--thicker letters--does not, unless the user disables extended color support.

Ideally, boldface fonts and extended color support would be supported simultaneously in Crawl.

1) Configure PuTTY to run Crawl over SSH as shown on http://crawl.develz.org/wordpress/howto , including "Data > Terminal-type string > set value to xterm-256color"

2) Run a game of Crawl over PuTTY SSH--I was doing this on the crawl.akrasiac.org server

3) Set PuTTY's "Window - Colours - Indicate bolded text by changing" setting to "Both"

    ==> "Bold" text in the game, such as the character name and title in the upper right, shows up as a brighter color, but not in a boldface (thicker) font

I was only able to get a boldface font by disabling the game's extended color support (disabling extended colors can be done by removing "-256color" from PuTTY's "Terminal-type string" setting, or by setting "allow_extended_colours = false" in the game's .rc file).

**EXTRA FILES:**
In PuTTY settings, setting bold for both font (thick, boldface letters) and color (brighter text colors):
![putty1](https://user-images.githubusercontent.com/91744319/143778040-0c63511a-8cfb-4012-a21b-f7c3715bc2be.jpg)

However, this does not make bold text in the game use a thicker font--notice the yellow character name and title in the upper right, for instance:
![putty0](https://user-images.githubusercontent.com/91744319/143778221-404bca1b-9c71-4834-8492-8b6001b1bf23.jpg)

Turning off extended color support via the .rc file:
![putty2](https://user-images.githubusercontent.com/91744319/143778061-f61214f6-5ac6-4cce-a289-448eaa3d0c4c.jpg)
![putty3](https://user-images.githubusercontent.com/91744319/143778069-8e1a6cd2-4f48-4f33-a613-4c91a1e53051.jpg)

Now the boldface font is used; however, extended color support has been sacrificed:
![putty4](https://user-images.githubusercontent.com/91744319/143778078-ca89f71e-9c4f-4c06-832d-7cc4c0aaf609.jpg)

**Comment by ebering** [comment]
This was an intensional change in 52be93032c369 to default `allow_extended_colours` to true. Crawl's appearance using boldface was to use the convention that boldface characters render as "bright" colors for terminals that did not support extended colours.

As you've discovered, the bolding behavior can be produced by setting `allow_extended_colours` to false.
