### ISSUE TITLE
Missile quivered from its details screen with (q)uiver doesn't stay in quiver

### ISSUE THREAD

**Issue by smbhax** [crawl/crawl#2257]
**PLATFORM and OS or BROWSER:**
SSH - PuTTY 0.76 64-bit x86 Windows

**DCSS VERSION AND GAME INFORMATION:**
0.28-a0-938-gbc3f381ebc

**DESCRIPTION:**

I have a Minotaur Fighter with a war axe for weapon a, paired with quivered stones for throwing, and a hunting sling for weapon b, with stones in the quiver for firing. I want to switch the sling to firing the sling bullets I've found; I can do this through the (q)uiver command on the sling bullets' details page, but when quivered this way--rather than with Q--the sling's quiver will revert to stones when I toggle to the axe and back.

This resembles closed issue 2084, a similar bug found when using the (q)uiver command from a *bow's* details screen--(q)uiver was subsequently removed from the bow details screen, and that issue marked fixed. (q)uiver is still causing a problem from a missile's details screen, however:

1) Use apostrophe (') to switch to weapon b, the sling, if necessary
2) Press i to pull up the inventory
3) Select the sling bullets (v in my inventory)
4) Press q to (q)uiver the bullets
==> The bullets are now shown in the sling's quiver. Oddly though, on the right edge of the screen from the sling's listing in the player's status display at upper right (playing in SSH), the previously quivered missiles, stones, appear in parentheses: "(341 stones)"
5) Press apostrophe (') twice to toggle to the axe and back to the sling
==> The stones are quivered now instead of the bullets, which are not shown

Video here: https://youtu.be/GuXzHCm1oTE?t=4700

**EXTRA FILES:**
Save backup: http://crawl.akrasiac.org/saves/smbhax-crawl-git-bc3f381ebc-211128-2007.tar.bz2

The sling with stones quivered:
![q1](https://user-images.githubusercontent.com/91744319/143798375-f5f102b6-5237-4965-b0b5-9c2c9262507a.JPG)

Selecting sling bullets from inventory:
![q2](https://user-images.githubusercontent.com/91744319/143798395-679fb5fa-2d76-4e29-a77a-3981e68e1db7.JPG)

Sling bullets' details screen with the (q)uiver command:
![q3](https://user-images.githubusercontent.com/91744319/143798412-92419dc5-6ecd-41b0-88c1-0f127b5f3610.jpg)

After (q)uiver from the bullets' screen, they're quivered, but with stones showing to the right of the sling, in parentheses:
![q4](https://user-images.githubusercontent.com/91744319/143798423-32938388-62cb-4993-a9ad-022c8c03f152.JPG)

Toggling to the axe with ':
![q5](https://user-images.githubusercontent.com/91744319/143798447-f0e5831e-7534-46a7-bff6-0bbc1d87fa4e.JPG)

Toggled back to the sling with ' and the bullets have been replaced by the stones:
![q6](https://user-images.githubusercontent.com/91744319/143798462-490a0f16-1890-4e89-898b-23ef9efbc213.JPG)

**Comment by rawlins** [comment]
Thanks for the detailed report!
