### ISSUE TITLE
3 altars of Lugonu in the Ecumenical Temple

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2258]
**PLATFORM and OS or BROWSER:**
Local tiles, Linux

**DCSS VERSION AND GAME INFORMATION:**
Latest master branch

**DESCRIPTION:**
In a game of mine, the Ecumenical Temple contained 3 altars of Lugonu. I don't know if this is intended but i think there should be a limit of 1 altar per god in the temple.

**EXTRA FILES:**
![2021-11-29-111054_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/143849407-32ff65f1-1120-46ef-a864-09a7a723ec7f.png)

**Comment by ebering** [comment]
This is the "corrupted temple" and is intended.
