### ISSUE TITLE
Shape-shifters 

### ISSUE THREAD

**Issue by Danielbossbaby** [crawl/crawl#2269]
**PLATFORM and OS or BROWSER:**
*e.g. "local tiles", "webtiles", or "console". Putting this in the labels is
also fine. If this is an offline game or an issue with the build process,
please include your OS and OS version; if this is an online game please
include your browser and version.*

**DCSS VERSION AND GAME INFORMATION:**
*e.g. "0.18", ""0.19-a0-1891-ge1d1fe8". If you can launch the game, you can
find this information by pressing ?v; the version will be at the top of the
screen. If not, check the changelog in the 'docs' directory. If this is
a vault issue, it will be particularly helpful to provide the game seed (found
in the morgue after a completed game) and identify the dungeon level, so that
we can reproduce it. If relevant, please provide the server and username.
For online play, a morgue link for a completed game will give all of this
information.*

**DESCRIPTION:**
*What happened? What went wrong? What else was going on at the time of the
problem? Can you reproduce the issue? If you can provide a specific sequence
of steps that reproduces the issue, that will be extremely helpful to us (and
may also help you in writing the bug report). Screenshots are also very
welcome; you should be able to upload these directly to github.*

**EXTRA FILES:**
*Please include any morgue files, crashlogs, save files here, or extra
screenshots here. If this is a crash bug, the crashlog and save file will be
extremely helpful; the location of these is sytem-specific but if you ask
we can help you find them.*

*To upload a save file directly to github, compress it to a .zip archive, and
then github will accept the upload. (It will not take a .cs file directly.)*

*If this is an online game, see [these instructions](https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup)
for more information on how to make a save backup; you can provide the
resulting link here.*

Ok so shape-shifters getting health back when they change form.
is:issue is:open shape-shifters get thier health back when they shape shift. No scroll mutation is overpowered unbalanced and straight up unfair a high chance of getting it over and over. You can still read scrolls close the game and scroll is back unread. Weapons that you max out with scrolls should turn into random artifacts of the same type. You can't brand armour. Bardchie can't talk to frogs and toads. Anamate skeleton is so weak now now i don't even bother to learning it. I love not having to eat and identity of weapons. I think items in shops should be able to scroll id. Hellfire toment and flayed overpowered

**Comment by randomMesh** [comment]
> I think items in shops should be able to scroll id.

That woud be great!

**Comment by Danielbossbaby** [comment]
Thanks for the reply.

**Comment by ebering** [comment]
Hello, welcome to the crawl GitHub. The "Issues" tracker is for specific, single issues: bug reports and specifically fleshed out feature requests. For wide ranging discussion of gameplay [head on over to one of our community forums](https://github.com/crawl/crawl#community).
