### ISSUE TITLE
Game crashes upon launch

### ISSUE THREAD

**Issue by PeacefulPotato** [crawl/crawl#2276]
**PLATFORM and OS or BROWSER:** MX Linux 21, Devuan Chimaera 4.0, Linux 5.10.0-9, Flatpak version

**DCSS VERSION AND GAME INFORMATION:** 0.27.1

**DESCRIPTION:** I tried to open the game after installing from Flathub and it crashed. To reproduce it, install from Flathub and try to run. See the screenshot below:
![crash](https://user-images.githubusercontent.com/57071692/144958216-85fa5535-81aa-4a7f-8d5a-95d3c129bb99.png)

**EXTRA FILES:** [crash--20211206-215135.txt](https://github.com/crawl/crawl/files/7665170/crash--20211206-215135.txt)

**Comment by robertxgray** [comment]
There's an open issue in Flathub with the same error. I think you should report it there: https://github.com/flathub/org.develz.Crawl/issues/10

**Comment by rawlins** [comment]
I'm closing this here because to the extent this is a dcss issue 9c4cb82 should solve it. (But I think it's most likely an issue with how metadata is handled in a flatpak, I've also made a comment on the issue @robertxgray linked.)
