### ISSUE TITLE
Confusing colors in spell description

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2280]
**PLATFORM and OS or BROWSER:**
Local tiles, Linux

**DCSS VERSION AND GAME INFORMATION:**
Latest master branch

**DESCRIPTION:**
In local tiles, if you right-click a monster you'll see the spells it can cast. If you click multiple times, the color of the numbers is always the same.

Not so with the spell "Quicksilver Bolt" of "Quicksiver Dragon"s. It changes the colors everytime.
Is this intended or a bug? In either way, it's confusing.

Here is an example. Six successive clicks - six different colorisations.

**EXTRA FILES:**
![2021-12-08-174153_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/145249559-099c9b1c-0467-436f-a851-88b0aab08ac7.png)
![2021-12-08-174200_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/145249566-9181ceae-28b0-4081-9a01-8d08ab2cefbd.png)
![2021-12-08-174229_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/145249567-f1499cf6-2ffa-4680-afd5-cc06d8461b90.png)
![2021-12-08-174238_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/145249569-1b635545-db83-4b08-a95f-cb260d2a49a0.png)
![2021-12-08-174242_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/145249571-113ee635-ae51-462e-91f0-68ddc14fc37e.png)
![2021-12-08-174310_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/145249573-fe460762-d353-4ac6-a74a-6c2efb94ff29.png)

**Comment by rawlins** [comment]
The color of the damage indicator is derived from the spell's color theme, which for dispelling bolt, is random colors. I suspect this was to indicate some chaotic aspect to the spell. Chaos breath also has this color theme, so you will see similar coloring on an apocalypse crab's ability.

(I'm not sure a change is needed here.)

**Comment by randomMesh** [comment]
Ok, thanks. But when testing, i had one "color theme" which was all gray. Maybe then exclude all-the-same-color themes?

**Comment by ebering** [comment]
I don't think a change is required here. The odds of a monochrome 4 character string are quite small, and the spell's description is available from that menu for clarification.
