### ISSUE TITLE
Typo in monster description

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2282]
**PLATFORM and OS or BROWSER:**
Local tiles, Linux

**DCSS VERSION AND GAME INFORMATION:**
Lates master branch

**DESCRIPTION:**
There is a typo in the description for the Sphinx.

It says "fell magics" while it should be "[fel magics](https://wowpedia.fandom.com/wiki/Fel)".

Link to line: https://github.com/crawl/crawl/blob/a282ea246d36b12ac2f94000147c2ba87d252410/crawl-ref/source/dat/descript/monsters.txt#L2311

**Comment by semitonal** [comment]
This isn't a typo, see https://www.merriam-webster.com/dictionary/fell (definition 4).

**Comment by randomMesh** [comment]
Oops. Sorry for the noise.
