### ISSUE TITLE
Game stops accepting keyboard input after examining specific randart

### ISSUE THREAD

**Issue by Shapermc** [crawl/crawl#2284]
Webtiles, CKO, Dungeon Crawl Stone Soup version 0.28-a0-1110-g97e41b5463 (webtiles) Chrome Browser, Windows

While playing I tried inspecting this item: M - +0 kite shield of Hucuq {Harm rC+ Regen+ Str+3}

I open the inventory using (i) then I press the letter of the item (M) then the game just changes the - to the left of the item listing to a + then the game stops accepting inputs. I can esc out of the inventory menu, but no other button inputs are accepted. Character dump attached.
[Shapermc.txt](https://github.com/crawl/crawl/files/7695263/Shapermc.txt)

**Comment by ebering** [comment]
This was fixed in 5c4f51bb93
