### ISSUE TITLE
Stuck in a Tar-pit

### ISSUE THREAD

**Issue by sparkchaser** [crawl/crawl#2291]
**PLATFORM and OS or BROWSER:**
local tiles, Windows 10 20H2

**DCSS VERSION AND GAME INFORMATION:**
v0.28-a0-802-g09f76e8c00  (binary was an official nightly build)
seed: 1253952682822606321

**DESCRIPTION:**
I was exploring Tartarus and got randomly shafted to Tar:4.  I landed inside the vault named `grunt_tartarus_stairs_gauntlet_trap`, inside one of the side hallways.  Those hallways are disconnected from the rest of the map until that vault's trap gets "triggered", which can't be done from inside the hallways.  The walls aren't diggable, and a silent spectre has the area silenced so I couldn't use shatter/teleport scroll (some players wouldn't have those things available anyway).  After about 5-6 minutes of continually walking back and forth down the hallway, I got randomly shafted again and landed next to an exit back to the vestibule.

I made my way back to Tar:4 and after clearing about half the monsters (but without triggering that vault's trap), a random teleport trap landed me in the *other* side hallway.  This time I had to conjure up an escape hatch via wizmode in order to get out.

**EXTRA FILES:**
![stuck_in_tar](https://user-images.githubusercontent.com/1392511/145702875-2a3893bf-9709-4aa9-9fdc-97843bee0f0c.jpg)

It seems like if the hallways were always open at the top end, you wouldn't be able to get stuck inside there and you'd still spring the trap (but wouldn't have to face the monsters) when you left the hallway.

**Comment by ebering** [comment]
Fixed, thanks for the report!
