### ISSUE TITLE
Merfolk innate ability wrongly described

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2295]
**PLATFORM and OS or BROWSER:**
Local tiles, Linux

**DCSS VERSION AND GAME INFORMATION:**
Latest master branch

**DESCRIPTION:**
The description of the Merfolk mutation is wrong.

It says `You are quick and stealthy near water. (Stealth+, EV+, Speed+++)`.

This is not the case, as you can see in the screenshot. It's disabled "near" water.

 It has to say `You are quick and stealthy IN water.` instead.

**EXTRA FILES:**
![2021-12-15-084431_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/146144763-a3b7e49d-64b7-4d89-9133-67929dbe188d.png)

**Comment by randomMesh** [comment]
Thinking about it, it would be nice to enable this ability when near water also. So this bug report becomes a feature request now.

I don't know if it's feasible (performance-wise, i.e. checking the surrounding tiles instead the one standing on, balance-wise, etc.) but this would make the mutation more attractive.

**Comment by rawlins** [comment]
FWIW the wording of this is because this mutation activates for a flying Mf as well as a swimming one, so "in" would not be right.

**Comment by randomMesh** [comment]
Maybe do both: Change the wording to "besides" and enable it it there is water nearby.

**Comment by nicolae-carpathia** [comment]
Maybe just "You are quick and stealthy when in the same tile as water."

**Comment by randomMesh** [comment]
> in the same tile

Sounds too technical. In addition, this also applies to the console version which has no "tiles".

**Comment by nicolae-carpathia** [comment]
Wu Jian already mentions tiles in the description of the martial arts moves on the "Extra" tab.

**Comment by robertxgray** [comment]
I consulted this topic with an English philologist (my wife). She thinks "You are quick and stealthy around water" would be a good description, at least from the UK point of view. Because around can indicate a relationship with something, which would include both in and above. She is also currently playing a MfMo, so she knows about these things :wink:

**Comment by nicolae-carpathia** [comment]
Maybe just spell out the two situations explicitly: "You are quick and stealthy while in or flying above water."

**Comment by randomMesh** [comment]
"while water is in sight" would be nice. Of course this would be an extreme buff to that mutation.
