### ISSUE TITLE
Experimental "Spider rework" - artifact +2 armour without enchantment

### ISSUE THREAD

**Issue by DevastatorOne** [crawl/crawl#2296]
Browser: Google Chrome, ver. 96.0.4664.93

DCSS VERSION AND GAME INFORMATION:
Game was played on Webtiles, crawl.dcss.io, Spider rework
https://crawl.dcss.io/crawl/morgue/DevastatorOne/morgue-DevastatorOne-20211215-103201.txt

DESCRIPTION:
This is the first time I see this. I was almost on my way out with the Orb when i thought that buying all stuff from shops will be a good idea. This ring mail can be found on D:9.

EXTRA FILES:
![image](https://user-images.githubusercontent.com/81159762/146171292-e59b36dc-127c-4f45-bf58-28f4c1cf323b.png)

**Comment by Goratrix** [comment]
This was fixed in master in commit 4a18f0a on Sept 28, but spider rework branch was rebased on Sept 21, so it still happens there.
