### ISSUE TITLE
Message error in trunk: notify_dgn_event

### ISSUE THREAD

**Issue by oktalk** [crawl/crawl#2297]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
version 0.28-a0-1159-g27aa881441

**DESCRIPTION:**
While playing dungeon sprint Thunderdome I started receiving this red message:
`notify_dgn_event: Lua error: [string "global_prelude"]:54: Not a monster spell: 'teleport self'`
I have experienced this once before, but only in trunk.

**EXTRA FILES:**
https://cbro.berotato.org/morgue/bronco/morgue-bronco-20211215-164622.txt

**Comment by ebering** [comment]
This was resolved as part of the removal of teleport self.
