### ISSUE TITLE
Staff Of Battle shows targeter with force_spell_targeter = all setting

### ISSUE THREAD

**Issue by Goratrix** [crawl/crawl#2300]
When you have _force_spell_targeter_ set as _all_, the Staff Of Battle shows a targeter that needs to be confirmed each time it creates a battlesphere. While I understand why it does it (it practically casts the spell and the setting applies to that), I think the targeter setting should only apply to spells cast by the player and not apply in this case (not sure if there are any other items that cast a spell like this).

**Comment by semitonal** [comment]
Thanks, should be fixed now! As far as I can tell this was the only place using your_spells to cast a spell that the player shouldn't have any control over (other examples are all things where the player is supposed to be able to target and cancel them, like the staff of Olgreb).
