### ISSUE TITLE
Crash upon save for FeSu^J at desolation of salt entrance

### ISSUE THREAD

**Issue by Jackiecrazy** [crawl/crawl#2308]
**PLATFORM and OS or BROWSER:** local tiles

**DCSS VERSION AND GAME INFORMATION:**0.28-a0-1260-gc629bbe4ae

**DESCRIPTION:** the game will crash immediately upon saving my FeSu^G. It appears that new runs are fine, and so are all my other runs (DgHu, DDFi^E, DsGl^G, OpTm^G). Perhaps it has to do with the fact that I'm standing outside the entrance to the desolation of salt? This doesn't seem to be triggered by storm form, from what I can tell by fiddling around with what causes it (hence the rapid save-load).

**EXTRA FILES:**[crash](https://github.com/crawl/crawl/files/7776472/crash--20211225-183722.txt) [save](https://github.com/crawl/crawl/files/7776473/Inescapable.zip)

**Comment by rawlins** [comment]
Thanks for the report! The save enabled me to replicate this easily.
