### ISSUE TITLE
crawl 0.27.1 - Aborted (core dumped)

### ISSUE THREAD

**Issue by gramaphone** [crawl/crawl#2311]
Crawl version 0.27.1
Save file version 34.234
Compiled with GCC 6.3.0 20170516
Build platform: x86_64-linux-gnu
Platform: x86_64-linux-gnu
CFLAGS: -O2 -fdebug-prefix-map=/build/crawl-0.27.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -flto=jobserver -fwhole-program -fno-fat-lto-objects -pipe -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua5.1 -DWIZARD -DASSERTS -DCLUA_BINDINGS -DSAVE_DIR_PATH="~/.crawl" -DDATA_DIR_PATH="/usr/share/crawl/" -D_GNU_SOURCE -D_DEFAULT_SOURCE -isystem /usr/include/ncursesw
LDFLAGS: -rdynamic -fuse-ld=gold -O2 -fdebug-prefix-map=/build/crawl-0.27.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -flto=jobserver -fwhole-program -fno-fat-lto-objects

**DESCRIPTION:**
I died in-game, then crawl crashed after showing the high-scores screen.

**EXTRA FILES:**

ASSERT(save) in 'tags.h' at line 67 failed.

Version: Dungeon Crawl Stone Soup 0.27.1
Platform: unix
Bits: 64
Game mode: normal
Tiles: no

Seed: 15797548993487981771, deterministic pregen: 1
Command line: crawl

RC options:
restart_after_game = maybe

Crash caused by signal #6: Aborted

Obtained 27 stack frames.
crawl(+0x1ca2fb) [0x55afab8fe2fb]: 
crawl(+0x1f2a4d) [0x55afab926a4d]: 
/lib/x86_64-linux-gnu/libc.so.6(+0x46520) [0x7f1ffdd35520]: 
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0xf8) [0x7f1ffdd89808]: 
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7f1ffdd35476]: 
crawl(+0x6adb4b) [0x55afabde1b4b]: 
crawl(+0x1c1953) [0x55afab8f5953]: 
crawl(+0x22b818) [0x55afab95f818]: 
crawl(+0x324462) [0x55afaba58462]: 
crawl(+0x529b4f) [0x55afabc5db4f]: 
crawl(+0x552472) [0x55afabc86472]: 
crawl(+0x553fca) [0x55afabc87fca]: 
crawl(+0x251031) [0x55afab985031]: 
crawl(+0x67c87d) [0x55afabdb087d]: 
crawl(+0x627b9d) [0x55afabd5bb9d]: 
crawl(+0x55225b) [0x55afabc8625b]: 
crawl(+0x553fca) [0x55afabc87fca]: 
crawl(+0x252260) [0x55afab986260]: 
crawl(+0x511a0d) [0x55afabc45a0d]: 
crawl(+0x516229) [0x55afabc4a229]: 
crawl(+0x6fdb5a) [0x55afabe31b5a]: 
crawl(+0x702bd4) [0x55afabe36bd4]: 
crawl(+0x707d85) [0x55afabe3bd85]: 
crawl(main+0xb96) [0x55afab845b66]: 
/lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0) [0x7f1ffdd1cfd0]: 
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f1ffdd1d07d]: 
crawl(_start+0x2a) [0x55afab867bda]: 

Trying to run gdb.
GNU gdb (Ubuntu 11.1-0ubuntu2) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f1ffdddc6ca in __GI___wait4 (pid=9082, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#0  0x00007f1ffdddc6ca in __GI___wait4 (pid=9082, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
        sc_ret = -512
        sc_ret = <optimized out>
#1  0x000055afab8f0b8b in ?? ()
No symbol table info available.
#2  0x000055afab926a6b in ?? ()
No symbol table info available.
#3  <signal handler called>
No locals.
#4  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139775378877312) at pthread_kill.c:44
        tid = 8234
        ret = 0
        pd = 0x7f1ffdce6b80
        old_mask = {__val = {140729129669456, 8531018516025894656, 94212993721968, 139775382953148, 94212993721952, 140729129669696, 43, 94213010845040, 43, 8531018516025894656, 94212987559120, 43, 0, 94212993721952, 0, 140729129669696}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#5  __pthread_kill_internal (signo=6, threadid=139775378877312) at pthread_kill.c:80
No locals.
#6  __GI___pthread_kill (threadid=139775378877312, signo=signo@entry=6) at pthread_kill.c:91
No locals.
#7  0x00007f1ffdd35476 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#8  0x000055afabde1b4b in ?? ()
No symbol table info available.
#9  0x000055afab8f5953 in ?? ()
No symbol table info available.
#10 0x000055afab95f818 in ?? ()
No symbol table info available.
#11 0x000055afaba58462 in ?? ()
No symbol table info available.
#12 0x000055afabc5db4f in ?? ()
No symbol table info available.
#13 0x000055afabc86472 in ?? ()
No symbol table info available.
#14 0x000055afabc87fca in ?? ()
No symbol table info available.
#15 0x000055afab985031 in ?? ()
No symbol table info available.
#16 0x000055afabdb087d in ?? ()
No symbol table info available.
#17 0x000055afabd5bb9d in ?? ()
No symbol table info available.
#18 0x000055afabc8625b in ?? ()
No symbol table info available.
#19 0x000055afabc87fca in ?? ()
No symbol table info available.
#20 0x000055afab986260 in ?? ()
No symbol table info available.
#21 0x000055afabc45a0d in ?? ()
No symbol table info available.
#22 0x000055afabc4a229 in ?? ()
No symbol table info available.
#23 0x000055afabe31b5a in ?? ()
No symbol table info available.
#24 0x000055afabe36bd4 in ?? ()
No symbol table info available.
#25 0x000055afabe3bd85 in ?? ()
No symbol table info available.
#26 0x000055afab845b66 in main ()
No symbol table info available.
[Inferior 1 (process 8234) detached]

Compilation info:
<<<<<<<<<<<
Compiled with GCC 6.3.0 20170516
Build platform: x86_64-linux-gnu
Platform: x86_64-linux-gnu
CFLAGS: -O2 -fdebug-prefix-map=/build/crawl-0.27.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -flto=jobserver -fwhole-program -fno-fat-lto-objects -pipe -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua5.1 -DWIZARD -DASSERTS -DCLUA_BINDINGS -DSAVE_DIR_PATH="~/.crawl" -DDATA_DIR_PATH="/usr/share/crawl/" -D_GNU_SOURCE -D_DEFAULT_SOURCE -isystem /usr/include/ncursesw
LDFLAGS: -rdynamic -fuse-ld=gold -O2 -fdebug-prefix-map=/build/crawl-0.27.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -flto=jobserver -fwhole-program -fno-fat-lto-objects 
>>>>>>>>>>>

Place info:
branch = 0, depth = 3

Level id: D:3
Level build method = , level layout type  = corridors, absdepth0 = 2
Level vaults:
    layout_loops_cross
    kennysheep_generic_room_16

Markers:
<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>

Messages:
<<<<<<<<<<<<<<<<<<<<<<
Welcome, Muggerton the Minotaur Berserker.
Will you prevail where others failed? Will you find the Orb of Zot?
Trog says: Kill them all!
Press ? for a list of commands and other information.
Found a staircase leading out of the dungeon.
You open the door.
There is an open door here.
You open the door.
There is an open door here.
Found a stone staircase leading down.
You open the door.
There is an open door here.
There is an open door here.
A bat comes into view.
The bat hits you but does no damage. The bat closely misses you.
You hit the bat but do no damage. Your headbutt misses the bat. The bat misses
you.
You furiously retaliate! You headbutt the bat!
You kill the bat!
Trog accepts your kill.
A goblin comes into view. It is wielding a +1 dagger of holy wrath.
The goblin shouts!
You hit the goblin. Your headbutt misses the goblin.
The goblin is severely wounded.
The goblin hits you with a +1 dagger of holy wrath.
The goblin closely misses you. You furiously retaliate! You headbutt the
goblin!
You kill the goblin!
Trog accepts your kill.
Things that are here:
a +1 dagger of holy wrath; a goblin corpse
Unknown command.
c - a +1 dagger of holy wrath
A giant cockroach comes into view.
You hit the giant cockroach but do no damage.
You headbutt the giant cockroach.
You kill the giant cockroach!
Trog accepts your kill.
Things that are here:
a giant cockroach corpse; a goblin corpse
HP restored.
Found a lumpy emerald amulet.
There are no items here.
d - an amulet of reflection
You start putting on your amulet.
You continue putting on your amulet of reflection. x5
You finish putting on your amulet of reflection.
You feel a shielding aura gather around you.
d - an amulet of reflection (around neck)
Found a stone staircase leading down.
There is a stone staircase leading down here.
A jackal comes into view.
The jackal barks!
A ball python comes into view.
A jackal comes into view.
The jackal barks!
The ball python hisses angrily.
You hit the jackal. You headbutt the jackal.
You kill the jackal!
Trog accepts your kill.
You hear a bark!
You closely miss the jackal.
A jackal comes into view.
The jackal bites you. The jackal closely misses you.
You barely miss the jackal. The jackal closely misses you.
You barely miss the jackal. The jackal barely misses you. You block the
jackal's attack.
You slash the jackal!
You kill the jackal!
Trog accepts your kill.
The ball python bites you but does no damage.
The ball python grabs you. The ball python constricts you.
You slash the ball python!
You kill the ball python!
Trog accepts your kill.
A jackal comes into view.
The jackal bites you.
Your Fighting skill increases to level 4!
Your Axes skill increases to level 4!
You closely miss the jackal.
The jackal barks!
You headbutt the jackal.
The jackal is severely wounded.
The jackal bites you.
You closely miss the jackal.
The jackal is severely wounded.
You block the jackal's attack. The jackal closely misses you. You furiously
retaliate!
You headbutt the jackal.
You hit the jackal but do no damage.
The jackal is almost dead.
The jackal barely misses you.
You closely miss the jackal.
The jackal is almost dead.
You block the jackal's attack. The jackal closely misses you. You furiously
retaliate!
You headbutt the jackal.
You kill the jackal!
Trog accepts your kill.
You have reached level 2!
You barely miss the jackal. You headbutt the jackal.
You kill the jackal!
Trog accepts your kill.
Things that are here:
a jackal corpse; a ball python corpse; a jackal corpse
You start resting.
HP restored.
Found a hunting sling.
Found a faded altar of an unknown god.
Press: ? - help, . - travel
You can't see that place.
[the floor.]
You open the door.
A bat comes into view.
Found 14 stones.
There is an open door here.
The bat barely misses you.
You hit the bat. Your headbutt misses the bat.
The bat is heavily wounded.
The bat misses you. You block the bat's attack.
You hit the bat.
You kill the bat!
Trog accepts your kill.
There is an open door, spattered with blood here.
You open the door.
A goblin comes into view. It is wielding a +0 club.
The goblin shouts!
You hit the goblin.
You kill the goblin!
Trog accepts your kill.
There is an open door here.
You see here a +0 club.
Found a stone staircase leading down.
A rat and a kobold come into view.
The kobold shouts!
You hit the kobold.
You kill the kobold!
Trog accepts your kill.
You block the rat's attack.
You barely miss the rat. Your headbutt misses the rat. You block the rat's
attack.
You hit the rat.
You kill the rat!
Trog accepts your kill.
Found a club.
Things that are here:
a +0 short sword; a rat corpse
Found a scroll labelled QAXAULI YSSUO.
e - a scroll labelled QAXAULI YSSUO
Found a fuming grey potion.
f - a fuming grey potion
A bat comes into view.
The bat closely misses you. You furiously retaliate! You headbutt the bat, but
do no damage.
You block the bat's attack.
You hit the bat but do no damage. Your headbutt misses the bat. The bat closely
misses you.
You furiously retaliate! You headbutt the bat!
You kill the bat!
Trog accepts your kill.
A goblin comes into view. It is wielding a +0 dagger.
The goblin shouts!
You closely miss the goblin. The goblin hits you but does no damage.
An endoplasm comes into view.
You barely miss the goblin.
The endoplasm quivers.
You headbutt the goblin.
You kill the goblin!
Trog accepts your kill.
Press: ? - help, v - describe, . - travel
Here: an endoplasm
The floor.
An endoplasm is nearby!
You barely miss the endoplasm. Your headbutt misses the endoplasm.
You block the endoplasm's attack.
You barely miss the endoplasm.
The endoplasm hits you but does no damage.
You hit the endoplasm. You headbutt the endoplasm.
You kill the endoplasm!
Trog accepts your kill.
Things that are here:
a +0 dagger; a goblin corpse
Found 10 gold pieces.
An endoplasm comes into view.
The endoplasm quivers.
You hit the endoplasm.
The endoplasm is lightly wounded.
The endoplasm hits you but does no damage.
You hit the endoplasm. You headbutt the endoplasm.
You kill the endoplasm!
Trog accepts your kill.
You now have 10 gold pieces.
You open the door.
There is an open door here.
g - a fizzy grey potion
As you open the door, it creaks loudly!
There is an open door here.
You open the door.
An endoplasm comes into view.
There is an open door here.
The endoplasm quivers.
You hit the endoplasm.
The endoplasm is heavily wounded.
The endoplasm hits you.
You hit the endoplasm.
You kill the endoplasm!
Trog accepts your kill.
Found a book of Changes.
You see here a book of Changes.
You pick up a book of Changes and begin reading...
You add the spells Beastly Appendage, Wereblood and Spider Form to your
library.
Found an escape hatch in the floor.
A hobgoblin comes into view.
You hit the hobgoblin.
The hobgoblin is heavily wounded.
The hobgoblin misses you. You furiously retaliate! You headbutt the hobgoblin!
You kill the hobgoblin!
Trog accepts your kill.
You open the door.
As you open the door, it creaks loudly!
There is an open door here.
There is an open door here.
You open the door.
Found 22 arrows.
Found a robe.
There is an open door here.
You see here a +0 robe.
h - a +0 robe
Drop what? 8/52 slots (_ for help) (? for menu, Esc to quit)
You drop a +0 robe.
A quokka comes into view.
You closely miss the quokka. The quokka closely misses you.
You hit the quokka but do no damage. You headbutt the quokka.
You kill the quokka!
Trog accepts your kill.
You see here a +0 robe.
Done exploring.
There is a stone staircase leading down here.
You climb downwards.
There is a stone staircase leading up here.
You block the bat's attack. The bat closely misses you.
You barely miss the bat. You headbutt the bat.
The bat is moderately wounded.
You block the bat's attack. The bat misses you.
You hit the bat.
You kill the bat!
Trog accepts your kill.
Found a stone staircase leading down.
You open the door.
There is an open door here.
You open the door.
There is an open door here.
You open the door.
There is an open door here.
A hobgoblin comes into view.
The hobgoblin shouts!
You hit the hobgoblin.
The hobgoblin is heavily wounded.
The hobgoblin closely misses you.
You slash the hobgoblin!
You kill the hobgoblin!
Trog accepts your kill.
A giant cockroach comes into view.
You completely miss the giant cockroach.
You block the giant cockroach's attack.
You closely miss the giant cockroach. You headbutt the giant cockroach.
The giant cockroach is heavily wounded.
The giant cockroach closely misses you.
You closely miss the giant cockroach.
Your headbutt misses the giant cockroach.
The giant cockroach is heavily wounded.
The giant cockroach closely misses you.
You hit the giant cockroach but do no damage.
The giant cockroach is heavily wounded.
The giant cockroach bites you but does no damage.
A quokka comes into view.
The giant cockroach barely misses you.
You closely miss the giant cockroach.
The giant cockroach is heavily wounded.
The giant cockroach bites you but does no damage.
You barely miss the giant cockroach.
Your headbutt misses the giant cockroach.
The giant cockroach is heavily wounded.
You block the giant cockroach's attack.
You barely miss the giant cockroach.
The giant cockroach is heavily wounded.
The giant cockroach waves its antennae.
The giant cockroach bites you but does no damage. x2
You hit the giant cockroach but do no damage.
The giant cockroach is heavily wounded.
You block the giant cockroach's attack.
You block the giant cockroach's attack.
You barely miss the giant cockroach. You headbutt the giant cockroach.
You kill the giant cockroach!
Trog accepts your kill.
You hit the quokka but do no damage. The quokka bites you. The quokka
completely misses you.
You hit the quokka.
The quokka is moderately wounded.
The quokka misses you.
You closely miss the quokka. Your headbutt misses the quokka.
The quokka is moderately wounded.
The quokka bites you.
You closely miss the quokka.
The quokka is moderately wounded.
The quokka completely misses you. The quokka bites you.
You barely miss the quokka. Your headbutt misses the quokka.
The quokka is moderately wounded.
You block the quokka's attack.
You hit the quokka.
The quokka is almost dead.
The quokka closely misses you. You furiously retaliate! You headbutt the
quokka!
You kill the quokka!
Trog accepts your kill.
You have reached level 3!
Your experience leads to an increase in your attributes!
Increase (S)trength, (I)ntelligence, or (D)exterity? 
Uppercase letters only, please.
You feel stronger.
HP restored.
An adder comes into view.
The adder hisses angrily.
The adder bites you.
You are poisoned.
The adder poisons you!
You barely miss the adder. You feel sick. The adder bites you.
You closely miss the adder. You feel sick. The adder closely misses you. You
furiously retaliate!
You headbutt the adder!
You kill the adder!
Trog accepts your kill.
You start resting. You feel sick.
You are no longer poisoned.
You start resting.
HP restored.
Found a scroll labelled FEAPSO FOVUZ.
A bat comes into view.
You block the bat's attack.
The bat hits you but does no damage.
You miss the bat. Your headbutt misses the bat. The bat barely misses you.
The bat hits you but does no damage.
The bat hits you. You block the bat's attack.
You slash the bat!
You kill the bat!
Trog accepts your kill.
h - a scroll labelled FEAPSO FOVUZ
Found a falchion. Found a stone staircase leading up.
An endoplasm comes into view.
The endoplasm quivers.
You hit the endoplasm.
You kill the endoplasm!
Trog accepts your kill.
You can now call upon Trog for regeneration and willpower.
A jackal comes into view.
The jackal barks!
A jackal comes into view.
A jackal comes into view.
The jackal barks! x2
A jackal comes into view.
You hit the jackal. You headbutt the jackal.
You kill the jackal!
Trog accepts your kill.
You slash the jackal!
You kill the jackal!
Trog accepts your kill.
You hit the jackal. You headbutt the jackal.
You kill the jackal!
Trog accepts your kill.
You hit the jackal but do no damage. The jackal bites you. The jackal closely
misses you.
You barely miss the jackal. You block the jackal's attack.
You hit the jackal.
The jackal is heavily wounded.
You block the jackal's attack.
You barely miss the jackal.
The jackal is heavily wounded.
The jackal bites you. The jackal closely misses you.
You closely miss the jackal. Your headbutt misses the jackal.
The jackal is heavily wounded.
The jackal bites you.
You miss the jackal. Your headbutt misses the jackal.
The jackal is heavily wounded.
The jackal bites you. The jackal barely misses you.
You hit the jackal.
You kill the jackal!
Trog accepts your kill.
Things that are here:
a jackal corpse; a jackal corpse
You start resting.
HP restored.
You open the door.
Found a stone staircase leading down.
There is an open door here.
A ball python and a dart slug come into view.
The ball python hisses angrily.
There is an open door here.
You hit the ball python.
You kill the ball python!
Trog accepts your kill.
You see here a ball python corpse.
You hit the dart slug.
You headbutt the dart slug, but do no damage.
The dart slug is heavily wounded.
The dart slug launches a dart at you.
The slug dart hits you but does no damage.
You slash the dart slug!
You kill the dart slug!
Trog accepts your kill.
A kobold comes into view. It is wielding a +0 whip.
The kobold shouts!
A hobgoblin comes into view.
The hobgoblin shouts!
You slash the kobold!
You kill the kobold!
Trog accepts your kill.
You closely miss the hobgoblin. The hobgoblin barely misses you.
You hit the hobgoblin.
You kill the hobgoblin!
Trog accepts your kill.
Things that are here:
a +0 whip; a kobold corpse
Things that are here:
a +0 whip; a kobold corpse
There is a stone staircase leading down here.
Found a fizzy white potion.
i - a fizzy white potion
Found a scroll labelled VICEGIOPE.
A kobold comes into view. It is wielding a +0 dagger.
The kobold shouts!
A hobgoblin comes into view.
The kobold throws a stone. The stone hits you but does no damage.
The kobold throws a stone. The stone hits you but does no damage.
The kobold closely misses you.
You hit the kobold but do no damage. The kobold hits you with a +0 dagger.
You slash the kobold!
You kill the kobold!
Trog accepts your kill.
Things that are here:
a +0 dagger; a stone
The hobgoblin shouts!
You see here a scroll labelled VICEGIOPE.
j - a scroll labelled VICEGIOPE
You slash the hobgoblin!
You kill the hobgoblin!
Trog accepts your kill.
k - a scroll labelled CEOSEO ETTER
You see here a hobgoblin corpse.
There are no objects that can be picked up here.
a hobgoblin corpse
A quokka comes into view.
You closely miss the quokka. The quokka bites you.
You slash the quokka!
You kill the quokka!
Trog accepts your kill.
You start resting.
HP restored.
Found an escape hatch in the floor.
Found a stone staircase leading down.
You open the door.
There is an open door here.
You open the door.
There is an open door here.
Found a leather armour.
You see here a +0 leather armour.
l - a +0 leather armour
A frilled lizard comes into view.
The frilled lizard hisses angrily.
You slash the frilled lizard!
You kill the frilled lizard!
Trog accepts your kill.
You see here a frilled lizard corpse.
Found a bone wand.
m - a wand of acid (9)
There is an open door here.
There is an open door here.
A giant cockroach comes into view.
You hit the giant cockroach.
You kill the giant cockroach!
Trog accepts your kill.
Found a diamond ring.
An endoplasm comes into view.
Found an escape hatch in the ceiling. The endoplasm moves out of view.
You hit the endoplasm.
You kill the endoplasm!
Trog accepts your kill.
A ball python comes into view.
The ball python hisses angrily.
You slash the ball python!
You kill the ball python!
Trog accepts your kill.
n - a +6 ring of dexterity
Found 14 arrows. Found a stone staircase leading up.
There is a stone staircase leading up here.
Done exploring.
There is a stone staircase leading up here.
There is a stone staircase leading down here.
You climb downwards.
There is a stone staircase leading up here.
A worm comes into view.
You hit the worm. You headbutt the worm!
The worm is heavily wounded.
You hit the worm. You headbutt the worm!
You kill the worm!
Trog accepts your kill.
You see here a worm corpse.
A frilled lizard comes into view.
A frilled lizard is nearby!
The frilled lizard hisses angrily.
You closely miss the frilled lizard. The frilled lizard bites you.
You closely miss the frilled lizard. The frilled lizard closely misses you.
You closely miss the frilled lizard. You headbutt the frilled lizard.
You kill the frilled lizard!
Trog accepts your kill.
You see here a frilled lizard corpse.
Found a stone staircase leading up.
An orc comes into view. It is wielding a +0 club.
Found 25 bolts.
The orc shouts!
You closely miss the orc. The orc barely misses you.
You hit the orc but do no damage. The orc barely misses you. You furiously
retaliate!
You headbutt the orc!
You kill the orc!
Trog accepts your kill.
Things that are here:
a +0 club; an orc corpse
There is a stone staircase leading up here.
You see here 25 bolts.
Found 11 gold pieces.
You now have 21 gold pieces (gained 11).
Found a stone staircase leading down.
There is a stone staircase leading down here.
A goblin comes into view. It is wielding a +0 club.
The goblin shouts!
You barely miss the goblin. The goblin closely misses you.
You hit the goblin. You headbutt the goblin.
You kill the goblin!
Trog accepts your kill.
Things that are here:
a +0 club; a goblin corpse
An endoplasm comes into view.
The endoplasm quivers.
You hit the endoplasm. Your headbutt misses the endoplasm.
The endoplasm is severely wounded.
You block the endoplasm's attack.
You hit the endoplasm but do no damage. You headbutt the endoplasm.
You kill the endoplasm!
Trog accepts your kill.
You have reached level 4!
You feel stronger.
There is a stone staircase leading down here.
A hobgoblin comes into view.
The hobgoblin shouts!
The hobgoblin closely misses you.
You hit the hobgoblin.
You kill the hobgoblin!
Trog accepts your kill.
An orc comes into view. It is wielding a +0 hand axe.
The orc shouts!
You hit the orc.
The orc is lightly wounded.
The orc closely misses you. You furiously retaliate! You headbutt the orc.
You barely miss the orc. You headbutt the orc.
You kill the orc!
Trog accepts your kill.
Things that are here:
a +0 hand axe; a +3 ring mail; an orc corpse
o - a +3 ring mail
Things that are here:
a +0 hand axe; an orc corpse
Found a stone staircase leading up.
A hobgoblin comes into view.
The hobgoblin shouts!
You slash the hobgoblin!
You kill the hobgoblin!
Trog accepts your kill.
There is a stone staircase leading up here.
A goblin comes into view. It is wielding a +0 club.
You barely miss the goblin. Your headbutt misses the goblin.
The goblin hits you but does no damage.
You miss the goblin. The goblin closely misses you. The goblin hits you but
does no damage.
You hit the goblin.
You kill the goblin!
Trog accepts your kill.
Your Fighting skill increases to level 5!
p - a scroll labelled LERIEC EMNEASCH
Things that are here:
a +0 club; a goblin corpse
A scorpion comes into view.
The scorpion completely misses you.
You barely miss the scorpion. Your headbutt misses the scorpion. The scorpion
closely misses you.
You furiously retaliate! You headbutt the scorpion.
You closely miss the scorpion. You headbutt the scorpion.
The scorpion is lightly wounded.
You block the scorpion's attack.
You hit the scorpion but do no damage.
The scorpion is lightly wounded.
The scorpion misses you.
You hit the scorpion.
The scorpion is heavily wounded.
The scorpion barely misses you. The scorpion stings you.
You hit the scorpion.
The scorpion is severely wounded.
The scorpion stings you.
You hit the scorpion but do no damage.
You headbutt the scorpion, but do no damage.
The scorpion is severely wounded.
The scorpion barely misses you. You furiously retaliate!
You headbutt the scorpion, but do no damage.
You slash the scorpion!
You kill the scorpion!
Trog accepts your kill.
Your Axes skill increases to level 5!
You see here a scorpion corpse.
You start resting.
HP restored.
A water moccasin comes into view.
The water moccasin moves out of view.
You miss the water moccasin. The water moccasin bites you.
You are poisoned.
The water moccasin poisons you!
The water moccasin completely misses you.
You furiously retaliate! You headbutt the water moccasin.
You hit the water moccasin but do no damage.
The water moccasin is lightly wounded.
You feel very sick.
The water moccasin bites you.
You closely miss the water moccasin.
The water moccasin is lightly wounded.
You feel very sick.
The water moccasin bites you. x2
Your skin crawls.
You feel strong-willed.
You feel sick.
The water moccasin bites you but does no damage.
You closely miss the water moccasin.
The water moccasin is lightly wounded.
You feel sick. The water moccasin bites you.
You are more poisoned.
The water moccasin poisons you!
* * * LOW HITPOINT WARNING * * *
You feel very sick.
You block the water moccasin's attack.
You hit the water moccasin but do no damage.
The water moccasin is lightly wounded.
* * * LOW HITPOINT WARNING * * *
You feel very sick.
The water moccasin barely misses you.
You hit the water moccasin.
Your headbutt misses the water moccasin.
The water moccasin is moderately wounded.
* * * LOW HITPOINT WARNING * * *
You feel very sick.
You block the water moccasin's attack. The water moccasin bites you.
* * * LOW HITPOINT WARNING * * *
You slash the water moccasin! You headbutt the water moccasin.
The water moccasin is severely wounded.
You die...
Terminal too small (97,23); need at least (79,24)

>>>>>>>>>>>>>>>>>>>>>>

Version history:
No version history (current version is 0.27.1)

Game state:

mouse_enabled: 0, waiting_for_command: 0, terminal_resized: 1
io_inited: 1, need_save: 0, saving_game: 1, updating_scores: 1:
seen_hups: 0, map_stat_gen: 0, type: 1, arena_suspended: 0
Last resize was 0 seconds ago.

prev_cmd = CMD_MOVE_UP_LEFT
repeat_cmd = CMD_NO_CMD

Player:
{{{{{{{{{{{
Name:    [Muggerton]
Species: Minotaur
Job:     Berserker

HP: -1/42; mods: 0/0
MP: 3/3; mod: 0
Stats: 23 (23) 4 (4) 9 (9)
Position: (34, 68), god: Trog (10), turn_is_over: 1, banished: 0
Standing on/in/over feature: floor

Skills (mode: manual)
Name            | can_currently_train | train | training | level | points | progress
Fighting        |          X          |   1   |    50    |    5  |    627 | 97/212
Short Blades    |          X          |   0   |     0    |    0  |      0 | 0/42
Long Blades     |          X          |   0   |     0    |    0  |      0 | 0/35
Axes            |          X          |   1   |    50    |    5  |    627 | 97/212
Maces & Flails  |          X          |   0   |     0    |    0  |      0 | 0/35
Polearms        |          X          |   0   |     0    |    0  |      0 | 0/35
Staves          |          X          |   0   |     0    |    0  |      0 | 0/35
Slings          |          X          |   0   |     0    |    0  |      0 | 0/42
Bows            |          X          |   0   |     0    |    0  |      0 | 0/42
Crossbows       |          X          |   0   |     0    |    0  |      0 | 0/42
Throwing        |          X          |   0   |     0    |    0  |      0 | 0/50
Armour          |          X          |   0   |     0    |    2  |    153 | 47/106
Dodging         |          X          |   0   |     0    |    2  |    153 | 27/126
Stealth         |          X          |   0   |     0    |    0  |      0 | 0/59
Shields         |          X          |   0   |     0    |    0  |      0 | 0/35
Unarmed Combat  |          X          |   0   |     0    |    0  |      0 | 0/42
Spellcasting    |          X          |   0   |     0    |    0  |      0 | 0/100
Conjurations    |          X          |   0   |     0    |    0  |      0 | 0/84
Hexes           |          X          |   0   |     0    |    0  |      0 | 0/100
Summonings      |          X          |   0   |     0    |    0  |      0 | 0/84
Necromancy      |          X          |   0   |     0    |    0  |      0 | 0/84
Translocations  |          X          |   0   |     0    |    0  |      0 | 0/84
Transmutations  |          X          |   0   |     0    |    0  |      0 | 0/70
Fire Magic      |          X          |   0   |     0    |    0  |      0 | 0/84
Ice Magic       |          X          |   0   |     0    |    0  |      0 | 0/84
Air Magic       |          X          |   0   |     0    |    0  |      0 | 0/84
Earth Magic     |          X          |   0   |     0    |    0  |      0 | 0/70
Poison Magic    |          X          |   0   |     0    |    0  |      0 | 0/84
Invocations     |          X          |   0   |     0    |    0  |      0 | 0/50
Evocations      |          X          |   0   |     0    |    0  |      0 | 0/59

Spell bugs:

Durations:
    #11: 14024
    #103: 158

Attributes:
    #12: 21
    #27: 185
    #49: 33

Mutations:
    horns: 2 (innate)
    retaliatory headbutt: 1 (innate)

Inventory bugs:

Equipment:
    eq slot #0, inv slot #0: +0 hand axe
    eq slot #6, inv slot #1: +0 animal skin
    eq slot #9, inv slot #3: amulet of reflection

}}}}}}}}}}}

Screenshot:
  #..# #.#.#####.##.#
#.#..###.#.#####.##.#
...........##.......#
#.##.##.##.##.##.####
#.##.#...#.##. #.#
#............. ..#
####.#####.#######
   #S#####.#
   #.@.....#
   #########

clua stack:

dlua stack:

Lua persistent data:
<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>

Lua marker contents:
<<<<<<<<<<<<<<<<<<<<<<
>>>>>>>>>>>>>>>>>>>>>>

**Comment by ebering** [comment]
It appears what happened is that you resized your terminal after dying, so that when the high scores display initialized it crashed... inelegantly.

**Comment by randomdude999** [comment]
This seems to happen whenever drawing the main menu while the screen is too small. Can reproduce on trunk by opening main menu (or any submenu in the main menu) and resizing the terminal. I think the main menu should probably use code similar to the main game view, which shows a message "your screen is too small" until it's resized to a larger size.
