### ISSUE TITLE
Nemelex Velocity Card does nothing

### ISSUE THREAD

**Issue by bcharris** [crawl/crawl#2313]
**PLATFORM and OS or BROWSER:**
Webtiles, MS Edge 96.0.1054.62

**DCSS VERSION AND GAME INFORMATION:**
.27.1

**DESCRIPTION:**
I have pulled the velocity card 5 times as a merfolk in various circumstances - no monsters in sight, monsters in sight, in lair, in abyss. The result is the same:  ​"You draw a card... You have drawn Velocity. Nothing appears to happen."
Most recently, ​I have ****** piety and 13.6 Invocations skill. 5 consecutive failures is not impossible, but certainly unlikely. 
steps to reproduce: be merfolk, worship Nem, draw velocity card
Wiki is also out of date on effects of velocity card.

**EXTRA FILES:**
 http://crawl.kelbi.org/saves/jaboo-crawl-0.27-211227-2201.tar.bz2
 https://pastebin.com/bLYPqgM1

**Comment by bcharris** [comment]
I will also add that I ran into another card bug where using the destruction deck prompted me to choose a target after using a destruction card, but without saying which card it was. It ended up being vitriol. At other times throughout the playthrough it has said which card it was after activating the deck, but before targets were chosen (including vitriol). Unclear if it should be consistently prompting what i'm aiming or if it's supposed to be a surprise.

**Comment by bcharris** [comment]
Ok I was successful in using the card.  It must have been a few bad breaks. Someone on discord posted a link to this commit: https://github.com/crawl/crawl/commit/399e8c341965 which was helpful. The wiki is out of date, which threw me off. 

It was hard to tell what was going on since there is no logging of enemy monsters "resisting" the slow effect.

**Comment by ebering** [comment]
The "logging" of the "resisting" is exactly the canned message "Nothing appears to happen.", when nothing happens. Sometimes cards whiff. The in-game descriptions found in the `?/` look up menu (look under `C` for cards) are up to date with the effects. The wiki is a community effort and not maintained by the development team.

I am completely unable to replicate your prompt bug. It should (and does) consistently prompt for me. Please open a new issue if you have step by step replication instructions.
