### ISSUE TITLE
Orbs can be worn with two handed weapons

### ISSUE THREAD

**Issue by datlo** [crawl/crawl#2316]
**PLATFORM and OS or BROWSER:**

Playing on https://crawl.xtahua.com/ web tiles 

**DCSS VERSION AND GAME INFORMATION:**

DCSS version 0.28-a0-1339-ga5422284a4 (webtiles)

**DESCRIPTION:**

Orb of light (and presumably other orbs?) can be worn on the shield slot even with a two handed weapon equipped. I am not certain if this is an intended feature or a bug, but it's not intuitive either way and should be clarified in the orbs' description if it's a feature.

**EXTRA FILES:**

https://pastebin.com/E0fZdycc

**Comment by ebering** [comment]
Thanks for the report, fixed!
