### ISSUE TITLE
jorogumo pronouns inconsistent

### ISSUE THREAD

**Issue by crystalsolenoid** [crawl/crawl#2317]
**PLATFORM and OS or BROWSER:**

Linux, firefox, webtiles.

**DCSS VERSION AND GAME INFORMATION:**

0.28-a0-1340-g77f64c2

**DESCRIPTION:**

When examining, the description at the top uses "it" but the generated part uses "she".

![Screenshot from 2021-12-28 15-08-26](https://user-images.githubusercontent.com/8132415/147613642-46de08b7-c008-454e-86f2-22fcb1be7545.png)

**Comment by semitonal** [comment]
Fixed, thanks for reporting!

**Comment by randomMesh** [comment]
Not fixed. There are no male harpies, jorogumos or nymphs.
