### ISSUE TITLE
Delver background causes a black screen if portal is on starting level

### ISSUE THREAD

**Issue by datlo** [crawl/crawl#2318]
**PLATFORM and OS or BROWSER:**

Webtiles at https://crawl.xtahua.com/, browser is Brave 

**DCSS VERSION AND GAME INFORMATION:**

Version 0.28-a0-1347-g113dc556a4

**DESCRIPTION:**

When starting a new game as a delver, if there's a portal to for example a sewer on the starting level, the game won't start and will be stuck on an empty black screen. Refreshing the page to load back into the game functions as a work-around.

**Comment by RojjaCebolla** [comment]
@datlo you can also just hit escape several times
(i experience the same thing on kelbi / firefox but it's not a big deal imo)

**Comment by rawlins** [comment]
The immediate delver+portal problem should be fixed in that commit, though arguably it is also a bug (a very hard one to fix) that this messaging happens before the welcome message.
