### ISSUE TITLE
Stormform status light tooltip shows the description for heavenly storm

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2320]
**PLATFORM and OS or BROWSER:**
webtiles trunk 

**DCSS VERSION AND GAME INFORMATION:**
.28-a0-1347

**DESCRIPTION:**
i have stormform active, not heavenly storm.
![image](https://user-images.githubusercontent.com/70080435/147692962-30d4067f-6b4a-4bba-a41d-1e6be118de6a.png)

**Comment by perryprog** [comment]
Should be fixed by a5cd5ca.
