### ISSUE TITLE
No description for bog status light

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2321]
**PLATFORM and OS or BROWSER:**
webtiles trunk

**DCSS VERSION AND GAME INFORMATION:**
.28-a0-1347

**DESCRIPTION:**
casting eringya's noxious bog puts a status light up w/ no description
![image](https://user-images.githubusercontent.com/70080435/147699511-d4d5d55f-4c9b-4775-8bd7-25fb84702463.png)

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
