### ISSUE TITLE
Game Crashed while Yred Demonspawn

### ISSUE THREAD

**Issue by TenayaTenaya** [crawl/crawl#2323]
**PLATFORM and OS or BROWSER:**
<crawl.akrasiac.org  webtiles>

**DCSS VERSION AND GAME INFORMATION:**
<0.28-a0-1347-g113dc55>

**DESCRIPTION:**
<Twice today, I had a game crash in a Lair Branch.  Extant game just reset to Spider Nest 4 and earlier was in Shoals. I am playing a Demonspawn of Yred.  During combat, the game crashed and reset to my most recent entry to the level.  I have both a Bound soul tagging along and I generate fire from blood.   -->

**EXTRA FILES:**
< I do not see a link to the crashlogs on CAO.>

**Comment by ebering** [comment]
Crash reporting was a bit messed up, but for reference here is the crashlog http://crawl.akrasiac.org/rawdata/Tenaya/crash-Tenaya-20220101-062908.txt

I believe I understand what happened and will fix this soon.
