### ISSUE TITLE
Xom effect : Spell 'Shadow Creatures' is not a player castable spell.

### ISSUE THREAD

**Issue by datlo** [crawl/crawl#2324]
**PLATFORM and OS or BROWSER:**

Webtiles

**DCSS VERSION AND GAME INFORMATION:**

Version 0.28-a0-1356-g2ad6d04315

**DESCRIPTION:**

When playing Chaos Knight, Xom played with reality, turning a hobgoblin into a shapeshifter, which turned into a queen bee. After this, I received the message "Spell 'Shadow Creatures' is not a player castable spell.". 
I assume Xom casted the spell to help me out against the shapeshifter, but it bugged out.
No shadow creatures, or any kind of mobs, were summoned.

**EXTRA FILES:**

https://pastebin.com/vTQWd7An

**Comment by semitonal** [comment]
Fixed by a0dfb7b2014, thanks for reporting.
