### ISSUE TITLE
Weapon damage not shown in weapon-wielding monster descriptions, and the "[x] damage plus its [weapon]" phrasing is confusing

### ISSUE THREAD

**Issue by smbhax** [crawl/crawl#2326]
**PLATFORM and OS or BROWSER:**
PuTTY console, Release 0.76, Build Platform: 64-bit x86 Windows

**DCSS VERSION AND GAME INFORMATION:**
http://crawl.akrasiac.org/rawdata/smbhax/morgue-smbhax-20211231-071907.txt

~~~~~~~~~~
Dungeon Crawl Stone Soup version 0.28-a0-1359-g7b63960 (console) character file.

Game seed: 385170207530018012

4105 smbhax the Spear-Bearer (level 10, -4/86 HPs)
             Began as a Minotaur Fighter on Dec 31, 2021.
             Slain by a two-headed ogre (21 damage)
             ... on level 7 of the Dungeon.
             The game lasted 00:40:51 (8304 turns)
~~~~~~~~~~~~~

**DESCRIPTION:**

Playing trunk on crawl.akrasiac.org on 12/30/21, build 0.28-a0-1359-g7b63960.

The "x" description of the "two-headed ogre" said of its attacks:

~~~~~~~~~~~
It can hit for up to 15 damage plus its +0 giant club;
and hit for up to 20 damage plus its +0 giant club
(about 65% to hit you).
~~~~~~~~~~~

This description is confusing: what exactly does "plus its +0 giant club" mean? Does it do for instance up to 15 (or 20) damage plus 1dwhatever a giant club does? If so, shouldn't that just be added together into one number? Strictly speaking, the phrase "plus its +0 giant club" is grammatically nonsensical when speaking of attack damage.

(I see other weapon-wielding monsters follow "this x damage plus weapon" format in their descriptions: an orc's damage description says "It can hit for up to 2 damage plus its +0 club," for instance. This seems unnecessarily vague compared to non-weapon-wielding enemies, whose descriptions just list a single damage number per attack.)

Additional damage from whatever "plus its +0 giant club" means might explain how it appears to have done 39 points of damage to my MiFi with its two attacks: 

Video: https://youtu.be/6F_VlRQHTkA?t=5941

After drinking a heal wounds potion, under no status effects, I was at 45 HP and 4 MP (using MP as HP with the amulet of guardian spirit). The two-headed ogre hit me once and reduced me to 32 HP and 3 MP--and then hit me with both its attacks in the next round, taking me to -4 HP, which would mean it did 39 damage, four more than the 15 and 20 max damages listed in its description could do combined. In the morgue file, that sequence goes

~~~~~~~~~~
You feel much better.
You hit the two-headed ogre but do no damage.
Your headbutt misses the two-headed ogre.
The two-headed ogre is moderately wounded.
The two-headed ogre hits you with a +0 giant club!
The two-headed ogre barely misses you.
You puncture the two-headed ogre!
The two-headed ogre is moderately wounded.
The two-headed ogre hits you with a +0 giant club!
* * * LOW HITPOINT WARNING * * *
The two-headed ogre hits you with a +0 giant club!!
You die...
~~~~~~~~~~

and the morgue file says of the killing attack:

~~~~~~~~~~~
Slain by a two-headed ogre (21 damage)
~~~~~~~~~~~

--which is more than the highest damage number listed in its description.

Perhaps something I'm not aware of was boosting its damage somehow; it had been accompanied some turns before by a Sky Beast, for instance, who was left behind on the previous floor. In any case, the "plus its +0 giant club" phrasing of its damage output description is excessively nebulous, and I hope can be rendered much more clearly; if the weapon's base damage *is* intended to be added on top of the monster's hard-coded attack damage number, as seems to be happening and as the description text seems to be trying to say, in a very confusing way, the game should add them together and supply them as a single number in the monster description, for simplicity--why make the player do the math, and anyway players can't be expected to know all the weapon damages by heart--and to be consistent with how attack damage is listed for non-weapon-wielding monster attacks.

Ie, something more like "It can hit with its +0 giant club for up to [x] damage; and hit with its +0 giant club for up to [y] damage (about 65% to hit you)."

Although grammatically speaking, as phrased that hit % at the end only applies to the last attack; something like "It can hit with its +0 giant club for up to [x] damage, and hit with its +0 giant club for up to [y] damage. It has a 65% chance to hit you" would be better.

Going back as far as I can on akrasiac, I see the "[x] damage plus its [weapon]" format has been in the game since at least version 0.20, so perhaps I am just the crazy one. But as a noob I was a bit shocked that the game killed my character with such poorly specified extra damage.

At the least, if the maximum damage the monster can do with their weapon can't be added up for the player to see in the monster's description, the base damage the monster's weapon does should be included there in some way instead of just tacking the weapon name on to the monster's base attack damage--since the damage they actually inflict appears to be [monster base damage] + [monster weapon damage].

For the two-headed ogre, for instance, "?/i" and then "giant club" tells me that the giant club does base damage 20. So their damage description should say at least

~~~~~~~~~~
It can hit for up to 15 damage plus 20 damage from its +0 giant club;
and hit for up to 20 damage plus 20 damage from its +0 giant club
(about 65% to hit you).
~~~~~~~~~~

Or better, add the numbers together:

~~~~~~~~~~
It can hit for up to 35 damage from its +0 giant club;
and hit for up to 40 damage from its +0 giant club
(about 65% to hit you).
~~~~~~~~~~

Or even better, format it in a legible way, for instance

~~~~~~~~~~
It can hit with its +0 giant club for up to 35 damage,
and hit with its +0 giant club for up to 40 damage.
It has a 65% chance to hit you.
~~~~~~~~~~

For a monster with a magical weapon with additional damage bonuses, for instance a +5 giant club of flaming, those additional damages should also be added up in the displayed maximum damage. It is needless, inconsistent, and confusing to leave the monster damage + weapon damage knowledge and calculation up to the player.

There's an argument to be made that the portion of the weapon damage to which the player could have resistances should be listed there separately so that the player can estimate how much of the total maximum damage they might be able to resist. For the sake of quick legibility during gameplay, though, it might be best simply to include that damage in the one total number.

Although, given that the hit chance listed is specifically the chance to hit the player character, presumably with the player character's current stats and gear taken into account, then perhaps the maximum damage listed should also be specifically the maximum damage possible against the current player character, since that is what the player will need to know to stay alive at the moment.

I don't know precisely how inflicted damage is calculated, but for a crude example let's say the hypothetical +5 giant club of flaming adds a max of 9 flame damage, the player character has fire resistance to reduce that flame damage by 66%, and armor or whatever to reduce physical damage by 10 points--and the two-headed ogre's second weapon was a +3 giant club of freeze, for an additional (I'm making this up of course) 9 cold damage max, and the player character has cold resistance to reduce cold damage by 33%. So two-headed ogre attack 1 is 15 base monster damage + 20 base giant club damage + 5 magical weapon damage - 10 player character physical damage resistance + (9 flame damage * 0.33 player character flame resistance), and two-headed ogre attack 2 is 20 base monster damage + 20 base giant club damage + 3 magical weapon damage - 10 player character physical damage resistance + (9 cold damage * 0.33 player character cold resistance), and the player of that character would be shown the following in the monster description:

~~~~~~~~~~
It can hit you with its +5 giant club of flaming for up to 33 damage,
and hit you with its +3 giant club of freeze for up to 36 damage.
It has a 65% chance to hit you.
~~~~~~~~~~

That sort of display would be far more accurate and meaningful than the current "[base monster attack damage] plus its [weapon name]" format.

**EXTRA FILES:**
![ogre](https://user-images.githubusercontent.com/91744319/147812968-11102bf1-12b3-417e-91e5-43ab9cb7495d.jpg)
[morgue-smbhax-20211231-071907.txt](https://github.com/crawl/crawl/files/7795702/morgue-smbhax-20211231-071907.txt)

**Comment by PleasingFungus** [comment]
This is a very in-depth writeup! I respect your passion for the subject, and agree that we don't want players to have to do extra work or 'spoiler' themselves to get reasonable game information.

> For a monster with a magical weapon with additional damage bonuses, for instance a +5 giant club of flaming, those additional damages should also be added up in the displayed maximum damage.

This doesn't work. Brands like flaming, etc, apply **after** AC. For example, flaming adds an average of 25% extra damage *after* AC is applied. With base damage 1d40 and against a player with 0 AC, that'll be an average of an extra 5 damage. Against a player with 40 AC, it'll be an average of less than half that. (It's a little more complicated once GDR is involved, but let's pretend we don't know about that.)

That means that you can't simply add them up with the other effects - they're apples and oranges. Resists are also an issue, as you mention. This is the reason that I implemented the "plus its weapon" phrasing to begin with.

What one maybe could do is to add up the base damage & weapon damage and then say "plus its brand" when appropriate. That was the approach I used for player weapon damage displays.

**Comment by PleasingFungus** [comment]
79d4c32e18fbe35e6207ba32d087eaa004087ace does something along the lines of what I mentioned in my last comment.

**Comment by sharkjacobs** [comment]
> Brands like flaming, etc, apply after AC ... That means that you can't simply add them up with the other effects

You can't easily describe the distribution of branded weapon damage ranges (e.g. "1d40 damage and 1d20 flame damage") for the reason @PleasingFungus describes (flame brand damage is a derivative value which depends on actual damage done, not just base damage) 

But the current monster attack description is of an upper limit of damage potential, and it is possible to calculate the upper damage limit for an attack with a branded weapon, by using the maximum possible regular damage value to calculate the flame damage value

A flame brand does up to 50% of "damage done" as additional flame damage, so the description could accurately say "monster can hit for up to 45 damage and 23 flaming damage with its weapon..."

**Comment by PleasingFungus** [comment]
That seems pretty misleading, through, doesn't it? The two are calculated in very different ways, and a "max damage roll" is much more likely on the base attack than the brand - max damage on brand requires max damage on base attack, min roll on AC, and max roll on the brand itself. Seems like it'd lead players to think that brands are much more impactful than they are.

**Comment by PleasingFungus** [comment]
Think 3dd9dd102545124858822a3a7be2bdfaeaf5e578 makes this mostly moot. Still reasonable to continue a discussion about this in future, but we've moved so far away from the state described at the start of this issue that we should probably start a new issue if one's needed.
