### ISSUE TITLE
.24 download? 

### ISSUE THREAD

**Issue by lobf** [crawl/crawl#2334]
Hi there, is there a reason the .24 repo is't hosted? I'd like to download it... 

Thanks!

**Comment by ebering** [comment]
Each point release has a corresponding release branch contained in this repo, the branch for 0.24 is called `stone_soup-0.24` and is [here](https://github.com/crawl/crawl/tree/stone_soup-0.24). Further, each point release is available as a GitHub generated source archive under the [tags page](https://github.com/crawl/crawl/tags). Newer point releases also have GitHub generated build artifacts from our build process, but the project pre-dates this GitHub feature; some older builds can be downloaded [on our website](https://crawl.develz.org/release/?C=N;O=D).

Hope this helps!
