### ISSUE TITLE
Game crashes when finding gnarled glowing staff

### ISSUE THREAD

**Issue by entropino** [crawl/crawl#2337]
My current save keeps crashing once I encounter this staff. If there is a way to fix this that would be nice.
[crash-Pos Faix-20220104-024637.txt](https://github.com/crawl/crawl/files/7804911/crash-Pos.Faix-20220104-024637.txt)

**Comment by entropino** [comment]
Seems it happened again in another save, is it because I am playing earth elementalist deep dwarves?

[crash-Dajumig-20220104-173232.txt](https://github.com/crawl/crawl/files/7808992/crash-Dajumig-20220104-173232.txt)

**Comment by rawlins** [comment]
This is a known bug with 0.27, which is fixed but unfortunately not yet in an offline release. The crash is on looking at the description of an unidentified staff (which in local tiles can happen on mouseover). As a workaround, just step on the square with the staff and it should be fine.
