### ISSUE TITLE
"Unlinked item" messages when generating the abyss

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2342]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.28-a0-1429-gf3d713df7a

**DESCRIPTION:**
If I go to Abyss:5 in wizard mode and regenerate the level a few times, it gives messages such as:

```
  Unlinked item:
 bone wand
     item #11:  base: 3; sub: 0; plus: 4; plus2: 0; special: 2
     quant: 1; ident: 0x00000000; ident_type: 0
     x: 43; y: 58; link: 27000; Env.igrid(43,58) = 27000
```
There seems to be a chance of it happening whenever the game generates the level. I don't know if it occurs as you walk around.

I started to see this effect in 578a0bbfb4.

**EXTRA FILES:**
Save file with one of these items.
[Kirkiarik.zip](https://github.com/crawl/crawl/files/7832151/Kirkiarik.zip)

**Comment by ebering** [comment]
Thanks for the report! This was a wizmode bug it turns out.

**Comment by Aliscans** [comment]
Thanks for that. I could see when it started happening, but I had no idea why it behaved like that.
