### ISSUE TITLE
'Chance to affect' of Discord spell doesn't consider intelligence

### ISSUE THREAD

**Issue by dillytin** [crawl/crawl#2350]
**DCSS VERSION AND GAME INFORMATION:**
0.28-1459-gdc4c

**DESCRIPTION:**
![image](https://user-images.githubusercontent.com/65288602/148881607-b9f3abc7-10e1-4999-a1f1-2c95a72d0b01.png)

Acid blobs are mindless so you can't affect them with discord spell. However, the display of chance to affect doesn't take it into account.

I think there would be some spells or hexes that have similar problems just like a display bug with an orb of guile.

**Comment by ebering** [comment]
What is the bug with the orb of guile you're referring to in this report?

I have fix for the Discord bug reported though.

**Comment by dillytin** [comment]
@ebering https://discord.com/channels/205277826788622337/205316046230388737/930177455279448134
