### ISSUE TITLE
Ironbound Frosthearts using Malign Gateway "portal" as a wall. 

### ISSUE THREAD

**Issue by Shapermc** [crawl/crawl#2359]
Dungeon Crawl Stone Soup version 0.28-a0-1510-gd0f6b136d3 (webtiles), Chrome, HuDe. 

While in Vaults Ironbound Frosthearts use the "hole" that the malign gateway to cast Creeping Frost. Nothing about the language in the spell indicates this is an intentional interaction. If so the spell description for Creeping Frost should include "walls and portals" etc.

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
