### ISSUE TITLE
Unwielding weapons doesn't work

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2363]
**PLATFORM and OS or BROWSER:**
webtiles trunk

**DCSS VERSION AND GAME INFORMATION:**
0.28-a0-1510-gd0f6b136d3

**DESCRIPTION:**
Unable to unwield a weapon thru the `w` menu, `w-` doesn't work.

**Comment by ebering** [comment]
This does not replicate in console, but does in web tiles. @rawlins this seems related to your recent menu work? I'll hold off on diving into it until I hear from you (if its not something you see how to do quick then I'm happy to dive in.)
