### ISSUE TITLE
0.28 tag announcement

### ISSUE THREAD

**Issue by rawlins** [crawl/crawl#2379]
@crawl/serveradmins It's time to install the 0.28 stable version! Opening this issue in case it's useful for communicating about the update. I don't think there's anything major that you need to know about that will make this update process any different from normal or require specific intervention.

Some things that are relevant to you that happened during the 0.28 cycle that may be useful to have highlighted:

* Some administrative tools got pulled off into a separate python utility, [webserver/wtutil.py](https://github.com/crawl/crawl/blob/master/crawl-ref/source/webserver/wtutil.py). This includes setting and clearing reset password tokens, and banning.
* Speaking of which, a patch based on a PR from @floraline got merged that lets webtiles respect the db's ban flag (a dgamelaunch feature that was previously ignored by webtiles). You can set and clear bans using this tool at the command line, probably better than just resetting the password (which is what most of us have been doing previously).
* The webserver code mostly got refactored into a subdirectory/python package `webtiles`. This shouldn't affect anything, except that dgamelaunch (or similar copying processes) won't removed now-unused `.py` files -- this is every `.py` file in `webserver` except `server.py`, `config.py`, and `wtutil.py`. You could manually remove this from your chroot if the clutter bothers you. (They are otherwise ignored.)

Please feel free to post here (or ask in IRC/Discord) if you run into any snags when installing the new version or restarting the webtiles server.

**Comment by alexjurkiewicz** [comment]
Thanks for this very informative post! CPO is running 0.28 now. Can you please create GitHub releases for all tags? I'm subscribed to release announcements, so it's a good way to keep up with beta / stable tags.

**Comment by floraline** [comment]
0.28 is installed on CKO.

**Comment by ebering** [comment]
The 0.28 tournament is concluded and it looks like it has run successfully, so I'm closing this issue.
