### ISSUE TITLE
Examine Screen for Monsters with Quicksilver Bolt does not format properly

### ISSUE THREAD

**Issue by ahattaway** [crawl/crawl#2388]
**PLATFORM and OS or BROWSER:**
Windows, Firefox 96.0.3 (64-bit), CAO Trunk webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-22-gbf593bl

**DESCRIPTION:**
 The examine screen for any monster with Quicksilver Bolt does not format properly.
e.g. Purple Draconians (incl Shifters, Monks, Annihilators, etc); Quicksilver Dragons, Quicksilver Elementals

The graphical ability icon for Quicksilver Bolt is not present. Additionally, any further icons in the examine screen fail to display, causing jumbled formatting. This is most apparent on Purple Draconian Shifters, or others that have spells. 

The formatting is also jumbled on console, or at least when "tile_display_mode = glyphs" is enabled in the rc file. 

You can verify this by examining any monster with Quicksilver Bolt. This also applied for searching the ingame help menu with ?/m. Note that if you search for a draconian enemy, the color of the draconian will be random, so you might have to search for the draconian multiple times to get a purple one.

Also consider that it is flavourful for quicksilver bolt to dispel proper formatting.

**EXTRA FILES:**

![image](https://user-images.githubusercontent.com/26130415/151676598-cee85bd2-b248-43fc-91c9-8bb5fd769d2b.png)
Screenshot of the jumbled ability and spell list for a purple draconian shifter.

**Comment by rawlins** [comment]
Thanks for the report! I forgot to mark the issue in the commit, but this is fixed in: https://github.com/crawl/crawl/commit/df0a5da549d686d0aacd07de1752d655d7645882
