### ISSUE TITLE
Can't copy paste version number from ?v anymore

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2396]
**PLATFORM and OS or BROWSER:**
local tiles windos

**DCSS VERSION AND GAME INFORMATION:**
 0.28-a0-1629-gf728b707aa

**DESCRIPTION:**
Doin `?v` to copy version number for bug reports was handy. any click on `?v` closes the menu, which doesn't seem right? this is on a default rc as well.

**Comment by rawlins** [comment]
I won't close this but I'm not very sure of this, but I don't remember this ever being implemented for local tiles. Are you sure this worked in the past?

**Comment by ardl** [comment]
I could have sworn it did, but after trying on older versions it does not.

**Comment by rawlins** [comment]
Alright, thanks for the update. Well, this would be a good feature to have, maybe next version cycle.
