### ISSUE TITLE
Crashed while resting

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2405]
**PLATFORM and OS or BROWSER:**
0.28.0 webtiles 

**DESCRIPTION:**
Not really sure what happened. I rested after a fight to wait barbs out and the game crashed.

**EXTRA FILES:**
crashlog and save
https://crawl.kelbi.org/crawl/morgue/ironchadthunderc0ck/crash-ironchadthunderc0ck-20220206-214712.txt
 http://crawl.kelbi.org/saves/ironchadthunderc0ck-crawl-0.28-220206-2206.tar.bz2

**Comment by semitonal** [comment]
Should be fixed by 8ed1089bbe3c.
