### ISSUE TITLE
0.28.0 Makhleb Not Healing in Abyss

### ISSUE THREAD

**Issue by Shapermc** [crawl/crawl#2409]
Dungeon Crawl Stone Soup version 0.28.0 (webtiles) Chrome, Windows

Hello, 

High chance this was caught as I mentioned it in #dcss discord and PF responded to me, but was asked by other people to report it anyways. When I was in the abyss my kills were not refilling health. I keep monitoring it and I never got the "you feel better" message and my log was not displaying heal numbers. Log can be found here: 

https://crawl.kelbi.org/crawl/morgue/Shapermc/morgue-Shapermc-20220205-055107.txt

**Comment by semitonal** [comment]
This seems to work fine to me and give health as expected - from the ttyrec, it looks like your summoned hydras were doing all the killing which would explain not getting any healing in those particular cases.
