### ISSUE TITLE
Zombie Hands + Noxious Bog warnings overly intense

### ISSUE THREAD

**Issue by Shapermc** [crawl/crawl#2410]
Dungeon Crawl Stone Soup version 0.28.0 (webtiles) character file. CKO, chrome, windows
 
 GnVM: When trying to use BVC over Noxious bog whenever you aim the targeter you get asked to confirm 2x (twice) for if you're sure you want to summon, just to move the targeter, and the zombie hands aren't even effect by it. Very intense and unnecessary, is making playing kinda a challenge.

**Comment by Shapermc** [comment]
Same with OTR too. It's about 2 "y" responses then 2 "Y" responses.

**Comment by Shapermc** [comment]
I have no idea what's going on, but even just using z* to see what spells I have prompts this message and I have to hit y 3x: 
![image](https://user-images.githubusercontent.com/80350699/153088199-197fc819-59f9-4ec7-9ec3-d0c91bf2ed4a.png)

Here's the morgue. Whatever happened in my game almost killed me a couple times having to hit y so much and accidentally moving a couple times. Here is my morgue: 

https://crawl.kelbi.org/crawl/morgue/Shapermc/morgue-Shapermc-20220208-230600.txt

**Comment by ebering** [comment]
> Same with OTR too. It's about 2 "y" responses then 2 "Y" responses.

What do you mean "Same" as in, trying to cast OTR after Bog causes prompts?

I can't replicate this with a default RC can you provide your RC?

**Comment by Shapermc** [comment]
Sorry, yes, the same effect happens when trying to cast BVC while using OTR. So it would ask for multiple confirmations, and even just hitting z* to see my spell list to pick what to cast it would give the above warnings and require multiple y button press approvals. RC file here, I haven't change anything except the player tile line: 

https://crawl.kelbi.org/crawl/rcfiles/crawl-0.28/Shapermc.rc

**Comment by ebering** [comment]
Fixed by 097e55589aa
