### ISSUE TITLE
YANI - Starflower (abyssal oklob)

### ISSUE THREAD

**Issue by RojjaCebolla** [crawl/crawl#2413]
I ran into one of those Abyss vaults where the exit is surrounded by diggable walls, and I thought hey, that's pretty cute!

So that got me thinking about other "bonus exit" vaults, such as a portal out of the abyss that's guarded by an oklob, but oklobs are 1) a bit too mean maybe and 2) rather out of place in the abyss.

So I was thinkin of a portal  vault that's near, or directly beneath a Starflower.
(an oklob-like critter that grows in the presence of dimensional portals)
Rather than corroding, its ranged attack blinks the player on hit. Rarely, it imparts the `Tele` status instead, and even more rarely, when it hits or misses, it opens a portal deeper into the abyss at the end of its beam.

**Comment by ebering** [comment]
Oklobs aren't too mean, nor too out of place, in the unpredictable nightmare horroscape that is the Abyss. Vaultsmith away (but a depth restriction might be appropriate!).

An abyss specific stationary monster guarding the rune or an exit is a cool idea. With the mechanics you've described that's almost a ranged distortion brand, which might be a better way to implement the monster.

We don't really use GH issues for this kind of brainstorming, feel free to spitball about this with me further in ##crawl-dev.
