### ISSUE TITLE
Interaction between Aura of Silence (Ds mutation) and friendly Followers (Hep ancestor)

### ISSUE THREAD

**Issue by Drabon2** [crawl/crawl#2416]
**PLATFORM and OS or BROWSER:**
win 10 tiles local

**DCSS VERSION AND GAME INFORMATION:**
0.28

**DESCRIPTION:**
I have a question. I am currently playing a pure melee Demonspawn of Hepliaklqana with the mage ancestor. My Tier 3 Mutation evolved into the Black Mark including the 1 tile silence aura. After that happened it seemed like my ancestor is affected by said silence and stopped using its range attacks and Haste spell while inside. Is that intentional?

**Comment by ebering** [comment]
Yes, this is intentional. The ancestor is silenceable, so if you want them to cast spells you'll need them out of your silence aura. Demonspawn is funkadelic and sometimes you get a weird mutation curveball this way, like an Okawaru follower whose demonic guardians are told to stay behind.
