### ISSUE TITLE
Spectral Krakens be wack 

### ISSUE THREAD

**Issue by Monkooky** [crawl/crawl#2420]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
.28

**DESCRIPTION:**
Killed a kraken in abyss with Death-Chan active. 
Tentacles went wonky. See screenshot
(More detail, unfortunately, is difficult as I was not paying attention to the kraken.

**EXTRA FILES:**
https://cdn.discordapp.com/attachments/205316046230388737/942466486583308358/unknown.png

**Comment by semitonal** [comment]
What's the bug in this image? I could be missing something tiles-specific but it looks to me like their normal behaviour.

**Comment by Monkooky** [comment]
I assumed the large disconnect between kraken and tentacle was aberrant behaviour

**Comment by semitonal** [comment]
That's what kraken tentacles always do, they submerge in water and then extend out of it. I'd be all for removing this behaviour (it's the last place that submerging exists), but it's not a bug at least.
