### ISSUE TITLE
Staff of cold does not increase cold spells

### ISSUE THREAD

**Issue by erf** [crawl/crawl#2422]
**PLATFORM and OS or BROWSER:**

local tiles, macOS

**DCSS VERSION AND GAME INFORMATION:**

0.28.0

**DESCRIPTION:**

Staff of cold does not increase cold spells like Freeze, Freezing Cloud or Frozen ramparts

**EXTRA FILES:**

player dump:
[Erlend.txt](https://github.com/crawl/crawl/files/8056886/Erlend.txt)

**Comment by PleasingFungus** [comment]
Sorry, I don't understand the issue. What does it mean for the staff of cold to not 'increase' those spells?

It looks like all of your Ice spells are already at 100% power other than Freezing Cloud, and Freezing Cloud only increases duration with power, not damage. Is that what you were confused by?

**Comment by erf** [comment]
Sorry, i meant the damage was not increased when i wielded the staff of cold. Oh, i did not know it was "maxed out". So the staff of cold is pretty much useless at one point. I picked the wrong item from the acquirement scroll then 😅

**Comment by PleasingFungus** [comment]
Ah well! Hope you find more Cold spells soon :)

**Comment by erf** [comment]
> Ah well! Hope you find more Cold spells soon :)

Ah, so maybe the staff would still have effect on the more powerful cold spells?

**Comment by PleasingFungus** [comment]
Yep! You can test by wielding and unwielding the staff and comparing the displayed power %. I'd expect that it would still buff Polar Vortex and Ozocubu's Refrigeration.
