### ISSUE TITLE
Game periodically crashing when i pick up items (cause_msg = "ASSERT(item.props.exists(ARTEFACT_PROPS_KEY) || is_unrandom_artefact(item)) in 'artefact.cc' at line 1013 failed.")

### ISSUE THREAD

**Issue by RojjaCebolla** [crawl/crawl#2434]
Webtiles 0.28 (tournament) on Kelbi

Some of the most recent crashlogs, there's more before those:
https://crawl.kelbi.org/crawl/morgue/spicyDoesTourney/crash-spicyDoesTourney-20220220-154810.txt
https://crawl.kelbi.org/crawl/morgue/spicyDoesTourney/crash-spicyDoesTourney-20220220-164037.txt
https://crawl.kelbi.org/crawl/morgue/spicyDoesTourney/crash-spicyDoesTourney-20220220-154633.txt
https://crawl.kelbi.org/crawl/morgue/spicyDoesTourney/crash-spicyDoesTourney-20220220-081122.txt

**DESCRIPTION:**
Sometimes when I pick up an item, the game stops moving for a few moments, and then crashes. Some of my turns are reverted and, if I try to re-play them, events play out differently.

**Comment by rawlins** [comment]
If this game is still ongoing, can you do a save file backup? Requires using console, some instructions here: https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup

**Comment by RojjaCebolla** [comment]
oh sorry, i finished the game to make the tourney deadline. kinda wanted to go to hell but ran out of time!

**Comment by RojjaCebolla** [comment]
I wonder if dropping one of my many randart rings in the abyss or the treasure trove, to make space for something else, was the original culprit? i have no idea really though. the clearest thing is that the crashes usually occured after dropping or picking up randart rings, but if i loaded back into the game and tried taking my actions slightly differently, i could make a little more progress

**Comment by rawlins** [comment]
The crash looks like it was happening every time your inventory was sent to the webtiles client, it was probably one of the carried rings causing it. I may be possible to reconstruct using the seed, but I haven't tried that yet.

**Comment by RojjaCebolla** [comment]
@rawlins i'm getting it again now, conveniently! 
save: http://crawl.kelbi.org/saves/spicyDoesTourney-crawl-git-9445043ebc-220224-0357.tar.bz2
crashlog: https://crawl.kelbi.org/crawl/morgue/spicyDoesTourney/crash-spicyDoesTourney-20220224-031644.txt
