### ISSUE TITLE
MSYS2 trunk build on windows is broken

### ISSUE THREAD

**Issue by rawlins** [crawl/crawl#2440]
I'm opening this issue because I couldn't immediately figure out a solution and am not sure when I will. I think this is probably an upstream issue: https://github.com/msys2/MINGW-packages/issues/10761, but that doesn't seem to be resolved yet and may require some change to how we set up header include paths. First reported https://www.reddit.com/r/dcss/comments/sykds7/current_trunk_source_cannot_be_built/ and I have also replicated this myself in a VM with up-to-date MSYS2. That reddit poster provided a full build log here: https://pastebin.com/Jugns7Vv

**PLATFORM and OS or BROWSER:**
Windows 10, MSYS2 build.

**DCSS VERSION AND GAME INFORMATION:** Current trunk, probably not version specific.

**DESCRIPTION:** Importing `<cstdlib>` in `externs.h` fails with the following error:

```
In file included from externs.h:11,
                 from AppHdr.h:316,
                 from ability.cc:6:
C:/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
```

As noted above, hopefully a definitive fix or workaround will appear sooner or later in https://github.com/msys2/MINGW-packages/issues/10761. (There are some candidates there already that someone running on native windows would have an easier time testing.)

**Comment by Implojin** [comment]
Would it be a good idea to update INSTALL.md to recommend using WSL / debian when building on windows? This isn't the first time that Crawl builds have become broken under MSYS2...

**Comment by rawlins** [comment]
@Implojin MSYS2 is the only way to build the versions that resemble the official windows releases, and tiles is particularly tricky to get working on WSL. We also test cross-compiling mingw in CI which is fairly similar (this is our official windows release build method), so it generally doesn't become very broken. 

I don't really think that this kind of thing is all that different than e.g. the time a few months ago that an xcode update led to mac builds breaking, it's just inevitable with any complex system that is not completely static. The main difference is that no core dev uses any form of windows very much and I don't have time to look at the details right now, so I opened an issue rather than just fixing it.
