### ISSUE TITLE
Altar Generation Bug

### ISSUE THREAD

**Issue by riverfiend** [crawl/crawl#2441]
**PLATFORM and OS or BROWSER:**
Webtiles, CAO

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-207-gf982a88. Dump taken a few hundred turns afterwards is at https://pastebin.com/9KVvDAUm.

**DESCRIPTION:**
as soon as I entered a new floor, it hit me with this message:
![image](https://user-images.githubusercontent.com/63566628/155429701-f38b8bfb-7545-4dee-8cf8-a55441200e5d.png)

**Comment by riverfiend** [comment]
Here's a link to the save backup: http://crawl.akrasiac.org/saves/ISplatSpriggans-crawl-git-f982a884d8-220223-1853.tar.bz2

**Comment by rawlins** [comment]
This replicates reliably with the seed on current trunk on generating D:8; the erroring vault appears to be `nicolae_overflows_in_rows`: https://github.com/crawl/crawl/blob/master/crawl-ref/source/dat/des/altar/overflow.des#L5500. I'm guessing there's a mistake somewhere in the altar count calculations there. (There weren't any other clues from the debug build log that I saw.)

**Comment by nicolae-carpathia** [comment]
aw balls

i think i fixed this in https://github.com/crawl/crawl/commit/c45ea81df0f96a9e5a7bea7c80a0a7d5b2738693

**Comment by ebering** [comment]
Indeed fixed by nicolae
