### ISSUE TITLE
Armor slowdown or @ is not working on ranged?

### ISSUE THREAD

**Issue by ASilver** [crawl/crawl#2450]
**PLATFORM and OS or BROWSER:**
webtiles and Chrome

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-221-gceb61267dd (webtiles)

**DESCRIPTION:**
I am playing a Tengu Hunter with longbow. (Bow skill at 23.8) My armor was ring mail (armor skill is 8.0) and STR (modified) is 17. I just put on some Crystal Armor and was expecting a large speed hit, but instead the @ button is reporting no change. Is this correct or am I looking in the wrong place?

Here is a sample of the reported speed from messages:

_Something appears before you!
w - the +2 crystal plate armour "Vuozxiemn" {Int+3 Stlth+}
Magic restored.
Partly explored, unvisited transporter.
Unknown command.
You are flying quickly and evasively. Your flying speed is quick.
Your attack delay is about 0.7 (and cannot be improved with additional weapon
skill).
Your base attributes are Str 13, Int 12, Dex 19.
Unknown command.
You start removing your armour.
You continue taking off your +2 ring mail of fire resistance. x4
You finish taking off your +2 ring mail of fire resistance.
You feel less resistant to fire.
You start putting on your armour.
You continue putting on the +2 crystal plate armour "Vuozxiemn" {Int+3 Stlth+}.
x5
You finish putting on the +2 crystal plate armour "Vuozxiemn" {Int+3 Stlth+}.
You feel clever.
You are flying quickly and evasively. Your flying speed is quick.
Your attack delay is about 0.7 (and cannot be improved with additional weapon
skill) (and is slowed by your armour)._ 

**EXTRA FILES:**

[almostdecent-crystal-ranged.zip](https://github.com/crawl/crawl/files/8147509/almostdecent-crystal-ranged.zip)
[almostdecent-crystal-ranged.txt](https://github.com/crawl/crawl/files/8147510/almostdecent-crystal-ranged.txt)

**Comment by ASilver** [comment]
[almostdecent-crystal-ranged.txt](https://github.com/crawl/crawl/files/8147513/almostdecent-crystal-ranged.txt)

**Comment by PleasingFungus** [comment]
Nice find! Fixed now - thanks for reporting :)
