### ISSUE TITLE
Can't attack invisible enemy when in tree form

### ISSUE THREAD

**Issue by erf** [crawl/crawl#2455]
**PLATFORM and OS or BROWSER:**
local tiles on macos

**DCSS VERSION AND GAME INFORMATION:**
built from source: 945431f764

**DESCRIPTION:**
I drank a Potion of lignification and in tree form trying to fight a Shadow that turned invisible, i could not attack it, saying "Can't move". I usually use the move buttons to attack. Is this correct behavior? Do i have to use "v" to attack invisible monsters?

**EXTRA FILES:**

**Comment by liammcd** [comment]
This is correct behaviour. You can use "v" to attack or ctrl + direction to attack in a direction

**Comment by rawlins** [comment]
yes, traditionally ctrl-direction was the answer to attacking in treeform, but as @liammcd says these days also `v` should work with any weapon or unarmed.
