### ISSUE TITLE
merfolk can wear boots in statue form

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#2457]
**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-231-g945431f764

**DESCRIPTION:**
1. cast statue form
2. go to water tile
3. get out of water tile

then you are in statue form but boots unmeld
this bug does not occur if you are flying

![1](https://user-images.githubusercontent.com/97007398/156104633-8cfd9790-9dc9-4685-99e7-068d2881a611.PNG)

**Comment by Rosstin** [comment]
I can reproduce this (0.29-a0-286-g5b23f92790). I guess exiting water as Merfolk should check if your boots qualify for unmelding based on your form.

**Comment by acrobat3** [comment]
fixed
