### ISSUE TITLE
Cleaning d1 should not leave a player with XL1.5

### ISSUE THREAD

**Issue by ASilver** [crawl/crawl#2463]
**PLATFORM and OS or BROWSER:**

Webtiles - Chrome

**DCSS VERSION AND GAME INFORMATION:**

0.29-a0-234-g0dae59b3db (webtiles)

**DESCRIPTION:**

With a very elementary Minotaur Hunter, playing Tab-O, d1 was completely cleaned out except the character was left at XL1 and a mere 58% completed. There should be safeguards to avoid such things IMHO. 

**EXTRA FILES:**

![image](https://user-images.githubusercontent.com/3589847/156578384-e9b0aceb-f9d4-4d41-82e2-cd37a08a6a28.png)

**Comment by acrobat3** [comment]
Same thing happened to me on streak game a few weeks ago.
I'm not sure it's a bug, but it feels pretty unfair.

**Comment by ebering** [comment]
Sometimes you get a low roll on monsters, or loot, or both, or only one. This doesn't look like a particular vault has prevented monster generation, just the extreme low edge of random rolls. This game will have a more exciting D:2!

**Comment by ASilver** [comment]
Sort of. Cleaning D:2 left the character with XL2 and 60%.
