### ISSUE TITLE
Blank white on every characters while playing 

### ISSUE THREAD

**Issue by Pandacat-sudoer** [crawl/crawl#2464]
Problem on stone-soup desktop offline-local-tiles    
V: 0.28.0-1 OS: Linux (ArchLinux).

Log: "Texture player.png is bigger than maximum driver texture size (1024,4096 vs. 2048). Sprites from this texture will not display properly.
OpenGL error GL_INVALID_VALUE"

I have no idea about these, but before this version there's no such problems, I try to use the older (0.27) for player.png but it getting weird for every characters. I play these using both, code that I compiled from your crawl GitHub repository and my Linux distribution latest binary, there's no difference between both.

**Comment by rawlins** [comment]
This error usually happens with older graphics drivers / cards, and is reporting a texture limit set by the drivers. Are yours up to date? What is the graphics card?

**Comment by Pandacat-sudoer** [comment]
> This error usually happens with older graphics drivers / cards, and is reporting a texture limit set by the drivers. Are yours up to date? What is the graphics card?

Yeah, it's up-to-date I think, I use the correct settings for my drivers, it just go nicely for my daily usage and other games too, it's Intel GMA 3150 with g45-h264 branch driver.. however, it doesn't get such error before this version.

**Comment by rawlins** [comment]
> it doesn't get such error before this version.

Ok, thanks. I suspect the texture size increased this version (it's basically the sprite sheet size), I'll look into that and see. That's a relatively old card (2007) so I'm not surprised its drivers would be showing limits we haven't encountered before if the texture size increased.

**Comment by Pandacat-sudoer** [comment]
> > it doesn't get such error before this version.
> 
> Ok, thanks. I suspect the texture size increased this version (it's basically the sprite sheet size), I'll look into that and see. That's a relatively old card (2007) so I'm not surprised its drivers would be showing limits we haven't encountered before if the texture size increased.
> 
> 

Thanks for your response sir, I hope you can help me

**Comment by Pandacat-sudoer** [comment]
> > it doesn't get such error before this version.
> 
> Ok, thanks. I suspect the texture size increased this version (it's basically the sprite sheet size), I'll look into that and see. That's a relatively old card (2007) so I'm not surprised its drivers would be showing limits we haven't encountered before if the texture size increased.
> 
> 

Sir, I think the problem was only happened due to "player.png" file that might be larger than before, there's no problem with other pictures, so I think if you can make that file (player.png) to be separated into few parts, so it wouldn't make it bigger and load it at once rather than that it can be a smaller but two or more times be loaded

**Comment by rawlins** [comment]
I just committed some changes to the tile sheet that more or less fix this issue, for now: 370832a12f88 and b366d0e2d19ed in trunk. This is backported to 0.28 as well, though you would need to build from that branch yourself until there's a new stable release (not sure when this will happen). This is not really a permanent fix to the underlying problem, in that I just reordered the tile sheet a bit so it was more efficiently packed. The underlying problem ([https://crawl.develz.org/mantis/view.php?id=11378](https://crawl.develz.org/mantis/view.php?id=11378)) unfortunately requires a major refactor of how local tiles handles tile sheets / texture atlases to solve (on this implementation it's not at all straightforward to break up tilesheets into distinct textures).

I suspect this will recur sooner or later, as just about any non-trivial additions to the monster or player tileset are likely to lead to the same issue again. However, I'm going to close up this particular issue as the immediate problem should be solved; please feel free to open a new one if you (or anyone) notices it recurring.
