### ISSUE TITLE
Deep Dwarf of Jiyva loses god-granted MP Regen when wearing Guardian Spirit

### ISSUE THREAD

**Issue by Monkooky** [crawl/crawl#2469]
**PLATFORM and OS or BROWSER:**
All Platforms

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-266-gf56f883ddc

**DESCRIPTION:**
As a DD^Jiyva, put on an amulet of guardian spirit. MPRegen as listed under the % screen remains unchanged. However, mana does not regenerate; not even limited to the rate granted by Jiyva.
This is at odds with the HP regeneration granted by Jiyva, which is not blocked by Deep Dwarviness

**Comment by semitonal** [comment]
Rip to deep dwarves...
