### ISSUE TITLE
vampire castle

### ISSUE THREAD

**Issue by elliottbernstein** [crawl/crawl#2476]
**PLATFORM and OS or BROWSER:**
webtiles; chrome 98.0.4758.102

**DCSS VERSION AND GAME INFORMATION:**
0.28

**DESCRIPTION:**
In the "vampire castle"  Bailey, some orc warrior zombies are equipped with spears. However, these spears aren't displayed as part of their art, so you can easily take damage from these monsters without realizing why if you're not reading carefully.

**Comment by PleasingFungus** [comment]
Good catch! Fixed, thanks - apologies for the delay.
