### ISSUE TITLE
Beastly Appendage melding Naga Barding

### ISSUE THREAD

**Issue by cantbefantasy** [crawl/crawl#2486]
**PLATFORM and OS or BROWSER:**
local tiles / Windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-270-g1586fc07ea

**DESCRIPTION:**
Beastly Appendage spell is causing Naga barding to meld into body, negating its AC and brand effects. Wondering if its a leftover from when it used to give a 'Tail Spike' to Nagas, but it otherwise should have no reason to meld in barding as the spell only gives Horns to Nagas.

**Comment by semitonal** [comment]
This is intended behaviour, yeah - Beastly Appendage melds the foot and head slots for all species (including in cases where the species doesn't actually get an aux mut from that slot, such as Octopodes and Nagas), to prevent it being useful to keep casting later into the game.
