### ISSUE TITLE
Yara's Violent Unravelling causes input issues following casts

### ISSUE THREAD

**Issue by maxmilligan** [crawl/crawl#2488]
PLATFORM and OS or BROWSER:
crawl.kelbi.org / Chrome

DCSS VERSION AND GAME INFORMATION:
0.29-a0-274-g17cd264cf

DESCRIPTION:
For several versions of Trunk, casting Yara's Violent Unravelling has caused further spellcasting attempts--pressing z--and sometimes other types of input to default to trying to cast Yara's Violent Unravelling again, but with additional force more messages. Yara's can be cast again by using . or a different spell can be cast by pressing ? and selecting one from the menu, but simple sequences like z a or z b stop working.

**Comment by semitonal** [comment]
This sounds like it could be an rcfile issue, with having set a weird macro or keybind or something. Either way I can't reproduce it - if you can provide more context such as a log or save file feel free to re-open.
