### ISSUE TITLE
Alistair's Intoxication makes sleeping enemies walk around

### ISSUE THREAD

**Issue by laserbat** [crawl/crawl#2496]
**PLATFORM and OS or BROWSER:**

Online (CXC), over ssh

**DCSS VERSION AND GAME INFORMATION:**

0.28

**DESCRIPTION:**

If a sleeping enemy is confused by Alistair's Intoxication, they remain "sleeping" while stumbling around like a normal confused enemy.  

To reproduce, it's enough to cast AI on any sleeping enemy and succeed in confusing it. 

**EXTRA FILES:**

Dump of my character when this happened: [link](https://gist.github.com/laserbat/1b266f2c11d4a7e8ea069ad5e74e8af2)

**Comment by riverfiend** [comment]
That's not a bug--all confused sleeping enemies exhibit 'sleepwalking' behavior. This is working as intended.

**Comment by laserbat** [comment]
Oh, I see! Didn't think about this, neat. Thank you!
