### ISSUE TITLE
Reflection broken

### ISSUE THREAD

**Issue by ASilver** [crawl/crawl#2500]
**PLATFORM and OS or BROWSER:**

Chrome Webtiles

**DCSS VERSION AND GAME INFORMATION:**

**DESCRIPTION:**

I don't know if the Reflection was nerfed, but it is close to useless at the moment. It used to be strong defense against arrows, but right now I counted 14 shots and 3 reflections, and this has been par for the course in 0.29 of late.

Here is a paste from a moment I had to flee from while wearing an Amulet of Reflection:

The deep elf knight wields a +0 shortbow.
The deep elf knight shoots an arrow. The arrow hits you!
An earth elemental comes into view.
The deep elf knight shoots an arrow. The arrow hits you!
The deep elf archer shoots an arrow.
You reflect the arrow off an invisible shield around you!
The arrow barely misses the deep elf archer.
The arrow hits the deep elf archer!! The deep elf archer shoots an arrow.
The arrow hits you!
The deep elf archer mumbles some strange words.
The deep elf archer blinks! The deep elf archer shoots an arrow.
The arrow hits you!
LOW HITPOINT WARNING
The deep elf archer unwields a +0 dagger.
The deep elf archer wields a +0 longbow.
The deep elf archer shoots an arrow. The arrow hits you!
LOW HITPOINT WARNING
The deep elf knight gestures wildly while chanting.
The deep elf knight seems to speed up. The deep elf archer shoots an arrow.
The arrow hits you but does no damage. The deep elf archer shoots an arrow.
You reflect the arrow off an invisible shield around you!
The arrow hits the deep elf archer!! The deep elf knight shoots an arrow.
The arrow hits you but does no damage. The deep elf archer shoots an arrow.
The arrow hits you!
LOW HITPOINT WARNING

**EXTRA FILES:**

**Comment by ASilver** [comment]
And I died by arrows unable to flee quickly enough.

https://cbro.berotato.org/morgue/AlmostDecent/morgue-AlmostDecent-20220322-054657.txt

**Comment by ebering** [comment]
From the in-game description:

```
An amulet which exerts a force that blocks some incoming attacks, and can even
reflect any blocked ranged attacks back towards the attacker.

It affects your shielding (+5)
```

Amulets of reflection do two things: give you +5 SH and make all shield blocked projectiles reflect.

In the morgue you've provided you had EV 14 and SH 14, which gives a deep elf archer 37% chance to hit you in the first attack of a combat round, and that goes up (each shield block attempt reduces shield effectiveness for the combat round). According to the message log at the end of the morgue, you had 1 dodged arrow,  blocked 3, and were hit by 5, while both being hit and shot at. Each arrow you blocked was reflected back at the archer.

4 miss 5 hit is a plausible outcome of 37% to-hit even without accounting for the shield effectiveness decreases.
