### ISSUE TITLE
Sp is allowed to cast swift if theyre in shallow water, does nothing

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2503]
**PLATFORM and OS or BROWSER:**
local 0.28.0

**DESCRIPTION:**
Swift normally doesnt effect spriggans and they arent allowed to cast it. if a sp stands in shallow water theyre allowed to cast swiftness, which then doesnt do anything.

**Comment by semitonal** [comment]
Fixed in 6573418d013d1d29.
