### ISSUE TITLE
Yara's doesn't warn you when you are going to hurt and mutate yourself

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#2505]
**PLATFORM and OS or BROWSER:**
Webtiles, chrome

**DCSS VERSION AND GAME INFORMATION:**
Trunk a few days ago (sorry, don't have a precise version)

**DESCRIPTION:**
I cast Yara's Violent Unravelling on a monster next to me, and got no warning.

**Comment by semitonal** [comment]
As far as I can tell this works as expected and always gives a prompt. With no save file, log or any other context it's not really reproducible, feel free to re-open if it happens again and you can provide more information.
