### ISSUE TITLE
The DCSS Ohio Server certificate is not valid, I can log in, but I cannot play a game or spectate

### ISSUE THREAD

**Issue by 24metehantarhan** [crawl/crawl#2511]
PLATFORM and OS or BROWSER: US Ohio

DCSS VERSION AND GAME INFORMATION: All versions, including spectating

DESCRIPTION: The website certificate is expired, although I can log in to my account and go to the home page, I cannot spectate anyone, nor can I play a game in any version.
![Screenshot 2022-03-31 9 16 19 AM](https://user-images.githubusercontent.com/102740827/161063598-05c14963-97f8-40e5-bbd8-c986edcf173d.png)
![Screenshot 2022-03-31 9 15 58 AM](https://user-images.githubusercontent.com/102740827/161063602-89b47e0d-8a13-4c46-aefe-17e076668092.png)

**Comment by rawlins** [comment]
This should be fixed as of some time a couple days ago, thanks!
