### ISSUE TITLE
Delatra's Gloves vs Lignification

### ISSUE THREAD

**Issue by dwetuski** [crawl/crawl#2521]
**PLATFORM and OS or BROWSER:**
Windows 7 local tiles

**DCSS VERSION AND GAME INFORMATION:**
crawl_tiles-0.29-a0-284-gf9362112df

**DESCRIPTION:**
I was playing a Deep Dwarf, found Delatra's gloves on D:2, and drank an unidentified potion of lignification in an attempt to heal.  I did not receive healing, presumably as a side effect of the potion altering my maximum HP, as drinking other unidentified potions seems to provide healing normally.

**Comment by semitonal** [comment]
The issue here is that the gloves were melded by the potion, so their effect didn't get to trigger - should be fixed now, thanks for reporting!
