### ISSUE TITLE
Monsters slower than the player do aoop (when petrifying)

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#2529]
**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-334-gb41bcbb86e

**DESCRIPTION:**
Kobold(petrifying) is slower than player human. (right?)
But as you can see in the screenshot, he still does aoop.

![1](https://user-images.githubusercontent.com/97007398/164434898-3c0a4faa-243f-4275-a657-2907bca47729.PNG)

**Comment by PleasingFungus** [comment]
Sorry, just saw this now! Fixed, thanks :)
