### ISSUE TITLE
DCSS prints that Options errors happen in ~/.crawlrc, even when th.

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2536]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-384-g6960b1960d

**DESCRIPTION:**
If I start crawl with

`crawl`

and ~/init.txt consists of the line

`mon_glyph -= werewolf`

the game prints something like:

```
Crawl encountered errors during initialization:

 Data directory '/tmp/dat/' found.
 Options error: Unknown monster: "werewolf" (~/.crawlrc:1)
 Loading databases... Loading spells and features... Loading maps...
 Hello, welcome to Dungeon Crawl Stone Soup 0.29-a0-384-g6960b1960d!
 (c) Copyright 1997-2002 Linley Henzell, 2002-2021 Crawl DevTeam
 Options read from "/tmp/init.txt".
```
If I use

`crawl -extra-opt-first "include = /tmp/example.txt"`

it warns of problems in (`/tmp/example.txt`) instead.

I would only expect option error messages to name a file when this is the file the game found the error in.

From what I can see, the game sets a hardcoded value for Options.basefilename in read_init_file(), and uses it in error messages for the -rc file. I don't know if this serves a purpose.

EXTRA FILES:

None

**Comment by wheals** [comment]
Fixed in 18b7feefb4
