### ISSUE TITLE
Polearm Bailey 1 needs adjustment due to reallife reference.

### ISSUE THREAD

**Issue by Bracket-H** [crawl/crawl#2539]
This bailey layout 
https://github.com/crawl/crawl/blob/2e7ade144cf8d86961b2d1259be0582f5ae2a57d/crawl-ref/source/dat/des/portals/bailey.des#L631

matches the Japanese Kagome Crest
https://en.wikipedia.org/wiki/Kagome_crest

A shinto symbol.
(And the Shatkona https://en.wikipedia.org/wiki/Shatkona) 

Thus, in the light of adjusting things like the Ring of the Shaolin, the Sword of Jihad or Hellfire, this layout should be adjusted, as well.
Yes, this involves changing the map itself, but, renaming is simply not an option to remove this reference.

**Comment by rawlins** [comment]
Just resembling something in real life is not enough to require changes, and in the past the threshold for vault designs that aren't explicit references is if they resemble hate symbols (I can't find any evidence of that here, though please correct me if I'm wrong).

The motivations for two of the referenced changes went well beyond resemblance, see c3e0a5ca6ddc, 405fccface. The motivation for the hellfire change was thematic, see f90497cceb.

**Comment by Bracket-H** [comment]
It's a shinto symbol, and used in quite a few things pertaining to that, including, but not limited to the Sendai Daikannon.
https://www.youtube.com/watch?v=kSg2aLlAzpQ

It's a giant statue with the kagome crest on its chest.
I fail to see how this is not significant enough, when you nixed Shaolin just based on 'exoticism'.

This is beyond exoticism, this is concreate realism, a massive monument to it.

**Comment by rawlins** [comment]
I can't quite figure out what you are going for here. Is the claim that using a hexagram in a vault design is some form of exoticism because they show up in various world cultures? On closer examination I don't even think your parsing of the referenced symbols is very accurate, as they both involve interlocking equilateral triangles (as does the star of david, of course).

Good faith engagement on these issues is welcome, but to be honest, this doesn't really look like it to me.

**Comment by Bracket-H** [comment]
> I can't quite figure out what you are going for here. Is the claim that using a hexagram in a vault design is some form of exoticism because they show up in various [world cultures](https://en.wikipedia.org/wiki/Hexagram#Religious_usage)? (edit: removed a comment about interlocking triangles)
> 
> Good faith engagement on these issues is welcome, but to be honest, this doesn't really look like it to me.
The swastika also shows up in various world cultures, but you would very likely remove that one, right?

Why are you so reluctant to remove a symbol that is exactly used by so many realworld cultures in religious context?
When something like 'shaolin' is so benign in comparison?

What's going on here? I think you are not making a good faith engagement here, in fact, you're connecting a whole bunch of faiths to a brutish, blood lusting orc nest here.
