### ISSUE TITLE
Teleportation with long actions encourages spoilery behaviour

### ISSUE THREAD

**Issue by Monkooky** [crawl/crawl#2540]
.29 

Currently, a teleport scroll will wait 30-50 auts before going off. For the action on which the tele scroll fires, the sequence of events is:
Action is performed -> scroll fires -> monsters react. 

This is notable if, for example, you are swinging dark maul while in statue form or slowed. If at the start of the turn you have < 45 aut of teleport delay remaining, you will swing, the teleport will happen, and monsters will not get to react until after you are already gone. This allows you to functionally teleport instantly.

This is undesirable for two reasons:
Firstly, this encourages having access to very slow attacks, which in turn creates a perverse incentive to deliberately leave certain skills untrained.

Secondly, effectively using this requires intimately knowing the mechanics of teleport scrolls, in particular the maximum aut delay before the tele goes off. This is currently not accessible in game.

I don't see a solution to the fundamental problem here without some fundamental changes, but at a minimum it would be nice to see 'at most x turns until firing' on teleport scroll usage.

**Comment by PleasingFungus** [comment]
I'm unconvinced this is a problem in practice, but if it is, i'd rather add a long tail to the tele dur, so it's still avg 4 turns but max 8 or 10 or somesuch.

**Comment by rawlins** [comment]
Summary of some dev discussion:
* Not really practical knowledge to make use of in most situations
* if you need to teleport, taking defensive/healing actions (running away, etc) is probably still better
* If you get the timing right: your action delay before the TP gives any monsters in los after the TP that much time to act. So swinging dark maul in statform has a potential significant downside if you get a bad TP. (Not to mention, if you have miscalculated the timing.) If anything, it seems to me that if there's spoilery knowledge it's *not* to do this? (E.g. that a teleport delay fires after player action and before `world_reacts`.)

Anyways, it seems like PF and I are agreed that no particular change is needed for this.
