### ISSUE TITLE
Barachi Description 

### ISSUE THREAD

**Issue by tr2424** [crawl/crawl#2542]
I am playing the online game, 0.28, web tiles. When creating a new character, If I hover over `z - Barachi` the text display as follows:

> ... Their extended range of vision also allows them to be seen from further away.

I believe `to be seen` should read `to see`. I.e. indicating that they can see far, not be seen from afar. Thanks.

**Comment by semitonal** [comment]
Crawl LOS is symmetric, so being able to see further always means that you can also be seen from further away. The current wording looks correct to me, it's explaining what the result of having an extended range of vision is.
