### ISSUE TITLE
Problem with "tile_player_tile = mons:dancing weapon"

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2544]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-414-g5075937ec3

**DESCRIPTION:**
If I start crawl with

```
crawl -rc `tempfile` -extra-opt-last "option=name:random,species:random,background:random,weapon:random,tile_player_tile:mons:dancing weapon" 
```
the game asks me to press any key, and then crashes. Other monsters with TILE_* tiles do the same thing. I don't know if there's a way to make those tiles work as player tiles, or if it these are options the player shouldn't be allowed to choose.

EXTRA FILES:

[saved game](https://github.com/crawl/crawl/files/8695077/random.cs.gz)
[crash log](https://github.com/crawl/crawl/files/8695078/crash-random-20220515-144847.txt)

**Comment by rawlins** [comment]
> Other monsters with TILE_* tiles do the same thing.

I marked this as resolved because I couldn't get anything besides animated objects to crash, but is there something else I didn't try that this was referring to?

**Comment by Aliscans** [comment]
It crashes in tile_player_info(), so any monster with a tile.base which isn't between TILE_MAIN_MAX and TILEP_PLAYER_MAX-1 inclusive should work.

I think the only current examples are:
dancing weapon
sensed monster
friendly sensed monster
trivial sensed monster
easy sensed monster
tough sensed monster
nasty sensed monster

**Comment by rawlins** [comment]
Aha, thanks -- I'd tried the sensed monsters but hadn't got the syntax right, those do also crash.
