### ISSUE TITLE
Gozag shops not closing upon abondonment

### ISSUE THREAD

**Issue by jeremysacco** [crawl/crawl#2545]
Despite the message when I abandoned Gozag, the stores I funded through him remained open in my latest game - trunk, CBRO, on 5/17.  Game is still going so I can't share a seed, but player name is snackwell.  For now you can see all the shops on L1 here: https://cbro.berotato.org/morgue/snackwell/snackwell.lst

Switched from Gozag to Jiyva for kitty reasons.

**Comment by dillytin** [comment]
#1983 reported the same bug. It seems that felid is associated with it.

**Comment by rawlins** [comment]
Thanks for the report! Merging with #1983
