### ISSUE TITLE
Mobs Spawn on Traps

### ISSUE THREAD

**Issue by tr2424** [crawl/crawl#2549]
This may be working as intended... but just in case. I've noticed several times that when I enter a new level, a monster may have spawned (and still be asleep (z)) on a dispersal or teleport trap. If that's normal, please ignore me, sorry to bother!

Noticed this on 0.28, web tiles.

**Comment by PleasingFungus** [comment]
Thanks for reporting! @ebering says this is working as intended, so I'll close this. Apologies for the delay. :)
