### ISSUE TITLE
Unexplored hatches are slow

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2551]
**PLATFORM and OS or BROWSER:**
webtiles trunk

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-472-ge5599a681e

**DESCRIPTION:**
Unused hatches take 1.7-1.8 to use for the first time. Pleasingfungus said they should work the same as stairs. 
![image](https://user-images.githubusercontent.com/70080435/169713234-97a486ef-9d8a-4679-a74b-9ddc9cf56533.png)

**Comment by rawlins** [comment]
This is actually the same as stairs into an unexplored area take; if it were explored it would be about 2.5.

**Comment by ardl** [comment]
Unexplored stairs take .7-8 tho?

**Comment by rawlins** [comment]
They take 1 (on the level above as a result of `start_delay<DescendingStairsDelay>(1);`) + .7-.8 (on the new level via the `load_level` code). The UI shows 1.7-1.8 after taking the stairs/hatch as a result.
