### ISSUE TITLE
a +10 morningstar becomes the +10 morningstar Eos when examined

### ISSUE THREAD

**Issue by Monkooky** [crawl/crawl#2552]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
![image](https://user-images.githubusercontent.com/6244827/169884709-c83681ed-0a97-4a8d-aaa6-33cb499e7564.png)

**DESCRIPTION:**
Found in shop "a +10 morningstar {elec, Halo rElec}". Examined it. It became (in shop) "the +10 morningstar "Eos" {elec, Halo rElec}"
I am not 100% sure this isn't my memory betraying me.

**EXTRA FILES:**
The relevant screen:
![image](https://user-images.githubusercontent.com/6244827/169884167-c2540010-2376-41e2-83fa-d1850e70cfbc.png)

**Comment by rawlins** [comment]
Can you provide the seed for this game? (Also the shop location.)

**Comment by Monkooky** [comment]
Seed should be 6390396475851393907
Store is on D:13

**Comment by rawlins** [comment]
Thanks for the seed!

Not to say that this didn't happen, but I couldn't replicate it. It's possible that this could result from something being weird about the item's ident state? But on a fresh char on current trunk on that seed it doesn't happen. I'm going to close, happy to reopen if this occurs again.
