### ISSUE TITLE
Devestator triggering an “attacking allies” message when attacking near a Hep ancestor.

### ISSUE THREAD

**Issue by FatBunny13** [crawl/crawl#2554]
**PLATFORM and OS or BROWSER:**
Webtiles - Firefox 100.0.2

**DCSS VERSION AND GAME INFORMATION:**
0.29a. - GAME VERSION

NAME - AnimeIsTrash

**DESCRIPTION:**
When attacking using Devastator near your Ancestor, a message triggers you warning about attacking near your allies along with a prompt. However the Ancestor takes no damage from this attack, so the message is pointless.

**EXTRA FILES:**

**Comment by FatBunny13** [comment]
Note, I think it’s likely that with the recent change of being able to fire through the Ancestor that it’s likely that there’s an error in making messages about warnings with the Ancestor.

**Comment by PleasingFungus** [comment]
Thanks for reporting, and apologies for the delay! Fixed. :)
