### ISSUE TITLE
Krakens can still submerge?

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2556]
**PLATFORM and OS or BROWSER:**
current trunk

**DCSS VERSION AND GAME INFORMATION:**
CBR2: 0.29-a0-490-g77b3608bb8

**DESCRIPTION:**
Auto explored into this 
![image](https://user-images.githubusercontent.com/70080435/170582266-6cbd5e27-1840-484e-8e03-9c9dfa3f0973.png)
I have no idea how this could have happened without the kraken being able to submerge, and carefulodds told me that they can still submerge.

Theres no reference of submerging left anywhere I can find in game docs, and I thought submerging was wholly removed aside from tentacle segments due to how tedious it makes optimal exploring. Past commits about submerging imply that no monsters submerge. Specifically, b743457d49c23d2d12f7cd6db9761b9143c5b6d7 . mon-data.h also doesnt have kraken's tagged with m_submerges.

**Comment by PleasingFungus** [comment]
Weird. I agree that krakens shouldn't be able to submerge, and I can't repro this easily. Are you sure you didn't get teleported, or something?
