### ISSUE TITLE
Scroll of Fog Negates Scroll of Poison

### ISSUE THREAD

**Issue by tr2424** [crawl/crawl#2562]
**PLATFORM and OS or BROWSER:**
Web Tiles/MacOS/Safari

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-557-g43b9904bd1

**DESCRIPTION:**
If you read a scroll of poison in fog (i.e. right after reading a scroll of fog), it does not work. The scroll is read but there are no poison clouds. This may be intended, unsure.
To duplicate:

- Read a "scroll of fog"
- Read a "scroll of poison" immediately after.

**Comment by riverfiend** [comment]
This is working as intended: Clouds will not displace other clouds. You can use this to your advantage by reading fog before fighting a dangerous cloudy enemy like a catoblepas or a death drake, their clouds will not be placed where your benign fog clouds have been placed.

**Comment by PleasingFungus** [comment]
Yep, riverfiend is right. Arguably the scroll should be marked temporarily useless in this case, or should warn the player. Thanks for reporting!
