### ISSUE TITLE
[Meteoran][Scarf of Shadows][LOS] Game crashes when Zot's clock is 0

### ISSUE THREAD

**Issue by DevastatorOne** [crawl/crawl#2567]
**PLATFORM and OS or BROWSER:**
Windows 10, 21h2

**DCSS VERSION AND GAME INFORMATION:**
Offline trunk 0.29-a0-274-g17cd264cf

**DESCRIPTION:**
If you put scarf of shadows on Meteoran and wait for Zot Clock to be 0, game will crash because of the 0 LOS

**Comment by DevastatorOne** [comment]
I have made a mistake in version, sorry.

Version is
0.29-a0-542-g075992c915
[crash-Trunk 3rd June-20220610-200342.txt](https://github.com/crawl/crawl/files/8881899/crash-Trunk.3rd.June-20220610-200342.txt)

**Comment by rawlins** [comment]
Probably the same crash: http://crawl.akrasiac.org/rawdata/physeK/crash-physeK-20220624-170832.txt

(We haven't managed to replicate this one yet, there's still some unknown factor I think)
