### ISSUE TITLE
Turncount in HUD doesn't match morgue/goodbye screen

### ISSUE THREAD

**Issue by powerbf** [crawl/crawl#2569]
Webtiles Trunk 0.29-a0-563-g64e4043 (CPO)

At the end of my game, the HUD said 18522.6 turns, but the "goodbye" window and the morgue said 20036 turns.

[morgue](https://crawl.project357.org/morgue/MrDizzy/morgue-MrDizzy-20220611-123910.txt)

Screenshot:
![turncount_mismatch](https://user-images.githubusercontent.com/45711639/173195951-5d7fe150-3240-4de6-a99a-c45e6eafb810.png)

**Comment by ebering** [comment]
The HUD is showing time taken (in deca-auts, crawl's time unit). Most turns are 10 auts, but some things (like attacks with weapons, or any action while hasted) are fewer.

**Comment by powerbf** [comment]
Hmmmm, ok. It's kind of confusing though that there are two time measurements that are almost, but not quite, the same.
