### ISSUE TITLE
new yred - Drain life and necromancy information

### ISSUE THREAD

**Issue by Krisselack** [crawl/crawl#2574]
The new Yredelemnul gameplay is fun! 

Two issues (0.28, offline): 
- The drain life ability needs to be targeted (I thought it's LOS). Why? 
- Apparently, Yred works as a manual of necromancy (this is nowhere to be found written, neither in description, nor in wiki). Cool! 

Thanks!

**Comment by ebering** [comment]
In 0.27 and 0.28 targeters have been implemented for just about every ability; in the case of drain life it will display a targeter which will indicate its LOS area of effect (this is helpful in situations with fog or glass for example where it might not be clear what will be hit).

Can you elaborate on what you mean by "works as a manual of necromancy"? Yred doesn't impact necromancy skill training.

**Comment by Krisselack** [comment]
Ah, LOS-Indicator, thanks! 

Concerning necromancy skill training: I must have overlooked a picked up manual, they don't show up in the inventory anymore :-). Was just a weird coincidence on first time new yred, sorry for the fuss.
