### ISSUE TITLE
After trunk update, can't start ongoing Gnoll game

### ISSUE THREAD

**Issue by jdallm** [crawl/crawl#2584]
**PLATFORM and OS or BROWSER:**
CHROME 105.0.5137.4

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-653-gd47aff673

**DESCRIPTION:**
After the latest trunk update, when I open my GnWn^Ok game I have the potion of experience interface asking me to distribute the experience to chosen skills. However, as a gnoll, I am unable to choose any skills to give the experience. I cannot exit the screen using any keys and the game eventually just crashes.

**Comment by rawlins** [comment]
Thanks for the report! This is fixed as of: https://github.com/crawl/crawl/commit/365da2f8ac5d

It'll need servers to update before the fix takes effect; I just started a rebuild on CAO, and CKO/CPO will update quickly, but some of the others may take another day or so.
