### ISSUE TITLE
No Orcish Mines

### ISSUE THREAD

**Issue by Qudnik** [crawl/crawl#2585]
**PLATFORM and OS or BROWSER:**
Playing online via ssh on CAO.

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-719-g0fec994 (console)

**DESCRIPTION:**
No entrance to the Orcish Mines spawned. I double checked the relevant floors and it didn't show up in the dungeon overview either.

**EXTRA FILES:**
Morgue file: http://crawl.akrasiac.org/rawdata/Qudnik/morgue-Qudnik-20220626-211201.txt

**Comment by dillytin** [comment]
Orc entry was on D:11 according to your morgue

**Comment by ebering** [comment]
Orc mines generated correctly in this game, though the path there was blocked by an alarm trap.
