### ISSUE TITLE
Two bad icons

### ISSUE THREAD

**Issue by natelastname** [crawl/crawl#2592]
**PLATFORM and OS or BROWSER:**
Local tiles 
**DCSS VERSION AND GAME INFORMATION:**
0.28
**DESCRIPTION:**
1. The "Acrobat" and "Magic regeneration" amulets have icons that are hard to distinguish, plus the "acrobat" icon doesn't make sense (why is it a round purple emblem?)
2. One of the staffs looks like a blood stain. You can probably guess which one I'm talking about.
**EXTRA FILES:**
N/a

**Comment by strategineer** [comment]
This PR seems to resolve at least part of this issue: https://github.com/crawl/crawl/pull/2607
