### ISSUE TITLE
After upgrade the 'a' key is "attach" not "abilities", leave me unable to access religion abilities. 

### ISSUE THREAD

**Issue by lembark** [crawl/crawl#2602]
**PLATFORM and OS or BROWSER:**

Gentoo Linux 

**DCSS VERSION AND GAME INFORMATION:**

games-roguelike/stone-soup 0.28.0-r1 running in tiles mode.

Compiled as:
$ /usr/bin/crawl-0.28 --version

Crawl version 0.28.0
Save file version 34.239
Compiled with GCC 11.3.0
Build platform:
Platform:
CFLAGS: -O2 -march=native -pipe -DUSE_TILE -DUSE_TILE_LOCAL -DUSE_SDL -DUSE_GL -DUSE_FT -D_REENTRANT -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wno-format-zero-length -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua5.1 -isystem /usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -isystem /usr/include/SDL2 -DWIZARD -DASSERTS -DPROPORTIONAL_FONT="/usr/share/fonts/dejavu/DejaVuSans.ttf" -DMONOSPACED_FONT="/usr/share/fonts/dejavu/DejaVuSansMono.ttf" -D_REENTRANT -DCLUA_BINDINGS -DSAVE_DIR_PATH="~/.crawl-0.28" -DDATA_DIR_PATH="/usr/share/stone-soup-0.28/"
LDFLAGS: -Wl,-O1 -Wl,--as-needed

Thanks, by the way, to whomever designed the verbose mode to dump the relevant information. 

**DESCRIPTION:**

Oddity after recent upgrade: The 'a' key changed from showing abilities (including ones provided by religion) to group attack (i.e., "What are your orders). This leaves no way to access god-provided abilities. 

'A' is still innate abillities &c, ^A is still autopickup; only 'a' changed. 

Using ?? to get the list of commands, 'a' is still listed as "use special ability", 'a!' doesn't give the ability help it targes myself. 

Looks like a typo in a config (or *.h)?

**EXTRA FILES:**

**Comment by lembark** [comment]
Q: Where are they key assignments made, in a *.h or a config file?

**Comment by TheloTheGreat** [comment]
> Q: Where are they key assignments made, in a *.h or a config file?

As a user, you can put key rebinds in the config file settings/init.txt , and check what the default keybinds are in docs/keybind.txt  . I've used this myself today to work around another recent keybind bug...

**Comment by rawlins** [comment]
I think most likely you have an accidental macro or keybind for this key, `a` has not changed (and the internal bindings would show the change in help). You can check and clear them via the ctrl-d menu.

**Comment by robertxgray** [comment]
I think this issue can be closed. Please feel free to reopen if you need further support.
