### ISSUE TITLE
Frozen Ramparts Visual Bug When Cast Next to a Transparent Wall

### ISSUE THREAD

**Issue by SubtlePants** [crawl/crawl#2609]
**PLATFORM and OS or BROWSER:**
 webtiles, google chrome

**DCSS VERSION AND GAME INFORMATION:**
 0.29-a0-834-g1e95ca9

**DESCRIPTION:**
When casting frozen ramparts in a one tile wide corridor with a "window" into another one tile wide corridor, webtiles seems to indicate that the tiles in the adjacent corridor have been affected by frozen ramparts. However, monsters in those tiles are unaffected and do not take damage.

This seems like a visual bug since I think the fact that the spell does not apply to monsters on the other side of a wall makes sense?

**EXTRA FILES:**
<img width="480" alt="Frozen_Ramparts_Visual_Bug" src="https://user-images.githubusercontent.com/5874376/178560934-2bc45a52-906f-4567-943c-fa00071c87c3.png">

My apologies, I did not get a copy of the save file when the bug happened. I have seen this bug in a couple of other similar situations as well

**Comment by PleasingFungus** [comment]
I've fixed this. Thanks for reporting! :)
