### ISSUE TITLE
Wereblood spell description is misleading

### ISSUE THREAD

**Issue by buh-optm** [crawl/crawl#2617]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-845-g6161e89988

**DESCRIPTION:**
Butterflies do not trigger the beneficial effects of the spell.

**Comment by PleasingFungus** [comment]
Butterflies are not your enemies.

**Comment by buh-optm** [comment]
Pikel's lemur band also does not trigger the beneficial effects of the spell.
