### ISSUE TITLE
Can't use abyss exit

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#2618]
**PLATFORM and OS or BROWSER:**
Webtiles, edge

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-866-g0545e20025

**DESCRIPTION:**
- With the abyssal rune, I got the message '_The substance of the Abyss twists violently, and a gateway leading out appears!'
- The tile has 'A gateway leading out of the Abyss, summoned.' on it.
- When I try to exit, I get 'you can't go up here' or 'you can't go down here'. These (failed) actions take a turn

**EXTRA FILES:**
Backup: http://crawl.kelbi.org/saves/CarefulOdds-crawl-git-0545e20025-220716-2102.tar.bz2

**Comment by PleasingFungus** [comment]
Hopefully maybe fixed, thanks!
