### ISSUE TITLE
AltGr keybindings not working in latin american keyboard layout

### ISSUE THREAD

**Issue by KurzedMetal** [crawl/crawl#2623]
**PLATFORM and OS or BROWSER:**
Windows 10 Tiles

**DCSS VERSION AND GAME INFORMATION:**
crawl_tiles-0.29-a0-838-g385bb11a5b

**DESCRIPTION:**
I noticed that a few default keybindings are not working in my latin american layout keyboard.
Just in case, I tried using an empty config file and didn't solve it.

* "show item knowledge" which is <kbd>\\</kbd> aka <kbd>AltGr</kbd> + <kbd>'</kbd> **is not working**
* "display character status" which is <kbd>@</kbd> aka <kbd>AltGr</kbd> + <kbd>q</kbd> **is not working**
* "show religion screen" which is <kbd>^</kbd> aka <kbd>AltGr</kbd> + <kbd>ñ</kbd> **DOES WORK**, but I have to press <kbd>AltGr</kbd> + <kbd>ñ</kbd> + <kbd>Space</kbd>, or I don't see the screen. I think it's because this key is behaving like an accent and it's expecting a letter to add the `^` on top: like `â`. This keybinding has always worked like this, I don't mind too much, but I wanted to mention its current behavior just in case.

<kbd>\\</kbd> and <kbd>@</kbd> were 100% working in either 0.26 and 0.27 (I took a break since then, can't remember exactly which version), so the bug was probably introduced in some refactor / overhaul.

**Comment by TheloTheGreat** [comment]
I have the same problem with my Canadian French layout keyboard, the \ "show item knowledge", @ "display character status", and } "show runes" keys stopped working (Windows tiles build).

These keys are all AltGr+key characters, reference: https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/KB_Canadian_French_text.svg/800px-KB_Canadian_French_text.svg.png

crawl_tiles-0.28-a0-1236: Works fine
crawl_tiles-0.29-a0-648: Does not work

**Comment by TheloTheGreat** [comment]
Maybe related to this commit, which messed with modifier keys and fits the timeline?
https://github.com/crawl/crawl/commit/cf85d113b3eab75315230add0f9505f8eb5e3737

**Comment by TheloTheGreat** [comment]
Note that pressing the AltGr key is, behind the scenes, exactly equivalent to pressing the Ctrl key and the left Alt key. In other words, AltGr+2 is really Ctrl-Alt-2.

**Comment by Goratrix** [comment]
I just tested it with latest build 0.29-a0-1016-g236c7fd91e on Windows 10 tiles on Slovak keyboard layout (which has @ on AltGr+V and \ on AltGr+Q) and can confirm it is working fine now.

**Comment by rawlins** [comment]
Great, thanks @Goratrix!

**Comment by TheloTheGreat** [comment]
Yep, fix confirmed as of today's build, 0.29-a0-1019-g84f7d21838, thanks.

**Comment by KurzedMetal** [comment]
Works for me too, thanks for the fix!
