### ISSUE TITLE
Offline trunk (tiles and ascii) crashes when selecting certain combos

### ISSUE THREAD

**Issue by YakkingAway** [crawl/crawl#2634]
**PLATFORM and OS or BROWSER:**

Windows 10

**DCSS VERSION AND GAME INFORMATION:**

0.29-a0-923-g6e406bff71

**DESCRIPTION:**

Selecting Palentonga Fighter or Troll Fighter causes a crash to desktop (honestly I couldn't be bothered to test how many other combos were affected) Bug has been reproduced by other players.

**Comment by Goratrix** [comment]
Can confirm the crash happens in windows offline tiles current trunk with Palentonga, Troll and Ghoul Fighter. I have tested all species with Fighter, and only these 3 crash, others are fine. Randomly testing a bunch of other combos, didn't run into any other that would crash.

**Comment by PleasingFungus** [comment]
Can't repro on OS X, don't see any obviously relevant recent commits. Think someone needs to bisect this and find the first build in which the crash appears.

**Comment by Goratrix** [comment]
Crash was added in between these two builds 121 doesn't crash, 187 does:
![image](https://user-images.githubusercontent.com/54112839/181811648-7288d465-6c72-4812-964f-2dffc7243e19.png)
I think that was all the different stuff merged right after tournament...

**Comment by PleasingFungus** [comment]
Sorry for the trouble! Fixed now.
