### ISSUE TITLE
Various issues with new menus in local tiles (windows)

### ISSUE THREAD

**Issue by Goratrix** [crawl/crawl#2640]
I have tested both of these with version 0.29-a0-973-gac7da5f7f0 (new menus) and a0-925-g0a7a3d12f8 (old menus) in windows local tiles.

1. The first issue affects the inventory menu (i) and search menu (ctrl+f), maybe also other item-containing menus? The width of the menus is larger, without any apparent reason.

Inventory menu in old menu system:
![old-menu](https://user-images.githubusercontent.com/54112839/182020113-4182fb40-6a98-461f-bc54-20fcc7230615.png)

The same menu in new menu system:
![new-menu](https://user-images.githubusercontent.com/54112839/182020132-534c4d50-0119-49c3-a113-2cffdd12fa1f.png)

However, when you actually use the new menu and scroll to the last item in the menu, the whole menu suddenly redraws itself to the smaller size (except there is a larger margin at the bottom):
![new-menu_scrolled](https://user-images.githubusercontent.com/54112839/182020160-09460624-a4e8-4712-9152-aff3c1d94019.png)

2. Second issue: when using the search menu (ctrl+f), you can use _numpad enter_ to select an item and it gets shown on the map. However, when you then press numpad enter to travel to the item, that doesn't work. With standard (non-numpad) enter, both of these work fine.

**Comment by Goratrix** [comment]
Update: issue 2 is resolved with commit c1b7fc9

Regarding issue 1, I just realized that the menus are missing the bottom row with the key hints, that's what exlains the 'empty' margin at the bottom.

And the hint bar is only missing when the menu is not scrolling (i.e. when there are fewer items). When the menu contains enough items to have a scrollbar, the key hint bar does appear and also the menu size doesn't change anymore when you scroll to the bottom.

Example, ctrl+f menu with few items:
![image](https://user-images.githubusercontent.com/54112839/182181993-d063b304-db31-4205-a546-f969f11dc861.png)

Same ctrl+f menu with enough items to have a scrollbar:

![image](https://user-images.githubusercontent.com/54112839/182182164-27b2e360-4a60-47e2-b92a-294524deb1b6.png)

Inventory menu behaves the same.

**Comment by rawlins** [comment]
Thanks for the detailed reports! I didn't notice it before committing, but part 1 is fixed as a side effect of 0638b6a9f9a82127.
