### ISSUE TITLE
Orb Of Destruction goes in incorrect directions during sprint

### ISSUE THREAD

**Issue by vgatherps** [crawl/crawl#2641]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
Stone Soup 0.29-a0 (through 0.29-a0-875-g74bf5736c)

**DESCRIPTION:**
When casting an orb of destruction, the orb works initially but as the game goes on starts flying in a random direction. Death and respawn as felid briefly fixes the issue but the orb starts misfiring after. However, when adjacent/very close to a target, the orb usually hits the target on cast instead of flying somewhere random.

Edit:

Experimented a little bit more - the orb seems to want to go northwestish no matter what, so if the target is northwest it aims right and otherwise flies into the northwest. Enemies occasionally sort of go off on northwest detours as well

**EXTRA [FILES:**]
I can't get ssh to work into the server I'm playing on (webzook), so not sure how to otherwise get a save file link. Here's a screenshot of what happens when I fire (the target is on the right side of the screen):

<img width="770" alt="Screenshot 2022-07-31 at 7 51 32 PM" src="https://user-images.githubusercontent.com/39539071/182025454-2dacc4d9-5006-4b73-bd93-acfaf21fb8ce.png">

**Comment by rawlins** [comment]
I have not so far been able to replicate this locally. (Map in the screenshot is from pitsprint.)

**Comment by vgatherps** [comment]
This doesn't happen anymore in newer versions, closing
