### ISSUE TITLE
"explore_greedy" option doesn't consider items known on minimap (e.g. from "Strong nose")

### ISSUE THREAD

**Issue by jfcaron3** [crawl/crawl#2642]
**PLATFORM and OS or BROWSER: webtiles**

**DCSS VERSION AND GAME INFORMATION: 0.29-a0-982-gaed3a0c8d8**

**DESCRIPTION:**
For gnolls, with the "Strong nose" innate mutation, items sniffed that show up on the minimap are not considered when using the "explore_greedy" rcfile option.  This leads to unintuitive autoexploration where you will walk very close to a known item (say behind a door) to continue exploring, instead of going to find it.  I think "explore_greedy" should consider items known only from the minimap, for gnolls or other ways of detecting items (e.g. Xom effects, I think some Jivya mutations do it?).

**Comment by rawlins** [comment]
This is perhaps not an unreasonable feature request, but given how far it is from dcss' autoexplore implementation, I'm closing it as out of scope for a github issue. (We try to keep FRs to a minimum here.) PRs welcome, but I can say that this would require a complete rewrite of autoexplore.
