### ISSUE TITLE
The infinity symbol (∞) causes a minor layout issue in the Character Overview (%) page

### ISSUE THREAD

**Issue by DevJac** [crawl/crawl#2643]
The infinity symbol (∞) in the Character Overview screen (%) seems to cause the remainder of the line to shift one character to the right. This appears to be a small layout issue. I'm new to the game and found this issue while playing a Gargoyle Berserker which has immunity which I believe is the source of the infinity symbol. Screenshots of Character Overview and game version follow. This is the macOS game client, tiles version, game version 0.28. I have not modified the init files or any other options, it's just a default install.

Platform / Version: macOS Tiles 0.28

![Screen Shot 2022-08-02 at 12 27 43 PM](https://user-images.githubusercontent.com/5282489/182450053-ac78fd5a-6fb8-4288-89af-8b2bb8495c8e.jpg)
![Screen Shot 2022-08-02 at 12 31 30 PM](https://user-images.githubusercontent.com/5282489/182450047-af1cdabc-2edb-43eb-a212-582479938cb8.jpg)

**Comment by rawlins** [comment]
Thanks for the report! This is fixed in current trunk, though I'm not entirely sure what fixed it (but I have replicated the bug in 0.28 and verified that it is no longer present).
