### ISSUE TITLE
Repeated Ghosts in Zigs (when doing multiple zigs)

### ISSUE THREAD

**Issue by RMGiroux** [crawl/crawl#2647]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-1023-g6ae1a4a2c7

**DESCRIPTION:**
When doing multiple ziggurats in the same game, the same ghosts get reused. 

e.g.
  The ghost of Fepho the Acrobat, a legendary OpEE of Vehumet (Zig:20)
  The ghost of Fepho the Acrobat, a legendary OpEE of Vehumet (Zig:22)
  The ghost of Fepho the Acrobat, a legendary OpEE of Vehumet (Zig:22)
...
  The ghost of Taph the Archmage, a legendary GrCj of Vehumet (Zig:20)
  The ghost of Taph the Archmage, a legendary GrCj of Vehumet (Zig:22)

**EXTRA FILES:**
https://crawl.kelbi.org/crawl/morgue/SlowGraham/morgue-SlowGraham-20220811-112425.txt

**Comment by RMGiroux** [comment]
Note that we (the player on that game, another friend, and myself) aren't sure this is a bug, but since it's odd, I thought this should be entered just in case this is unintended.

It's definitely not something that should block the release unless it's a symptom of a serious underlying issue - I haven't looked at the ghost selection code to check.

**Comment by ebering** [comment]
The Ghost population for Zigs comes from a rather small pool; once the mega zig requires enough ghosts it starts re-using them. Not a bug, but thanks for checking.

**Comment by RMGiroux** [comment]
Thanks, fair enough!
