### ISSUE TITLE
Wu Jian Extra tab text cuts off on webtiles

### ISSUE THREAD

**Issue by strategineer** [crawl/crawl#2648]
**PLATFORM and OS or BROWSER:**
webtiles
Latest version of Firefox on Windows 10

**DCSS VERSION AND GAME INFORMATION:**
server: https://crawl.kelbi.org/
version: 0.29-a0-1027-gcd8c55af63 
username: strategineer
morgue (if relevant): https://crawl.kelbi.org/crawl/morgue/strategineer/morgue-strategineer-20220812-021924.txt

**DESCRIPTION:**
1. Worshipped at a faded altar.
2. It was Wu Jian (who I'm not very familiar with).
3. Opened the religion window and tabbed over to the extra tab (which I've never seen before).
4. I noticed that the text at the bottom of the page was cutting off.

this looked like this:
![cd8c55a_kelbi_web_tiles](https://user-images.githubusercontent.com/2420411/184347811-3555db03-324a-4743-b4dd-81d6db7dad24.png)

**EXTRA FILES:**
I tried reproducing this error by compiling the code and running the tiles version of the game locally but sadly I could not.

It looked like this:
![cd8c55a_tiles](https://user-images.githubusercontent.com/2420411/184348042-5c69755a-7576-469d-acc3-c677b96e9247.png)

**Comment by PleasingFungus** [comment]
@rawlins you might have more context on whatever's going on here wrt menu code, formatting, etc?
