### ISSUE TITLE
A confirmation dialog asks if I want to fizzle when canceling a view character

### ISSUE THREAD

**Issue by DevJac** [crawl/crawl#2649]
Platform: Tiles, Web Version 0.29-a0-1027-gcd8c55af63

I've gotten into the habit of abusing the evoke command (v) by pressing v v to quickly view the character I'm about to attack, but doing this asks me "Are you sure you want to fizzle?" for some reasons. I'm guessing this is a bug? I don't see any reason to have a confirmation dialog when exiting this screen. Below are screenshots and a quick workflow:

While playing the game and fighting a monster:

While fighting a monster:
![Screen Shot 2022-08-12 at 6 05 44 AM](https://user-images.githubusercontent.com/5282489/184352214-daf15b14-13a1-4915-b0e9-b6dc332b09c8.jpg)

Press v:
![Screen Shot 2022-08-12 at 6 05 56 AM](https://user-images.githubusercontent.com/5282489/184352268-1c736658-6515-414e-a6c6-2c6efd1a750c.jpg)

Press v again:
![Screen Shot 2022-08-12 at 6 06 16 AM](https://user-images.githubusercontent.com/5282489/184352296-4ee080ba-cbca-41a3-baff-be0cfb948f88.jpg)

Press escape and observe the confirmation dialog:
![Screen Shot 2022-08-12 at 6 06 28 AM](https://user-images.githubusercontent.com/5282489/184352313-726c2b85-7d57-4902-b077-7f2c4ae2fae6.jpg)

**Comment by PleasingFungus** [comment]
Nice find! Should be fixed now, thanks :)
