### ISSUE TITLE
Banned account names list? Racism on server

### ISSUE THREAD

**Issue by Setanta22** [crawl/crawl#2651]
Hi,

I was wondering if there is a list of banned account names an if so, it may need to be updated. I play on Xtahua server and there is currently a player with the account name N*ggerDarts2 which is obviously very offensive and racist. When I click on the name to view the scoring page it actually returns a 404 so I presume the name has been deleted from the scoring site (http://crawl.akrasiac.org/scoring/) but they still seem to be in the server playing games and viewing others play. I joined one of their games and they asked do I know any good N word jokes and that they wanted to type them before they ascended in the game. 

Would someone be able to look into this? Crawl is too great a community for this kind of crap to be going on. Thanks

**Comment by semitonal** [comment]
Hi, thanks for reporting - we've alerted the admin of that server and are working on getting a fix implemented to prevent new accounts being registered with similarly offensive names (I believe this has already been handled on most of the other servers, just not on CXC yet).

**Comment by semitonal** [comment]
I believe this should be resolved now, and there's measures in place to stop new accounts with those names being registered on CXC (but please do let us know if it happens again in future).
