### ISSUE TITLE
Neo layout broken on MacOS

### ISSUE THREAD

**Issue by loewenheim** [crawl/crawl#2652]
**PLATFORM and OS or BROWSER:**
Local tiles, MacOS

**DCSS VERSION AND GAME INFORMATION:**
The problem affects every build following commit dbb8aaeb5fe9d61eff7c9b39bdba3db7a25e3fbc.

**DESCRIPTION:**
I'm using the [Neo keyboard layout](neo-layout.org) on MacOS. It includes a simulated numpad on the `UIO/JKL/M,.` keys, accessed via a modifier key. The layer containing the fake numpad is implemented via Karabiner Elements on MacOS, the rule in question being "Neo2 mod 3 key and layer 4 (Apple keyboards). Rule applied to Apple-made keyboards only." in [this list](https://ke-complex-modifications.pqrs.org/#neo2). Ever since dbb8aaeb5fe9d61eff7c9b39bdba3db7a25e3fbc the inputs are suppressed and only executed when another key (like return) is pressed. For now I've fixed this locally by just reverting the commit in question.

**EXTRA FILES:**
N/A

**Comment by rawlins** [comment]
Just to check, have you tried a version since 8251ee3229 (which fixes a similar issue with regular numpad)? Also, the "Neo keyboard layout" link is broken.

**Comment by loewenheim** [comment]
That commit does indeed seem to fix it. I hadn't downloaded a new version in a while since I'm travelling. Thank you very much for pointing me in the right direction!
