### ISSUE TITLE
Only two types of scrolls are ever generated in trunk

### ISSUE THREAD

**Issue by raymond-holmboe** [crawl/crawl#2653]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-875-g74bf5736c

**DESCRIPTION:**
I have started a new character three times, two of those the only scrolls that dropped were scrolls of fog and scrolls of acquirement. The third time it dropped scrolls of fog and scrolls of enchant weapon.
No other scrolls are dropped.

**Comment by raymond-holmboe** [comment]
Cannot repo anymore

**Comment by rawlins** [comment]
I believe this was fixed by 489732b8f08
