### ISSUE TITLE
This artifact has Wiz, but doesn't explain what that means

### ISSUE THREAD

**Issue by DevJac** [crawl/crawl#2664]
![Screen Shot 2022-08-17 at 9 06 49 AM](https://user-images.githubusercontent.com/5282489/185176435-b8ee3343-1fd7-4448-9c25-58a15363d1ea.jpg)

This artefact has Wiz but the description doesn't explain what "Wiz" is.

This is on the web version of the game, with tiles, trunk:
```
Dungeon Crawl Stone Soup 0.29-a0-1052-g6990b1bffc

Features
--------
 * Lua user scripts
 * Web Tile support
 * Wizard mode
 * PCRE regexps
 * Milestones

Stone Soup 0.29-a0 (through 0.29-a0-1033-gb6c65ffae6)
```

**Comment by Goratrix** [comment]
It does explain it: "It improves your spell success rate."

The problem is that the description is not prefixed with "Wiz:". Looks like the reason is that Wiz doesn't actually exist as an artefact property (listed in artefact_prop_type), so the description is formatted in the 'old' way, as all the descriptions were before 60794d8.

**Comment by DevJac** [comment]
I see. Thanks for your response. I'll leave it to your discretion whether or not to close this ticket or change artifact display.

**Comment by Gopall** [comment]
> It does explain it: "It improves your spell success rate."
> 
> The problem is that the description is not prefixed with "Wiz:". Looks like the reason is that Wiz doesn't actually exist as an artefact property (listed in artefact_prop_type), so the description is formatted in the 'old' way, as all the descriptions were before [60794d8](https://github.com/crawl/crawl/commit/60794d8430dbf9915b8c2b130df2aabe46a0f5e9).

I assume this is because Ring of Wizardry is the base item for the artifact in this case.
