### ISSUE TITLE
The option `autopickup = }` does not include tins of tremorstones

### ISSUE THREAD

**Issue by DevJac** [crawl/crawl#2671]
![Screen Shot 2022-08-18 at 10 54 08 AM](https://user-images.githubusercontent.com/5282489/185453070-83310630-3625-4824-8f34-385889d9dee1.jpg)

![Screen Shot 2022-08-18 at 10 53 33 AM](https://user-images.githubusercontent.com/5282489/185453067-ddb47ee6-e773-48dd-879b-ef504625840b.jpg)

I have the `autopickup = }` option set, because I want to autopickup all misc items. This mostly works, but tins of tremorstones are not included in the autopickup. I suspect a there is a tag missing from tremorstones or something?

Whatever the case, if I have `autopickup = }` set, then I would expect to autopickup all misc items, including tremorstones.

I'm aware I can manually adjust the autopickup settings in game, but I would like to adjust the defaults in my RC file.

Web tiles version, trunk, in-game version info is as follows:
```
Dungeon Crawl Stone Soup 0.29-a0-1065-g47a6bb87d6

Features
--------
 * Lua user scripts
 * Web Tile support
 * Wizard mode
 * PCRE regexps
 * Milestones

Stone Soup 0.29-a0 (through 0.29-a0-1033-gb6c65ffae6)
```

**Comment by jfcaron3** [comment]
I've tried to work around this with "autopickup_exceptions += <tins of tremorstones" in my rcfile but it also doesn't end up autopickingup tremorstones.

**Comment by ardl** [comment]
doing `autopickup_exceptions ^= <tin of tremorstones` should work for now

**Comment by wheals** [comment]
Arguably this was never a bug, but at any rate it no longer happens since 7ef6b13b4ffd54d657
