### ISSUE TITLE
0.29 tag announcement

### ISSUE THREAD

**Issue by rawlins** [crawl/crawl#2674]
@crawl/serveradmins The `stone_soup-0.29` branch exists, so it can be installed at any time -- tournament begins Aug 26, and the release is  upcoming in the next few days. No really major changes to webtiles, but a server restart is recommended in order to get some bugfixes that won't happen otherwise.

Here's an overview of the main webtiles changes in the 0.29 development cycle.

* Community management changes:
    - new account logging is clearer, and more easily extracted from the overall log
    - new config option `nick_check_fun` that, if defined, takes a nickname and returns a boolean to indicate whether it is (dis)allowed. This supplements an existing regex-based check.
    - new user "account hold" mode. An account in this state can play, but doesn't appear in the lobby, can't chat, can't spectate while logged in, and can't generate ghosts. This currently can be set via the `wtutil.py` command line utility (similar to bans).
    - new config option `new_accounts_disabled` that entirely disables new account creation while set.
    - new config option `new_accounts_hold` that puts all new accounts into account hold mode. Also, for use with this option, `wtutil.py` has a clo that will clear all held accounts at once.
* New option `hup_reloads_config` that if set to true, will reload the config settings and all game modes on a SIGHUP. (This defaults to false for legacy issues, but I'm pretty sure it should be safe to enable for most servers; check your init.d scripts to make sure they are not using SIGHUP to shut down the server.)
* If you encounter game definition errors on restarting, you may need to ensure that you are setting `use_game_yaml = False` and/or `games_config_dir = None`. (This is a relatively old issue, so I suspect that most servers will already have one or the other set.)

Also worth noting: I've been threatening python2 deprecation for some time, and I've finally managed to shoehorn python 3 onto CAO. So assuming this works well, this time is finally coming for real. It should overall be pretty painless: just a matter of making sure an up-to-date tornado/pyyaml version is installed (e.g. `pip3 install tornado pyyaml`), making sure the python lib is installed correctly in the chroot, and tweaking init.d scripts to call py3.

**Comment by rawlins** [comment]
> new account logging is clearer, and more easily extracted from the overall log

Re this point, here's a handy one line script I'm using on CAO and CBR2 to provide persistent new account logging, in case anyone else wants to use it:

```
#!/bin/sh
tail -Fs 1 webtiles.log 2>&1 | grep --line-buffered Registered >> newaccounts.log
```

**Comment by alexjurkiewicz** [comment]
Wow, python 3! Nice one, exciting times for development

**Comment by rawlins** [comment]
The 0.29.0 release now exists!

I would recommend that admins consider restarting webtiles once before the tournament in order to get 5d08c370806fe; I'm still not entirely clear on the exact preconditions to trigger this or whether it has been happening on servers other than CAO (it may be that only CAO is slow enough to get easily backlogged with key input) but, if this bug is happening at all, it will be noticeable to users.

**Comment by rawlins** [comment]
Anyone still running py27 who has restarted their server in the last couple of days should probably make sure to get 743cabc6810231b961 and restart again. (Please update! But you really don't want the bug that commit fixes if you haven't yet..)

Also, https://github.com/crawl/crawl/blob/master/crawl-ref/source/webserver/CHANGELOG.md is the new in-repo place for the kind of information I've been putting in tag announcement issues. (I will still open them in the future, but just lean on the changelog more.)
