### ISSUE TITLE
Poison clouds are inconsistent for Grey Dr and dform grey dr

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2678]
**PLATFORM and OS or BROWSER:**
local tiles
![image](https://user-images.githubusercontent.com/70080435/185809193-2c41b23e-cf97-4ee7-b5d3-2d0eff6b48ba.png)

**DESCRIPTION:**
Grey drac can be poisoned by poisonous clouds, but if you cast dform as a grey drac you dont get poisoned by poison clouds

![image](https://user-images.githubusercontent.com/70080435/185809238-88e86909-2b0c-4f0e-9ffb-9618e59d6b44.png)
![image](https://user-images.githubusercontent.com/70080435/185809250-983728de-871f-410c-9c0c-b69f403c014d.png)

**Comment by ardl** [comment]
I think its related to these commits 9b0c66ea95681a196b8765dfa3fd3fb05007e06f a3e552604e076939ad7e5bce0a1361ac1509dd26 and b657c59d09c5a876df25bc32c9d76db94899c321

**Comment by semitonal** [comment]
This is working as intended - dragon form always grants rPois.
