### ISSUE TITLE
Webtiles crash

### ISSUE THREAD

**Issue by pisastrish** [crawl/crawl#2679]
**PLATFORM and OS or BROWSER:**
Webtiles, firefox 103.0.2, windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-4-ga7cffc9

**DESCRIPTION:**
Game froze and then exited to main menu, saying “unfortunately your game ended unexpectedly.” Happened twice (same game, playing GrCj^Usk), once in dungeon while browsing a shop, once in lair during a fight. No data was lost

**EXTRA FILES:**
 http://crawl.akrasiac.org/saves/pisaster-crawl-git-a7cffc901d-220821-1619.tar.bz2

**Comment by pisastrish** [comment]
This just happened again in a different game
 http://crawl.akrasiac.org/saves/pisaster-crawl-git-7c9e10e132-220822-2051.tar.bz2

This is the first time it's happened since I posted the issue; this time I got the save backup immediately after it crashed, so whatever happened last could be the issue

**Comment by pisastrish** [comment]
(Let me know if additional reports aren't useful)
Happened once more, in a third game.
http://crawl.akrasiac.org/saves/pisaster-crawl-git-4cc3fdd212-220823-1540.tar.bz2

This time I think only a few turns worth of data were lost

**Comment by rawlins** [comment]
Thanks for the reports; these crashes aren't about anything happening in the specific games, but rather, an issue on the server. We're still working on debugging.

**Comment by rawlins** [comment]
>  these crashes aren't about anything happening in the specific games

Well, I said that, but do you know if there is anything in particular you were doing in these games around when it froze? I can replicate this by holding down keys under certain circumstances, e.g. with a ranged weapon + slow animation, but I'm not sure that is applicable to this character.

**Comment by pisastrish** [comment]
I never hold down keys, but when the game is laggy I often spam escape (or rapidly alternate it with another key like p) to make sure I’m not queuing actions that will kill me. I think that’s the only thing all of these had in common

**Comment by pisastrish** [comment]
There have been a couple times now where it has frozen like it was about to crash, but switching to a different tab and back immediately unfroze it

**Comment by rawlins** [comment]
I'm pretty sure I fixed these crashes via 5d08c370806fe, hasn't happened since I activated that on CAO (there may still be other slowdowns happening for different reasons of course, but shouldn't be anything nearly so bad).
