### ISSUE TITLE
Rift reach is inconsistent (3 tiles or 1 tile)

### ISSUE THREAD

**Issue by johndannuz** [crawl/crawl#2683]
**PLATFORM and OS or BROWSER:**
webtiles (akraisiac)

**DCSS VERSION AND GAME INFORMATION:**
trunk (8/22/2022)

**DESCRIPTION:**
While playing gnoll chaos knight, using a demon trident (distort + reach) gifted by Xom, I noticed that I was hitting 3 tiles away. Then, after going to a new level and killing a horde of enemies, when I hit [Tab] it would only return "Okay, then" and not attack unless the enemy was right next to me. 

I then tried using v to target. First, I had to unbind all macros (since v was bound to cast ensorcelled hibernation), but then it would only target the squares next to me instead of 2 or 3 tiles away.

Then I got next to an enemy and tab-killed it, and suddenly was reaching 3 tiles again!

I saved out at that point in case you wanted to see it. I saved it below:

**EXTRA FILES:**
http://crawl.akrasiac.org/saves/VAMPKILLER-crawl-git-7c9e10e132-220822-2227.tar.bz2

Crawl is the greatest and you all rock for keeping it alive and interesting!
jdnz/VAMPKILLER/MINOKILLER

**Comment by rawlins** [comment]
This report looks to be specifically about the Rift unrand (which I notice is labeled somewhat poorly in the hud).

**Comment by johndannuz** [comment]
Noting that the other time I saw the reach go down to 1 was when Xom decided to give me cleave. It resumed reaching 3 tiles once cleave expire. I'm not sure if I had cleave for the initial report (I didn't notice it if I did).

Either way, it seems that Tab autoattack returning "Okay, then" when cleaving with Rift/reach weapon would still be behavior to be potentially looked at. Will monitor and report anything else I see with this weapon. :)

**Comment by johndannuz** [comment]
I am pretty sure that this occurs when you have Rift, and Xom gives you Cleave. Cleave doesn't allow reaching anymore, and when you hit Tab, it just says "Okay, Then." instead of moving towards a target. If you hit v, it gives you an option to use your trident to reach towards a target, but your range is only 1 so you can't actually reach.

![example](https://user-images.githubusercontent.com/111829003/188773436-e7997143-1b13-40f9-8aa0-42d8bbc91208.png)
