### ISSUE TITLE
Attack of Opportunity Bypassed Sanctuary

### ISSUE THREAD

**Issue by tarsierscripter** [crawl/crawl#2685]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29

**DESCRIPTION:**
I took a step away from Nessos inside of Zin's sanctuary. Nessos launched an attack of opportunity and hit me, despite being under the protection of the sanctuary.

**EXTRA FILES:**
https://cbro.berotato.org/morgue/ChongLi/ChongLi.txt

I couldn't include a save file because CBRO doesn't have the console menu for 0.29.

**Comment by PleasingFungus** [comment]
Fixed, thanks! :)
