### ISSUE TITLE
poor code quality

### ISSUE THREAD

**Issue by gravestench** [crawl/crawl#2686]
i've been playing this game for over a decade, and i'm super sad to finally clone the source and see it in such a miserly state.

* +3K lines of code in `~/crawl-ref/source/main.cc`, with tons of references to shit that isn't related to high-level behaviors of the game
* `~/crawl-ref/source` is a Kafkaesque god-directory with 700+ files inside of it
* lack of `README`'s throughout all subdirectories, including `~/crawl-ref/source` which is arguably the most important subdirectory in the project. Every subdir deserves a detailed description for newcomers. I immediately asked myself **what the fuck _is_ all of this shit and _why is it here_?** and I am not the first person to do so. The `docs` subdir has lots of shit which should be moved elsewhere
* super inconsistent about what is or isn't commented throughout codebase
* +100 comments throughout codebase with the following form: `// FIXME:: Foo Bar Baz Qux`. Of the ones i checked, none have issues filed(!)
* hardcoded locale strings throughout

All of this just reeks of a codebase that is so fragile that nobody dares refactor any of it.

**Comment by rawlins** [comment]
I'm going to close this as not specifically actionable, github issues are not a good place for general rants (if it can't fit into the bug reporting template, it's not a great candidate for an issue here).

Refactoring and documentation PRs are welcome! However, please in the future be polite, constructive, and specific when interacting with this repo or team members.

**Comment by gravestench** [comment]
Me being blunt doesn't delegitimatize these issues. Sweeping this under the rug is a huge disservice to the project.

Proposed solutions:
* Break up the `main.cc` file, leave only high-level functionality. It should be pretty simple:
  - parse cli flags
  - load any config stuff
  - kick off game loop
* Create more subdirectories under `~/crawl-ref/source`:
  - `~/crawl-ref/source/branch`
  - `~/crawl-ref/source/debug`
  - `~/crawl-ref/source/describe`
  - `~/crawl-ref/source/dungeon`
  - `~/crawl-ref/source/god`
  - `~/crawl-ref/source/item`
  - `~/crawl-ref/source/player`
  - etc
* Put a readme in every directory and subdirectory
  - main `README.md` of each subdir describes purpose of directory and files/subdirectories within
  - convert all `.txt` docs to `.md`
  - move high-level development docs into root of repo
    - `~/crawl-ref/docs/develop/contribution-process.md` -> `~/CONTRIBUTING.md`
    - `~/crawl-ref/docs/develop/coding_conventions.md` -> `~/CONVENTIONS.md`
  - migrate any information inside of `~/crawl-ref/docs/` to coherent places
    - `~/crawl-ref/docs/develop/god_creation.txt` -> `~/crawl-ref/source/god/god_creation.` **`md`**
* Enforce linting throughout project (perhaps as part of ci/cd), change `CONVENTIONS.md` to enforce descriptive comments on all public methods/fields, and any functions not starting with an underscore
* Add issues for all `TODO`, `FIXME`, `XXX` comments

**Comment by PleasingFungus** [comment]
![image](https://user-images.githubusercontent.com/1192475/186541942-b600408e-fe37-4669-ba30-ebb7f4ef70ef.png)

**Comment by damerell** [comment]
https://github.com/battlelinegames/nes-starter-kit/issues/4

**Comment by rawlins** [comment]
I'm locking, please use this issue tracker appropriately @gravestench, it's not for discussions. As before, PRs that *actually improve something* are welcome. Hint: nothing has been swept under the rug here, there's even [a twitter account](https://twitter.com/crawlcode?lang=en) -- but actually improving code quality in a large, old, volunteer project is not easy and requires action, not general/superficial suggestions. (Re PRs though, I will say that the only one of these suggestions where I would unreservedly accept a PR is the first, and several of these are actively terrible ideas.)
