### ISSUE TITLE
Game seed: 4524186747423876392 --> random death corridor on d3.  Lava generates behind water.  If you explore into the water as an aquatic species, steam clouds appear and will just kill low level characters in 1-2 moves.  Not enough time to TP, or in this case even make it to a spot where attempting a hop was possible.

### ISSUE THREAD

**Issue by TheMeInTeam** [crawl/crawl#2695]
Game seed: 4524186747423876392 --> random death corridor on d3

**PLATFORM and OS or BROWSER:**
Windows/Webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29 tournament game

**DESCRIPTION:**
 Lava generates behind water on D3.  If you explore into the water as an aquatic species, steam clouds appear and will just kill low level characters in 1-2 moves.  Not enough time to TP, or in this case even make it to a spot where attempting a hop was possible.

**EXTRA FILES:**

https://crawl.kelbi.org/crawl/morgue/TheMeInTeam/morgue-TheMeInTeam-20220828-001303.txt

**Comment by PleasingFungus** [comment]
Fixed in 42789b21ef9e48a40cd17e7d828221657b8fb7a1 . Thanks for reporting!
