### ISSUE TITLE
Trying to wear a randart from the floor when inventory full crashed the game (range check error (-1 / 52))

### ISSUE THREAD

**Issue by btonasse** [crawl/crawl#2699]
**PLATFORM and OS or BROWSER:**
Webtiles - Chrome  104.0.5112.102

**DCSS VERSION AND GAME INFORMATION:**
0.29 - unfortunately can't provide the morgue, since I have already won and the game is now showing in the list of completed games

**DESCRIPTION:**
Was somewhere in Snake Pit with a full inventory and tried wielding a randart boot from the floor (while already wearing boots). Then the game crashed with the message below:

<img width="280" alt="Capture" src="https://user-images.githubusercontent.com/33516406/188019390-cb330450-6977-48d3-a643-7d5ec882e0ec.PNG">

**Comment by PleasingFungus** [comment]
Fixed in [ec41be8ddcda17f86806e817bf377724c93b0da2](https://github.com/crawl/crawl/commit/ec41be8ddcda17f86806e817bf377724c93b0da2) . Thanks for reporting!
