### ISSUE TITLE
Culcivora message indicates 'healed somewhat' even when blocked x2.

### ISSUE THREAD

**Issue by johndannuz** [crawl/crawl#2703]
**PLATFORM and OS or BROWSER:**
webtiles - akraisiac

**DCSS VERSION AND GAME INFORMATION:**
trunk on 2 September 2022 (crawl v29)

**DESCRIPTION:**
In Spider's Nest, culcivora attacked me. It was blocked x2 with a buckler of protection, but still generated the message that it healed somewhat. In that situation, though, it did NOT generate the message that the culcivora draws strength from your injuries. It only generated the "draws strength" message when it actually hit me.

Possible bug message log:
You block the culcivora's attack. x2; the culcivora is healed somewhat.

Normal healing message log:
The culcivora bites you!
The culcivora draws strength from your injuries!
The culcivora is healed somewhat.

**EXTRA FILES:**

![bug](https://user-images.githubusercontent.com/111829003/188251003-f198a554-9b5e-43c5-b7a9-58dbf3b45182.png)

-->

**Comment by johndannuz** [comment]
Note: In image, highlighted text is the normal culcivora attack. Directly above it is the erroneous attack where the culcivora heal message played even though the culcivora did not hit me (x2).

**Comment by semitonal** [comment]
This was actually the culicivoras casting their Heal Other spell, but there was no cast message when that happened, so a different bug instead!
