### ISSUE TITLE
Bad mutation Devolution can give another Devolution

### ISSUE THREAD

**Issue by DevastatorOne** [crawl/crawl#2706]
**PLATFORM and OS or BROWSER:**
Webtiles, Google Chrome 105.0.5195.53

**DCSS VERSION AND GAME INFORMATION:**
0.29.0-11-gd7f09526c8
Xtahua server
https://crawl.xtahua.com/crawl/morgue/DevastatorOne/morgue-DevastatorOne-20220903-130943.txt

**DESCRIPTION:**
Bad mutation "Devolution" can give another "Devolution" when it ends. Check turn 83056 in morgue file

**Comment by semitonal** [comment]
This isn't a bug, just bad luck I'm afraid!
