### ISSUE TITLE
acquirement crash

### ISSUE THREAD

**Issue by mgdelmonte** [crawl/crawl#2714]
Version: Dungeon Crawl Stone Soup 0.30-a0-26-gdcabb77fc3
Platform: unix (OS X)
Bits: 64
Game mode: seeded
Tiles: yes

Seed: 3, deterministic pregen: 1

Read acquirement and got immediate crash.  Stack says 

```
Crash caused by signal #10: Bus error: 10

Obtained 16 stack frames.
0x0000000104477274: write_stack_trace(__sFILE*) + 224
0x0000000104480134: do_crash_dump() + 1360
0x0000000104476fc4: crash_signal_handler(int) + 192
0x00000001b00474a4: _sigtramp + 56
0x0000000104869b6c: player::could_wield(item_def const&, bool, bool, bool) const + 400
0x0000000104869b6c: player::could_wield(item_def const&, bool, bool, bool) const + 400
0x000000010462974c: is_useless_item(item_def const&, bool, bool) + 220
0x00000001043ebd50: acquirement_create_item(object_class_type, int, bool, coord_def const&) + 956
0x00000001043f0d48: _acquirement_item_def(object_class_type) + 124
0x00000001043ee54c: acquirement_menu() + 300
0x000000010461c668: read(item_def*, dist*) + 4684
0x0000000104ae79dc: process_command(command_type, command_type) + 832
0x0000000104aeeb60: _input() + 1696
0x0000000104aec8c0: _launch_game() + 2240
0x0000000104ae72a8: main + 1052
0x00000001054bd08c: start + 520
```

See attached crash report.

[crash-AutoGargoyle-20220907-220248.txt](https://github.com/crawl/crawl/files/9522996/crash-AutoGargoyle-20220907-220248.txt)

**Comment by robertxgray** [comment]
I probably suffered the same bug in the Android port today, but I didn't find any crash log confirm it. I lost some progress and the game didn't crash when I read the scroll again. Weird.

**Comment by Helyos96** [comment]
Happened to me as well on Android. Crashed again on second try. Uploading the save as .txt (fuxod.txt) because uploading the .cs file bugs out.

[Fuxod.txt](https://github.com/crawl/crawl/files/9896075/Fuxod.txt)
[crash-Fuxod-20221030-152524.txt](https://github.com/crawl/crawl/files/9896080/crash-Fuxod-20221030-152524.txt)
