### ISSUE TITLE
Local Tiles Rendering Issue

### ISSUE THREAD

**Issue by liammcd** [crawl/crawl#2724]
**PLATFORM and OS or BROWSER:**

Mac

**DCSS VERSION AND GAME INFORMATION:**

0.29-a0-1182-g744e84de5b

**DESCRIPTION:**

Many (all?) tiles are not rendering correctly - character creation screen, character, inventory, floor items, etc..

**EXTRA FILES:**
![Screen Shot 2022-09-12 at 12 50 13 PM](https://user-images.githubusercontent.com/11138182/189711877-a38c169d-5a72-4465-93b2-e43e8ea7606c.png)

![Screen Shot 2022-09-12 at 12 49 45 PM](https://user-images.githubusercontent.com/11138182/189711900-83d1c432-6455-459d-915b-a4e8a800220a.png)

**Comment by rawlins** [comment]
Did you build this yourself? If so, try just re-running the `make` command. There's a race condition that no one has managed to sort out in the build process that can lead to this effect. (If this works, this is probably the same issue as https://github.com/crawl/crawl/issues/2426).

**Comment by liammcd** [comment]
Thanks that was the issue, I'll close this as a duplicate of #2426
