### ISSUE TITLE
Outdated options documentation

### ISSUE THREAD

**Issue by Nufirdy** [crawl/crawl#2727]
**PLATFORM and OS or BROWSER:**
webtiles
Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)

**DCSS VERSION AND GAME INFORMATION:**
Game version 0.29.1 server CXC

**DESCRIPTION:**
Using option `pregen_dungeon = full` or `pregen_dungeon = true` causes 
`Options error: Bad pregen_dungeon value: full (should be classic, false or incremental) (~/.crawlrc:94)`
While [options docs](https://github.com/crawl/crawl/blob/a018f8e90fb9c78aa3785693854a9891290a5bdd/crawl-ref/docs/options_guide.txt#L442) lists these values for option as available

**Comment by semitonal** [comment]
This isn't an issue with the documentation - as noted in options_guide, online servers may disable full pregeneration.
