### ISSUE TITLE
Eringya's Noxious Bog makes Passage of Golubria portals permanent (until used)

### ISSUE THREAD

**Issue by tarsierscripter** [crawl/crawl#2728]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29

**DESCRIPTION:**
I cast Passage of Golubria but did not enter the portal. I then cast Eringya's Noxious Bog nearby so that the bog covered up the portal. I then continued to play and when I returned to the area hundreds of turns later the portal was still there. I then found I could cast Passage of Golubria again and return to this permanent portal. However, once I emerged from the portal it seems to have had its timer reset and closed on its own a few turns later.

I believe it only occurs if the portal is currently covered up by the bog at the time when it is supposed to close. Anyway, this could be used to set up a permanent portal in a safe corner of the map and give an extremely reliable escape option at the cost of some tedium.

**EXTRA FILES:**
Morgue standing near a permanent portal:
https://cbro.berotato.org/morgue/ChongLi/ChongLi.txt

Screenshot of same situation:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/156594/190038100-c194fb75-af38-4535-9a6c-16854aaca38f.png">

Save file from the same turn as the morgue above:
https://cbro.berotato.org//ChongLi-crawl-0.29-220914-0124.tar.bz2

**Comment by Monkooky** [comment]
Did some reproduction.
This occurs only if all PoG portals on the map get covered by bog. 
The timer for all portals is restarted when PoG is cast again.
