### ISSUE TITLE
The headmaster in Yara's Duelist Academy has an indefinite article before the name when they show up

### ISSUE THREAD

**Issue by Flugkiller** [crawl/crawl#2738]
**PLATFORM and OS or BROWSER:**
Local, Windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.29.1 stable

**DESCRIPTION:**
Loaded up a local game in wizmode, went into Yara's Duelist Academy, opened the door to the room with the headmaster, log says: "A naga mage and a Xathriw come into view."
Since the headmaster's name is a proper noun I figure this is not intentional.

**EXTRA FILES:**
Here's a screenshot.
![crawl_2022-09-20_00-24-39](https://user-images.githubusercontent.com/59402112/191130982-40412dda-d059-4c21-991a-bd9abb072d2a.png)

If there's something else that's necessary or something I can improve, just let me know.

**Comment by SamanthaTobias** [comment]
![image](https://user-images.githubusercontent.com/114337819/192150573-a25b6e15-555c-46aa-8da6-06ad4c4d549e.png)
i think this may be an issue for when these wizlab wizards come into view with multiple other monsters at the same time

i have not been able to replicate this for wizlab wizards which come into view on their own
