### ISSUE TITLE
Dream sheep attack type

### ISSUE THREAD

**Issue by T-Minutiae** [crawl/crawl#2740]
Version: Windows local tiles 0.30-a0-134-gb40fab5c76

AT_HEADBUTT would make infinitely more sense than AT_BITE. It is technically possible to get bitten by a sheep but due to the fact that they have no teeth in the front part of the upper jaw and the angle of their heads it would be an extremely awkward means of attack. They'd use their incredibly hard heads to smash you instead.

And yes, I am fully aware that this is a fantasy video game. With murderous sheep that can use PSI. But we have to draw the line _somewhere_.

**Comment by PleasingFungus** [comment]
Just to clarify, you're aware that AT_HEATBUTT does not exist?

**Comment by PleasingFungus** [comment]
Ah, I see you tried to add it in #2761. Did you compile the game to test? Your change won't work as written - you also need to update `mon_attack_name`. (And, as kd7uiy noted, you should make that change in a separate PR.)

Sorry for the belated response on this. :)
