### ISSUE TITLE
Damage rating formula is incorrect for Throwing and UC 

### ISSUE THREAD

**Issue by nploskey** [crawl/crawl#2748]
**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-140-gd1020e658a

**DESCRIPTION:**
The displayed damage rating (shown in item descriptions and in @) is calculated incorrectly for both throwing and unarmed combat, resulting in inflated numbers.  Currently, both the Fighting skill multiplier and weapon skill multiplier are rolled into one number for display (Skill), but throwing and unarmed combat should not be including a weapon skill multiplier.

Wizmoding a character with 27 in all skills and 30 strength results in these damage ratings:

Boomerang: 
`Damage rating: 110 (Base [6 + 27 (Thrw)] x 150% (Str) x 223% (Skill))`

Unarmed Combat: 
`Your damage rating with unarmed combat is about 100 (Base [3 + 27 (UC)] x 150% (Str) x 223% (Skill))`

**Comment by nploskey** [comment]
At 27 Fighting and 27 UC/Throwing, that `223% (Skill)` should only be `145% (Skill)` from Fighting, but you can tell that weapon skill is also being included.

Fighting multiplier: `1 + (27/2) / 30 = 1.45`
Non-UC/Throwing weapon skill multiplier: `1 + (27/2) / 25 = 1.54`
`1.45 * 1.54 = 2.233`

**Comment by PleasingFungus** [comment]
Great catch! What a silly oversight on my part.
