### ISSUE TITLE
Cursed items aren't marked as red in "bottom right" inventory

### ISSUE THREAD

**Issue by T-Minutiae** [crawl/crawl#2751]
Version: Windows local 0.30-a0-149-g7f746667c4

They are in the (i)nventory, however.

![Cursed Items](https://user-images.githubusercontent.com/114019424/192351730-12e950a2-ff21-4aeb-a140-b06951f37af9.jpg)

**Comment by DracoOmega** [comment]
Was fixed by 0f6f1dd4b9273ad70c2c0f737dad5444d255bb93
