### ISSUE TITLE
Is it possible to avoid Stair Camps when entering new level down?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [crawl/crawl#2755]
Is there some way where the level generator could prevent a large group (large compared to the level of the player) from occurring?  Too many times, there are a heap of monsters at the stairs, and it's often impossible to do anything about it, particularly early in the game.  (It just wastes time having to roll another attempt.)

**Comment by ebering** [comment]
You might claim that it is impossible to deal with these things but the double-digit streaks are evidence otherwise. These situations are part of the variance that gives crawl spice.

**Comment by Napoleon-BlownApart** [comment]
I can always go spend my time doing other things.

**Comment by Napoleon-BlownApart** [comment]
![Is this really random](https://user-images.githubusercontent.com/6958677/193760714-bfd5c702-24fb-46d6-9c8a-714ef303b5db.png)
How's this for random?

**Comment by Picklenugget1** [comment]
That's not really that random if you are talking about Yiuf.

**Comment by Napoleon-BlownApart** [comment]
Na, I was thinking about the hammers.  I understand Yiuf frequently shows up like that.

**Comment by Picklenugget1** [comment]
He always has his hammers. Part of his vault design

**Comment by Napoleon-BlownApart** [comment]
> He always has his hammers. Part of his vault design

No, he does not normally have that many hammers laying around in the area next to him.
