### ISSUE TITLE
Bad teleport in to a single square, no escape

### ISSUE THREAD

**Issue by kd7uiy** [crawl/crawl#2759]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-176-gdd20fb75b6 (webtiles) 

**DESCRIPTION:**
Teleported in to a single tile with no way out

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/5951269/193428426-a7d51b4c-89bf-4d2a-89ae-6d5c0e08f0fc.png)

The morgue file can be see at https://crawl.kelbi.org/crawl/morgue/RoadsterTracker/morgue-RoadsterTracker-20221001-214757.txt. The incident happened on D2

**Comment by DracoOmega** [comment]
Should have been fixed by 4d48fc061a5f55a8c0f6659aa7f356f7060d6111
