### ISSUE TITLE
Crashing on emptying a shop by buying everything on a shopping list (in Trunk) (on CKO)

### ISSUE THREAD

**Issue by culcube** [crawl/crawl#2760]
**PLATFORM and OS or BROWSER:**
console - crawl.kelbi.org

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-177-g1cb5dbfd7a
Game started: 0.30-a0-170-g85af917532 (but this was long before finding the shop)
This is on crawl.kelbi.org, Trunk, as phyphor:

**DESCRIPTION:**
Went to a shop and bought the entire contents as part of buying from my shopping list:

From last save point:
keypress: $
(to see shopping list)
keypress: [Enter]
(to go to the first item/shop in the list)
keypress: <
(to enter the shop)
keypress: [Enter]
(to buy the contents, all 3 items, which have previously been added to my shopping list)
keypress: Y
(to confirm buying the contents)
(also crashes with a lowercase "y")

**EXTRA FILES:**
Crash:
/dgldir/morgue/phyphor/crash-phyphor-20221002-032240.txt
Save file:
http://crawl.kelbi.org/saves/phyphor-crawl-git-1cb5dbfd7a-221002-0330.tar.bz2

**Comment by culcube** [comment]
I can successfully buy the first item, leave, re-enter and buy the remaining two by pressing [Enter]y without it crashing. I am, therefore, unable to do any more testing.

**Comment by rawlins** [comment]
Thanks for the report and especially the save! (This was tricky enough that I would never have been able to figure it out without it.)

**Comment by culcube** [comment]
Thanks (to the community) for making it so easy to report an issue, including the save!
