### ISSUE TITLE
[Console] roll 1 random mutation doesn't give the ability to roll

### ISSUE THREAD

**Issue by SurrExtended** [crawl/crawl#2762]
**PLATFORM and OS or BROWSER:**
Console
Xtahua
Putty

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-187-gd9c2deaf24

**DESCRIPTION:**
I gained the random mutation "Roll 1" but I cannot find the ability in [a] menu.

**EXTRA FILES:**
https://crawl.xtahua.com/saves/surr-crawl-git-d9c2deaf24-221003-0703.tar.bz2

**Comment by semitonal** [comment]
This was a leftover remnant of the removed Palentonga roll mutation that wasn't supposed to be randomly obtainable. This has been fixed to no longer be available as a random mutation (since the ability has been removed), see also #2766.
