### ISSUE TITLE
0.29-1 mac build and compiled release both seem to fail

### ISSUE THREAD

**Issue by jmdugan** [crawl/crawl#2776]
the 0.29-1 build via xcode on Mac OSX is building the executable "./crawl" successfully, 
but, when it runs, the shell shows:

"1: no such table: dbm" 

and the program fails during loading

ALSO

the compiled binary, linked here:
https://crawl.develz.org/download.htm
to
https://github.com/crawl/crawl/releases/download/0.29.1/dcss-0.29.1-macos-tiles-universal.zip
[that is also linked here
https://github.com/crawl/crawl/releases/tag/0.29.1
]

this seems to point to a zero-sized file

**Comment by rawlins** [comment]
Thanks for the report! However, building crawl with XCode is not a supported build method; it may be possible to get it to work but we can't really help with whatever would be needed. See [INSTALL.md](https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md) for supported (command line) build instructions, which are very similar to those on linux.

Re the 0.29.1 tiles build, I've verified that this file downloads and works on a couple of mac devices, and is not a 0 byte file. Not sure what to say, beyond maybe something went wrong with the download? You will need to override gatekeeper, it's not a signed app, and the message that the OS presents might be confusable with a broken download error.
