### ISSUE TITLE
Stray screen items

### ISSUE THREAD

**Issue by mike663** [crawl/crawl#2781]
While playing 0.29, every once in a while I see clusters of purple items on the screen that don't see to be there on purpose. Today I saw a similar arrangement of plants away from me when I descended the stairs for the first time. Attaching a screen shot.
<img width="2557" alt="DCSS Screenshot" src="https://user-images.githubusercontent.com/17882620/195988925-d42ac19c-59fa-450b-ad45-f3e03ca7ca4e.png">

**Comment by mike663** [comment]
After fully exploring that floor, I see there are no plants at all.
<img width="2546" alt="DCSS Screenshot 2" src="https://user-images.githubusercontent.com/17882620/195989345-c071a508-79bf-495b-9560-2dddecffe71f.png">

**Comment by mike663** [comment]
Here's a screenshot after fully exploring the floor while standing on the same tile. There are no plants where the strays were.
<img width="2546" alt="DCSS Screenshot 3" src="https://user-images.githubusercontent.com/17882620/195989460-3105e3c6-1b4c-4b3c-8a99-ffd65e114781.png">

**Comment by mike663** [comment]
And here are the purple dots
<img width="2556" alt="Purple Dots" src="https://user-images.githubusercontent.com/17882620/197340521-b99c1872-20a3-4b46-b18a-3538df02107c.png">

**Comment by PleasingFungus** [comment]
Fixed in 92e331aaff18e3f31798db4228f1dcdd364e5e65. Thanks for reporting!
