### ISSUE TITLE
Exploration bug not reporting correctly when a dungeon is completely mapped out.

### ISSUE THREAD

**Issue by Railbird80** [crawl/crawl#2785]
**PLATFORM and OS or BROWSER:**
Platform: CAO server
OS: Windows Vista SP 2
Browser: Maxthon v5.3.8.2000

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup version 0.29.1-1-gd02db6906a (webtiles)

**DESCRIPTION:**
I had completely mapped out the Temple using flight, the game still reports the level as being: 
"Partly explored, can't reach some places"  I am used to the game reporting: "Done exploring" when a level is completely mapped out.  I've brought this issue up on the DCSS discord channel and it is a problem that has been around for a while.  

**DCSS DISCORD CHAT:**
Here are some of the pertinent DCSS chat responses:

Railbird80 — Today at 12:48 PM
I've completely mapped out this level of the Temple with flight and it still gives me the message of "Partly explored, can't reach some places."   Is this a bug?
Image
ardl — Today at 12:50 PM
think its a bug w/ the big ocean boundary tiles? i vaguely remember it coming up before a long time ago
very possible im mistaken tho
Railbird80 — Today at 12:50 PM
Should I report this to the dev channel? @ardl
ardl — Today at 12:51 PM
id just put an issue on the github and see what comes of it
PleasingFungus — Today at 12:51 PM
sounds right

**EXTRA FILES:**

Here is a link to the screen shot showing the bug:
https://snipboard.io/wLYrJE.jpg

Here is a link to a backup of the game:
http://crawl.akrasiac.org/saves/Railbird80-crawl-0.29-221017-1646.tar.bz2

**Comment by kd7uiy** [comment]
http://crawl.akrasiac.org/rawdata/Railbird80/morgue-Railbird80-20221019-012243.txt is the morgue, BTW. chequers_temple_sunken is the map.

**Comment by kd7uiy** [comment]
Likely the easiest way to fix this will have a likely unintended, but minor issue. Let's not allow invalid tiles to be "unexplored". Essentially auto-explore will no longer look for the edge ocean tiles, it should treat those as invalid and not try to look further.  This can best be accomplished by adding the "Wall" attribute to the "open sea" tile type. While I'm at it, adding the same attribute to endless lava and expanse of salt to prevent any such future issues that might result.

The most unusual thing with this solution is that the edge tiles will be partially explored and the auto-explore will stop. I think this is fine, as there isn't any real reason to explore the edge screen, but...
