### ISSUE TITLE
Problem building using native dependencies

### ISSUE THREAD

**Issue by FDVG** [crawl/crawl#2789]
**PLATFORM and OS:**
Linux x86_64

**DCSS VERSION AND GAME INFORMATION:**
Building from current master
https://github.com/crawl/crawl

**DESCRIPTION:**
Followed this compiling guide: https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md#Compiling
I can't use DCSS's packaged dependencies and purposefully want to build using native.
So at this step: `make -j4 TILES=y`
When compiling I get the following:
```
* Need to build contribs: lua/src sqlite
**********************************************************

The 'lua/src' directory is missing. Have you run
   'git submodule update --init'?
(It's probably better to install all native dependencies instead.)

**********************************************************
make[1]: *** [Makefile:24: lua/src] Error 1
make: *** [Makefile:1833: .contrib-libs] Error 2
```
I guess it tries to build everything in contrib, but why tho?
So my question is what am I doing wrong?
I checked it a bunch of times and I installed sqlite and all required libs.

**Comment by robertxgray** [comment]
I'm sorry this ticket was left unanswered. Crawl can be built on Linux both using the dependencies provided by the distribution or the repository submodules. If you still need help please confirm your distribution and the packages you have installed.

**Comment by robertxgray** [comment]
I'm closing this. Please feel free to reopen if you need further support.
