### ISSUE TITLE
Unable to play the game start.

### ISSUE THREAD

**Issue by Sobieck** [crawl/crawl#2790]
**PLATFORM and OS or BROWSER:**
Webtiles trunk.

**DCSS VERSION AND GAME INFORMATION:**
![image](https://user-images.githubusercontent.com/6256765/197550469-35d8d3cc-2cfa-4237-9f81-7528b9e2fb46.png)

**DESCRIPTION:**
This start is impossible to get out of as a kobold. It'd be fine if it was a flying or swimming start. 

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/6256765/197550063-67edad3b-b1c7-404e-9f76-6b56a855b470.png)

**Comment by kd7uiy** [comment]
You can kill the mushrooms and get out. Might not be ideal for a start, however...

**Comment by Sobieck** [comment]
Shit. Didn’t think of that. It was fine just creating a new character.

Thomas Anderson Sobieck
________________________________

**Comment by PleasingFungus** [comment]
Resolved in 7fabdf1491b48c74e815bddf6339cde91db91acf (we removed this start setup). Sorry for the trouble!
