### ISSUE TITLE
Can't enter Zig portal created on temporary shallow water

### ISSUE THREAD

**Issue by NathanRose** [crawl/crawl#2797]
**PLATFORM and OS or BROWSER:** Webtiles and MacOS

**DCSS VERSION AND GAME INFORMATION:** 0.30-a0-331-g8ab09dc110

**DESCRIPTION:**
I encountered the first issue in webtiles (current trunk version) involving use of a figurine of the ziggurat (zig fig) while standing on shallow water created by an elemental wellspring. Recreating the situation offline in wiz mode I found two additional related issues.

1. Evoking a zig fig on temporary shallow water created by an elemental wellspring creates a portal to a ziggurat.  Hitting ‘>’ on this portal prompts the user “If you enter this portal you might not be able to return immediately. Continue?”.  Confirming with ‘Y’ gives the message “You can’t go down here!”, and the attempt passes 1 turn (10 Auts). 
 
2. If you are standing on a down stairs that gets covered by temporary shallow water and evoke a zig fig it generates a portal to a ziggurat.  Hitting ‘>’ prompts the user about not being able to return immediately, but confirming with ‘Y’ sends the player downstairs (not into a ziggurat).

3. Possibly intended: a ziggurat portal created on temporary shallow water disappears forever without a message when the terrain reverts to normal.  A  portal made on normal ground that is covered by shallow or deep water is also permanently destroyed without a message.

Testing in wiz mode it seems like these 3 issues happen with temporary shallow water made from any source.  I tried it with an elemental wellspring, a water nymph, casting Eringya's noxious bog, and evoking Phial of floods.

**Comment by semitonal** [comment]
Thanks for reporting!
