### ISSUE TITLE
Uskayaw-paralysed monsters continue to constrict you, wand-paralysed don't

### ISSUE THREAD

**Issue by damerell** [crawl/crawl#2801]
**PLATFORM and OS or BROWSER:**
Linux console

**DCSS VERSION AND GAME INFORMATION:**
4b46babb2116ae353106ba07e40373d6d2cfa759

**DESCRIPTION:**
Monsters paralysed by Uskayaw continue to constrict you. Monsters paralysed by wands do not. This is because apply_bolt_paralysis in beam.cc calls stop_directly_constricting, but _prepare_audience in god-passive.cc does not.

There may be a number of paths by which a monster can end up with ENCH_PARALYSIS, but I think mon-ench.cc add_ench() and add_enchantment_effect() may be a choke point where constriction could be stopped.

**Comment by hellmonk3** [comment]
fixed in f74bfe1, thanks.
