### ISSUE TITLE
`Fatal error:  SDL_image.h: No such file or directory` on ubuntu

### ISSUE THREAD

**Issue by scarf005** [crawl/crawl#2807]
**PLATFORM and OS or BROWSER:**
local tiles
```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-52-generic (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 4700U with Radeon Graphics
Memory: 30.7 GiB of RAM
Graphics Processor: AMD RENOIR
```

**DCSS VERSION AND GAME INFORMATION:**
`0.30-a0-341-g68270651`

**DESCRIPTION:**
```sh
$ ls /usr/include/SDL2/SDL_image.h 
/usr/include/SDL2/SDL_image.h
```
however in `windowmanager-sdl.cc:23:11`, it's `# include <SDL_image.h>`, not `# include <SDL2/SDL_image.h>`, causing failure in building.

**EXTRA FILES:**
```
 ~/r/c/c/source   master ±  LANG=C make -j7 TILES=1 SOUND=1
make -C rltiles all ARCH=x86_64-linux-gnu NO_PKGCONFIG= TILES=1
make[1]: Entering directory '/home/scarf/repo/crawl/crawl-ref/source/rltiles'
make[1]: Leaving directory '/home/scarf/repo/crawl/crawl-ref/source/rltiles'
    CXX windowmanager-sdl.o
    GEN compflag.h
    GEN build.h
    CXX version.o
windowmanager-sdl.cc:23:11: fatal error: SDL_image.h: No such file or directory
   23 | # include <SDL_image.h>
      |           ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1805: windowmanager-sdl.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by robertxgray** [comment]
Please review the [INSTALL.md](https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md) file and make sure you are not missing a dependency or step. The build process is checked very often in Ubuntu 22.04. You can find a [sample log here](https://github.com/robertxgray/crawl/actions/runs/4579905032/jobs/8088116004).

**Comment by robertxgray** [comment]
I'm closing the issue. Please feel free to reopen if you need further assistance.
