### ISSUE TITLE
Lookup descriptions submenus crash on exit

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2824]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-359-gd0147acb1a

**DESCRIPTION:**
If I start crawl, and type `? / g Escape` (so go into one of the help menus and back out again) the game crashes. It does the same thing if I have a character loaded, or if I look at one of the god descriptions before leaving the menu.

Replacing `DescMenu` with `InvMenu` in `_full_describe_menu()` stops it from happening. I've attached a patch to show what I mean, but I'm sure there's a better way to correct this problem.

On an unrelated note, I notice that the crash message states that a save file called `.cs` has been created, but none actually is.

**EXTRA FILES:**
[crash log](https://github.com/crawl/crawl/files/9993651/crash.zip)
[patch to replace DescMenu](https://github.com/crawl/crawl/files/9993410/dif.txt)

**Comment by robertxgray** [comment]
It doesn't crash for me. Did I do anything different?


https://user-images.githubusercontent.com/9676118/230626583-ab64368c-0689-458a-8c54-045d71d6c101.mp4

**Comment by Aliscans** [comment]
I don't think so. A segmentation fault means that it's an error in the way Crawl uses memory. C++ doesn't specify what should happen then, so it's not unusual for a different compiled program to behave differently.

I think the real explanation is near the top of that 200Mb crash log.

```
./crawl(_ZN7InvMenuD1Ev+0x3e) [0x7f30a55ccc04]: InvMenu::~InvMenu()
./crawl(_ZN8DescMenuD1Ev+0x38) [0x7f30a59e6c60]: DescMenu::~DescMenu()
```

lookup-help.cc says:

`class DescMenu : public Menu`

menu.cc says:

`class Menu { ... }`

`DescMenu` is not supposed to be an `InvMenu`, but Crawl calls the `InvMenu` destructor anyway. This happens  because there is a second class called `DescMenu` (in directn.cc) in the default namespace. Class names have external linkage, so Crawl can call either of them for any `DescMenu`.

To fix this, you could put one of the `DescMenu` declarations (it doesn't matter which) into a `namespace {}` block, or rename one of them to something else.
