### ISSUE TITLE
green draconian breathe does not penetrate enemies

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#2832]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-368-g86fb4627a9 (latest trunk)

**DESCRIPTION:**
Green draconian breathe does not penetrate enemies in trunk. In 0.29, it normally penetrates enemies. I couldn't find any related nerf commit. So I'm pretty sure it is a bug.

![0 30 trunk](https://user-images.githubusercontent.com/97007398/202837748-ef182b82-2e03-456f-9660-4653ffa123e9.PNG)
in trunk

![0 29](https://user-images.githubusercontent.com/97007398/202837751-e6221bb8-94dd-484d-9540-e21f611fb481.PNG)
in 0.29

**Comment by semitonal** [comment]
Fixed, thanks for reporting! It was caused by the spell/zap noise changes using Mephitic Cloud as the base spell for Green Draconian breath.
