### ISSUE TITLE
CTD opening scroll of acq 

### ISSUE THREAD

**Issue by b2** [crawl/crawl#2834]
**PLATFORM and OS or BROWSER:**
mac local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.29.1 Custom seed: 3121381558354691732

**DESCRIPTION:**
Crash opening the second acquistion scroll of 3 found with that seed. 

Octopode Transmuter, which I suspect is the key. The crashlog makes me think a newish unrand perhaps isn't flagged properly for Octopi. 

**EXTRA FILES:**
[crash-Tropohmi-20221119-103013.txt.zip](https://github.com/crawl/crawl/files/10047656/crash-Tropohmi-20221119-103013.txt.zip)

**Comment by b2** [comment]
[crash-jan3dewan-20230103-142711.txt](https://github.com/crawl/crawl/files/10339926/crash-jan3dewan-20230103-142711.txt)

custom seed 20230103
Another CTD, same failure as before in ?acq processing, but on a demonspawn wanderer instead of an octopode.

**Comment by robertxgray** [comment]
Thank you for the report. This bug has already been fixed on trunk and the patch will be included in the next release of Crawl. See PR #2806 for details.
