### ISSUE TITLE
formicid can use Shaft Self ability while it has Stuck status

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#2839]
PLATFORM and OS or BROWSER:
local tiles

DCSS VERSION AND GAME INFORMATION:
0.30-a0-368-g86fb4627a9 (latest trunk)

DESCRIPTION:
As you can see below, Stuck(translocation miscast effect) status blocks taking shaft.
![1](https://user-images.githubusercontent.com/97007398/202914065-e753ee0a-3c9f-42ff-b828-8c3c9ace8e12.PNG)
But formicid still can use Shaft Self ability while it has Stuck status.
![2](https://user-images.githubusercontent.com/97007398/202914103-66e750cf-33b7-449a-95d6-f3ad2b5fd31d.PNG)
this is bug, right?

**Comment by PleasingFungus** [comment]
I think it's fine. `Stuck` means you can't voluntarily move, but when you shaft yourself, you're just digging a hole - gravity is moving you. Same as if a worm harpooned you.

**Comment by PleasingFungus** [comment]
Acrobat notes:

> in trunk, Stuck status prevents the player from being pulled by harpoon shot actually. So what's the difference between that the earth physically pulls the player(gravity) and that worms physically pull the player(harppon shot)? Why is one possible and the other not?
> And also if it is fine that formicid still can use Shaft Self ability while it has Stuck status, then why Stuck status prevent player taking already existing shaft trap?

Reopening whilst as I consider.

**Comment by PleasingFungus** [comment]
Very well. Done.
