### ISSUE TITLE
Beogh gifting bug

### ISSUE THREAD

**Issue by Gichin13** [crawl/crawl#2840]
Playing online tiles 0.29 version

Recently noted that I had gifted one my followers a polearm and they were now armed with a crossbow but no polearm. I had missed the gift from Beogh, but it appeared Beogh gave the same orc a crossbow and then they dropped my original melee polearm. I was unable to give this named orc a gift either. 

**PLATFORM and OS or BROWSER:**

**DCSS VERSION AND GAME INFORMATION:**

**DESCRIPTION:**

**EXTRA FILES:**

**Comment by regret-index** [comment]
0.32's reworks no longer involves Beogh gifting any equipment to orc allies, obsoleting this issue entirely.
