### ISSUE TITLE
29.1 quaff / quiver issue....

### ISSUE THREAD

**Issue by D-Donovan** [crawl/crawl#2847]
**PLATFORM and OS or BROWSER:**
webtiles - windows

**DCSS VERSION AND GAME INFORMATION:**
29.1

**DESCRIPTION:**
I notice the issue in 29.0 and thought it to be resolved in 29.1 - it appears quaff and quiver have issues to be confused for one for the other....

**EXTRA FILES:**
<!-- Please include any morgue files, crashlogs, save files here, or extra
 Seeded DCSS version 0.29.1 (tiles) character file.

Game seed: 3504225572099801645 (custom seed)

248 Futreq the Covered (level 5, 0/41 HPs)
             Began as a Mummy Fighter on Nov 25, 2022.
             Slain by Prince Ribbit (10 damage)
             ... on level 5 of the Dungeon.
             The game lasted 00:18:08 (4170 turns).

Futreq the Covered (Mummy Fighter)                  Turns: 4170, Time: 00:18:09

Health: 0/41       AC: 14    Str: 24    XL:     5   Next: 86%
Magic:  5/5        EV:  9    Int: 13    God:    
Gold:   183        SH:  5    Dex: 16    Spells: 4/4 levels left

rFire   x . .      SeeInvis .   a - +0 war axe
rCold   + + .      Faith    .   c - +0 buckler
rNeg    + + +      Spirit   .   b - +0 scale mail
rPois   8          Reflect  .   l - +0 helmet
rElec   .          Harm     .   p - scarf {repulsion}
rCorr   .          Rampage  .   h - +2 pair of gloves
Will    .....                   g - +2 pair of boots
Stlth   ..........              (no amulet)
HPRegen 0.13/turn               u - ring of Wonder {rC+ Str+3 Dex+4}
MPRegen 0.09/turn               d - +6 ring of intelligence

@: repel missiles
A: cold resistance 1, negative energy resistance 3, torment resistance 2, heat
vulnerability 1, in touch with death 1, no potions
a: no special abilities

You were on level 5 of the Dungeon.
You visited 2 branches of the dungeon, and saw 6 of its levels.

You collected 183 gold pieces.

Inventory:

Hand Weapons
 a - a +0 war axe (weapon)
Armour
 b - a +0 scale mail (worn)
 c - a +0 buckler (worn)
 g - a +2 pair of boots (worn)
 h - a +2 pair of gloves (worn)
 l - a +0 helmet (worn)
 p - a scarf of repulsion (worn)
Jewellery
 d - a +6 ring of intelligence (right hand)
 u - the ring of Wonder (left hand) {rC+ Str+3 Dex+4}
   (You found it on level 2 of the Dungeon)   
   
   [ring of protection from cold]
   
   Str:       It affects your strength (+3).
   Dex:       It affects your dexterity (+4).
   rC:        It protects you from cold.
Wands
 y - a wand of flame (16)
Scrolls
 e - 2 scrolls of vulnerability
 n - a scroll of identify
 w - a scroll of teleportation
 z - a scroll of magic mapping
Potions
 f - a potion of berserk rage {unknown}
 i - 2 potions of resistance
 j - 3 potions of degeneration
 k - a potion of magic {unknown}
 m - 2 potions of heal wounds
 o - a potion of curing {unknown}
 r - a potion of haste
 s - 2 potions of mutation {unknown}
 t - a potion of cancellation {unknown}
 x - a potion of invisibility {unknown}

   Skills:
 + Level 3.4 Fighting
 + Level 3.4 Axes
 + Level 3.7 Armour
 + Level 0.8 Dodging
 + Level 2.8 Shields

You had 4 spell levels left.
You didn't know any spells.
Your spell library contained the following spells:

 Spells                   Type           Power      Damage    Failure   Level
 Inner Flame              Hex/Fire       0%         N/A       96%         3
 Cause Fear               Hex            0%         N/A       100%        4
 Discord                  Hex            0%         N/A       100%        8

Dungeon Overview and Level Annotations

Branches:
Dungeon (5/15)             Temple (1/1) D:4         

Altars:
Cheibriados
Fedhas
Kikubaaqudgha
Makhleb
Nemelex Xobeh
Okawaru
Ru
Sif Muna
Lugonu

Annotations:
D:4 3 runed translucent doors, Futreq's ghost, amateur HuFi
D:5 Prince Ribbit

Innate Abilities, Weirdness & Mutations

You are immune to poison.
Your flesh is cold resistant. (rC+)
You are immune to negative energy. (rN+++)
You are immune to unholy pain and torment.
You are vulnerable to heat. (rF-)
You are in touch with the powers of death.
You do not drink.

Message History

There is a stone staircase leading down here.
As you read the scroll labelled FYFAM PUEPSAPH, it crumbles to dust.
The air around you briefly surges with heat, but it dissipates.
It was a scroll of immolation.
There is a stone staircase leading down here.
You climb downwards.
Prince Ribbit gives a loud, deep croak!
There is a stone staircase leading up here.
Found a falchion and 5 gold pieces. Prince Ribbit blinks!
You block Prince Ribbit's attack. Prince Ribbit hits you.
You hit Prince Ribbit but do no damage. Prince Ribbit hits you!
Prince Ribbit hits you but does no damage.
You miss Prince Ribbit. You block Prince Ribbit's attack. Prince Ribbit blinks!
Prince Ribbit blinks!
You slash Prince Ribbit!
Prince Ribbit is lightly wounded.
Prince Ribbit hits you. Prince Ribbit completely misses you.
You hit Prince Ribbit.
Prince Ribbit is moderately wounded.
Prince Ribbit hits you. x2
You hit Prince Ribbit.
Prince Ribbit is moderately wounded.
Prince Ribbit hits you but does no damage.
Prince Ribbit lets out a mournful croak.
Prince Ribbit blinks!
Prince Ribbit hits you but does no damage.
Prince Ribbit barely misses you. Prince Ribbit hits you!
* * * LOW HITPOINT WARNING * * *
Prince Ribbit catches a blue-tailed skink with his tongue.
Prince Ribbit completely misses you.
You miss Prince Ribbit.
Prince Ribbit is moderately wounded.
Prince Ribbit hits you but does no damage.
Prince Ribbit closely misses you.
You barely miss Prince Ribbit.
Prince Ribbit is moderately wounded.
Prince Ribbit asks, "Just a little smooch?"
Prince Ribbit blinks!
Prince Ribbit attacks as you move away! Prince Ribbit hits you!
You die...

     ##
   ###.
    ...    #
     ..   .#
     #.###.#
     #.....
######.#.### #
.......<...#.#
######.#.#.#.###
 ......F@§.)...#
 #####.$.....###
 #####....#..#
 .........#..#
 ######.#.# .#
      #. ... #
      ## .#...
         .#.###
         .# #
         ..
         .#

You could see Prince Ribbit.

Vanquished Creatures
  Natasha (twice) (D:4)
  2 orc wizards (D:4)
  5 adders
  2 worms (D:3)
  2 dart slugs
  8 orcs
  8 bats
  6 endoplasms
  2 giant cockroaches
  8 goblins
  5 hobgoblins
  2 jackals (D:1)
  13 kobolds
  3 quokkas (D:2)
  8 ball pythons
  3 frilled lizards
  5 rats
84 creatures vanquished.

Vanquished Creatures (others)
  Natasha (D:4)
  2 demonic plants (Temple)
3 creatures vanquished.

Grand Total: 87 creatures vanquished

Notes
Turn   | Place    | Note
-------+----------+-------------------------------------------
     0 | D:1      | Futreq the Mummy Fighter began the quest for the Orb.
     0 | D:1      | Reached XP level 1. HP: 18/18 MP: 1/1
   345 | D:1      | Reached XP level 2. HP: 17/24 MP: 2/2
   939 | D:2      | Identified the +1 leather armour of Wurgh {rN++ Slay+2
                  | SInv}
  1103 | D:2      | Gained mutation: You are in touch with the powers of death.
                  | [Mummy growth]
  1103 | D:2      | Reached XP level 3. HP: 29/29 MP: 3/3
  1406 | D:2      | Reached XP level 4. HP: 34/35 MP: 4/4
  1410 | D:2      | Identified the ring of Wonder {rC+ Str+3 Dex+4}
  2226 | D:3      | Found a faded altar of an unknown god.
  2226 | D:3      | Noticed a soul eater
  2531 | D:4      | Noticed Natasha
  2542 | D:4      | Killed Natasha
  2807 | D:4      | Found a runed translucent gate.
  2808 | D:4      | Found a runed translucent gate.
  2808 | D:4      | Found a runed translucent gate.
  2808 | D:4      | Noticed Natasha
  2838 | D:4      | Killed Natasha
  2839 | D:4      | Reached XP level 5. HP: 18/41 MP: 5/5
  3444 | D:4      | Found a staircase to the Ecumenical Temple.
  3444 | D:4      | Noticed Natasha
  3455 | D:4      | Killed Natasha
  3817 | Temple   | Entered the Ecumenical Temple
  4077 | D:4      | Noticed Futreq's ghost (amateur HuFi)
  4151 | D:5      | Entered Level 5 of the Dungeon
  4151 | D:5      | Noticed Prince Ribbit
  4170 | D:5      | Slain by Prince Ribbit

Illustrated notes

Levels and vault maps discovered:
D:1:      ncdulo_watergridlock, layout_basic
D:2:      minmay_angry_zag, layout_rooms
D:3:      layout_loops_ring, dreamdust_ecumenical_altar_sealed_demon
D:4:      layout_basic, temple_fountains, gammafunk_ghost_nasty_kobolds,
          uniq_natasha
D:5:      layout_loops_ring, minitemple, uniq_prince_ribbit1
Temple:   kb_corrupted_temple

Skill      XL: |  1  2  3  4 |
---------------+-------------+-----
Axes           |     2     3 |  3.4
Armour         |        3    |  3.7
Fighting       |             |  3.4
Dodging        |             |  0.8
Shields        |             |  2.8

Action                   |  1- 3 |  4- 6 || total
-------------------------+-------+-------++-------
Melee: War axe           |    94 |   176 ||   270
  Use: Scroll            |       |    10 ||    10
Armor: Scale mail        |    96 |   132 ||   228
Dodge: Dodged            |    90 |    65 ||   155
       Repelled          |       |     5 ||     5
Block: Buckler           |    37 |    51 ||    88

**Comment by rawlins** [comment]
Can you clarify what the issue actually is? Quaff is `q` and quiver is `Q`, so they might be confusable, but that's sort of the nature of crawl controls; aside from that as far as I know everything is working fine.

**Comment by D-Donovan** [comment]
Attached are two screenshots that might help..

I am finding you cannot quaff a potion - instead asked to quiver it....

I'm surprised something as glaring would make it past basic testing...I believe the bug was introduced in 0.29.0 and still persists in 0.29.1

Windows
Tiles


From: Kyle Rawlins ***@***.***>
Sent: Friday, November 25, 2022 2:42 PM
To: crawl/crawl ***@***.***>
Cc: Donovan, David A. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [crawl/crawl] 29.1 quaff / quiver issue.... (Issue #2847)


Can you clarify what the issue actually is? Quaff is q and quiver is Q, so they might be confusable, but that's sort of the nature of crawl controls; aside from that as far as I know everything is working fine.

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcrawl%2Fcrawl%2Fissues%2F2847%23issuecomment-1327874469&data=05%7C01%7Cddonovan%40mayo.edu%7C24b66b679864498c34cd08dacf2594b6%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638050057571867114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AFx6MzA3Y%2FIBfWypyy5qFPdCACh%2FB8fHn939jG2zG8c%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA4MP4LPRPGUXAASZJNPNVTDWKEQCZANCNFSM6AAAAAASLTJZBU&data=05%7C01%7Cddonovan%40mayo.edu%7C24b66b679864498c34cd08dacf2594b6%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638050057571867114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kGY6xOv8M88HoLMOSUn2PCFIxG5wHqbiO2LOphViuM8%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

 Seeded DCSS version 0.29.1 (tiles) character file.

Game seed: 3504225572099801645 (custom seed)

Kic Ruro the Trooper (Mummy Fighter)                Turns: 1656, Time: 00:08:20

Health: 35/35      AC: 14    Str: 24    XL:     4   Next: 7%
Magic:  4/4        EV:  9    Int:  7    God:    
Gold:   132        SH:  5    Dex: 15    Spells: 3/3 levels left

rFire   x . .      SeeInvis .   a - +0 war axe
rCold   + + .      Faith    .   c - +0 buckler
rNeg    + + +      Spirit   .   b - +0 scale mail
rPois   8          Reflect  .   l - +0 helmet
rElec   .          Harm     .   n - scarf {repulsion}
rCorr   .          Rampage  .   j - +2 pair of gloves
Will    .....                   i - +2 pair of boots
Stlth   ..........              (no amulet)
HPRegen 0.11/turn               q - ring of Wonder {rC+ Str+3 Dex+4}
MPRegen 0.09/turn               (no ring)

@: repel missiles
A: cold resistance 1, negative energy resistance 3, torment resistance 2, heat
vulnerability 1, in touch with death 1, no potions
a: no special abilities


You are on level 2 of the Dungeon.
You have visited 1 branch of the dungeon, and seen 3 of its levels.

You have collected 132 gold pieces.

Inventory:

Hand Weapons
 a - a +0 war axe (weapon)
Armour
 b - a +0 scale mail (worn)
 c - a +0 buckler (worn)
 i - a +2 pair of boots (worn)
 j - a +2 pair of gloves (worn)
 l - a +0 helmet (worn)
 n - a scarf of repulsion (worn)
Jewellery
 q - the ring of Wonder (left hand) {rC+ Str+3 Dex+4}
   (You found it on level 2 of the Dungeon)   
   
   [ring of protection from cold]
   
   Str:       It affects your strength (+3).
   Dex:       It affects your dexterity (+4).
   rC:        It protects you from cold.
Scrolls
 d - a scroll labelled FIAGOE HUMIO
 e - a scroll labelled BEFYDO BIKUSKI
 f - a scroll of vulnerability
 h - 4 scrolls labelled HOXARO NEAXZO
 o - a scroll labelled XERUOF ARCHI
Potions
 g - 2 lumpy green potions
 k - 3 white potions
 m - a grey potion
 p - an inky potion
 r - a lumpy blue potion
 s - an amethyst potion
 t - a yellow potion
 u - a bubbling ruby potion


   Skills:
 + Level 3.4 Fighting
 + Level 2.5 Axes
 + Level 2.7 Armour
 + Level 0.5 Dodging
 + Level 0.1 Stealth
 + Level 2.8 Shields


You have 3 spell levels left.
You don't know any spells.
Your spell library contains the following spells:

 Spells                   Type           Power      Damage    Failure   Level
 Inner Flame              Hex/Fire       0%         N/A       99%         3
 Cause Fear               Hex            0%         N/A       100%        4
 Discord                  Hex            0%         N/A       100%        8


Dungeon Overview and Level Annotations

Branches:
Dungeon (3/15)            

Altars:


Innate Abilities, Weirdness & Mutations

You are immune to poison.
Your flesh is cold resistant. (rC+)
You are immune to negative energy. (rN+++)
You are immune to unholy pain and torment.
You are vulnerable to heat. (rF-)
You are in touch with the powers of death.
You do not drink.

Message History

You slash the hobgoblin!
You kill the hobgoblin!
You barely miss the quokka.
The quokka bites you but does no damage.
You barely miss the frilled lizard. You closely miss the quokka. The quokka
barely misses you. The frilled lizard barely misses you.
The quokka bites you but does no damage.
The frilled lizard bites you but does no damage.
You slash the frilled lizard!
You kill the frilled lizard!
You closely miss the quokka.
The quokka bites you but does no damage. x2
The quokka bites you.
Things that are here:
a frilled lizard corpse; a hobgoblin corpse
You closely miss the quokka.
The quokka bites you but does no damage.
The quokka closely misses you.
You hit the quokka.
You kill the quokka!
A hobgoblin comes into view.
The hobgoblin moves out of view.
You barely miss the hobgoblin.
The hobgoblin hits you but does no damage.
You hit the hobgoblin.
The hobgoblin is lightly wounded.
The hobgoblin barely misses you.
The hobgoblin hits you but does no damage.
You hit the hobgoblin.
You kill the hobgoblin!
Things that are here:
a frilled lizard corpse; a hobgoblin corpse
There is a stone staircase leading down here.
You see here a frilled lizard skeleton.
You see here a bat skeleton.
You see here a quokka skeleton.
Found a bubbling ruby potion.
You see here a bubbling ruby potion.
You see here a bubbling ruby potion.
u - a bubbling ruby potion
Save game and return to main menu? 

#.......<#####.#   #.........#   ####..#....##..######
#........#   #.#   #.........#####.......#.......<....
#........#   #.#   #.........#.....##.####.###........
#(.......#   #.#   #####.#####.####...#  #.###........
##########   #.#       #.###...###..###  #...#........
             #.#       #.##..####..##    ###.#########
             #.#       #.#..........#      #...#
            ##.##      #.#..........#      ###.#
            #...#     ##.#..........#        #.#
            #...#     #.>.).........#        #.#
            #...#     #.#...........#        #.#
            #...#     #.#÷########..####     #.#
            #...#     #.#.#      ##....#     #.#
            #...#######...#       ####.##    #.#
            #..........÷###          #..######.###
            #...######÷##            ##..).......#
            #.>.# ####.####           ########...#
            ##### #.......#                  #####
                  #.......####
                  ***@***.***###
                  #.......##...#
                  ############.#
                             ###


There are no monsters in sight!

Vanquished Creatures
  3 adders (D:2)
  A dart slug (D:3)
  3 endoplasms
  2 giant cockroaches
  4 goblins
  4 hobgoblins
  2 jackals (D:1)
  4 kobolds
  3 quokkas (D:2)
  3 ball pythons
  6 bats
  3 frilled lizards
  2 rats (D:1)
40 creatures vanquished.

Notes
Turn   | Place    | Note
-------+----------+-------------------------------------------
     0 | D:1      | Kic Ruro the Mummy Fighter began the quest for the Orb.
     0 | D:1      | Reached XP level 1. HP: 18/18 MP: 1/1
    93 | D:1      | Reached XP level 2. HP: 6/24 MP: 2/2
   864 | D:2      | Gained mutation: You are in touch with the powers of death.
                  | [Mummy growth]
   864 | D:2      | Reached XP level 3. HP: 29/29 MP: 3/3
   876 | D:2      | You fall into a shaft and drop 1 floor!
  1190 | D:2      | Identified the ring of Wonder {rC+ Str+3 Dex+4}
  1484 | D:2      | Reached XP level 4. HP: 34/35 MP: 4/4

Illustrated notes

Skill      XL: |  1  2 |
---------------+-------+-----
Axes           |     2 |  2.5
Fighting       |       |  3.4
Armour         |       |  2.7
Dodging        |       |  0.5
Stealth        |       |  0.1
Shields        |       |  2.8

Action                   |  1- 3 |  4- 6 || total
-------------------------+-------+-------++-------
Melee: War axe           |   105 |    12 ||   117
  Use: Scroll            |     1 |       ||     1
Armor: Scale mail        |   170 |    12 ||   182
Dodge: Dodged            |   139 |    10 ||   149
Block: Buckler           |    57 |     1 ||    58

**Comment by rawlins** [comment]
> I am finding you cannot quaff a potion - instead asked to quiver it....

This ... isn't replicating. Can you provide some detail on *exactly* what you are doing? What server are you playing on, what is in your rc file, etc?

**Comment by D-Donovan** [comment]
Local - windows - 0.29.1

For an *.rc file - not sure where to find...

From: Kyle Rawlins ***@***.***>
Sent: Friday, November 25, 2022 4:33 PM
To: crawl/crawl ***@***.***>
Cc: Donovan, David A. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [crawl/crawl] 29.1 quaff / quiver issue.... (Issue #2847)


I am finding you cannot quaff a potion - instead asked to quiver it....

This ... isn't replicating. Can you provide some detail on exactly what you are doing? What server are you playing on, what is in your rc file, etc?

-

**Comment by D-Donovan** [comment]
If it helps...0.28.0 does not have the issue but I think 0.29.0 / 0.29.1 does

From: Kyle Rawlins ***@***.***>
Sent: Friday, November 25, 2022 4:33 PM
To: crawl/crawl ***@***.***>
Cc: Donovan, David A. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [crawl/crawl] 29.1 quaff / quiver issue.... (Issue #2847)


I am finding you cannot quaff a potion - instead asked to quiver it....

This ... isn't replicating. Can you provide some detail on exactly what you are doing? What server are you playing on, what is in your rc file, etc?

-

**Comment by PleasingFungus** [comment]
Mummies can't drink.
