### ISSUE TITLE
Confusing engulf messages

### ISSUE THREAD

**Issue by RypoFalem** [crawl/crawl#2859]
**PLATFORM and OS or BROWSER:**
Tested on linux, console and tiles

**DCSS VERSION AND GAME INFORMATION:**
0.29.1 and 0.30-a0-390-g80c34de65d

**DESCRIPTION:**
When you are engulfed, and move from a space adjacent to the engulfing monster and to another space adjacent to an engulfing monster, you stay engulfed. However, the message log says you "You slip free".

```
 You slip free of the ooze engulfing you.
 Your lungs strain for air!
```
https://github.com/crawl/crawl/blob/80c34de65d922034fe06ff263c30f0d1ef8d132c/crawl-ref/source/movement.cc#L216-L224

The slip-free message is printed before you know if you slipped free or not. Maybe it should duplicate logic and only print if you step away, maybe it should reflect an attempt to break away or hint that you need to move away, not around.

the simple duplicated logic version:
```c++
monster * const mons = monster_by_mid(you.props[WATER_HOLDER_KEY].get_int());
    if (you.duration[DUR_WATER_HOLD] 
        && (!mons || !mons->alive() || !adjacent(mons->pos(), you.pos())))
    {
        mprf("You slip free of the %s engulfing you.",
             water_hold_substance().c_str());
        you.clear_far_engulf();
    }
```

**Comment by semitonal** [comment]
Thanks for reporting! I refactored the message handling a little to avoid duplicating those checks.
