### ISSUE TITLE
 using recall ability of Yred near lava can insta-kill some friendly zombies

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#2866]
PLATFORM and OS or BROWSER:
local tiles

DCSS VERSION AND GAME INFORMATION:
0.30-a0-368-g86fb4627a9 (latest trunk)

DESCRIPTION:
using Recall Undead Harvest ability of Yred near lava can kill salamander zombie, salamander mystic zombie, salamander tyrant zombie, lava snake zombie.
![1](https://user-images.githubusercontent.com/97007398/206381168-91ffecfa-b232-4b82-b7c3-50c157fd44ab.PNG)
![2](https://user-images.githubusercontent.com/97007398/206381172-3f139071-a706-4acb-8fe3-b7d0964cee57.PNG)

**Comment by PleasingFungus** [comment]
Nice bug! Moderately sure it's been around since https://github.com/crawl/crawl/commit/db45db7b37df5989d9c321bacdf7e9ea7097a0e6 (April 2013). Should be fixed now.
