### ISSUE TITLE
Servitor wastes turns with Arcjolt

### ISSUE THREAD

**Issue by RypoFalem** [crawl/crawl#2875]
Linux local tiles 0.30-a0-457-g4b7bca3bfa

A spellforged servitor with arcjolt is much more reluctant to get into range of monsters than with other spells. With other spells, the servitor will move seemingly every turn until it gets into range and then will occasionally cast spells. However, with arcjolt, the servitor spends a lot more turns not in range and not moving.

Perhaps it's because the listed range of the spell is much more than 1 tile away?

Attached is a video where it takes over 20 turns for the servitor to move 3 tiles (sometimes it can be more or less)

https://user-images.githubusercontent.com/7819240/206946769-d2af960b-6312-40f9-acff-ae64a4c3df10.mp4

**Comment by semitonal** [comment]
Should be fixed, thanks for reporting!
