### ISSUE TITLE
Two compiler warnings

### ISSUE THREAD

**Issue by Goratrix** [crawl/crawl#2891]
Not important, but as most warnings have been resolved now, I thought I flag these two that are remaining. Getting them on a MSYS2 build not sure if that's relevant.

`outer-menu.cc: In member function 'void OuterMenu::add_button(std::shared_ptr<MenuButton>, int, int
':
outer-menu.cc:314:13: warning: 'r' may be used uninitialized [-Wmaybe-uninitialized]
  314 |     Widget *r;
      |             ^
`

and

`view.cc:1528:6: warning: no previous declaration for 'void view_add_glyph_overlay(const coord_def&,
cglyph_t)' [-Wmissing-declarations]
 1528 | void view_add_glyph_overlay(const coord_def &gc, cglyph_t glyph)
      |      ^~~~~~~~~~~~~~~~~~~~~~
`

**Comment by rawlins** [comment]
I cannot for the life of me see where the view.cc warning is coming from; that function is declared unconditionally in the header as far as I can see. I also don't see this warning in any of the CI builds I have checked, so maybe there is something MSYS2 specific about it?

**Comment by Goratrix** [comment]
I don't have my MSYS2 up now, so can't test, but could it have been fixed in 1df383f? That commit was 5 days after my report.

**Comment by rawlins** [comment]
Aha good catch -- I looked at blame but missed that there were removed lines. I think you are right, it was a def mismatch and so is also resolved.
