### ISSUE TITLE
ally monsters without Sinv do not fire properly when player is invisible

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#2892]
PLATFORM and OS or BROWSER:
local tiles

DCSS VERSION AND GAME INFORMATION:
0.30-a0-368-g86fb4627a9

DESCRIPTION:
ally monsters without Sinv do not fire properly when player is invisible.

![1](https://user-images.githubusercontent.com/97007398/209143623-51a9e26d-d4c1-4926-a60b-259e1af7e0bb.PNG)
example1
In this situation, servitor never fire iron shot to rats.

![2](https://user-images.githubusercontent.com/97007398/209143634-c9f57e13-1ca7-4f88-b838-a53413a77c60.PNG)
example2
In this situation, oklob plants never fire acid to Tiamat.

**Comment by PleasingFungus** [comment]
Fixed, thanks!
