### ISSUE TITLE
vine stalker can't use curing potion when poisoned

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#2897]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-540-g0af01429fa (latest trunk)

**DESCRIPTION:**
vine stalker can't use curing potion when poisoned.

![1](https://user-images.githubusercontent.com/97007398/209482138-dcf4695c-7e60-4431-b23f-bdcd92e35ec7.PNG)

**Comment by hellmonk3** [comment]
fixed (I think), reopen if it keeps happening.
