### ISSUE TITLE
Sceptre of Asmodeus claims to be evokable, but isn't.

### ISSUE THREAD

**Issue by powerbf** [crawl/crawl#2912]
**PLATFORM and OS or BROWSER:**
Webtiles trunk (CPO)

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-591-g3c58d2b

**DESCRIPTION:**
In the description for the Sceptre of Asmodeus, it says it can be evoked:
"It can be evoked to summon fiery demons, with success rate depending on Evocations skill. Those summoned this way will remain friendly only for a limited time."

However, it's not actually possible to evoke it.

It's not in the list of evokable items presented by the V command, even when wielded. 

Pressing the letter of the Sceptre from the evoke menu gives the message: "That's the wrong kind of item! (Use * to select it.)"

Doing V, asterisk, letter of the Sceptre, gives "That item cannot be evoked!"

**EXTRA FILES:**

**Comment by powerbf** [comment]
Same with Staff of Dispater.

**Comment by pdpol** [comment]
I think this might be an issue with the term "evoke" referring both to items such as wands and tools that are evoked with `V`, and gear with evokable skills accessed through the `a` abilities menu. For both of the items you referenced, those are evoked through the `a` menu. Not disputing that it might be confusing for a player that the word is used ambiguously.

**Comment by powerbf** [comment]
Ah well, would you look at that. Do you know how many times I've had these items and not known you could evoke them?

I think the fix here is just to update the text to make it clear that you have to wield the item and then go into the abilities menu in order to invoke it.

**Comment by PleasingFungus** [comment]
I've tweaked the wording. Thanks for reporting! :)
