### ISSUE TITLE
demon whip (holy), eudemon blade (heavy)

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#2913]
PLATFORM and OS or BROWSER:
local tiles

DCSS VERSION AND GAME INFORMATION:
0.30-a0-587-gfd7c166f36 (latest trunk)

DESCRIPTION:
for some reason, demonic weapons can have holy wrath brand and blessed demonic weapons can have other brands besides holy wrath in trunk.
https://github.com/crawl/crawl/commit/c5509c9e3150074caf3d933b7def97f56d2ca427
I think this commit solved the problem before, but it happen again.

![0](https://user-images.githubusercontent.com/97007398/210737566-3330395b-c135-4ca4-886f-cc8d3cfc423a.png)
![1](https://user-images.githubusercontent.com/97007398/210737573-cc20537c-bf8f-4ef4-b6b5-f872c8b50ee8.png)

**Comment by PleasingFungus** [comment]
Mostly fixed in 0ee6a06047e57c82ddb8123da0993e77481f9919 and 17dd5e2ed6d840e0e81607b61f9e7fdf520ee976, thanks! There are still two vaults which can cause this; I'll look at them later.
