### ISSUE TITLE
randart with Drain missing the "*"

### ISSUE THREAD

**Issue by dustinjmathis** [crawl/crawl#2914]
**PLATFORM and OS or BROWSER:**
Windows 11 Local Tiles

**DCSS VERSION AND GAME INFORMATION:**
v0.29.1; game Seed 8410465094181841585

**DESCRIPTION:**
On DL 2 found the randart +8 hand axe of the Harvest with spectral, Drain, rElec Str+4 Dex +5. The Drain effect should have an * indicating that it is a negative effect on unequip.

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/44122033/210834849-4de4ce49-77a8-45dc-944c-8a7dab275553.png)

**Comment by PleasingFungus** [comment]
Intended. See bac1ddba907 .

> Adjust *Contam and *Drain to be just Contam and Drain, so that * consistently indicates an effect that triggers randomly while equipped (*Noise, *Corrode, *Slow, *Tele etc).
