### ISSUE TITLE
ozocubu's refrigeration turns friendly simulacra hostile

### ISSUE THREAD

**Issue by ZillyBean** [crawl/crawl#2917]
**PLATFORM:** 
local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.29.0

**DESCRIPTION:**
When casting refrigeration with friendly simulacra, the game shows a warning, and choosing to cast the spell turns the simulacra hostile.

**EXTRA FILES:**
![2](https://user-images.githubusercontent.com/122182898/211173687-ac4317ed-a887-4dbd-bf14-72b3b0020f9a.png)
![3](https://user-images.githubusercontent.com/122182898/211173689-625b44a1-588a-454e-ab27-44c4e0a2a7cd.png)
![4](https://user-images.githubusercontent.com/122182898/211173690-3bc75624-feb2-4d29-8517-10d2145c6948.png)
save file: [save.zip](https://github.com/crawl/crawl/files/10367355/save.zip)

**Comment by semitonal** [comment]
Should be fixed by b3c18b1f4e, thanks for reporting.
