### ISSUE TITLE
Odd messages when summoned things explode

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2937]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-626-gd6a5dd7a1f

**DESCRIPTION:**
If I summon a monster, read a scroll of immolation on it, and then let a monster kill it, it gives messages along the lines of:
```
 The jackal bites your rat. Flame seeps out of your rat. 
 Your rat is engulfed in blazing flames.
 Your rat's corpse disappears in a puff of smoke!
 Your rat explodes!
```
This creates a 9x9 square shape of fire, although the centre is sometimes replaced by black smoke.

The messages:
- refer to a corpse before they refer to a death; and
- say that a monster disappears and then explodes.

To me, it would make more sense to say something like:
```
 Your rat explodes!
 Your rat's remains disappear in a puff of smoke!
```
This uses two messages in order to explain both the fire and the smoke.

`monster_die()` is quite long and complicated, so I don't know what it would take to fix something like this.
**EXTRA FILES:**
[save.zip](https://github.com/crawl/crawl/files/10397220/save.zip)
Save file in which this has just happened.

**Comment by DracoOmega** [comment]
It should have been fixed by d9015ae29d17d9fb551e92c09c08022577a67ff7
