### ISSUE TITLE
Can't climb stairs due to Lua error in webtiles

### ISSUE THREAD

**Issue by breakfastpizza** [crawl/crawl#2941]
**PLATFORM and OS or BROWSER:**
Platform: webtiles https://crawl.kelbi.org
OS: MacOS Ventura 13.1 (22C65)
Browser: Firefox 108.0.2 (64-bit)

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.30-a0-634-g8abc85282e (Console/Webtiles)

**DESCRIPTION:**
When trying to climb up stairs I get an error
`Lua error: ...-master/crawl-git-8abc85282e/data/dat/dlua/macro.lua:38: Unknown function in macro: 'safe_upstairs'`

I thought it might be my .rc file so I cleared it but the issue persists. I've included a link to my .rc file below.

**EXTRA FILES:**
[Morgue](https://gist.github.com/breakfastpizza/e958dd4095ede29af97dde95f84f5886)
[RC file](https://gist.github.com/breakfastpizza/606e5f7b3996588d78c82a263c895aef)
[Backup](http://crawl.kelbi.org/saves/maskedpotato-crawl-git-8abc85282e-230114-1459.tar.bz2)

**Comment by rawlins** [comment]
Sorry no one got to this earlier; this is going to be something in your macro file, not rc file; you can view and edit this in-game via the game menu (`~` or F1). Your CKO macros can be seen [url=https://crawl.kelbi.org/crawl/rcfiles/crawl-git/maskedpotato.macro]here[/url].

In this case, most likely what happened is that you defined the `safe_upstairs` macro in your rc file at some point (it's an example in [url=https://github.com/crawl/crawl/blob/master/crawl-ref/settings/advanced_optioneering.txt]this file[/url], maybe you included this), bound it, and then removed the lua for the command from your rc.
