### ISSUE TITLE
Ozocubu's Armour dispelled by phantom (blink other) attack

### ISSUE THREAD

**Issue by rdaland** [crawl/crawl#2942]
**PLATFORM and OS or BROWSER:**
local tiles
Mac OS 12.5.1

**DCSS VERSION AND GAME INFORMATION:**
0.29.1

**DESCRIPTION:**
Playing as MfIE, I cast Ozocubu's Armour to beef up my AC in preparation for a battle with a phantom.
A successful attack by the phantom resulted in a character blink as per usual. What I did not expect, and somewhat believe is a bug, is that the AC reset back to baseline (baseline: 2; after Ozocubu's Armour: 11; after phantom blinked me: 2).

The spell's description on Crawlwiki is as follows:
>Envelops the caster's body in a protective layer of thick ice, granting a substantial bonus to armour as long as they remain in their current location. The ice will crack and fall away if the caster moves to a new position. The spell decreases in effectiveness in heavier armour, granting a lower bonus the higher the encumbrance rating of the caster's armour. 

Technically, being blinked by an external attack is a change in position, so one could argue this is expected behavior. On the other hand, it is not a willful action by the caster, and so one could also argue that it is not the caster who has deliberately moved to a new position.

My general sense is that the purpose of the cracking mechanic is to require the caster to spend an extra turn to rebuff, if they move for tactical gain after the original cast. And in this case, the phantom blinking attack is serves to nullify or add variance to the potential tactical gains of moving. From a flavor perspective, I imagine the ice armor as encasing the caster, just like their clothing. From both perspectives, my sense is the ice armour should not be dispelled by a blink. Or, if devs decide that the armour should be dispelled by the phantom's Blink Other attack, at least this should be noted to the user in the console. (That is, "your icy armour was lost when the phantom's attack teleported you", or something similar.) I will attach by chardump.

**EXTRA FILES:**
[Ceonnaes.txt.zip](https://github.com/crawl/crawl/files/10420979/Ceonnaes.txt.zip)

**Comment by semitonal** [comment]
This is working as intended (see 8403051) - Ozocubu's Armour just happens to be less effective against monsters like phantoms and tramplers that can forcibly move the player. I think that the current message is general enough to be accurate as-is (and it'd be fairly involved to change it depending on what caused the movement).

**Comment by rdaland** [comment]
Ok. Thanks for taking a look!
