### ISSUE TITLE
- should toggle unrecognized in \ menu

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#2949]
**PLATFORM and OS or BROWSER:**
online console, MacOS terminal 

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-672-gc3a7216ad8
server cbr2, user jejorda2

**DESCRIPTION:**
When I press \\, I see a list of recognized items as expected.
When I press -, I expect the list to change to unrecognized items.  Instead, the list does not change at all.

I am trying to see what items are left to identify so I can decide how to use scrolls of identify.

This is what I see when I press \\:
<img width="1002" alt="Screen Shot 2023-01-18 at 1 46 41 PM" src="https://user-images.githubusercontent.com/19559511/213267959-b598c541-e6c1-4da7-8687-76087803d4ff.png">
The instructions at the bottom make me think - is still intended to toggle to unrecognized items.  Here is what I see after pressing - in this menu:

<img width="1002" alt="Screen Shot 2023-01-18 at 1 48 19 PM" src="https://user-images.githubusercontent.com/19559511/213268132-65d90962-a30f-4a7e-ab19-9b4684ffede3.png">

**Comment by PleasingFungus** [comment]
Thanks for reporting! I believe @rawlins ' https://github.com/crawl/crawl/commit/50ae3c0e086c7b5ac7115b11f10fcf12238ffb4e fixes this.
