### ISSUE TITLE
can't join gods on alter by pressing enter. "J" still works

### ISSUE THREAD

**Issue by merlinm** [crawl/crawl#2951]
**PLATFORM and OS or BROWSER:**
conole, online (crawl.akrasiac.org)

**DCSS VERSION AND GAME INFORMATION:**
trunk

**DESCRIPTION:**
can't join gods on alter by pressing enter. "J" still works

**Comment by merlinm** [comment]
looks resolved

**Comment by rawlins** [comment]
Thanks for the report; resolved by 83e5d6458590a
