### ISSUE TITLE
please consider enabling `discussions` in repo

### ISSUE THREAD

**Issue by scarf005** [crawl/crawl#2952]
## Problem
currently discord and irc is mainly used for ideas, q&a, and dev questions.
however, they are not suitable for these tasks, because 

1. irc chat log is volatile, iirc there's log file but there's hundreds, however searching the info you want from these files are very hard
2. discord has no structured way to store each threads. there are forum and threads feature, but it's not used, thus previous information is lost.
3. questioning in irc and discord is very hard since you have to be in right time. you have to make sure no another discussion is going on, core devs are there, and even then you may not get a single reply.
4. developing documentation is scattered accross tavern, subreddit, irc, and discord, which makes finding information even harder.

conclusion: it's very hard to develop crawl efficiently in current communication methods.

## Advantages
use github's [discussions](https://docs.github.com/en/discussions) feature.
while it looks like yet another forum, it has following advantages.

![image](https://user-images.githubusercontent.com/54838975/213358122-cf361d7d-d36f-4829-8491-5eee678e4dce.png)
[(example of next.js's discussions)](https://github.com/vercel/next.js/discussions)

1. single source of trust: alleviates burden of having to search through multiple said methods earlier to find dev documentation
2. locality: it's directly on `crawl/crawl`, which makes accessing it very easy for developers.
3. mentioning: discussions are treated as same as issues or pr link-wise. you can reference them using `#(number)`s. it makes mentioning them easier.

## Details
discussions could use default categories, maybe except `show-and-tell` (r/dcss kinda already does that)

- `Ideas`: directly creating PR has severe risks, such as duplicate fixes, and out-of-scope PRs which get closed. having Ideas tab to discuss such PRs help streamlining PR process.
- `Help`: developer questions. no need to worry if it's hidden under flood of chats.

**Comment by PleasingFungus** [comment]
Hi! Thanks for suggesting this!

I agree with many of your points (eg IRC search being quite cumbersome). However, there are some issues with your proposal.

Firstly, opening up a new forum means that there's another place to moderate. This is more work for whoever has to do that work - dealing with requests for help, arguments, trolls, etc.

Second, it's another place for discussion to be fragmented in. Interested people might never find the discussion here.

> 1. single source of trust: alleviates burden of having to search through multiple said methods earlier to find dev documentation

This is only true if we shut down the IRC, the discord, the reddit, and Tavern, right? Otherwise, we've just added *another* place to search. (C.f. [xkcd](https://xkcd.com/927/).)

> developing documentation is scattered accross tavern, subreddit, irc, and discord, which makes finding information even harder.

I don't really understand what you mean here, sorry. What is 'developing documentation'? Do you mean *discussions of dev plans/ideas*? Or do you mean *documentation for how to develop crawl?* I believe the latter is all [in the repo](https://github.com/crawl/crawl/tree/master/crawl-ref/docs/develop) at present.

> questioning in irc and discord is very hard since you have to be in right time. you have to make sure no another discussion is going on, core devs are there, and even then you may not get a single reply.

It's completely possible to have discussions in IRC or Discord asynchronously. I skim the scrollback, and you can use !tell and @ mentions for anything truly urgent in IRC and Discord respectively (though probably best to use this only in special cases :) ).

The root issue here is that the devs have limited time and energy. Adding another discussion forum will make this worse, not better. :)

Cheers!

**Comment by scarf005** [comment]
> I don't really understand what you mean here, sorry. What is 'developing documentation'? Do you mean discussions of dev plans/ideas?

yes, i meant the former. what i meant was a reliable way to discuss a PR before actually working on it. if discussions are too much work to maintain, i suggest at least allow issues with feature request label.

### at least issues are needed
> It's completely possible to have discussions in IRC or Discord asynchronously.

it might be true for individual contributor and lead devs, but how about other contributors? i've read through a few PRs (to be specific, #2946, #2944, #2934, #2903, #2786, #2920, #2911, #2873, #2902 #2898, #2616, #2889, #2882, #2883). all but #2920 had a link to a discussions thread related to it (in case of 2920, paste of irc log). it's simply not feasible for other contributors to follow the discussions of certain PRs.

### 
this is troublesome because it's like making new recipe(PR) before the resturant owner(lead dev) asks it. let's take this analogy further and look at typical PR process:
```
1. chef(contributor) asks owner about their new idea for recipe (issue labeled feature request)
2. owner, chef and customers (other contributors) discuss together to narrow down which recipe they exactly wants. (PR directions discussion in issue)
3. chef cooks the recipe, owner and other customers inspects it. only minor modification has to be made (code review)
4. owner accepts new recipe for their resturant (PR merged)
```
now compare it to current DCSS PR process:
```
1. chef cooks recipe without talking to owner. (they might have, however as those list of PRs say, others have no way to figure out how)
2. chef waits endlessly for owner's review (due to limited dev time and energy) while food is getting stone cold (merge conflicts will happen while waiting)
3. owner and chef discuss about modification, however due to lack of previous discussion, it's hard for other customers to discuss it together.
```

### conclusion
discussions about a PR can be effortlessly done by [linking a feature request issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). please reconsider allowing feature request issues. 

thanks for your time!

**Comment by PleasingFungus** [comment]
Thanks for the in-depth response!

> all but https://github.com/crawl/crawl/pull/2920 had a link to a discussions thread related to it...

I don't understand. I looked through half of those PRs, and I don't see hyperlinks to discussions from any of them. I agree that some of them have had discussions outside the PR, either before or after the PR was filed, but that's the nature of having multiple discussion platforms. Regardless of whether we opened 'feature request issues', unless we shut down the Discord and the IRC, we would still have discussion in multiple places.

> it's simply not feasible for other contributors to follow the discussions of certain PRs.

I don't understand why this matters. If you aren't writing the PR, and you aren't reviewing it, why do you need to follow it?

> this is troublesome because it's like making new recipe(PR) before the resturant owner(lead dev) asks it...

I agree that writing a PR without discussing it first with the devs is a poor idea! Our [contributions guide](https://github.com/crawl/crawl/blob/master/crawl-ref/docs/develop/contribution-process.md) notes exactly this - along with a few out of date points, such as references to the Tavern and the old wiki.

However, once again, you are perfectly capable of communicating with the developers without needing to open GitHub feature issues. As I said in my previous comment, you can propose your idea asynchronously in IRC or Discord, just as you would via Discord. I do not understand why you need feature issues for this.

Best wishes,
P. Fungus :)

**Comment by rawlins** [comment]
Just to add a practical suggestion to this discussion, if dealing with IRC is not to your taste you may prefer to connect via the matrix bridge: https://libera.chat/guides/faq#can-i-connect-with-matrix or consider using an IRC bouncer.

We have considered off and on adding a forum somewhere to replace tavern, and this could still happen eventually. However, I'm not sure github discussions would be the right place for that and it needs to be a carefully considered choice and not just development-oriented (previous discussions have learned towards Discourse). In addition, moderating GDD/CYC in tavern was (I believe) one of the highest moderation burdens of any crawl discussion location ever, while it was active, and I expect that this would transfer to any FR-oriented open discussion forum. Feature request discussions for game development can be .. fraught -- and for that matter, tavern didn't seem to be a place that was very good for actual practical discussion of patches. So no one is extremely eager to start this up again.
