### ISSUE TITLE
[linux] pipewire support

### ISSUE THREAD

**Issue by basiliscos** [crawl/crawl#2954]
**PLATFORM and OS or BROWSER:**

```
Linux xps 6.1.4_1 #1 SMP PREEMPT_DYNAMIC Wed Jan 11 00:28:48 UTC 2023 x86_64 GNU/Linux
```

void linux distribution

**DCSS VERSION AND GAME INFORMATION:**
crawl-tiles-0.29.1_1

**DESCRIPTION:**

Everytime I launch `crawl-tiles` it hangs endlessly on `loading database` phase and ... nothing happens. It started to hang when I switched from `pulseaudio` to `pipewire`  (with pulseaudio compatibility support via `pipewire-pulse` daemon). 

I was able to launch it via `strace`, I managed to get the following information:

```
openat(AT_FDCWD, "/home/b/.config/pulse/cookie", O_RDONLY|O_NOCTTY|O_CLOEXEC) = 14
...

poll([{fd=14, events=POLLIN|POLLPRI}], 1, 2147482270) = 1 ([{fd=14, revents=POLLIN}])
recvmsg(14, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="#\203O\1\n\0\0\0\21\0\2\0gK\345\2\0\0\0\0\n\0\2\0\0\0\0\0\0\0\0\0"..., iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 72
recvmsg(14, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
```

Last message with `EAGAIN` repeat endlessly.

**Comment by rawlins** [comment]
Thanks for the report! I'm having a hard time looking at this and seeing this as a likely crawl bug, though it's not impossible; crawl doesn't use sound at all on the default linux build settings (though it looks like the void package may enable it), and definitely has no direct interaction with any of the mentioned libraries -- certainly doesn't issue that open call. It's possible there's some incompatibility with the version of SDL that package is built against; this would probably require someone who knows about these libraries to debug though.

You may want to contact the maintainer of the void package for crawl and see if they have any suggestions (if this is a general issue on void then they may want to drop `SOUND=y` from the [package build](https://github.com/void-linux/void-packages/blob/master/srcpkgs/crawl-tiles/template) script). Also, if you are able to build crawl yourself the default build settings most likely won't have this problem.

**Comment by basiliscos** [comment]
@rawlins Thank you. I submitted the issue, cross-posting the link here https://github.com/void-linux/void-packages/issues/41989

**Comment by jv84** [comment]
No problems on Arch Linux. Can you close this?
