### ISSUE TITLE
Palentonga barding issue

### ISSUE THREAD

**Issue by ChiakiHiro** [crawl/crawl#2958]
**PLATFORM and OS or BROWSER:**
Local Tiles.

**DCSS VERSION AND GAME INFORMATION:**
0.29.1

**DESCRIPTION:**
I know Palentongas are being reworked, however I don't want to spend a multi hour run to potentially recreate this on the trunk, and I did not see any sort of fix when I checked the changelogs. The bug seems to be whenever the palentonga grows talons or hooves via mutation, I was worshiping Jiyva, it kicks your barding off as if it's your boots. This was very annoying when I was potentially in danger and my barding would randomly explode off of me, it happened multiple times with hooves and would assumedly with talons, I believe.

**EXTRA FILES:**
None to offer

**Comment by PleasingFungus** [comment]
Fixed by 840a4f330f4. Sorry for the delay, and thanks for reporting!
