### ISSUE TITLE
"Retreating" monsters still able to run for several turns when put to sleep

### ISSUE THREAD

**Issue by erichfiederer** [crawl/crawl#2972]
**PLATFORM and OS or BROWSER:**
CAO server chrome

**DCSS VERSION AND GAME INFORMATION:**
http://crawl.akrasiac.org/rawdata/Boodz/morgue-Boodz-20230129-060511.txt

**DESCRIPTION:**
When I cast ensorcelled hibernation on monsters who run away like orb spinners and merfolk avatars, they are still able to run away for several turns while asleep.

**EXTRA FILES:**

**Comment by SergioJThompson** [comment]
I just tested this and can confirm that orb spiders can move while asleep on Tiles 0.29.1.

**Comment by erichfiederer** [comment]
Fixed bad morgue link. Currently an issue in trunk.
