### ISSUE TITLE
Arrived in a vault in Pandemonium that some characters can't leave

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#2979]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
Version: 0.30-a0-737-gf23d940 (webtiles)
Seed: 9865686082877275760

**DESCRIPTION:**
Arrived in a vault in Pandemonium that required flight to leave but none of the potions it contained were flight.

**EXTRA FILES:**
![Screenshot (43)](https://user-images.githubusercontent.com/26264063/216260414-1aa28310-2594-4777-abf6-89b60489f155.png)
https://crawl.project357.org/morgue/Wizard1ke/morgue-Wizard1ke-20230201-033253.txt

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
