### ISSUE TITLE
Inescapable area on Geh:7 after teleport

### ISSUE THREAD

**Issue by edwinsage** [crawl/crawl#2980]
**PLATFORM and OS or BROWSER:**

console, CAO server

**DCSS VERSION AND GAME INFORMATION:**

Dungeon Crawl Stone Soup version 0.29.1-2-gbd0b4ee654 (console)

**DESCRIPTION:**

Upon reaching the final floor of Gehenna, my flying character was instantly teleported by a sourceless malevolence, and I was sent out to a lava-filled area.  After exploring it completely, I have found no way back to the main part of the floor or to any stairs.  There are numerous iron grates around, but I have no wand of digging.  I do happen to have the Blink spell memorized which I think can get me past grates, but I suspect the game did not take that into account.  Even now, it would be possible to forget the spell and fill the slots and then be unable to ever leave the floor.  Looking through the source, the map appears to be called `evilmike_geh`.

**EXTRA FILES:**

http://crawl.akrasiac.org/saves/edwinsage-crawl-0.29-230202-0449.tar.bz2

**Comment by robbiemu** [comment]
line 957: https://github.com/crawl/crawl/blob/master/crawl-ref/source/dat/des/branches/geh.des

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
