### ISSUE TITLE
Identified scroll of immolation appear on faded altar

### ISSUE THREAD

**Issue by PotatoGolem** [crawl/crawl#2982]
**PLATFORM and OS or BROWSER:**

webtiles

**DCSS VERSION AND GAME INFORMATION:**

0.29.1

**DESCRIPTION:**

This has happened 3 times I've played the game. An identified scroll of immolation appear on the faded altar, even though I have not yet identified any scrolls of immolation. When I auto explore the characters does not pick up the scroll, but I can pick it up manually. 

**EXTRA FILES:**

[scroll of immolation](https://user-images.githubusercontent.com/124343869/216546017-e89b86a5-b679-4f7c-ad69-03f493cccb74.png)

**Comment by Picklenugget1** [comment]
Pretty sure this is intended behavior. If a vault is guaranteed to place something it will be pre-identified.

**Comment by rawlins** [comment]
Thanks for the report! Yes, this is intended; the vault `hellmonk_ecumenical_altar_blasted` (https://github.com/crawl/crawl/blob/master/crawl-ref/source/dat/des/altar/ecumenical.des#L628) intentionally places an identified scroll of immolation. Vault designers occasionally do this when the item flavor aligns with the vault's flavor in some way (which I think is the idea here).
