### ISSUE TITLE
Attempting to put a waypoint closes the page

### ISSUE THREAD

**Issue by zlobryak** [crawl/crawl#2984]
### PLATFORM and OS or BROWSER:
Google Crome, 109.0.5414.120, 64
Windiws 10.

### DCSS VERSION AND GAME INFORMATION:
Dungeon Crawl Stone Soup version 0.30-a0-738-g116ff8c

### DESCRIPTION:
When you press shift-X and then  ctrl-W, the page closes. This is the standard hotkey for closing a page in Chrome.

**Expected Result:** Waipoint added.
**Actual result:** Close page dialog box

**Comment by riverfiend** [comment]
My hunch is this is working as intended -- Pressing * then w allows you to place a waypoint and isn't eaten by chrome -- But there is definitely a bug here: The "assign a waypoint to which number" dialog doesn't appear (it isn't drawn over the top of the shift-X menu.

**Comment by zlobryak** [comment]
Yes, * allows adding waypoint trough w.
But this would not work
![image](https://user-images.githubusercontent.com/39959717/216789343-809cbb18-e07b-4b26-beca-ffd737a5feaf.png)

**Comment by rawlins** [comment]
There are several hotkeys that browser-based apps simply can't remap, and ctrl-w is one of those. Using `*` is the official way to enter control codes like this in webtiles. (ctrl-n, ctrl-t, ctrl-q are the others.) So there's nothing that can really change here in terms of ctrl-w handling. I may actually experiment with using `w` in the map view for the set waypoint command, which would dodge this issue.

Yes, @riverfiend there does seem to be a webtiles bug where the prompt isn't displayed.
