### ISSUE TITLE
Ru Aura of Power intimidates butterfly

### ISSUE THREAD

**Issue by Picklenugget1** [crawl/crawl#2988]
**PLATFORM and OS or BROWSER:**
Webtiles: CKO
**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-743-gbfdf073431
**DESCRIPTION:**
While autoexploring in the lair, I passed by a butterfly and noticed that it was "stunned by my conviction and failed to attack." Of course, butterflies don't have any attacks to make, so this makes no sense.
**EXTRA FILES:**

![Screenshot 2023-02-07 8 15 03 AM](https://user-images.githubusercontent.com/113951792/217256675-7d3f145d-3ee9-4a82-a485-a3232b45902a.png)

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
