### ISSUE TITLE
When you press Ctrl+T it wold open closed tab.

### ISSUE THREAD

**Issue by zlobryak** [crawl/crawl#2990]
### PLATFORM and OS or BROWSER:
Google Crome, 109.0.5414.120, 64
Windiws 10.

### DCSS VERSION AND GAME INFORMATION:
Dungeon Crawl Stone Soup version 0.30-a0-738-g116ff8c

### DESCRIPTION:
When you press Ctrl+T it wold open closed tab. This is the standard hotkey for open closed tab in Chrome.

**Expected Result:** Set your trevel speed to your slowest ally
**Actual result:** Open closed tab

### Screenshot from help
![image](https://user-images.githubusercontent.com/39959717/217422265-5898542b-7db8-4d14-9d95-9d17cf26dc4c.png)

**Comment by riverfiend** [comment]
For what it's worth, you can use * t rather than Ctrl-t.

**Comment by PleasingFungus** [comment]
Resolved by 74ab47f37005686658c84f8f461c648da268b509. Thanks for reporting!
