### ISSUE TITLE
orb spiders act buggy when frightened

### ISSUE THREAD

**Issue by ZillyBean** [crawl/crawl#2992]
local tiles, 0.29.1

Orb spiders seem to behave strangely when affected by fear. Sometimes they actively chase the player and even attack in melee, all while under the fear effect. Testing in wizard mode I can't seem to get any other monster to do this. To be clear, this isn't a result of the monster feeling it can't escape and choosing to fight. It's easy to tell since there's message that states when that happens. ("cornered, the monster turns to fight" or whatever)

message history showing spider effected by fear and immediately attacking (the python was unaffected)
![fear scroll 2](https://user-images.githubusercontent.com/122182898/217568817-2f3f4d5a-403c-4faa-9f42-4c9e3b0ac5f1.png)

frightened (!) spider attacking me in the middle of an empty room with several escape paths
![fear scroll](https://user-images.githubusercontent.com/122182898/217568820-38499e3c-c2d8-4695-a60e-1de7b17818d4.png)

**Comment by PleasingFungus** [comment]
This was an extremely silly bug. Thanks for reporting, and sorry for the delay in response! Should be fixed now.
