### ISSUE TITLE
Tengu gets the message "You have no appropriate body parts free." from Beastly Appendage

### ISSUE THREAD

**Issue by DracheReborn** [crawl/crawl#3000]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-782-ge64f9170bb

**DESCRIPTION:**
On casting Beastly Appendage when playing as Tengu, the message "You have no appropriate body parts free." appears. Previous behavior was that Tengu get horns. 

This [old commit](https://github.com/crawl/crawl/commit/0a87f5eab1e328c699095b51f6c3bab50546dac3) appears to achieve this by having MUT_BEAK _not_ return EQ_HELMET. However, in the current mutation.cc line 97, MUT_BEAK does return EQ_HELMET, thus horns are blocked and Tengu get nothing from Beastly Appendage. This seems to be an unintended result of code streamlining.

**EXTRA FILES:**

**Comment by PleasingFungus** [comment]
Resolved by 18800231877e12caceb48c2f929f842d55aac934. Sorry for the delay, and thanks for reporting!
