### ISSUE TITLE
Jiyva: Attacking hostile slimes while under penance increases penance

### ISSUE THREAD

**Issue by AlexanderPosch** [crawl/crawl#3003]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-782-ge64f9170bb

**DESCRIPTION:**
While worshipping Jiyva and under penance slimes are hostile, but since attacking them increases penance it can be rather hard to ever escape penance.

**EXTRA FILES:**
A screenshot from a recent game:
![image](https://user-images.githubusercontent.com/49498206/220093998-4c8368d2-a873-4ebd-9d1a-4386a0a0bd1c.png)

**Comment by DracoOmega** [comment]
Jiyva no longer places the player under penance, so I'm closing this.
