### ISSUE TITLE
Electric eel crawls on land when confused

### ISSUE THREAD

**Issue by smannAcgl** [crawl/crawl#3014]
Possibly not a bug, but when I confused an electric eel, it moved to a non-water square.  Version 0.30-a0-782-ge64f9170bb

![dcbug](https://user-images.githubusercontent.com/6489182/220717532-c020f88a-eb0e-43b6-880e-626db61f9096.png)

**Comment by riverfiend** [comment]
This is intended behavior, it gets confused, flops out of the water, and suffocates. Similar behavior can be observed by confusing land monsters near deep water (hint: they will stumble into the deep water and drown).

**Comment by semitonal** [comment]
As noted by riverfiend, this is intended behaviour.
