### ISSUE TITLE
Ring of Shadows is halving stealth

### ISSUE THREAD

**Issue by enigmoo123** [crawl/crawl#3018]
**PLATFORM and OS or BROWSER:**
<Webtiles>

**DCSS VERSION AND GAME INFORMATION:**
<.29 stable>

**DESCRIPTION:**
<Instead of boosting stealth, Ring of Shadows is cutting it by about half.>

**EXTRA FILES:**
<http://crawl.akrasiac.org/saves/enigmoo-crawl-0.29-230224-2253.tar.bz2)
-->

**Comment by semitonal** [comment]
Per https://crawl.develz.org/mantis/view.php?id=12715, stealth isn't actually being halved here.
