### ISSUE TITLE
Enslaving the Royal Jelly does not always open slimy rune vault

### ISSUE THREAD

**Issue by Talandazar** [crawl/crawl#3025]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.28, still occurs in 0.30 trunk

**DESCRIPTION:**
Binding the Royal Jelly's soul for Yred sometimes opens the slimy rune vault, sometimes not.

**EXTRA FILES:**
In both of these two games, the Royal Jelly was enslaved.

The rune vault opened:
https://underhound.eu/crawl/morgue/RepoMan/morgue-RepoMan-20220501-151401.txt

The rune vault did not open:
https://cbro.berotato.org/morgue/Jingleheimer/morgue-Jingleheimer-20220803-134023.txt

The same issue was reported on reddit on Feb 25, 2023 for trunk.
https://www.reddit.com/r/dcss/comments/11bv9jt/trunk_bound_royal_jelly_vault_walls_dont_drop/

**Comment by DracoOmega** [comment]
Hopefully fixed by 5325a588fe410bdf8263c29792d49b88364c1003
