### ISSUE TITLE
Kiku gifts don't check against spells already in your library

### ISSUE THREAD

**Issue by Robth1** [crawl/crawl#3031]
**PLATFORM and OS or BROWSER:**
Webtiles on firefox

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-834-g1789cb11db on crawl.kelbi.org

**DESCRIPTION:**
After receiving a surprisingly small batch of gifts from Kiku (two spells, when I thought I'd more or less guaranteed myself Animate Dead by having several other eligible necromancy spells in my library), I got curious to figure out how kiku gifting actually works, and looked up the logic in religion.cc.  (Function is at line 1556 of religion.cc.)  Kiku will always give necrotise in the first gift batch, with no test of whether you actually have it or a uselessness check (although I don't think necrotise would ever be useless to a Kiku worshipper.)  They will then additionally gift several more spells with a uselessness check but no check against whether it's in your library.  This creates, unless I'm missing something, the possibility that a player could receive one or zero spells despite having missing spells from Kiku's "first gift" list.

It's not clear to me whether this behavior is intended.  If I were making a suggestion it would be as follows:

"Eligible spell" = spell that is not useless AND not in the player's library

Gift is composed as follows:

1. One eligible spell out of the set {SPELL_NECROTISE,SPELL_ANIMATE_DEAD}, if either is eligible
2. Whichever is fewere: all eligible spells or (2 + 1d2 - number of spells gifted by section 1) eligible spells out of the set {SPELL_KISS_OF_DEATH, SPELL_SUBLIMATION_OF_BLOOD, SPELL_ROT, SPELL_VAMPIRIC_DRAINING} plus any eligible spell from section 1 not gifted in section 1.

This strikes me as more intuitive to the player and should avoid a case where Kiku assembles a gift entirely composed of stuff that's already in your library.  It still maintains some randomness in the size and composition of the gift.  On the other hand I'm trying to win an iffy mummy build right now and am maybe dreaming of how the code could bail me out of some of my own life choices, so perhaps I'm trying to reverse an intentional nerf of Kiku.

If the suggestion I made above appeals, I can try to whip up a pull request implementing it.

**Comment by semitonal** [comment]
While it does mean that you can sometimes get smaller gifts if you've found lots of necromancy spells, this is intended behaviour, in particular so that starting as a Necromancer and then worshipping Kiku doesn't guarantee you a much more specific set of spell gifts.
