### ISSUE TITLE
Hep ancestor is immune to enemy's irradiate

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#3033]
PLATFORM and OS or BROWSER:
local tiles

DCSS VERSION AND GAME INFORMATION:
0.30-a0-800-g7c544603b3 (latest trunk)

DESCRIPTION:
When enemy monster casts irradiate on ancestor, ancestor recognizes it as being cast by the player, so it dodges it.

![1](https://user-images.githubusercontent.com/97007398/222358561-ab6429fb-dc38-4a9f-91a1-dd2a8d07ee66.PNG)
![2](https://user-images.githubusercontent.com/97007398/222358584-c1bec933-ff47-443c-85ba-3263968e0f04.PNG)

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
