### ISSUE TITLE
Is there a problem with curse scrolls dropping?

### ISSUE THREAD

**Issue by ddildine11** [crawl/crawl#3034]
**PLATFORM and OS or BROWSER:**

**DCSS VERSION AND GAME INFORMATION:**

**DESCRIPTION:**

**EXTRA FILES:**

**Comment by nicolae-carpathia** [comment]
Curse scrolls were removed ages ago. The only way to curse items these days is to follow Ashenzari.

**Comment by ddildine11** [comment]
Please close this isssue
