### ISSUE TITLE
Skyshark inflicts sleep

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#3036]
**PLATFORM and OS or BROWSER:**
online console, MacOS Terminal

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-847-g17996783a1
CBR2, MfBe, user jejorda2
Lair:3

**DESCRIPTION:**
In a fight with a skyshark with a Bullfrog on screen, I saw this message sequence:
 
The skyshark tastes blood and grows stronger!
 You fall asleep.

No equipment or mutations mention sleep.
I don't think I should have fallen asleep.

https://cbro.berotato.org/saves/jejorda2-crawl-git-17996783a1-230304-0025.tar.bz2

**Comment by semitonal** [comment]
Fixed in 34551f55!
