### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by Korb** [crawl/crawl#3037]
Without a preview, only by a text description, it is difficult to decide whether to download and install the application or not. I propose to add a few screenshots that most fully describe the appearance and functionality of the application. With pictures Dungeon Crawl Stone Soup will be able to be shown on the [f-droid.org/en/packages/](https://f-droid.org/en/packages/) and on the main page of the f-droid app. More people will be able to see and find Dungeon Crawl Stone Soup.

https://f-droid.org/packages/org.develz.crawl/

**Comment by robertxgray** [comment]
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

It looks like f-droid requires the screenshots to be added to the source repository. I can do it if the core developers agree. Maybe a different repository can be used via git submodules.

**Comment by robertxgray** [comment]
https://forum.f-droid.org/t/metadata-in-different-repo/19206

According to this post, a different repository can be used and it doesn't need to be a submodule. It can be cloned during the build process.

How do you feel about creating a new repository for screenshots and metadata? It would also solve #2700.

**Comment by rawlins** [comment]
Just to clarify, is this issue a request simply have some good screenshots (e.g. if we just point you to screenshots is that enough for your purposes)?

**Comment by Korb** [comment]
> Just to clarify, is this issue a request simply have some good screenshots (e.g. if we just point you to screenshots is that enough for your purposes)?

I myself can google screenshots or make them by installing the application. My goal was not to get screenshots, but to post screenshots on the app page in the F-Droid FOSS-app directory. Exactly this.

**Comment by robertxgray** [comment]
People at Fdroid confirmed they can store the screenshots: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12336#note_1315496510

I'm also considering the option to auto-scrape the info required by Fdroid from Google Play during the build process.

**Comment by robertxgray** [comment]
I made new screenshots to showcase the launcher and they have been accepted in the F-Droid data repository. They are not showing in the website yet but I guess they will soon.
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12769

**Comment by robertxgray** [comment]
The F-droid website is showing the screenshots.
