### ISSUE TITLE
Soul-bound monsters should not be targettable by simulacrum

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#3038]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
Trunk

**DESCRIPTION:**
- Kill pharoah ant, binding the souls of monsters.
- Target one of those monsters with Simulacrum
- This is allowed with no warning, but has no effect (killing the monster produces a hostile simulacrum)

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
