### ISSUE TITLE
Meteoran keeps reduced LOS after picking up The Orb

### ISSUE THREAD

**Issue by DevastatorOne** [crawl/crawl#3041]
**PLATFORM and OS or BROWSER:**
Local tiles, Windows 10
but first seen on a 0.29 tourney

**DCSS VERSION AND GAME INFORMATION:**
crawl_tiles-0.30-a0-859-gf88a04b62d

**DESCRIPTION:**
If Meteoran with reduced LOS (Zot timer) takes The Orb, this reduced LOS persists until it is changed with items

**EXTRA FILES:**
It first happened to me on the tourney, when I had the toughest play in my entire dungeoncrawlin' life, but it took me ages to report.
Video for easier understanding
https://www.youtube.com/watch?v=cnGAGO3MQx8

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
