### ISSUE TITLE
Plasma Beam does not see fire immune enemies as a susceptible target

### ISSUE THREAD

**Issue by Tttiimmm** [crawl/crawl#3057]
**PLATFORM and OS or BROWSER:**
webtiles, firefox, kelbi server

**DCSS VERSION AND GAME INFORMATION:**
trunk, 0.30-a0-937-ga0a21ad780

**DESCRIPTION:**
When trying to cast plasma beam on an efreet or a fire crab, it sees it as immune to the spell and it requires Z to cast it.

**EXTRA FILES:**
https://crawl.kelbi.org/crawl/morgue/DaftChap/morgue-DaftChap-20230324-234956.txt

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
