### ISSUE TITLE
Fire and steam clouds confuse monsters

### ISSUE THREAD

**Issue by DracheReborn** [crawl/crawl#3058]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-946-gec5dcfc036

**DESCRIPTION:**
I noticed steam clouds and fire clouds confusing enemy mobs. It might be related to https://github.com/crawl/crawl/commit/298cdec9adcf027655bebcf0ea3c2ce1d60239f5

In _actor_apply_cloud_side_effects(), I noticed a break statement is removed (line 1068 in the old cloud.cc) which might be causing the case fallthrough. I don't have the code setup to debug properly though, sorry.

**EXTRA FILES:**
From log:
 The five-headed hydra is engulfed in blazing flames.
 The five-headed hydra appears confused.

**Comment by jejorda2** [comment]
My player was confused by a steam cloud in 0.30-a0-948-g4fa250aae5
https://cbro.berotato.org/saves/jejorda2-crawl-git-4fa250aae5-230326-1806.tar.bz2
