### ISSUE TITLE
friendly killer klown pies "you" viciously

### ISSUE THREAD

**Issue by yrdzrfxndfvh** [crawl/crawl#3060]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29.1

**DESCRIPTION:**
friendly killer klown attacking other enemies will still pie "you" viciously (doesnt actually attack you, just shows up in the text box like that)

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/27397852/227828930-2c0bbf9c-cef1-4181-9d74-2d90283bf51f.png)
i recreated this in a wizmode game on local tiles because when i actually saw this it was a few days ago and i forgot to take a screenshot

**Comment by semitonal** [comment]
Fixed, thanks for reporting!
