### ISSUE TITLE
WebTiles CBR2 crawl-git-d452b5e7fa Crash on attempting to go down stairs to d:5

### ISSUE THREAD

**Issue by Domiryuu** [crawl/crawl#3064]
**PLATFORM and OS or BROWSER:**
webtiles: cbr2 

**DCSS VERSION AND GAME INFORMATION:**
Version: Dungeon Crawl Stone Soup 0.30-a0-964-gd452b5e7fa
(current git version on cbr2)

**DESCRIPTION:**
game crashes on attempting to go down stairs to d:5, information on dith is gone, and when following dith ^ shows an error without crash "buggy UI of type describe-god" https://imgur.com/2Vme8RN 

**EXTRA FILES:**
https://cbro.berotato.org/morgue/bakla/crash-bakla-20230330-141635.txt
https://cbro.berotato.org/saves/bakla-crawl-git-d452b5e7fa-230330-1533.tar.bz2

**Comment by rawlins** [comment]
Thanks for the report! Both bugs mentioned here have been fixed, in 42e074c17a0 and 745981c80b.
