### ISSUE TITLE
"You riposte" when the attacker is not in range

### ISSUE THREAD

**Issue by damerell** [crawl/crawl#3066]
If you are attacked by a polearm-equipped monster from range 2, block the attack, but do not have a reach weapon yourself, you can be told "You riposte". No actual attack takes place, so AFAICT this is only a text bug. This is easily reproduced in wizmode with the Fencer's Gloves, a corridor, a test blob, a shield, and a halberd gnoll.

I think this is because melee-attack.cc handle_phase_dodged does adjacency checks before retaliation, but if you block, it just invokes maybe_riposte. The other pre-retaliation checks seem like they might be worth doing, too.

(The question of whether you should be able to retaliate at range with a polearm I leave up to you).

**Comment by PleasingFungus** [comment]
You definitely should. :) Thanks!
