### ISSUE TITLE
Octopode Beastly Appandage bug

### ISSUE THREAD

**Issue by metehankahraman** [crawl/crawl#3079]
Local tiles, Windows 11

version: 0.30-a0-1018-g25214051b3

Bug: Casting beastly appandage with an octopode character melds equipped hat into octopodes body,
Beastly Appandage gives a spiked tentacle to octopodes so it shouldn't meld hats into body.

How to reproduce: Start as octopode transmuter, equip a hat, cast beastly appandage.

**Comment by PleasingFungus** [comment]
Dupe of #2919 and #1699. Sorry. I'll fix this in a nicer way someday.
