### ISSUE TITLE
Arcjolt with Majin-Bo does not heal

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#3083]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
Current trunk

**DESCRIPTION:**
Arcjolt does not trigger spellvamp. This is very surprising for a direct damage spell.

**Comment by semitonal** [comment]
Fixed (and for a few other damage spells), thanks for reporting!
