### ISSUE TITLE
CAO crashing repeatedly during weird lag spikes

### ISSUE THREAD

**Issue by ryak2** [crawl/crawl#3093]
ERROR in 'tileweb.cc' at line 234: Socket write error: Resource temporarily unavailable

We crashed! This is likely due to a bug in Crawl.
Please submit a bug report at https://github.com/crawl/crawl/issues or at
https://crawl.develz.org/mantis/ and include:
- The crash report: /dgldir/ttyrec/Ryak/crash-Ryak-20230417-042454.txt
- Your save file: /crawl-master/crawl-0.29/saves/Ryak.cs
- A description of what you were doing when this crash occurred.

**Comment by ryak2** [comment]
It looks like the server may be having resource issues?  I was just playing normally not doing anything particularly special during the crash.

**Comment by rawlins** [comment]
CAO is having some disk issues that, we hope, will be resolved soon (by replacing the disk). Latest estimate was some time this week. The symptom of the disk issue for webtiles is these crashes.

**Comment by rawlins** [comment]
The disk got replaced last weekend, and these spikes have abated, so I'm going to close this up.
