### ISSUE TITLE
Strange corrosion display bug

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#3095]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-1104-g706747fef1

**DESCRIPTION:**
- Descended to Slime:5, did some fighting
- Went back up to Slime:4, rested (and in particular, definitely didn't have any corrosion)
- Using X, viewed the situation on Slime 5
- It showed -32 corrosion.

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/23155525/232879702-53894088-de2c-4818-a673-1e18fa6dd9a5.png)

**Comment by PleasingFungus** [comment]
Fixedish in 48e7df34defa20a8deba30af653f07f48c2a0e04. Thanks!
