### ISSUE TITLE
Upgraded trunk game to most recent version; now persistently crashes on resume

### ISSUE THREAD

**Issue by gellingson** [crawl/crawl#3101]
**PLATFORM and OS or BROWSER:**

webtiles on https://crawl.kelbi.org/

**DCSS VERSION AND GAME INFORMATION:**

trunk

**DESCRIPTION:**

current active game, restarted (after just an hour or so suspended, so it should be just 1 version out-of-date), accepted update-to-current, and the game crashed-on-resume; replicable. Crash report:

https://crawl.kelbi.org/crawl/morgue/geewiz/crash--20230424-035210.txt

**EXTRA FILES:**

**Comment by gellingson** [comment]
Looks to be resolved by c8ec674a0c. Closing. Thanks!

**Comment by rawlins** [comment]
Yes, that commit should fix this (though unfortunately the bug is still live on CXC until it rebuilds..)
