### ISSUE TITLE
abyss_greek_temple doesn't place Ru

### ISSUE THREAD

**Issue by damerell** [crawl/crawl#3103]
The abyss_greek_temple vault in dat/des/branches/abyss.des doesn't place Ru. It seems unlikely this is by design (it's a very old vault and someone adding a god just has to know it exists) and adding one god would make it a more symmetrical design.

I was testing in tiles and personally also I think it looks very odd if the COLOUR line gets white and the FTILE line gets nerves. Suggest adding most of the alphabet to the COLOUR line to make it like the FTILE line.

**Comment by PleasingFungus** [comment]
Fixed, thanks!
