### ISSUE TITLE
Randart desc has slightly confusing text due to missing "-"

### ISSUE THREAD

**Issue by MarshP** [crawl/crawl#3105]
**PLATFORM and OS or BROWSER:**
Webtiles (EU)

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-1160

**DESCRIPTION:**
Randart desc has slightly confusing text due to missing "-" 

"rF: It makes you vulnerable to fire."

**EXTRA FILES:**

![Screenshot 2023-04-25 170544](https://user-images.githubusercontent.com/10521654/234336809-d4fffcd9-12f6-4e67-a11d-73b14a5c5cd2.png)

**Comment by rawlins** [comment]
I forgot to tag it, but this is resolved by: https://github.com/crawl/crawl/commit/791ea4fb0e9dc1387a23d46c5fd8b0c6ce7d434f
