### ISSUE TITLE
Map does not change level viewed using [ key

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#3110]
**PLATFORM and OS or BROWSER:**
online console, CBR2, MacOS Terminal

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-1161-g0704695555
https://cbro.berotato.org/saves/jejorda2-crawl-git-0704695555-230427-1245.tar.bz2

**DESCRIPTION:**
I press X to see the level map, and it appears as expected.
I press [ to view the map for the floor above, and the current floor is still displayed.
? still shows that "[ or ]     : Examine the next higher or lower level."
Exclusions and travel keys are still working.
In normal view, [ still shows worn armour, so it's not a broken key or terminal setting.
**EXTRA FILES:**
n/a

**Comment by rawlins** [comment]
In this save, what has happened is that you were shafted down two floors, from D:3 to D:5. I can verify by examining the save in wizmode that D:4 hasn't been visited at all. Hence, you can't view D:4. This is basically working as intended, though it is a missing feature that there's no way (that I know of) to view other floors in this sort of situation.
