### ISSUE TITLE
crash after using phial of floods, ERROR in 'mon-util.cc' at line 681: bogus mc (no monster data): invalid monster_type 1000 (1000)

### ISSUE THREAD

**Issue by windowmaker** [crawl/crawl#3122]
**PLATFORM and OS or BROWSER:**
webtiles, kelbi server, Chrome Version 111.0.5563.147 (Official Build) (64-bit)

**DCSS VERSION AND GAME INFORMATION:**
Version: Dungeon Crawl Stone Soup 0.30.0
WindowMaker on https://crawl.kelbi.org/

**DESCRIPTION:**
If I use phial of floods on an enemy in elf 3 (haven't tested everywhere, but happened twice when I did this on this level) I get a crashed game.

ERROR in 'mon-util.cc' at line 681: bogus mc (no monster data): invalid monster_type 1000 (1000)
Crash caused by signal #6: Aborted

Obtained 24 stack frames.
/usr/games/crawl-0.30(_Z17write_stack_traceP8_IO_FILE+0x28) [0x560a8f9aaf18]: write_stack_trace(_IO_FILE*)
/usr/games/crawl-0.30(_Z13do_crash_dumpv+0x3b3) [0x560a8f9b44a3]: do_crash_dump()
/usr/games/crawl-0.30(_Z20crash_signal_handleri+0x1ca) [0x560a8f9ab35a]: crash_signal_handler(int)
/lib/x86_64-linux-gnu/libc.so.6(+0x37840) [0x7f86d5151840]: 
/lib/x86_64-linux-gnu/libpthread.so.0(raise+0x10b) [0x7f86d52ec5cb]: 
/usr/games/crawl-0.30(+0x427d26) [0x560a8f9b3d26]: 
/usr/games/crawl-0.30(+0x427fbd) [0x560a8f9b3fbd]: 
/usr/games/crawl-0.30(_Z19mons_class_holiness12monster_type+0x6b) [0x560a8fce570b]: mons_class_holiness(monster_type)
/usr/games/crawl-0.30(_Z19mons_is_unbreathing12monster_type+0x9) [0x560a8fce58d9]: mons_is_unbreathing(monster_type)
/usr/games/crawl-0.30(_ZNK7monster18res_water_drowningEv+0x21) [0x560a8fcf8f41]: monster::res_water_drowning() const
/usr/games/crawl-0.30(+0x3d2e34) [0x560a8f95ee34]: 
/usr/games/crawl-0.30(_ZN4bolt16monster_post_hitEP7monsteri+0x3b1) [0x560a8f96c6f1]: bolt::monster_post_hit(monster*, int)
/usr/games/crawl-0.30(_ZN4bolt14affect_monsterEP7monster+0xa87) [0x560a8f9702f7]: bolt::affect_monster(monster*)
/usr/games/crawl-0.30(_ZN4bolt11affect_cellEv+0x219) [0x560a8f970f39]: bolt::affect_cell()
/usr/games/crawl-0.30(_ZN4bolt7do_fireEv+0xcf0) [0x560a8f974110]: bolt::do_fire()
/usr/games/crawl-0.30(_ZN4bolt4fireEv+0x1038) [0x560a8f9755a8]: bolt::fire()
/usr/games/crawl-0.30(_Z10evoke_itemiP4dist+0x2b43) [0x560a8fa65763]: evoke_item(int, dist*)
/usr/games/crawl-0.30(_Z11use_an_item15operation_typesP8item_def+0x146) [0x560a8fb54826]: use_an_item(operation_types, item_def*)
/usr/games/crawl-0.30(_Z15process_command12command_typeS_+0x330) [0x560a8ff63a60]: process_command(command_type, command_type)
/usr/games/crawl-0.30(+0x9d6a46) [0x560a8ff62a46]: 
/usr/games/crawl-0.30(+0x9d7265) [0x560a8ff63265]: 
/usr/games/crawl-0.30(main+0x17b) [0x560a8f91025b]: 
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f86d513e09b]: 
/usr/games/crawl-0.30(_start+0x2a) [0x560a8f910b1a]: 

**EXTRA FILES:**
[crash-WindowMaker-20230507-015722.txt](https://github.com/crawl/crawl/files/11413749/crash-WindowMaker-20230507-015722.txt)

**Comment by PleasingFungus** [comment]
I believe this was fixed in 38777b0aa055626789af6181ad675a162da88d68. Sorry for the trouble!
