### ISSUE TITLE
"99 orc v the Royal Jelly" arena crash

### ISSUE THREAD

**Issue by lua-rocks** [crawl/crawl#3127]
**PLATFORM and OS or BROWSER:**

crawl-tiles on manjaro 22.1.1

**DCSS VERSION AND GAME INFORMATION:**

crawl-tiles 0.29.1-2

**DESCRIPTION:**

Start arena game "99 orc v the Royal Jelly". Sometimes it works fine, but pretty often crashes.

**EXTRA FILES:**

[crash-Arena-20230510-235813.txt](https://github.com/crawl/crawl/files/11445919/crash-Arena-20230510-235813.txt)

**Comment by jv84** [comment]
You have an old version. It's already fixed. https://github.com/crawl/crawl/issues/2955

**Comment by lua-rocks** [comment]
Oh, sorry. Previously Manjaro updated its repositories much faster than now.
