### ISSUE TITLE
Add the game to steam

### ISSUE THREAD

**Issue by wiki-me** [crawl/crawl#3135]
Why I think it will be beneficial:

* it is very popular and it's website has a lot of visitors (similarweb ranks it as the 183 most popular website on the internet).

* Seeing a lot of good reviews can really tip the scales and make me (and probably others) take a chance on trying a game (it's basically [social proof](https://en.wikipedia.org/wiki/Social_proof)), it could lead to more exposure which will mean more developers and more feedback (former developer of naev [said](https://www.reddit.com/r/opensourcegames/comments/tcwkr6/naikari_020_open_source_space_trading_and/i0kb8dd/) it brought new developers).

* Steam is one of the only game review systems that i know of which is able to rank games only based on \"recent reviews\" (besides gog.com), so if a game starts badly and keeps getting developed and becomes good the old review don\'t prevent it from getting a good rating, this is especially good for open source games that can have a very long history of development (being developed for more then a 15 years is common).

* Another nice feature of steam is that you can find reviews for players that played more then a certain number of hours , some games can be half done and a review after three hours of play time might not reflect problems, a review after say 30h indicates you can pour some time into it without the game failing (and you will have to wait for a newer version and maybe play it until the point you reached before because save files are not always compatible with future versions).

* Some FOSS projects on steam have a price (for example the game [Mindustry](https://store.steampowered.com/app/1127400/Mindustry/) ). Maybe you could use that for funding and paying freelancers to create graphics and sound (iirc this is what shattered pixel dungeon does). 

* early feedback can be useful, there is a saying that if you are not embarrassed when releasing the software then you released it too late, steam can mark a game as early access (like *[*supertux*](https://store.steampowered.com/app/1572920/SuperTux/)* does) so there is no danger of disappointing players because the game isn't fully polished.

**Comment by Zireael07** [comment]
Mate, again with this copy-pasta (I've seen you post the same to e.g. Angband) ? Crawl is very much NOT a beta/early game so your latest paragraph does NOT apply at all and including it shows you didn't even try the game to whose repo you're posting (or look at commit history)

**Comment by wiki-me** [comment]
> Mate, again with this copy-pasta (I've seen you post the same to e.g. Angband) ? Crawl is very much NOT a beta/early game so your latest paragraph does NOT apply at all and including it shows you didn't even try the game to whose repo you're posting (or look at commit history)

Did you see it's release page? The version number is the less then 1.0 , which IMO most people will interperet as "the developers think it's not 100 percent mature".

No offence, but why are you replying? you are not a developer in this project, in other cases I requested this the developers seemed to have a pretty positive attitude toward at least discussing this with me, Your the only one that seems to have a problem with this (which you repeatedly mention) , I know it can be hard for FOSS contributors to squeeze in time for FOSS work so lets spare them the drama.

**Comment by Zireael07** [comment]
> version number is the less then 1.0

I have seen a LOT of FOSS software use version numbers less than 1.0 not because it's alpha/beta, but because they don't want to imply it's "complete". 

I see suggesting early access to developers of a game that's been around for YEARS as a bit... weird to see the least.

However I see no "drama" here, I'm just wondering why you keep shilling Steam to various repos (Especially as this is often your only activity on said repos)

**Comment by wiki-me** [comment]
> I have seen a LOT of FOSS software use version numbers less than 1.0 not because it's alpha/beta, but because they don't want to imply it's "complete".

A project i linked to ([supertux](https://store.steampowered.com/app/1572920/SuperTux/)) has been in development for at least 20 years and the developers choose to have it appear as early access, open source projects don't have the funding and the man power of commercial projects and a project can undergo a refactor the makes it less mature (as i said on the angband issue tracker).

also under promise -> over deliver is a thing, and there is also the issue of [risk aversion](https://en.wikipedia.org/wiki/Risk_aversion) (developers don't want to take the risk they will disappoint players, which is understandable).

> > I see suggesting early access to developers of a game that's been around for YEARS as a bit... weird to see the least.

Maybe you are having a hard time understanding people because you reacting a little impulsively, take at least a day to let your mind process what i say, you reponded about an hour after me and made a basic spelling mistake.

> However I see no "drama" here, I'm just wondering why you keep shilling Steam to various repos (Especially as this is often your only activity on said repos)

I am interested in playing those games eventually, i was interested in a open source game before that had good reviews on sourceforge but when i played it it was basically half backed so i "wasted" a few hours on it and i want a better platform for assesing quality, plus it helps the project get more developers so why not? .

Another issue worth mentioning is that [according](https://www.reddit.com/r/cataclysmdda/comments/11u1u8y/coming_soon_to_steam/jcu2nhb/) to at least one FOSS developer there is a risk that someone will add it on steam and charge money for it, and then the developers would not be able to do that or even put it there for free.

**Comment by rawlins** [comment]
Thanks for the interest in improving crawl. We do not use github issues for discussion topics, so I'm going to close this up. In general, if the issue does not fit with the issue template and you are not a devteam member, this is not the right place for it.

Re the issue raised, the devteam has discussed on and off whether it would be worth the complications involved in releasing the game on steam; currently the needle is at "no". It could conceivably happen some day.

> Maybe you are having a hard time understanding people because you reacting a little impulsively , take at least a day to let your mind process what i say, you reponded about an hour after me and made a basic spelling mistake.

Please be polite to other contributors here, this is extremely rude (and ironically itself contains multiple typos). Also, I have to second the recommendation that you not open what are essentially copy-paste issues on multiple FOSS repositories, this is not a good or effective way to engage with existing communities that all will have their own priorities and goals.

**Comment by Zireael07** [comment]
@wiki-me: I'm not a native speaker, I apologize if "Shilling" is considered rude, I had no clue

**Comment by rawlins** [comment]
> so i should post this to the [game design discussion section](https://crawl.develz.org/tavern/viewforum.php?f=8&sid=2db943ba5f791f17a1165f448617cb8f) in the forum?

To discuss things with the community, these days reddit (r/dcss) and the roguelikes discord in the `#dcss` channel would be the best bets; previously GDD was used for this, but the forum is mostly archived these days (new signups are not open). To discuss ideas with the devteam, the best place would be in the `#crawl-dev` channel on libera.chat (though be aware that it is fairly asynchronous so devs may or may not be around at any given time, they will see messages later though).
