### ISSUE TITLE
strange machines do not get auto excluded

### ISSUE THREAD

**Issue by yrdzrfxndfvh** [crawl/crawl#3139]
**PLATFORM and OS or BROWSER:**
webtiles (likely not relevant)

**DCSS VERSION AND GAME INFORMATION:**
0.30

**DESCRIPTION:**
strange machines (the things in tukimas studio) do not get marked as unsafe like oklob plants and other statues

**Comment by PleasingFungus** [comment]
Fixed in https://github.com/crawl/crawl/commit/2e3c275290d99f6ced86436532b9e5b7ed0a80f4, thanks!
