### ISSUE TITLE
Book vault generates with identical placeholder names for all books

### ISSUE THREAD

**Issue by Flugkiller** [crawl/crawl#3144]
**PLATFORM and OS or BROWSER:**
Webtiles, Google Chrome

**DCSS VERSION AND GAME INFORMATION:**
trunk, 0.31-a0-66-ge618eeaa78

**DESCRIPTION:**

I got the book vault nicolae_shop_i_like_small_books_too generated in my game, and all the books have the same name: "a book of Fixed Theme". I have been entirely unsuccessful in reproducing this bug in my offline stable copy of crawl, the vault seems to generate without any issues there. I do not know how to compile the trunk version on my computer so unfortunately I cannot test this properly.

Unfortunately, it seems like I cannot log in via ssh to xtahua right now for some reason (some other servers seem to work), so it is impossible for me to attach the actual game file. Hopefully this will not be necessary, I've attached a pastebin link to my chardump and a screenshot instead.

**EXTRA FILES:**

https://pastebin.com/wKWderxd

![chrome_2023-05-22_15-48-58](https://github.com/crawl/crawl/assets/59402112/65501c07-17ea-41cc-a7a2-c5add60596aa)

**Comment by PleasingFungus** [comment]
Should be fixed for future in be637cbdd6b991db40107e63cc8be35861416954 . Thanks for reporting!
