### ISSUE TITLE
Corpse tile is displayed in every inventory slot

### ISSUE THREAD

**Issue by jv84** [crawl/crawl#3145]
**PLATFORM and OS or BROWSER:**

local tiles

**DCSS VERSION AND GAME INFORMATION:**

0.31-a0-66-ge618eeaa78

**EXTRA FILES:**

screenshot included
![corpses](https://github.com/crawl/crawl/assets/34145636/d522ceaf-9935-42b1-8c5f-c882c4b1ec1c)

**Comment by rawlins** [comment]
This is most likely a dup of #2426, usually rebuilding with an identical build command will also fix it.

**Comment by jv84** [comment]
> This is most likely a dup of #2426, usually rebuilding with an identical build command will also fix it.

I always use the same command.
