### ISSUE TITLE
Trying to worship Ash looks like abandoning

### ISSUE THREAD

**Issue by Nubinia** [crawl/crawl#3146]
webtiles on Chromebook, OS 113.0.5672.114 

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-73-g838c9eb66

**DESCRIPTION:**
At an altar of Ash, about to join, pressed enter or J, and was asked if I wanted to abandon.

Not reproduced

**Comment by Nubinia** [comment]
Sorry, my mistake

**Comment by semitonal** [comment]
Closing per the above comment!
