### ISSUE TITLE
All monsters somehow dying on their own

### ISSUE THREAD

**Issue by krehera** [crawl/crawl#3147]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
version 0.31-a0-88-g38777b0aa0 (webtiles)

**DESCRIPTION:**
All I had to do was either press 5 (wait) a few times, or else go up and down stairs, and nearly all monsters on the level died somehow (Gozag confusion??)

**EXTRA FILES:**
https://crawl.kelbi.org/crawl/morgue/Chish/morgue-Chish-20230524-232613.txt

**Comment by semitonal** [comment]
Thanks for reporting, this was fixed in 637a80eef!
