### ISSUE TITLE
Hep ancestor should be same speed as me

### ISSUE THREAD

**Issue by kscheirer** [crawl/crawl#3156]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
trunk

**DESCRIPTION:**
Hep ancestor should be as fast as me. Playing as a spriggan, I keep leaving them behind. Presumably they would also be spriggan in this case, would be much more convenient if they could keep up.

**Comment by PleasingFungus** [comment]
This is intentionally not the case. Adjusting ally stats based on the player species is a huge can of worms - should octopode ancestors get constriction? Should felid ancestors be unable to use equipment? (Etc, etc.)

Use ctrl-t or *t in-game to set your travel speed to your slowest ally's.
