### ISSUE TITLE
Crash when fighting maggie

### ISSUE THREAD

**Issue by eScribMac** [crawl/crawl#3164]
**PLATFORM and OS or BROWSER:**
webtiles chrome

**DCSS VERSION AND GAME INFORMATION:**
0.30 https://crawl.kelbi.org/crawl/morgue/T4S/crash-T4S-20230615-043852.txt

**DESCRIPTION:**
The game crashes, semi-reproducible. 

repro steps:
press o
(after encounter maggie) press f then Q then a to quiver throwing nets.
throw 2 throwing nets (second one should entangle maggie)
press tab 
repeat tab until game crashes

this worked 3 times in a row for me

**EXTRA FILES:**
I will add the save file tomorrow when I have access to a computer with ssh

**Comment by PleasingFungus** [comment]
I can't repro this, sorry. The save file would be helpful.

**Comment by PleasingFungus** [comment]
This was probably resolved by https://github.com/crawl/crawl/commit/fc9fac7961a261fbadc65f0fa38b5a114fd2d4b5. Please report if you see it again in a newer version. :)
