### ISSUE TITLE
Crash after descending stairs - possibly related to Zin's sanctuary

### ISSUE THREAD

**Issue by Oddbjorg** [crawl/crawl#3170]
PLATFORM and OS or BROWSER:
Webtiles on Firefox

DCSS VERSION AND GAME INFORMATION:
Version: .30
Username: Oddbjorg on CAO
Seed: 12531716777392728553

DESCRIPTION:
The game crashed when I descended the stairs from Swamp:4 to Swamp:5.  This wasn't the first weird thing that happened though - I had been stair hopping between the two levels, and had used Zin's sanctuary ability a couple of times.  I noticed that one of the sanctuaries seemed to persist after I returned to the level after resting for many turns.  It was graphical only, the tiles appeared to be under a sanctuary effect but were, in fact, not.  When I left the level just before the crash there was one actual sanctuary and one graphical bug sanctuary.  I then returned to Swamp:5 and the crash occurred. The webtiles save now crashes on launch.  Would love love love it if some wonderful person could help me recover xD

EXTRA FILES:
Crash log - http://crawl.akrasiac.org/rawdata/Oddbjorg/crash-Oddbjorg-20230622-233711.txt
Backup save -  http://crawl.akrasiac.org/saves/Oddbjorg-crawl-0.30-230622-1950.tar.bz2

**Comment by rawlins** [comment]
This crash should be fixed next time CAO updates with trunk. Sorry that this crash took a few days for someone to get to!

**Comment by Oddbjorg** [comment]
Amazing, thank you so much!  Is it possible to move the save to trunk, or is it lost?
