### ISSUE TITLE
Ingame FAQ directs to (old) Tavern

### ISSUE THREAD

**Issue by crystalsolenoid** [crawl/crawl#3172]
**DCSS VERSION AND GAME INFORMATION:**

0.31-a0-198-g2ad674f

**DESCRIPTION:**

The link should probably be updated to Tavern 2.

![Screenshot from 2023-06-25 13-43-08](https://github.com/crawl/crawl/assets/8132415/fa0d88d3-e55e-4fbd-b920-86d165bd4629)

**Comment by PleasingFungus** [comment]
Thanks for reporting! Fixed in b37851dbb3.
