### ISSUE TITLE
Game repeatedly crashing after abandoning Gozag for Lugonu

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3173]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
Version: 0.31-a0-204-g7da18ca

**DESCRIPTION:**
Soon after converting from Gozag to Lugonu the game starting crashing in most fights. This would reset the game to when I last used a staircase making it impossible to progress. The crash didn't seem to depend on what action I was using. I was able to repeat the problem in an offline game and get a crash log

**EXTRA FILES:**
Crash Log: 
[crash-Tester-20230627-160439.txt](https://github.com/crawl/crawl/files/11878830/crash-Tester-20230627-160439.txt)

**Comment by PleasingFungus** [comment]
Sorry! Should be fixed in 2cbb21b356.
