### ISSUE TITLE
SHIFT+NUMPAD3 and SHIFT+NUMPAD9 do not work in console version (Linux)

### ISSUE THREAD

**Issue by ghost** [crawl/crawl#3174]
**PLATFORM and OS or BROWSER:**
Console, Linux

**DCSS VERSION AND GAME INFORMATION:**
Any version (old bug)

**DESCRIPTION:**
`SHIFT+NUMPAD3` and `SHIFT+NUMPAD9` are supposed to make the character run in the respective direction, but they instead log `_Unknown command.` in the message log. The weird thing is that other `SHIFT+NUMPADX` keys do work, it is just these two (`SHIFT+NUMPAD3` and `SHIFT+NUMPAD9`) that don't.

The bug is reproduced in the tutorial and in the normal game. I'm using the default DCSS config (nothing overridden) and turning `NUMLOCK` on or off has no effect.

**EXTRA FILES:**
[Also reported here on Mantis](https://crawl.develz.org/mantis/view.php?id=2486)

Screenshot from the tutorial when I try to run with `SHIFT+NUMPAD3` (notice `_Unknown command.` in the message log):
![Screenshot from 2023-06-27 09-59-20](https://github.com/crawl/crawl/assets/137689550/7037c9c3-f9dd-4e87-8cd5-6d0a0322a07c)

**Comment by robertxgray** [comment]
Same problem with mate-terminal on Fedora. When the numlock is off, the numeric keyboard behaves like the arrow/special keys and some keycodes are not configured.

- 0 = Insert
- . = Delete
- 1 = End
- 2 = Down
- 3 = Pgdn
- 4 = Left
- 5 = Clear
- 6 = Right
- 7 = Home
- 8 = Up
- 9 = Pgup

**Working keycodes**

- Up => Keycode -254
- Down => Keycode -253
- Left => Keycode -252
- Right => Keycode -251
- Home => Keycode -249
- End => Keycode -248
- Pgup => Keycode -246
- Pgdn => Keycode -245
- Shift+Up => Keycode -243
- Shift+Down => Keycode -242
- Shift+Left => Keycode -241
- Shift+Right => Keycode -240
- Shift+Home => Keycode 89
- Shift+End => Keycode 66
- Shift+Delete => Keycode -202 (no action assigned)

**Non working keycodes**

- Insert => Keycode -331
- Delete => Keycode -255 (only enabled on local tiles)
- Clear => Keycode -354
- Shift+Pgup => Keycode -398
- Shift+Pgdn => Keycode -396
- Control+Up => Keycode -573
- Control+Down => Keycode -532
- Control+Left => Keycode -552
- Control+Right => Keycode -567
- Control+Home => Keycode -542
- Control+End => Keycode -537
- Control+Pgup => Keycode -562
- Control+Pgdn => Keycode -557

**These combinations seem to produce a sequence of keycodes?**

- Shift+Insert => Keycodes 97 114
- Shift+Clear => Keycodes 27 91 98 59 106 69
- Control+Clear => Keycodes 27 91 98 59 53 69

**Comment by robertxgray** [comment]
Please have a look at #3191. I was unable to fix everything but I hope it can be a step in the right direction.
