### ISSUE TITLE
Incorrect warning that you can't shaft yourself in tomb as a formicid

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3181]
**PLATFORM and OS or BROWSER:**
local tiles and webtiles

**DCSS VERSION AND GAME INFORMATION:**
webtiles version: 0.30.0
local tiles version: 0.31-a0-221-gbdcc013574

**DESCRIPTION:**
When going up or down any staircase in Tomb I get the warning "Beware, you cannot shaft yourself on this level.". However, I can shaft myself on levels 1 and 2 of Tomb.

**EXTRA FILES:**
![Screenshot 2023-07-04 204431](https://github.com/crawl/crawl/assets/26264063/e783502d-10a7-49bf-8d19-774e6c51d6c9)

**Comment by KafoKajKodo** [comment]
Shafting works for me in Tomb, it looks like you were on a staircase, shafting does not work on staircases.

**Comment by WizardIke** [comment]
Shafting does work for me in Tomb. I just get a message when I enter the level saying it shouldn't.

**Comment by PleasingFungus** [comment]
Fixed, thanks! Oversight in 4d237caa85e2dd7638bbde1e443ca14111cf8674.
