### ISSUE TITLE
Inconsistency in physiology_mutation_conflict

### ISSUE THREAD

**Issue by pisastrish** [crawl/crawl#3189]
**PLATFORM and OS or BROWSER:**
All

**DCSS VERSION AND GAME INFORMATION:**
0.31 trunk

**DESCRIPTION:**
I was looking through mutation code to update the wiki and noticed that physiology_mutation_conflict [here](https://github.com/crawl/crawl/blob/master/crawl-ref/source/mutation.cc#L1710C8-L1710C8) says that it checks to prevent draconians and most demonspawn from receiving random scales mutations, but it only actually checks iridescent scales and not the other scales muts currently available from random mutation (bone plates, thin skeletal structure, and sturdy frame. I verified in wiz mode that these can be received, but not iridescent). This seems fine for draconians since these aren't really thematically scales, but it seems like demonspawn should either check for all or none of the scales muts.

**Comment by semitonal** [comment]
This is working as intended - see 66c8afceed3. Bone plates, thin skeletal structure and sturdy frame are now just regular random mutations that anyone can get, but they also happen to be in the Demonspawn mutation pool (in the same way that a Demonspawn who gains innate horns can also get claws from a potion of mutation).
