### ISSUE TITLE
Talismans use unprintable character glyph in console

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#3195]
**PLATFORM and OS or BROWSER:**
Online console
0.31-a0-263-ge8cad7f256 
Windows 11
PuTTY 0.78, Lucida Console typeface

**DCSS VERSION AND GAME INFORMATION:**
CBR2, player jejorda2, DrBe.
 https://cbro.berotato.org/saves/jejorda2-crawl-git-e8cad7f256-230713-2018.tar.bz2

**DESCRIPTION:**
When I see a talisman item on the dungeon floor, it is represented by a little rectangle representing a non-printable character.
I've seen a beast, blade, and dragon talisman this game, and they all have this problem.
I would expect it to look like a miscellaneous evoker, or maybe an amulet or an orb.

**EXTRA FILES:**
This is online console:
![unprintable talisman](https://github.com/crawl/crawl/assets/19559511/a22e5e19-60d6-4c6c-94eb-393037eb2446)

This is webtiles with  "tile_display_mode = glyphs" in the .rc file:
![image](https://github.com/crawl/crawl/assets/19559511/0ee4ba28-ee92-430b-8a84-33c70f6a4920)

-->

**Comment by PleasingFungus** [comment]
Strange. Do clouds render correctly for you?

The intended glyph is ◑. This is near some of the cloud glyphs in unicode (§, ☼, ○, °), so I don't understand why only the talisman glyph would cause issues for your terminal.

**Comment by jejorda2** [comment]
Clouds rendered correctly in that game, along with things like shop doors.  I could copy the talisman character from putty to notepad and it would show the intended ◑ glyph with the same font selected.  I now understand notepad is smart enough to substitute characters from a different font when a character isn't available, but PuTTY isn't without some registry hacks.  So I just picked a different front in PuTTY (Deja Vu Mono) and now it works.  So this is all on my end, and not a problem with crawl.  Thanks.

**Comment by PleasingFungus** [comment]
Switched to another character in aec59ea2826d82c00a0fe6cb7e62231baaa129e3, since there are many other PuTTY users, and I don't expect people to need to mess around with their fonts to get the game to work. Sorry for the trouble!
