### ISSUE TITLE
Serpent Form allows crosing Deep Water but doesn't path through it

### ISSUE THREAD

**Issue by MIC132** [crawl/crawl#3199]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-271-gb88eb75e06

**DESCRIPTION:**
When using Serpent form, you can walk over Deep Water spaces, however neither autoexplore nor autopathing actually paths through them (so for example you will get "no path" if you try to the game to go somewhere that's on the other side).
One of those has to be unintended, but I'm not clear which one.

(Also there is a minor ui bug where after you leave Serpent Form, the top-right ui still shows the +5 strength until something else refreshes it - like opening the % menu).

**Comment by PleasingFungus** [comment]
Former is fixed in a29a1f0fbba05300a126edc8792768eacad602ad.

**Comment by PleasingFungus** [comment]
Fixed the latter bug too. Thanks!
