### ISSUE TITLE
Mut screen doesn't list dragon form aux attacks

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#3200]
**PLATFORM and OS or BROWSER:**
Online console
**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-263-ge8cad7f256
https://cbro.berotato.org/morgue/jejorda2/morgue-jejorda2-20230714-133309.txt

**DESCRIPTION:**
Pressing "A" lists mutations, including those gained from using forms.
In Dragon Form, there is no listing that includes the bite attack and tail slap.  It would be helpful to show those and display the damage.

**Comment by PleasingFungus** [comment]
Done in 7bf6ffcfedc1ade70be49e13497bda85946f64d9, thanks!
