### ISSUE TITLE
Description for talisman of death is misleading

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#3201]
**PLATFORM and OS or BROWSER:**
Online console
0.31-a0-263-ge8cad7f256
https://cbro.berotato.org/morgue/jejorda2/morgue-jejorda2-20230714-133309.txt

**DESCRIPTION:**
The description for the talisman of death contains:
Foes struck by user's melee weapons or hands are weakened, slowed, and drained,
and they can heal themselves by tormenting foes nearby.

This sounds like foes can heal themselves by tormenting.  I suggest updating to something like:

Foes struck by user's melee weapons or hands are weakened, slowed, and drained.
The user can heal themselves by tormenting foes nearby.

**Comment by PleasingFungus** [comment]
Good catch. Fixed!
