### ISSUE TITLE
The tail mutation of the stone statue 'Mf' works in the water. However, the effect of the attack failure also works.

### ISSUE THREAD

**Issue by sdynet** [crawl/crawl#3213]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-347-ge7fe003f5b

**DESCRIPTION:**
The tail mutation of the stone statue 'Mf' works in the water. However, the effect of the attack failure also works.

**EXTRA FILES:**
[bug.zip](https://github.com/crawl/crawl/files/12137993/bug.zip)

**Comment by Monkooky** [comment]
![image](https://github.com/crawl/crawl/assets/6244827/ba2a75af-1e34-4bb3-bf35-aa216077402c)

also oddly- you get 'your wading speed is quick' from @, indicating the movespeed works but the description does not.

**Comment by PleasingFungus** [comment]
Duplicates #3175. Thanks for reporting!
