### ISSUE TITLE
Minor visual bug with magic mapping

### ISSUE THREAD

**Issue by eScribMac** [crawl/crawl#3225]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
.30

**DESCRIPTION:**
When you read a magic mapping scroll, and then inspect a shop or portal, all shops and portals show an "unknown" tile, except (as far as I have observed) gauntlets, which show the gauntlet tile. I believe this is unintended behavior.

**EXTRA FILES:**

<img width="749" alt="image" src="https://github.com/crawl/crawl/assets/4968747/0504bd20-4aef-475b-bbd5-118594c73189">

**Comment by PleasingFungus** [comment]
Fixed in #3251.
