### ISSUE TITLE
GCC 13.2 warns about -Wredundant-decls

### ISSUE THREAD

**Issue by jv84** [crawl/crawl#3227]
Some issues with strlcpy.

**Comment by jv84** [comment]
glibc 2.38 includes strlcpy so that's the issue.

**Comment by jv84** [comment]
There's also this message before linking is completed.

`unrecognized command-line option ”-Wno-null-conversion” may have been intended to silence earlier diagnostics`

**Comment by rawlins** [comment]
[d5cd04e](https://github.com/crawl/crawl/commit/d5cd04eec476a0d14076d63d69501292e4c3f5a3) should fix the last two (which I think are independent of the change you made, they appear in CI and are related to very recent commits).

Re the original report, I'm not sure if anyone on the devteam is using GCC 13.2; CI isn't for sure, and I use clang myself. So without a PR this may need to wait for someone with access to the warnings to produce a fix. It'll perhaps cycle into CI eventually.

**Comment by jv84** [comment]
Fixed. It was misleading to mention GCC version but distro upgrade might break things.
