### ISSUE TITLE
Kikubaaqudgha ability "Receive Forbidden Knowledge" still shows it grants Necromutation

### ISSUE THREAD

**Issue by pyy156941** [crawl/crawl#3228]
**PLATFORM and OS or BROWSER:**
Webtiles, Microsoft Edge Version 115.0.1901.188 (Official build) (64-bit)

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-455-g1a7b003ef0

**DESCRIPTION:**
Kikubaaqudgha ability "Receive Forbidden Knowledge" still shows it grants Necromutation, however this spell in obsolete in trunk.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/62455298/e7c0c0a9-6b40-4580-ac43-3aac5eaf6f9b)

**Comment by PleasingFungus** [comment]
Fixed, thanks!
