### ISSUE TITLE
Ash devices curse isn't working

### ISSUE THREAD

**Issue by Nubinia** [crawl/crawl#3231]
**PLATFORM and OS or BROWSER:**
webtiles, Chromebook, Chrome 114.0.5735.239

**DCSS VERSION AND GAME INFORMATION:**
0.31

**DESCRIPTION:**
I've cursed one item with dev and melee; melee skils are showing in bright green on the 'm' screem, but evocations and shapeshifting aren't

**Comment by Nubinia** [comment]
Working now

**Comment by Nubinia** [comment]
It doesn't work in serpent form or statue form, but does in beast and untransformed.

**Comment by PleasingFungus** [comment]
Working as intended. Melded curses don't have any effects, just like any other property of a melded item.
