### ISSUE TITLE
Old description of Wr should be updated

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3233]
**PLATFORM and OS or BROWSER:**

webtiles, kelbi
**DCSS VERSION AND GAME INFORMATION:**

0.31(trunk)
**DESCRIPTION:**

As title. Warpers now start with darts of dispersal instead of boomerangs of disperal but the description is not changed.
**EXTRA FILES:**

**Comment by PleasingFungus** [comment]
Done, thanks!
