### ISSUE TITLE
Confusion from the mix of old-fashioned description and new inscript&descript

### ISSUE THREAD

**Issue by fbwer** [crawl/crawl#3234]
**PLATFORM and OS or BROWSER:**
local tiles, webtiles and consoles

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-460-g9e667d4245

**DESCRIPTION:**
Hello, I'm a returning user. I recently had YASD related to the +3 Elemental Staff in a shop. In the latest version, the random artifact staff had a "spell-enhanced" inscription like "Earth", whereas the +3 Elemental staff had an old-fashioned description and felt confused as a returning user, and new user would feel this confusion. Can't the +3 Element Staff have an "Elemental" inscription? 
It seems that these old-fashioned description and new inscript&descript notation are being mixed not only in the +3 Elemental Staff but also in many places within DCSS. I think it has become difficult to determine which text is related to performance or not. In this regard, if you want, I can look for more and try to make a pull request.

**EXTRA FILES:**
![1](https://github.com/crawl/crawl/assets/117167196/86df1fcb-96d9-4042-a9d7-f377d9ed9e5b)
![2](https://github.com/crawl/crawl/assets/117167196/ef51de58-969d-42a4-97c8-36197917ce93)
![3](https://github.com/crawl/crawl/assets/117167196/cfbff0c6-fb55-4e5e-843c-ebb16afe86d7)
![5](https://github.com/crawl/crawl/assets/117167196/c1f24f09-1bd8-4e31-84b1-82bb77ebcad9)
![6](https://github.com/crawl/crawl/assets/117167196/e3d8b5eb-1622-4773-a0f0-fa98668607a5)
![7](https://github.com/crawl/crawl/assets/117167196/01b5dd44-cd60-4b43-a817-832c627aef3f)

If this is an online game, see [these instructions](https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup)
for more information on how to make a save backup; you can provide the
resulting link here.
-->

**Comment by PleasingFungus** [comment]
Done, thanks!
