### ISSUE TITLE
vile clutch says "something" for invisible target that you can see

### ISSUE THREAD

**Issue by mgdelmonte** [crawl/crawl#3237]
local tiles v0.30.0 on mac

I cast Vile Clutch on an ancient lich.  I have SInv.  The lich casts invisibility.  The message says, "The zombie hands lose their grip on something" even though I can clearly see the lich.

<img width="476" alt="image" src="https://github.com/crawl/crawl/assets/2027885/6dd9aa68-62c3-40b9-a250-28dafc77f546">

**Comment by PleasingFungus** [comment]
This was fixed sometime before 9adf0d1. Thanks for reporting! :)
