### ISSUE TITLE
Mobs can switch off a distortion-branded weapon safely?

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3252]
**PLATFORM and OS or BROWSER:**

 
**DCSS VERSION AND GAME INFORMATION:**

webtiles, kelbi, 0.31(trunk); localtiles, 0.29.0
**DESCRIPTION:**

As title. (intentional?)
**EXTRA FILES:**

<img width="1187" alt="Screenshot 2023-08-14 135506" src="https://github.com/crawl/crawl/assets/82269729/0cb5fd28-0389-4520-9ddf-9cdcc1f73544">

**Comment by semitonal** [comment]
Sorry, monsters get to cheat!
