### ISSUE TITLE
Key conflict of Enter on webtiles

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3254]
**PLATFORM and OS or BROWSER:**

webtiles, kelbi
**DCSS VERSION AND GAME INFORMATION:**

any version
**DESCRIPTION:**

I opened the text box (on the rd corner of the screen). Then I tried to pick up an item and when I hit Enter the text box went open and close instead of picking up that item. This is very annoying.
**EXTRA FILES:**

**Comment by projectNoob** [comment]
> I can't replicate this unless the chat box has focus, in which case this is the intended behavior. Can you provide some more information about what exactly you did in what order, what browser you are using, etc?

Chrome(113.0.5672.127)
1.open the chat box
2.open a menu (drop, pick, shop, etc)
3.press enter

**Comment by rawlins** [comment]
Thanks! This seems to be chrome-specific.

**Comment by projectNoob** [comment]
Not reoccuring.
