### ISSUE TITLE
Can't find arrows to shoot with bows

### ISSUE THREAD

**Issue by gjmcclure** [crawl/crawl#3259]
**PLATFORM and OS or BROWSER:**
Windows 10

**DCSS VERSION AND GAME INFORMATION:**
"0.30.0"

**DESCRIPTION:**
I used to find arrows in the various levels.  No arrows seem to appear since I
switched to V30.  All kinds of bows are found to shoot arrows, but no arrows.
Killing off characters with bows (and shoot arrows at me) results in the bow
being available but no arrows ever.  This happens for any species or character.
Is it me or is it V30.0?

**Comment by Cureja** [comment]
Ammo has been phased out since 0.29. You should be able to already shoot without them.

**Comment by rawlins** [comment]
Yes, there is no ammo any more; use `F` to fire a wielded ranged weapon.
