### ISSUE TITLE
More Description Nitpicks

### ISSUE THREAD

**Issue by OctopodesWeekly** [crawl/crawl#3263]
**DCSS VERSION AND GAME INFORMATION:** 0.30.X, Windows

**DESCRIPTION:**

1. Various scroll/potion descriptions:

A. The scroll of immolation description is less than enlightening:
>A scroll that fills the creatures around the reader with an unstable and powerful inner flame.

It is unlikely that a new player would know what an "inner flame" does without looking at the spell description, and its also unlikely that new players know that it's a spell. Copying the description from the spell Inner Flame is fine enough (though mentioning that it doesn't work against MR immune enemies is also important).

Minor FR: Make ?immolation affect infinite willpower, since it doesn't check will in any other way. It's unintuitive that, say, zombies can be immolated, but not spectres.

B.  ?Fog's description:
> This scroll surrounds the reader with a dense cloud of fog.

It should probably mention blocking sight, as in "...dense cloud of fog, blocking sight of both you and enemies". This isn't necessary but makes it easier to understand "what the scroll is for".

C. In 0.30, there's little reason why stuff like !curing, !heal wounds, !magic, doesn't have exact numbers for recovery. If you're willing to state that elec  brand deals "8-20 damage, 25% chance", I think it'd be good to state the min/max healing for !hw.

----
2. The manual claims:
> Resting is the **only way to get rid of manticore spikes**, but is otherwise indistinguishable from any other action

However, this hasn't been true since e097ebc5.

----
3. Conjure Living Spells states that it can deal 2 x XdY damage (3 for divine tomes). However, this spell creates 2-3 living spells ~~(3-4 for divine)~~. While this fact would be obvious when the spell is used, this is still an error. If displaying 2-3 x XdY is too cluttered, it would be better to display 3 x XdY, as knowing max damage/turn is important to players.

~~The same error applies to Conjure Ball Lightning (the monster version summons 2-5 ball lightnings).~~

**Comment by PleasingFungus** [comment]
Thanks for the reports! I've addressed 1A, 1B, 2, and 3.

> Conjure Living Spells states that it can deal 2 x XdY damage (3 for divine tomes). However, this spell creates 2-3 living spells. 

This was a bug, ha. I've fixed it - thanks!

> ...(3-4 for divine)...

Can you reproduce this? AFAIK, all tomes other than crystal produce 2-3 spells per cast.

> The same error applies to Conjure Ball Lightning (the monster version summons 2-5 ball lightnings).

Can you reproduce this?

**Comment by OctopodesWeekly** [comment]
> Can you reproduce this? AFAIK, all tomes other than crystal produce 2-3 spells per cast.

Whoops, MB - i didn't realize it was changed in 36894cf

> Can you reproduce this? [CBL]

Also my problem. I think I saw lom cast CBL, then only 1 lightning exploded, then cast it again, so there were 5 ball lightnings
