### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#3269]
Playing as jejorda2 on CBR2 (console), tabbing to hit some orcs in pre-lair dungeon with an axe, I encountered a crash:

G
ERROR in 'mon-util.cc' at line 2021: bogus mc (no monster data): invalid monster_type 1000 (1000)

We crashed! This is likely due to a bug in Crawl.
Please submit a bug report to:
    https://github.com/crawl/crawl/issues
and include at least:
- The crash report: /dgldir/morgue/jejorda2/crash-jejorda2-20230825-142323.txt
- Your save file: /crawl-master/crawl-git-285b096dc4/saves/jejorda2.cs
- Information about your computer and game version: Dungeon Crawl Stone Soup 0.31-a0-631-g285b096dc4 (Console/Webtiles)
- A description of what you were doing when this crash occurred.

**Comment by rawlins** [comment]
Thanks! This should be fixed in https://github.com/crawl/crawl/commit/766dd24fdfe591da2995ccc7dc2342b66c4361f3, and CBR2 has now been updated.
