### ISSUE TITLE
Game crashes on kill in Snake

### ISSUE THREAD

**Issue by PaperTar** [crawl/crawl#3270]
**PLATFORM and OS or BROWSER:**
webtiles, Firefox

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-631-g285b096dc4

**DESCRIPTION:**
Crashed twice when killing enemies. In both cases enemies were different. Same enemy types has been killed without crashing as well.

**EXTRA FILES:**
https://crawl.xtahua.com/crawl/morgue/PaperRat/PaperRat.txt
https://crawl.xtahua.com/crawl/morgue/PaperRat/crash-PaperRat-20230826-105748.txt

**Comment by BaeGyuHo** [comment]
https://crawl.xtahua.com/crawl/morgue/SuPeRPuSSyNoOTAB/crash-SuPeRPuSSyNoOTAB-20230826-111750.txt

It also happens for centaur or centaur captain.

**Comment by rawlins** [comment]
Thanks for the report! This should be fixed as of: 766dd24fdfe59. CXC doesn't appear to have this version yet, but I believe it updates about once a day so it should come reasonably soon.

**Comment by PaperTar** [comment]
Ah, I'm a dummy, even saw the relevant commit, but didn't connect the dots. Thank you!
