### ISSUE TITLE
Missing 'flux talisman' icon

### ISSUE THREAD

**Issue by erf** [crawl/crawl#3277]
**PLATFORM and OS or BROWSER:**

"local tiles" on macos 13.5.1 (22G90)

**DCSS VERSION AND GAME INFORMATION:**

"b4d89c20fa"

**DESCRIPTION:**

Missing 'flux talisman' icon

**EXTRA FILES:**

**Comment by PleasingFungus** [comment]
Fixed (well, implemented) in 39726597b9d330587d631f323ca564a3be4d8024.
