### ISSUE TITLE
Starting a descent game asks for updates from trunk game (CAO webtiles)

### ISSUE THREAD

**Issue by RypoFalem** [crawl/crawl#3283]
**PLATFORM and OS or BROWSER:**
CAO Webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-685-g86692c7075 (descent mode)

**DESCRIPTION:**
I had an old trunk game on cao. When I tried to start a new descent game, it asked me if I wanted to update to the latest version. If it matters, the trunk game was still on 0.30 when I encountered the issue. When asked to transfer the save, I clicked neither yes nor no and went back. 

I updated my trunk game to the latest version and now I have started a descent game without issue.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/7819240/1545ca75-5a09-43cd-9724-888886f6feec)
![image](https://github.com/crawl/crawl/assets/7819240/fc1d0399-42bd-4416-9055-6f8ac31d72d5)

**Comment by rawlins** [comment]
Thanks for the report! I think I've fixed this specific issue (though based on the fix there may still be more mode-specific bugs that continue to show up, feel free to open a new bug if you do run into anything).
