### ISSUE TITLE
Segfault on casting Dimensional Bullseye

### ISSUE THREAD

**Issue by loewenheim** [crawl/crawl#3285]
**PLATFORM and OS or BROWSER:**
macOS 13.2 on a 16-inch 2019 MacBook Pro

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.31-a0-700-gf13585253f (SDL Tiles), manually compiled from f13585253f7a1d48c7b48c1ac9ea64e70d928398

**DESCRIPTION:**
The game crashed with a segmentation fault when I cast Dimensional Bullseye on an orc high priest in a bailey. I had successfully cast the spell on a different enemy once before.

**EXTRA FILES:**

[crash.zip](https://github.com/crawl/crawl/files/12549702/crash.zip)

**Comment by semitonal** [comment]
This was fixed a few commits later in cfe89afef65.
