### ISSUE TITLE
Autotravel steps on sigil of binding

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#3290]
**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-705-ga145531891

**DESCRIPTION:**
After casting Sigil of binding, and travelling to a staircase via X+<, I step in the sigil and get stuck. Autotravel should avoid this square.

**Comment by DevJac** [comment]
Sigils also don't warn the player before they step on them. Every other trap in the game warns the player before they step on it.
