### ISSUE TITLE
description of unknown randart ring has 'talisman' text.

### ISSUE THREAD

**Issue by fbwer** [crawl/crawl#3291]
**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-706-g405de50

**DESCRIPTION:**
![4](https://github.com/crawl/crawl/assets/117167196/502185db-e0f5-4a50-8e9a-2a3c2f514a80)
i think it can be read as a bug.
a common noun 'talisman' becomes a proper noun, but common noun 'talisman' still exist.

**Comment by Implojin** [comment]
Thanks for the report, I've fixed this in ecc126b380.
