### ISSUE TITLE
Text truncated `([,] to select)` in `wear` armour dialog (`shift+w`)

### ISSUE THREAD

**Issue by temporaryMan1233** [crawl/crawl#3305]
**PLATFORM and OS or BROWSER:**
Linux, Console

**DCSS VERSION AND GAME INFORMATION:**
`0.30.1` (or any newer version)

**DESCRIPTION:**
Stand on a tile containing armor (check the `Items and Inventory` tutorial) then press `shift+w` to `wear` the armor that is on the ground. Notice the truncated text `([,] to select)`. Also notice that the `equip` dialog (opened by pressing `!`) doesn't have this truncation issue.

Edit: This issue actually affects all menus that have relatively long [heading menu items](https://github.com/crawl/crawl/blob/0d66cbabe8aa5c3182205dfc02f2e61dcadf872b/crawl-ref/source/menu.cc#L184) (relative to other non-heading menu items).

**EXTRA FILES:**
After pressing `shift+w` on a tile containing armor:
![image](https://github.com/crawl/crawl/assets/137689550/240e79bf-8222-4cee-967e-4874368f6c30)

After pressing `,`:
![image](https://github.com/crawl/crawl/assets/137689550/ebcaeea7-cb97-47f6-8795-78216d0427a6)

**Comment by temporaryMan1233** [comment]
It seems that the [code that determines the width of the column (?)](https://github.com/crawl/crawl/blob/0d66cbabe8aa5c3182205dfc02f2e61dcadf872b/crawl-ref/source/menu.cc#L504) only takes the length of items into consideration, so `Inventory Items ([,] to select)` is truncated because its length is longer than the names of all listed items.

**Comment by temporaryMan1233** [comment]
The issue is resolved if we move [this line](https://github.com/crawl/crawl/blob/0d66cbabe8aa5c3182205dfc02f2e61dcadf872b/crawl-ref/source/menu.cc#L517) out of the `else` block.

**Comment by rawlins** [comment]
Thanks for the report! I'll look at this later, but this interacts with multicolumn rendering in a complex way, so unconditionally incorporating the header width will break other stuff.
