### ISSUE TITLE
Got a dirty word for an artifact name

### ISSUE THREAD

**Issue by JosephCarrington** [crawl/crawl#3315]
**PLATFORM and OS or BROWSER:**
webtiles, chrome

**DCSS VERSION AND GAME INFORMATION:**
0.3

**DESCRIPTION:**
Not sure if this is intentional or not, but this is a spicy ring!

<img width="810" alt="Screenshot 2023-09-21 at 9 29 09 AM" src="https://github.com/crawl/crawl/assets/1017852/65727257-d2f9-4054-ac0d-cc200ded50be">

**Comment by PleasingFungus** [comment]
This was fixed in a0b03e459dddbbedaa43f3e1bbc4681d1996c0be (in 0.31). Thanks for reporting!

**Comment by Zireael07** [comment]
I love the solution <3

Q from a non-native speaker of English: how is squaw a rude word? I understand it's the Native word for woman?

**Comment by ebering** [comment]
It has always been a rude word in English. The English word does have some morphological connection to an Algonquin stem for woman. However, the English word entered the language in the 17th century when it was used by the colonists specifically as an ethic and sexist slur for any Native woman.

**Comment by Zireael07** [comment]
Thanks, TIL. (Tbh I only encountered the word in books and stories about Native Americans, and used BY Native American characters themselves, that's why I was confused)
