### ISSUE TITLE
Monsters with multiple weapons share brands

### ISSUE THREAD

**Issue by FaultyScience** [crawl/crawl#3316]
**PLATFORM and OS or BROWSER:**
webtiles, Chrome v117.0.5938.92

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-478-g4fd37da4f0

**DESCRIPTION:**
Nessos inflicted poison with a +2 longbow of flaming, presumably because he was also carrying a short sword of venom at the time. I was certainly not already poisoned - no other monsters on the screen, 100% health, no status effects.

Nessos unwields a +1 short sword of venom.
It stops dripping with poison. Nessos wields a +2 longbow of flaming.
It bursts into flame! Nessos shoots an arrow. The arrow hits you.
You are poisoned.

This does seem like a bug - I would not expect all the weapons a monster carries to share brands.

**Comment by nicolae-carpathia** [comment]
Nessos specifically is hard-coded to deal poison damage with their arrows in addition to their bow's other brands.
