### ISSUE TITLE
Wretches killed does not trigger Animate Dead

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3317]
**PLATFORM and OS or BROWSER:**
webtiles, kelbi, chrome

**DCSS VERSION AND GAME INFORMATION:**
0.31(trunk)

**DESCRIPTION:**
As title. My friend had said that Kiku's Wretches can be killed with Necromancy effects triggered so I think it must be intended. However I still want to check it.

**EXTRA FILES:**

**Comment by semitonal** [comment]
This appears to work as expected. If you can provide a save file or a log then feel free to re-open (bearing in mind that Animate Dead depends on spellpower and isn't guaranteed to create zombies except at max power).
