### ISSUE TITLE
The orc priest said 'by the altar or by the *axe*' even if there's no heretic orcs weilding axes nearby

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3319]
**PLATFORM and OS or BROWSER:**
webtiles, cpo, chrome

**DCSS VERSION AND GAME INFORMATION:**
0.31(trunk)

**DESCRIPTION:**
As title.

**EXTRA FILES:**
<img width="591" alt="image" src="https://github.com/crawl/crawl/assets/82269729/d07f6bca-4044-42ba-b95a-3c6e03c3fbff">

**Comment by PleasingFungus** [comment]
It's more of an idiom.
