### ISSUE TITLE
Throwing Net in a quantum state

### ISSUE THREAD

**Issue by shummie** [crawl/crawl#3341]
**PLATFORM and OS or BROWSER:**
Webtiles - Chrome OS

**DCSS VERSION AND GAME INFORMATION:**
Webtiles 0.31-a0-478-g4fd37da4f0

**DESCRIPTION:**
As seen in the image, there's a throwing net that says it's holding me, it's also visible on the ground.
I was throwing boulders at Harold, who then threw a net which hit the boulder. I don't remember what happened to the boulder, but it left the net in a state where it's visible, apparently holding me (which it isn't), and unable to be picked up.

**EXTRA FILES:**

![image](https://github.com/crawl/crawl/assets/3296707/47dc0587-3505-4650-a67a-aa54d4faec41)

**Comment by PleasingFungus** [comment]
This was probably resolved by fc9fac7. Please report if you see it again in a newer version. :)
