### ISSUE TITLE
Slightly misleading information in the combat tutorial

### ISSUE THREAD

**Issue by readyready15728** [crawl/crawl#3344]
**PLATFORM and OS or BROWSER:**

```
Distributor ID: Linuxmint
Description:    Linux Mint 21.2
Release:        21.2
Codename:       victoria
```

**DCSS VERSION AND GAME INFORMATION:**

```
Dungeon Crawl Stone Soup 0.31-a0-984-gbfb7dba898 (Console)
```

**DESCRIPTION:**
After picking up the boomerangs in the combat tutorial, the player is instructed to head over to the training dummy and type "f" to target the dummy automatically, which does not work. It is possible to use (capital) "F" to select the missile weapon in question manually or, better, "Q" to quiver the boomerangs, then use "f" as originally suggested. I knew this because of substantial prior experience with roguelikes, but an entirely new player might be very confused.

**EXTRA FILES:**
n/a

**Comment by RypoFalem** [comment]
Related pull request https://github.com/crawl/crawl/pull/3336
