### ISSUE TITLE
Stash search doesn't search artefacts correctly.

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#3350]
**PLATFORM and OS or BROWSER:**
Linux 6.1.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-1009-g454b1f1e0a

**DESCRIPTION:**
If I am carrying a suit of ring mail, and search (Ctrl-f command) for "ring && !!mail", it doesn't find it.
If I have an artefact suit of ring mail, it does.
The "stash search" help text says it should not find ring mail. so I would have expected it to find neither.

This happens because the game searches for non-artefacts using the name together with any stash search prefixes.
It does this for artefacts, but also searches `chardump_desc(item)`. This contains a longer description of the item's properties, but  no name. It contains "ring" (as part of the word "wearing"), but not "mail".

If, instead, it carried out one search which included all of the relevant text this wouldn't happen.

**EXTRA FILES:**
[x.zip](https://github.com/crawl/crawl/files/13362475/x.zip)
Save file with two ring mails, one an artefact.

**Comment by wheals** [comment]
Done in 7fc57aa741
