### ISSUE TITLE
descriptions of abilities and spells are truncated in trunk

### ISSUE THREAD

**Issue by BooperDCSS** [crawl/crawl#3351]
**PLATFORM and OS or BROWSER:**
Playing webtiles in Firefox: 
119.0.1 (64-bit)
Mint-001 - 1.0

Operating System: Linux Mint 21.2                 
Kernel: Linux 5.15.0-88-generic

**DCSS VERSION AND GAME INFORMATION:**

I'm playing on Kelbi in the latest version of trunk:

0.31-a0-1010-g5322dac6a2

**DESCRIPTION:**

I loaded up my game, converted too the newest version of trunk, and went to look at my God abilities (worshiping Zin). I noticed that the description for each of the abilities was truncated. I then checked the list of spells available for memorization and saw that the descriptions for those were also truncated, along with the spells I had already memorized. In each case, I see approximately one line of the ability/spell's description.

The description of all my items appears normal. I've attached some screen shots to show you what I mean.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/99783258/7cba5a42-036c-4176-be5a-41f486b8fb43)
![image](https://github.com/crawl/crawl/assets/99783258/6d4e92eb-f0a5-4009-bf5e-236c2ac25dfc)

**Comment by PleasingFungus** [comment]
As mentioned in Discord, you'll need to force-refresh your browser to fix this. Sorry for the trouble!
