### ISSUE TITLE
When Opening the spells menu with 1 spell, pressing down crashes the game.

### ISSUE THREAD

**Issue by nezred** [crawl/crawl#3354]
**PLATFORM and OS or BROWSER:**

Offline, "local tiles", 
Im using **Pop!_OS 22.04 LTS x86_64**

**DCSS VERSION AND GAME INFORMATION:**
0.30.1 (SDL Tiles)

**DESCRIPTION:**
*I was in the Magic and Spellcasting tutorial*.
When I opened the spells menu (I), and pressed down with only one spell memorized, the game crashed.
I was just going through the tutorial normally, but pressed down in the spells menu when I only had one spell.

**EXTRA FILES:**

**Comment by PleasingFungus** [comment]
Thanks for reporting! This was fixed in adbfe6a7a0300fb932504e4a171f2f74fe38e6fe / 38d16f33a9d8aa52b2bc6c7dc0db606508566061, which we'll presumably include in 0.30.2 when 0.31 comes out in a week and a half.
