### ISSUE TITLE
Text in description box does not wrap

### ISSUE THREAD

**Issue by OcalaDave** [crawl/crawl#3360]
![Capture](https://github.com/crawl/crawl/assets/108342624/4ed834a7-1506-4fe3-9be2-7cb516fd0d02)

**PLATFORM and OS or BROWSER:**
< Windows 10, Firefox 120.0 64 bit>

**DCSS VERSION AND GAME INFORMATION:**
< Dungeon Crawl Stone Soup version 0.31-a0-1071-gaead2f62b1 (webtiles) character file.>

**DESCRIPTION:**
<As stated in title, long lines get cut off rather than wrapping.>

**Comment by PleasingFungus** [comment]
Does this reproduce if you force-refresh your browser? (Command-shift-r or equivalent.)

**Comment by OcalaDave** [comment]
Thanks for responding! The problem seems to have resolved itself - hasn't
occurred in the last couple of weeks.
Happy Holidays,
Dave (Pooter)

**Comment by PleasingFungus** [comment]
Cheers, you too!
