### ISSUE TITLE
Misc Species/Background Recommendations

### ISSUE THREAD

**Issue by OctopodesWeekly** [crawl/crawl#3365]
**DCSS VERSION AND GAME INFORMATION:** 0.30.X / 0.31-aX

1. Recommend EE to Kobolds

* Sandblast, Stone Arrow are range 4, which lines perfectly with Kobold LOS
* Passwall, Petrify give opportunities to stab, Kobolds are naturally stealthy/good at stabbing
* Kobold reduced LOS also helps with other spells, like Conjure Boulder, BVC, and the later Earth/Conj spells
* Kobolds have slightly above average magic across the board

Arguably IE could be recommended to Kobolds too, but the case isn't as convincing.

----

2. Remove Meteoran from various background recs

I believe Me is over-represented in the background recs. Me is one of the most difficult races to learn, as turn-count is hard if you don't have great experience with the game (e.g. branch order). While their advanced category would suggest players to stay away, I believe some of the recs do not fit the "flavorful" and/or strong combo" criteria.

* Fighter / Gladiator: Me -> Fo / VS. Formicids have the shield gimmick for the one background that starts with a shield. VS is often used as a melee species.
* Wizard: Me -> Gn. The spellbook has an eccentric variety of spell schools, which works well with Gnoll gimmick. I'm sure MeHW is alright, but there is some anti-synergy: Me find less items -> less spellbooks -> less likely to upgrade. This is not a dealbreaker... but it does make it harder ("when do I switch to melee?" is not a clear q). It also aligns less with the player ideal of playing a mage.
* Wanderer: Me -> Ba. Is MeWn really *that* good of a combo to be recommending? Ba has good apts in almost everything, which imo is a better fit.

----

3. When picking IE, recommend Ba over Na

Come'on, Ba have one background -> species rec, and Na have 8. Ba have great aptitudes in ice. Plus many cold-resistant enemies (in the early game) are resistant to the poison spit.

**Comment by projectNoob** [comment]
TeHu was a fine combo before the nerf in trunk. Te could kite monsters with 0.9 movement delay and shoot hard with their +1 Ranged and 9 DEX. However it was neither way recommended!

**Comment by PleasingFungus** [comment]
Sure, seems reasonable. Basically done in 829106c53c and 7e0a1e97996f0ee0be3ee58f7be8147199230d30, thanks!
