### ISSUE TITLE
Deep Elf Earth Elementalist inside sealed vault can cast Awaken Earth outside of the vault

### ISSUE THREAD

**Issue by damscott** [crawl/crawl#3367]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
`0.30.1-11-g7821555`
Game seed: `5717889739232818315` | [Morgue Link](http://crawl.akrasiac.org/rawdata/Bei0000/morgue-Bei0000-20231202-020904.txt)
Vault located on west side of Elf:2

**DESCRIPTION:**
Passing by the sealed ghost vault on the west side of Elf:2, the Deep Elf Earth Elementalist inside the vault was able to cast Awaken Earth to summon Earth Elementals outside of the vault.

**EXTRA FILES:**
N/A

**Comment by regret-index** [comment]
Awaken Earth was removed from deep elf elementalists in 1d195df of 0.31-a trunk, preventing this from being a problem in the most absolute sense possible.
