### ISSUE TITLE
Issues with Djinni with the crystal ball of Wucad Mu

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#3372]
**PLATFORM and OS or BROWSER:**
Linux 6.1.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-1009-g454b1f1e0a

**DESCRIPTION:**
If a djinni finds the Crystal Ball of Wucad Mu, I notice two issues with it.

1. It isn't marked as useless.
2. Examining the item gives a message which includes the text "It is utterly useless to Djinni." Crawl normally uses "Djinn" as the plural.

Orbs of energy are marked as useless but don't have any extra text to explain it. This seems better to me.

**EXTRA FILES:**

**Comment by PleasingFungus** [comment]
Both issues fixed, thanks!

**Comment by Aliscans** [comment]
Thanks.
