### ISSUE TITLE
Vault speech text uses wrong monster name

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#3379]
0.31-a0-1204-ge2c1a860ed (Console/Webtiles)
https://cbro.berotato.org/saves/jejorda2-crawl-git-e2c1a860ed-231212-1335.tar.bz2

In the Trog altar vault where a monster is burned by a flame cloud, the wizard was recently changed to an arcanist.
But when the monster comes into view, the text reads:
"Flames erupt from the bowels of the wizard! Trog roars with satisfaction!"

I feel "wizard" and "arcanist" ought to be the same word here.  I'd rather see the vault rename the monster to wizard than change the text to arcanist.

Thanks!
<img width="1002" alt="Screen Shot 2023-12-12 at 8 34 22 AM" src="https://github.com/crawl/crawl/assets/19559511/ab4b513e-f4e7-4915-8d34-316cccfdee9f">

**Comment by PleasingFungus** [comment]
Hm, I see what you mean about the inconsistency, but it feels a little weird to define a 'wizard' monster that only exists for this one gag. I'll think about it.
