### ISSUE TITLE
Call Canine familiar crash

### ISSUE THREAD

**Issue by Qio1234** [crawl/crawl#3389]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
Sydney server. Agrajag
 Dungeon Crawl Stone Soup version 0.31-a0-1225-g50297eb (webtiles) character file.

Also  Dungeon Crawl Stone Soup version 0.31-a0-1225-g50297eb (webtiles) character file.

Game seed: 297907097011365659
On Lair 5

**DESCRIPTION:**
Casting call canine familiar crashes out the webtiles and reverts to an earlier save Character was not drained from a previous death of the ingumi. Working okay up until Dungeon 5 on current game. Previous morgue I think was between updates and it happened in lair 5.

**EXTRA FILES:**

-->

**Comment by PleasingFungus** [comment]
Hi! I believe this was fixed last week, probably in c6352e7e69d3bed38ff4b98734c59bd3339ab290 . Sorry for the trouble, and thanks for reporting!
