### ISSUE TITLE
Crash when trying to open known items screen

### ISSUE THREAD

**Issue by loewenheim** [crawl/crawl#3404]
**PLATFORM and OS or BROWSER:**
local tiles, macOS 13.6 x86_64

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-1315-gcae00c0fb1 (SDL tiles)

**DESCRIPTION:**
The game crashes with a segfault when I try to open the "known items" screen (`\`). This happens every time, not sporadically.

**EXTRA FILES:**

[crash.zip](https://github.com/crawl/crawl/files/13722013/crash.zip)

**Comment by PleasingFungus** [comment]
Whoops! Fixed. Thanks for reporting!

**Comment by latteier** [comment]
Thanks! I can confirm that the fix works for me.
