### ISSUE TITLE
Borgnjor's wizlab get lua error

### ISSUE THREAD

**Issue by dillytin** [crawl/crawl#3405]
Version: 0.31-a0-1321-g5021b54

![image](https://github.com/crawl/crawl/assets/65288602/e03f8a57-caf6-4f60-84f4-f1060b1d8230)

Lua error: [string "global_prelude"]:384: bad monster sumon type: "call lost soul"

This wizlab are trying to contantly do something and constantly fail. Just as human beings are...

**Comment by bobross419** [comment]
Seems to only happen in mausoleum and only from the auto spawn.  There was a necro that I killed that was able to summon the little souls within the mausoleum manually.

**Comment by regret-index** [comment]
Fixed in 007bd0a. Thank you for reporting this!
