### ISSUE TITLE
Artefact ring without any additional properties

### ISSUE THREAD

**Issue by LiciTheCrawler** [crawl/crawl#3410]
**PLATFORM and OS or BROWSER:**
webtiles 

**DCSS VERSION AND GAME INFORMATION:**
 0.31-a0-1317-gdfb52cbc09 

**DESCRIPTION:**
 A shop bought from gozag contains an artefact ring with Will+ and nothing else

**Comment by DracoOmega** [comment]
Should have been fixed by ade28b5
