### ISSUE TITLE
Description box text does not wrap

### ISSUE THREAD

**Issue by Qio1234** [crawl/crawl#3419]
**PLATFORM and OS or BROWSER:**
Browser, Project357 
Tested in MS Edge and Firefox 120.0.1

**DCSS VERSION AND GAME INFORMATION:**
 Dungeon Crawl Stone Soup version 0.31-a0-1406-g2bdb5a6 (webtiles) character file.

**DESCRIPTION:**
Text in description box for spells/items etc does not wrap. Have tried reseting the browser with CTRL-F5

**EXTRA FILES:**
![temp](https://github.com/crawl/crawl/assets/88114335/5e604473-41ba-446b-b7b8-53c0a512c23f)

**Comment by Qio1234** [comment]
Playing on trunk in Akrasiac does not seem to have the issue so it could be somewhere on my end?

**Comment by powerbf** [comment]
I have been seeing this for several weeks on CPO trunk webtiles.
I'm on linux mint, and use Chromium Version 120.0.6099.71. I've also tried Firefox v120.0.1. Same issue.
Refreshing the browser does not help.

**Comment by gellingson** [comment]
I have had this behavior for several weeks on akrasiac, playing trunk. Chrome Version 120.0.6099.129 (Official Build) (arm64) on mac. Switching to Safari it goes away (can load the same game back and forth, problem exists on Chrome but not Safari)... but I doubt it's directly the browser; possibly an interaction with some browser setting, maybe related to font sizes/handling?

**Comment by powerbf** [comment]
I did another browser refresh today and now it's working. It seems the file styles.css was out-of-date. It must have been out-of-date on the server though because I did several forced refreshes the other day and it made no difference.

**Comment by PleasingFungus** [comment]
Yes, I talked with the server admin for CPO and they fixed things. Thanks, chequers :)

Leaving this open for @gellingson's issue.

**Comment by gellingson** [comment]
I just did a full chrome settings reset and my wrapping issue was resolved, so I think it's reasonable to close this ticket. Borked browser, server was in fact OK. At least for me.

**Comment by PleasingFungus** [comment]
Gotcha! Sorry for the trouble, but glad it worked out. :)
