### ISSUE TITLE
GDR calculations may be wrong for triple AC reduction

### ISSUE THREAD

**Issue by wferguss** [crawl/crawl#3426]
This bug report concerns the calculation of GDR in the case when the damage should be reduced thrice.
(e.g. involving the Sandblast or Splinterspray spells)
This bug was found by examining the code to see how the thrice AC reduction was calculated.
I don't think I have ever seen this bug manifest in any crawl games.

**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION AND GAME INFORMATION:**
Code is from Trunk (build.h\04:#define CRAWL_VERSION_LONG "0.31-a0-133-gaae73658be")

**DESCRIPTION:**
The code in actor.cc from line 389 is:
    case ac_type::triple:
        saved = random2(1 + ac);
        saved += random2(1 + ac);
        saved += random2(1 + ac);
        ac *= 3;
        // apply GDR only twice rather than thrice, that's probably still waaay
        // too good. 50% gives 75% rather than 100%, too.
        gdr = 100 - gdr * gdr / 100;
        break;
The calculations of GDR do map an initial value of 50% to a new value of 75% as in the comment above.
However it maps an initial value of 10% to a new value of 99%.
My conclusion is having lower GDR makes triple GDR actually higher.
I don't think this was intended.

In almost all triple reduction cases, the actual damage reduction would not make use of the GDR.
This would be large enough that the AC/2 limit or the triple AC roll damage reduction would be the norm.
Thus this code error would seldom be noticeable and I do not recall ever seeing is manifest.

I think the correct formula should be:
        gdr = 100 - (100 - gdr) * (100 - gdr) / 100;
This would map a GDR of 50% to 75% as before.
This would also map a GDR of 10% to 19%.
This makes more sense to me.

Walter

**Comment by DracoOmega** [comment]
That formula may well be broken, but also: GDR only applies to melee attacks, none of which use triple AC. I am not sure if we want to fix this formula on spec that this will change or just rip it out since it's never used (and probably never will be).

**Comment by PleasingFungus** [comment]
Yes, ripping it out seems good to me. It's a very silly thing. :)
