### ISSUE TITLE
Bribed oof strange behavior

### ISSUE THREAD

**Issue by pisastrish** [crawl/crawl#3443]
**PLATFORM and OS or BROWSER:**
firefox webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-1469-gd420192

**DESCRIPTION:**
I bribed zot 5 and one oof became neutral but stopped moving. When it encountered a friendly or hostile oof, the other oofs would also stop taking any action. In the screenshots below, I was able to wait indefinitely while the oofs stood there doing nothing. If I issued a command, got too close, or lured another monster near them, they would attack each other as usual, but then return to doing nothing. Other oofs on the level seemed normal, the bug only occured after they encountered the buggy oof (they would kill other monsters that got close so I'm not sure if the bug would affect other monster types).

Maybe relevant: I read a summoning scroll before this happened.
Also maybe relevant: I'm 90% sure it was the neutral oof that started out buggy, but it may have been the friendly one.

**EXTRA FILES:**
http://crawl.akrasiac.org/rawdata/pisaster/morgue-pisaster-20231229-223545.txt
![Screenshot from 2023-12-29 14-22-47](https://github.com/crawl/crawl/assets/89609062/b9353df2-a538-44df-bd83-7737281e1e14)
![Screenshot from 2023-12-29 14-28-09](https://github.com/crawl/crawl/assets/89609062/dfa7d3e1-215a-4e42-b2e2-fdadc3060f31)

**Comment by DracoOmega** [comment]
This isn't strictly a bug, just a weird manifestation of Crawl monster behavior in general.

Orbs of fire have literally no way to affect another orb of fire. They have no melee attack and none of their spells can do anything useful. They are aware of this, and thus won't cast any of those spells which would be useless. But monsters in Crawl also don't generally look around for *other* monsters they could target instead, if there's nothing useful they could do to the one they are targeting.

So what tends to happen in these cases is that when two orbs of fire end up with each other as a target, internally, they walk up to each other until they can no longer move and then run out of any action they can usefully perform. If something wandered nearby that their spells could *incidentally* harm while aiming at each other, they would fire like usual. They're still taking their turn as normal, just not finding anything useful to *do* with it.

Changing this behavior would involve an extremely major rewrite of how monsters act in Crawl on the whole, in a way that extends much further than this one weird matchup (as virtually every other set of mobile monsters can do *something* to each other.), so I opting to close this. (Even though I agree that this looks very silly.)
