### ISSUE TITLE
Earth elementalist shouldn't start with alcehmy skill

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#3444]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-1522-g43313d8a59

**DESCRIPTION:**
Earth elementalists still start with some alchemy trained. With passwall moving off alchemy, this makes little sense; conjurations is their clear secondary school early game.

**Comment by pooka109** [comment]
Fixed. Thanks.
