### ISSUE TITLE
Player can swap place with an ally who got -move from sigil of binding

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#3454]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.31-a0-1589-g8f5e8aebd6 (latest trunk)

**DESCRIPTION:**
Player can swap place with an ally who got -move from sigil of binding.
![1](https://github.com/crawl/crawl/assets/97007398/88efbea5-43e7-481d-83c4-029450d0b9c3)
![2](https://github.com/crawl/crawl/assets/97007398/d920ab9a-f185-458e-9911-a2b21e5a6e00)

This shouldn't be allowed considering that player can't swap place with an ally who is constricted or paralyzed imo.

**Comment by PleasingFungus** [comment]
Yep, bug! Fixed, thanks. (Monsters were already blocked from swapping with other bound monsters...)
