### ISSUE TITLE
Bai-Suzhen drops her loot when she turns into dragons, not when she die.

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#3455]
PLATFORM and OS or BROWSER:
webtiles

DCSS VERSION AND GAME INFORMATION:
0.31-a0-1589-g8f5e8aebd6 (latest trunk)

DESCRIPTION:
Bai-Suzhen drops her loot when she transform into a dragon, not when she die.

![1](https://github.com/crawl/crawl/assets/97007398/d56e9873-6426-4bd0-9c97-d02d0b8b103e)
![2](https://github.com/crawl/crawl/assets/97007398/c7436913-f2fb-4e5b-b4c2-0de4b966445c)

(This is not intended, right?)

**Comment by PleasingFungus** [comment]
Great bug! No, definitely not intended...
