### ISSUE TITLE
Sturdy frame description is outdated

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#3457]
PLATFORM and OS or BROWSER:
webtiles

DCSS VERSION AND GAME INFORMATION:
0.31-a0-1589-g8f5e8aebd6 (latest trunk)

DESCRIPTION:

![1](https://github.com/crawl/crawl/assets/97007398/40c15873-a4f9-4487-bf5f-34e565358a4f)

Sturdy frame(demonspawn mutation) description is outdated. Body armour ER does not have acc penalty anymore, but now it slows ranged weapon attack speed. (and this also omits EV penalty.)

**Comment by PleasingFungus** [comment]
Fixed, thanks!
