### ISSUE TITLE
Octopode tentacle mutation description is incorrect

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#3458]
PLATFORM and OS or BROWSER:
webtiles

DCSS VERSION AND GAME INFORMATION:
0.31-a0-1589-g8f5e8aebd6 (latest trunk)

DESCRIPTION:
Octopode tentacle mutation description is incorrect.

![1](https://github.com/crawl/crawl/assets/97007398/b68bb2b6-23a1-466a-976b-91832b316aa3)

It is actually 100% chance. (though it can be missed or blocked.)
Here is description of naga tail for reference.

![2](https://github.com/crawl/crawl/assets/97007398/b0f24aad-07c2-4c59-90bb-de30fe6e0c93)

**Comment by PleasingFungus** [comment]
Octopodes have two different tentacle aux attacks. The description above is mixing up those two. I've done my best to clear things up.
