### ISSUE TITLE
Crash when I try to enter Pandemonium, Hell, and Ziggurat.

### ISSUE THREAD

**Issue by ihatemudryk** [crawl/crawl#3460]
PLATFORM and OS or BROWSER:
webtiles

DCSS VERSION AND GAME INFORMATION:
0.31-a0-1589-g8f5e8ae (latest trunk)

DESCRIPTION:
![bug](https://github.com/crawl/crawl/assets/155731306/fdbabf0d-ac93-46c9-a79b-57768c1f8fc6)

Crash when I try to enter Pandemonium, Hell, and Ziggurat.

When I try to enter Pandemonium, Ziggurat, and certain dungeons of Hell, the game stops on the screen above.

Pandemonium and Ziggurat are completely out of entry.

In hell, this happened from Dis, and the third floor of Cocytus.

Here is Gif.

![디스 입장 불가](https://github.com/crawl/crawl/assets/155731306/8a94d872-248d-4ac2-94a8-9da846ce5512)
![지구랏 입장불가](https://github.com/crawl/crawl/assets/155731306/e08c41dc-096e-4e1b-ba2a-3a2a1a88a8da)
![판데 입장 불가](https://github.com/crawl/crawl/assets/155731306/e4b29ebf-b84d-49a1-b939-f018f5dc0c4e)

EXTRA FILES:
Crash Log

Pandemonium
https://crawl.project357.org/morgue/ironshield/crash-ironshield-20240105-111205.txt

Ziggurat
https://crawl.project357.org/morgue/ironshield/crash-ironshield-20240105-111345.txt

Hell
https://crawl.project357.org/morgue/ironshield/crash-ironshield-20240105-111458.txt

The web server I play doesn't support the console. So I don't know how to provide a save backup.
If you need a save backup, you should tell me how to provide it.

**Comment by PleasingFungus** [comment]
Thanks for reporting! The crash log gave me everything I needed to hunt down the crash. (Lucky you, you found an 12-year-old bug!)

Should be fixed now.

**Comment by ihatemudryk** [comment]
Thanks!
