### ISSUE TITLE
Crash in trunk when killed eleionoma (turned to wand charming) w/staff of alchemy

### ISSUE THREAD

**Issue by johndannuz** [crawl/crawl#3468]
**PLATFORM and OS or BROWSER:**
webtiles on akraisiac/firefox (win 10)

**DCSS VERSION AND GAME INFORMATION:**
Trunk - Version history:
Game started: 0.31-a0-1593-ge08a94be7c
0.31-a0-1603-gbec6b6c
0.31-a0-1611-g890cdf5

**DESCRIPTION:**
Game crashed. DsAlch of Ashenzari in Swamp:1, 2nd enemy I fought was an eleinoma. Game crashed as eleionoma died, before I saw the tile change to the wand of charming.

You peck the eleionoma.
The eleionoma is almost dead.
The eleionoma is struck by your spines. The eleionoma hits you!
A demonic guardian appears!
You hit the eleionoma. You envenom the eleionoma!
You kill the eleionoma!
You hear a splash.
An eleionoma bone magically twists into a wand of charming (4).

**EXTRA FILES:**
(http://crawl.akrasiac.org/rawdata/SMASHER/crash-SMASHER-20240109-020643.txt)

**Comment by johndannuz** [comment]
Interestingly enough, when I went back into the game the game had not saved my previous 15 or so turns, so I went back in time to right after I entered Swamp, before I killed the first enemy I encountered (a bog body).

![image](https://github.com/crawl/crawl/assets/111829003/ec2ed020-b12a-455b-9a91-314ea33d5ab4)

**Comment by wheals** [comment]
Fixed in a12eea24be46dbc2e487727b5f10a52765ec4bce.
