### ISSUE TITLE
Hep ancestor doesn't travel at my speed

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#3478]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-22-g6ae6769602

**DESCRIPTION:**
Hep ancestor doesn't travel at my speed (e.g. when navigating to a staircase), in blatant defiance of https://github.com/crawl/crawl/commit/cda7ceedc950.

**Comment by DracoOmega** [comment]
Likely fixed by fa3d79c85def20982656fa910a6538b0d18bf261
