### ISSUE TITLE
Monster spectral weapons attack multiple times per turn

### ISSUE THREAD

**Issue by LiciTheCrawler** [crawl/crawl#3480]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
 0.31.0-1-g2c135a008e

**DESCRIPTION:**
After quaffing a potion got hit twice by Ijyb's spectral club without Ijyb attacking.  Later tested , quaffing a potion seems to have caused it, but after quaffing it it would also happen even with waiting. It seems to attack 3-4 times, even when the wielder does something else like zap a wand.  I've provided the morgue file of the char that found the bug below.

EDIT: qwqw tested no drinking potion prerequisite.

**EXTRA FILES:**
https://underhound.eu/crawl/morgue/EnegeticOcto/morgue-EnegeticOcto-20240120-190809.txt

**Comment by wheals** [comment]
Would seem this was fixed in 52a2dc7128ef1ce93f8a8fae806bd54ef13ec46b
