### ISSUE TITLE
Rare crash with Vhi's and a dispersal trap

### ISSUE THREAD

**Issue by geekosaur** [crawl/crawl#3482]
**PLATFORM and OS or BROWSER:**
webtiles, browser/OS unknown but irrelevant

**DCSS VERSION AND GAME INFORMATION:**
0.31.0

**DESCRIPTION:**

Morgue: https://underhound.eu/crawl/morgue/iamserjio/crash-iamserjio-20240120-174012.txt

Player cast Vhi's Electric Charge on a royal mummy. `_displace_charge_blocker` blinked the mummy onto a displacement trap, which among other things blinked a different monster onto the target square, causing the subsequent `move_player_to_grid` to trip an `ASSERT`.

This seems somewhat difficult to fix properly, since notionally the player did reach the target square and the electric clouds should be placed appropriately. But blinking the new monster away might not work in a tight space or if it lands on another dispersal trap.

**EXTRA FILES:**

**Comment by DracoOmega** [comment]
I think this should be fixed by 6658dcf83989395962b00b0004d06a43a9bcc29b (which makes Vhi's try repeatedly to ensure that the landing spot is clear, and if even *this* fails somehow, aborts the charge rather than try to move the caster there)
