### ISSUE TITLE
Asymmetric recommended species-background pair

### ISSUE THREAD

**Issue by vvokhom** [crawl/crawl#3483]
PLATFORM and OS or BROWSER: Webtiles, Firefox 121.0.1

DCSS VERSION AND GAME INFORMATION: 0.32-a0-35-gd9ff480968 

DESCRIPTION: The starting menu recommends Demonspawn when Shapeshifter is selected, but does not recommend Shapeshifter when Demonspawn is selected. Note that it recommends Shapeshifter when Djinni is selected - i dont know if this is intended. 

EXTRA FILES:
![2](https://github.com/crawl/crawl/assets/92056913/e7e6f897-6774-4385-ae0a-03f38f8ec2d9)

![1](https://github.com/crawl/crawl/assets/92056913/6f3a7549-b0db-40ff-b0fe-00f0011e591c)

**Comment by vvokhom** [comment]
Upd: Same is for Troll

**Comment by matthewgranstrom** [comment]
This appears to be intended behavior: There is deliberately no guarantee that species and background recs are symmetrical. See in particular Chaos Knight -- It's probably not good to recommend any species to go CK, but if somebody starts as a CK we should probably recommend them a species. This asymmetry is documented in [background_creation.md](https://github.com/crawl/crawl/blob/master/crawl-ref/docs/develop/background_creation.md).

**Comment by rawlins** [comment]
This is intended behavior, see #2089 etc
