### ISSUE TITLE
Serpent of Hell didn't spawn

### ISSUE THREAD

**Issue by eyestalker** [crawl/crawl#3486]
It's not in my kill list and I've explored the end of Hells multiple times while shattering most of the walls.

Link to my save: https://underhound.eu/crawl/saves/Sar-crawl-git-5c88369fb2-240124-0025.tar.bz2

Version history for this game:
Version history for your current game:
Game started: 0.31-a0-1343-gcd514f47d3
0.31-a0-1363-g282adc679d
0.31-a0-1395-g7c67ea8c80
0.31-a0-1412-g7b7c7d10e1
0.31-a0-1439-g542172135e
0.31-a0-1458-g2f8d4710b4
0.31-a0-1476-g8a4046af8c
0.31-a0-1612-g4aaf141004
0.31-a0-1616-gbeaec30b81
0.31-a0-1620-gcbf77bbcfc
0.31-a0-1626-g5cb510d322
0.32-a0-13-gbaedc5810e
0.32-a0-18-g89e19f1974
0.32-a0-19-g28bc0835a1
0.32-a0-35-gd9ff480968
0.32-a0-39-g5c88369fb2

**Comment by gammafunk** [comment]
A Dis end vault had bad logic for placing the Serpent of Hell. Fixed in in 3a7656b989, thanks!
