### ISSUE TITLE
bad keybind in dvorak_command_keys.txt

### ISSUE THREAD

**Issue by christakahashi** [crawl/crawl#3491]
**PLATFORM and OS or BROWSER:**
everything i guess.

**DCSS VERSION AND GAME INFORMATION:**
at least 0.31 and trunk from what i can see

**DESCRIPTION:**
Pressing K should bring up the fire menu but it just runs up instead.
the keybind on like 68 should be 
```bindkey = [K] CMD_FIRE_ITEM_NO_QUIVER```
but it instead referrs to an outdated command ```CMD_THROW_ITEM_NO_QUIVER```

**EXTRA FILES:**
N/A

**Comment by pooka109** [comment]
Done. Thank you.
