### ISSUE TITLE
dump_order += turns_by_place duplicating

### ISSUE THREAD

**Issue by LiciTheCrawler** [crawl/crawl#3495]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a

**DESCRIPTION:**
When adding dump_order += turns_by_place to rc file of trunk games in makes it duplicate like in the linked morgue below. 

**EXTRA FILES:**
https://crawl.dcss.io/crawl/morgue/enegeticocto/morgue-enegeticocto-20240128-235734.txt

**Comment by wheals** [comment]
What's happening here is that `dump_order` contains `turns_by_place` already in trunk builds (and only trunk). 

Some things that rcfile authors can do to get around this, if they want to use the same rcfile across versions:

* Check the version in lua to see if it is trunk
* Add `dump_order -= turns_by_place` before adding it to make sure it only shows up once
* Redefine the entire `dump_order` themselves with `dump_order = <...>`
