### ISSUE TITLE
Metabolic Englaciation does not work on all creates in area

### ISSUE THREAD

**Issue by erf** [crawl/crawl#3498]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.31.0

**DESCRIPTION:**
Metabolic Englaciation does not work on all creates in area as the description says. Instead you have to pick a single creature, rendering the spell pretty much useless compared to it's spell level.

**EXTRA FILES:**

**Comment by DracoOmega** [comment]
It is unclear what misunderstanding may have been happening here (perhaps all-but-one enemy in sight had rC+ and was thus immune to the spell? Or it simply failed its check against everything but where the cursor happened) but Metabolic Englaciation does indeed affect LoS at present and there is no indication it ever stopped doing so, so I am closing this.
