### ISSUE TITLE
Pikel death didn't kill his lemures

### ISSUE THREAD

**Issue by mohammad5305** [crawl/crawl#3499]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.31

**DESCRIPTION:**
I killed pikel on a D:5 but his lemures didn't die on D:6

**EXTRA FILES:**
[mohammadb5305.txt](https://github.com/crawl/crawl/files/14112469/mohammadb5305.txt)

**Comment by code2828** [comment]
Possible duplication of #1861.

**Comment by PleasingFungus** [comment]
Yep! Thanks for reporting :)
