### ISSUE TITLE
Meatsprint softlocks on skill training screen (Android .30, .31)

### ISSUE THREAD

**Issue by ZodachGonger** [crawl/crawl#3501]
**PLATFORM and OS or BROWSER:**
This bug is present in Android .31 and also happened to me in Android .30

**DESCRIPTION:**
After I the player reach level 27 and max out the skills the game wants to allocate more experience and brings up a fully loaded skill screen and refuses to let me exit it without throwing exp somewhere. Rebooting the game just brings up "you have quaffed a potion of experience" or similar and softlocks again.

Bloatcrawl 2 on Android avoids this problem and just says "You have mastered all available skills!" Boot up after accruing more exp and it even lets you put exp into skills it wasn't letting you train for lack of prerequisite. I figure the softlock bug is missing a skill id or a check if all displayed skills have been maxed. 

**EXTRA FILES:**
.31 screenshot
![Screenshot_20240203-083156](https://github.com/crawl/crawl/assets/142750960/2a8f5378-0586-4fe4-bc44-63b288c17015)

.30 screenshot
![Screenshot_20231029-210222](https://github.com/crawl/crawl/assets/142750960/041faa0c-4639-4dde-ad1e-97cc06a52f82)

**Comment by matthewgranstrom** [comment]
I think this issue is that there are still skills that you haven't mastered -- Pressing * should let you select from all skills (not just useful ones). The game doesn't think it would be 'useful' to train short blades or long blades, presumably because you don't have one in inventory, but you should still be able to put xp into those skills with *.

**Comment by ZodachGonger** [comment]
Well, opening up the app with .31 and doing a run, that works! It would
have been nice for those other runs, and I'm glad it's not as bad a bug but
it would still be nice to have the game press * to show those other skills
once all the main "useful" skills are golden/Lv. 27.
