### ISSUE TITLE
Lear's Hauberk melds completely when only your boots are melded

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3503]
**PLATFORM and OS or BROWSER:**

webtiles

**DCSS VERSION AND GAME INFORMATION:**

Version: 0.31

**DESCRIPTION:**

Stepping into water as a merfolk that isn't flying melds Lear's Hauberk leaving you defenseless. Having to avoid water as a merfolk seems unintentional.

**EXTRA FILES:**

**Comment by PleasingFungus** [comment]
This is in fact intended. It is ridiculous, but intended.
