### ISSUE TITLE
Pressing windows key + print screen crashes the game in some prompt menus

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3505]
**PLATFORM and OS or BROWSER:**

local tiles
Windows 11

**DCSS VERSION AND GAME INFORMATION:**

Version: 0.32-a0-85-g672eff3212

**DESCRIPTION:**

If I press the windows key at the same time as the print screen key while the game is asking if I really want to attack an ally and be placed under penance, the game crashes.

**EXTRA FILES:**

![Screenshot (1260)](https://github.com/crawl/crawl/assets/26264063/ac61ce35-65ee-441a-9744-bcb34cebfb88)
Crash log: [crash-Tester4-20240205-165859.txt](https://github.com/crawl/crawl/files/14160298/crash-Tester4-20240205-165859.txt)

**Comment by pooka109** [comment]
For the record, this is also not Windows-specific. I just reproduced it on my Ubuntu 22.04.4 LTS machine using its Windows key and PrintScreen.

**Comment by pooka109** [comment]
This should be fixed properly as of 281234c535975fadfb843a3f3d24a07101446678. Thank you.
