### ISSUE TITLE
Barbs from Wu Jian wraith do no damage

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3507]
**PLATFORM and OS or BROWSER:**

webtiles

**DCSS VERSION AND GAME INFORMATION:**

Version: 0.31

**DESCRIPTION:**

If you move with barbs from Wu Jian wraith it doesn't do any damage. You still get the warnings and other messages though.

**EXTRA FILES:**

![Screenshot 2024-02-05 174620](https://github.com/crawl/crawl/assets/26264063/8689cbb2-78e9-40df-bad8-8ed077202d85)
![Screenshot 2024-02-05 174648](https://github.com/crawl/crawl/assets/26264063/6fddfea3-e46e-423f-8eb2-2e29403f2cf8)

**Comment by pooka109** [comment]
Should be fixed now, at least in trunk.
