### ISSUE TITLE
Equipping eudemon blade in off hand on Steel Elf crashes the game

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3510]
**PLATFORM and OS or BROWSER:**
local tiles, windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-96-g9a50951780
two-swords-adventure fork

**DESCRIPTION:**
Equipping an eudemon blade in the off hand crashes the game. Reproducible in wizmode.

**EXTRA FILES:**
[crash-Puhyp-20240205-204900.txt](https://github.com/crawl/crawl/files/14165890/crash-Puhyp-20240205-204900.txt)

**Comment by wheals** [comment]
Unable to reproduce, presumably fixed (by Monkooky?) before the merge to trunk
