### ISSUE TITLE
Random crash in the abyss

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3512]
**PLATFORM and OS or BROWSER:**
local tiles, windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-96-g9a50951780
two-swords-adventure fork

**DESCRIPTION:**
Game crashed randomly in the abyss. Attempting to load the save now crashes too.

**EXTRA FILES:**
[crash-Tyemneul-20240205-203218.txt](https://github.com/crawl/crawl/files/14166010/crash-Tyemneul-20240205-203218.txt)
[Tyemneul.zip](https://github.com/crawl/crawl/files/14166016/Tyemneul.zip)

**Comment by rawlins** [comment]
Thanks! This should be fixed by https://github.com/crawl/crawl/commit/a335ffa919b07a2a1d92b669ab729fd87e7803a0. (May not be immediately available in the online versions of these branches, but will be sooner or later.)
