### ISSUE TITLE
Flaming branded weapon in the main hand causes off hand bladed weapon to cauterize hydra heads too

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3513]
**PLATFORM and OS or BROWSER:**
local tiles, windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-96-g9a50951780
two-swords-adventure fork

**DESCRIPTION:**
Have a flaming branded weapon in the main hand will allow bladed weapon on the off hand to chop off hydra heads without causing them to regrow even if the off hand weapon has a different brand. In this case I have a scimitar of flaming in the main hand and Throatcutter in the off hand.

Additionally, having a blunt weapon in the main hand will cause off hand bladed weapons to not cut off hydra heads, and having a bladed weapon in the main hand will cause off hand blunt weapons to cut off hydra heads.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/146337911/8ace920e-ce1b-48f2-b1a6-0e361832cf9b)
![image](https://github.com/crawl/crawl/assets/146337911/61d98d4f-2b61-433d-bfdf-2cf86f00f206)

**Comment by wheals** [comment]
Unable to reproduce, presumably fixed before the merge to trunk
