### ISSUE TITLE
Randart staff tile overlaps with tile of its base type in local tiles inventotry

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3518]
**PLATFORM and OS or BROWSER:**
local tiles, windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.31

**DESCRIPTION:**
In the inventory, the tile of randart staves overlaps with the tile of its base type. This does not happen in the wield menu.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/146337911/078057c8-94e3-476e-a2e1-66c529ded3c1)
![image](https://github.com/crawl/crawl/assets/146337911/8d48c1e9-9eaf-48e5-a91d-bd5718e14312)

**Comment by pooka109** [comment]
Should be fixed now.
