### ISSUE TITLE
Random crashes after attacking enemies with dual wielded slings

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3520]
**PLATFORM and OS or BROWSER:**
local tiles, windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-113-g13e607d822

**DESCRIPTION:**
Game randomly crashes after attacking enemies with dual wielded slings. Does not happen for every enemy but can be easily reproducing by otabbing after loading the save file.

**EXTRA FILES:**
[Gankunoo.zip](https://github.com/crawl/crawl/files/14174850/Gankunoo.zip)
[crash-Gankunoo-20240206-124211.txt](https://github.com/crawl/crawl/files/14174856/crash-Gankunoo-20240206-124211.txt)

**Comment by wheals** [comment]
Unable to reproduce, presumably fixed before the merge to trunk
