### ISSUE TITLE
Steel elves experimental crashed

### ISSUE THREAD

**Issue by Colgateinuntap** [crawl/crawl#3521]
**PLATFORM and OS or BROWSER:**
Webtiles librewolf 118.0.2-1

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-101-gab1390d076

**DESCRIPTION:**
I was o-tabbing through D:2, I met rat and game crashed. When I enter game again it throws me back to beginning of D:2 then I o-tab through again, sometimes it crashes on adder and sometimes little bit later on rat that comes after that.

**EXTRA FILES:**
 https://crawl.dcss.io/crawl/morgue/Colgate/crash-Colgate-20240206-172114.txt

**Comment by wheals** [comment]
Unable to reproduce, presumably fixed before the merge to trunk
