### ISSUE TITLE
Steel Elf crashes whenever monster with axe attempts to cleave

### ISSUE THREAD

**Issue by Mousus6** [crawl/crawl#3538]
**PLATFORM and OS or BROWSER:**
Webtiles, steel elf branch

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-180-g9ccb448e82
https://crawl.dcss.io/crawl/morgue/Mousus6/Mousus6.txt

**DESCRIPTION:**
As a steel elf who was mostly dual wielding slings the game crashes whenever a monster with an axe attempts to cleave (having just had my Hep ancestor develop an axe this is highly reproducible).  Game is left paused in this state as ensuring that my ancestor never gets an opportunity to cleave is very tricky but did allow me to narrow it down to cleaving rather than just axe wielding monsters attacking.  Crash happens regardless of weapons equipped by player (including with 2-handed axe).

**EXTRA FILES:**
Couldn't work out how to SSH to make a save dump.  Crash logs for my wide variety of attempts are at https://crawl.dcss.io/crawl/morgue/Mousus6/

**Comment by wheals** [comment]
Unable to reproduce, presumably fixed before the merge to trunk
