### ISSUE TITLE
Thrashing Horrors can trample while bound by fathomless shackles

### ISSUE THREAD

**Issue by Monkooky** [crawl/crawl#3547]
version 0.32-a0-329-ge6c31236d6
per title.

**Comment by pooka109** [comment]
Still happening as of version 0.32-a0-431-ge345137cd0, and I've noticed with that version that reapers can also drag when bound by fathomless shackles.

**Comment by pooka109** [comment]
And since Fathomless Shackles uses the same binding enchantment as Sigil of Binding, that means Sigil of Binding has the same problems, which I've also verified in-game.
