### ISSUE TITLE
Hill Orcs are deprecated, but can't be marked as such in YAML; Lua tests, etc. depend on their existence.

### ISSUE THREAD

**Issue by pooka109** [crawl/crawl#3551]
**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-350-g4f4d228785

**Comment by wheals** [comment]
According to DracoOmega, the lua tests use Hill Orcs to create a player with no racial mutations. Maybe this could be changed to Deep Elves?

**Comment by pooka109** [comment]
That does fix the Lua tests; thank you.

However, the tests are now getting a build error on the tag_upgrade builds. So, apparently, one of the TAG_VERSION 34 #ifdefs isn't quite right, although I haven't found where it is yet.
