### ISSUE TITLE
Beogh penances you if your follower is hit by enemy apostle scorch

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3552]
**PLATFORM and OS or BROWSER:**
windows local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-358-gd0bb48bc1f

**DESCRIPTION:**
An orc wizard apostle sent by beogh scorched one of my followers and beogh immediately penanced me. May have something to do with the fact that I was in shoals and the follower may have been standing above water but I don't remember.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/146337911/ea8e45be-42bf-439c-86fc-4bea05f460ec)

**Comment by pooka109** [comment]
This seems to have been fixed in baf8858e17e521a3d47357f32f4d9f0dcb5d1035.
