### ISSUE TITLE
Mobs don't seem to know about iceblast is 3x3 and will hurt themselves

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3555]
**PLATFORM and OS or BROWSER:**
webtiles, cpo, chrome

**DCSS VERSION AND GAME INFORMATION:**
trunk

**DESCRIPTION:**
I was adjacent to Erica who had a wand of iceblast. She evoked it and blew herself up.

**EXTRA FILES:**

**Comment by matthewgranstrom** [comment]
This is not unexpected -- Monsters are in general willing to inflict friendly fire (either to themselves or to other monster allies) if they would deal a more meaningful quantity of damage to you. The threshold for 'more meaningful' can be a little warped around enemies who are either much weaker than the attacking monster or around enemies who are nearly dead. See, for instance, orbs of fire blowing up wandering mushrooms or draconians.

**Comment by wheals** [comment]
As stated, this can be a bit odd, and the AI has room for improvement, but in general this sort of behavior is not considered a bug.
