### ISSUE TITLE
Attempting to equip weapon as coglin will destroy cursed weapon in slot

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3562]
**PLATFORM and OS or BROWSER:**
windows local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-393-g38ff01cdb3

**DESCRIPTION:**
1. Curse a weapon as a coglin with Ashenzari.
2. Click on another weapon to equip it.
3. The cursed weapon will be swapped off and destroyed without asking for confirmation.

![image](https://github.com/crawl/crawl/assets/146337911/cbad4434-4abe-40e7-9acd-677c865e7819)

**Comment by DracoOmega** [comment]
Should have been fixed by 8529b04c429318c8a
