### ISSUE TITLE
Weapon in main hand can be equipped again in off hand

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3564]
**PLATFORM and OS or BROWSER:**
windows local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-393-g38ff01cdb3

**DESCRIPTION:**
1. Play coglin.
2. Left click a weapon to equip it in main hand.
3. Ctrl + left click the same weapon to equip it again in off hand.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/146337911/0e6a6370-1199-45ba-92e5-4b5dd039f2f2)

**Comment by PleasingFungus** [comment]
Fixed in 0012f907a2bda4840cdb8dad20da91e7192e5a90, thanks!
