### ISSUE TITLE
Potion of lignification crashes while dual wielding

### ISSUE THREAD

**Issue by Tttiimmm** [crawl/crawl#3569]
**PLATFORM and OS or BROWSER:**
CBR2 server

**DCSS VERSION AND GAME INFORMATION:**
Trunk (coglin patch)

**DESCRIPTION:**
Game crashes when quaff-id ing a lignification potion while dual wielding as a coglin.

[treecrashdcss.zip](https://github.com/crawl/crawl/files/14325609/treecrashdcss.zip)

**Comment by crystalsolenoid** [comment]
Exact same thing just happened to me.
http://crawl.akrasiac.org/rawdata/purplemustard/crash-purplemustard-20240219-061604.txt

**Comment by PleasingFungus** [comment]
Duplicate of #3557. Thanks for reporting! :)
