### ISSUE TITLE
Jinxbite double trigger and inconsistency

### ISSUE THREAD

**Issue by SentientSupper** [crawl/crawl#3581]
**PLATFORM and OS or BROWSER:**
windows local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.31

**DESCRIPTION:**
Jinxbite can trigger twice on the same target if your target blocks your ranged attack.
It can also trigger with darts and throwing nets if your target blocks or dodges it when it usually doesn't on hits.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/146337911/07c36605-822d-401e-bfa2-aa19f4a262ce)
![image](https://github.com/crawl/crawl/assets/146337911/4da01215-de8d-462d-aa87-ad89cf204230)

**Comment by matthewgranstrom** [comment]
It also looks like there's a messaging bug here -- The first screenshot uses the pronoun 'its' to refer to Louise's +3 demon trident of venom (it would astound me if the game somehow thinks the imp has a +3  demon trident of venom) and the second screenshot uses the pronoun 'her' to refer to Louise's feet.

**Comment by pooka109** [comment]
The messaging bug should be fixed now in trunk (as of 0.32-a0-446-ge4683972fd).

**Comment by DracoOmega** [comment]
Should be fixed by 0cd9e5b16809b0597c30085cd38648d044f65154
