### ISSUE TITLE
Auto-explore is done exploring, "revealing" a dead end before I have explored it

### ISSUE THREAD

**Issue by RypoFalem** [crawl/crawl#3586]
0.32-a0-451-g26e3978 webtiles

When pressing `o` to auto-explore, I am told "Done exploring." even though I shouldn't know that I've uncovered all walkable tiles yet. In the picture provided you can see there is an unexplored hallway. The dark tiles are wall tiles but I shouldn't have known that at the time!

![image](https://github.com/crawl/crawl/assets/7819240/e663a234-f81f-4072-8a2b-636e28335977)

**Comment by NormalPerson7** [comment]
This is because the missing tiles form part of the map boundary and must therefore be (indestructible) walls. That said, I'm not sure there's any way for the player to know that those tiles are the map boundary, so autoexplore should probably reveal them

**Comment by Aliscans** [comment]
This is the same as #1636; and is apparently working as intended.

**Comment by RypoFalem** [comment]
Seems unexpected from a player perspective because the player doesn't know where the map boundaries are without at least seeing them. Unusual but harmless. Since it's intended behavior I'll close it :)
