### ISSUE TITLE
Can't go down to the depths

### ISSUE THREAD

**Issue by Moltengargoyle** [crawl/crawl#3588]
hello. I am a dcss user in Korea. Please understand that I am not good at using English, so I am using a translator.

The version of the game is Dungeon Crawl Stone Soup 0.32-a0-468-g38b2580 (Console/Webtiles)

While playing MuCj Beogh, Beogh requested a new challenge when all of Beogh's apostles were dead on the deep second floor.

I overcame Beogh's challenge and then recruited a new Apostle.

However, the new Apostle also died, and when he tried to re-enter the second layer of Depth, the game crashed.

I thought I couldn't move up the stairs, so I went back to the 15th floor of the dungeon or moved to the crypt, but I was able to move to other places safely.

Below is the log of the game. thank you

https://crawl.project357.org/morgue/Draconianmaid/crash-Draconianmaid-20240224-092621.txt

**Comment by wheals** [comment]
I saw you quit the game in question. My apologies for not fixing this sooner.
