### ISSUE TITLE
Wizmode crash when trying to spawn an item

### ISSUE THREAD

**Issue by RypoFalem** [crawl/crawl#3595]
0.32-a0-506-g4120381aae local tiles

Trying to spawn an item crashes the game. `&o[` will crash before the prompt to specify which armour. Also tested with `&o/`

[crash-wizcrash-20240226-153709.txt](https://github.com/crawl/crawl/files/14411668/crash-wizcrash-20240226-153709.txt)

**Comment by SentientSupper** [comment]
This only happens if you have prompt_menu = false in your rc file. Probably introduced by a recent commit.
