### ISSUE TITLE
Yellow draconian acid spray deals 200 damage

### ISSUE THREAD

**Issue by pyy156941** [crawl/crawl#3597]
**PLATFORM and OS or BROWSER:**

Windows 11 Microsoft Edge

**DCSS VERSION AND GAME INFORMATION:**

0.32-a0-519-g08f29ac

**DESCRIPTION:**

A yellow draconian annihilator in the realm of Lom Lobon in Pan killed me from afar by an acid spray that dealt 200 damage.
[Morgue](https://crawl.project357.org/morgue/1n5z/morgue-1n5z-20240227-062711.txt)

**EXTRA FILES:**

**Comment by tarsierscripter** [comment]
I can corroborate this. I just lost my character to the same thing. It dealt exactly 255 damage!

**Comment by naddleman** [comment]
Looks like it was fixed [here](https://github.com/crawl/crawl/commit/344ed53f661988eb73563a9d0dc65100b42e7451)
