### ISSUE TITLE
Saw "a metal statue" base type in vaults (not gold or silver or whatever)

### ISSUE THREAD

**Issue by tarsierscripter** [crawl/crawl#3598]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-485-g70f7560b1c

**DESCRIPTION:**
Saw "a metal statue" base type in vaults (not gold or silver or whatever). The description said to file a bug report!

**EXTRA FILES:**
[Save file](https://cbro.berotato.org/saves/ChongLi-crawl-git-70f7560b1c-240227-0709.tar.bz2).

**Comment by BackslashEcho** [comment]
Spotted on webtiles version 0.32-a0-616-g9348d4545b
Can't get to my savegame on cbro but it seems to be a vault issue so hopefully OP's will suffice.

![image](https://github.com/crawl/crawl/assets/29342498/77ebb0f0-14b2-427e-a91f-286ad828c4dd)
The same; this looks like a Zin vault, and there's a pair of them:
![image](https://github.com/crawl/crawl/assets/29342498/38ecd5ec-09ff-4c25-95c2-0085c72d606e)

**Comment by wheals** [comment]
Original issue was fixed in 991db66f5c. Looks like a different vault for the second screenshot though.

**Comment by BackslashEcho** [comment]
> Original issue was fixed in [991db66](https://github.com/crawl/crawl/commit/991db66f5ceb7512270f0057779b07f9d538ebe9). Looks like a different vault for the second screenshot though.

Do you need a separate issue report? I'll need to figure out how to dig up my save file from CBRO.

**Comment by wheals** [comment]
No need now, I found it (that was the commit just now).
