### ISSUE TITLE
Weird waterlogged behaviour

### ISSUE THREAD

**Issue by LiciTheCrawler** [crawl/crawl#3600]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-530-gb6d6f0d0ac

**DESCRIPTION:**
If an enemy blocks and reflects the torrent of water produced by the phial of floods, but still gets splashed by the water (in case of standing next to the player) it won't get waterlogged.

**Comment by wheals** [comment]
Was this enemy Donald by any chance? He can't get waterlogged because he can swim.

**Comment by wheals** [comment]
Never mind, there really is a bug here
