### ISSUE TITLE
Wizard mode item creation keyboard shortcuts for scrolls/potions do nothing

### ISSUE THREAD

**Issue by pooka109** [crawl/crawl#3610]
**PLATFORM and OS or BROWSER:**
local tiles, Ubuntu 22.04.4 LTS

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-569-g667c705b62

**DESCRIPTION:**
This can be reproduced as follows (assuming that prompt_menu = true in your rc file):

1. Activate wizard mode and try to create an item, via "&o".
2. At the popup window, try to create a scroll by pressing "?". or a potion by pressing "!". Instead of prompting you for which scroll or potion type you want to create, the game will act as though no key was pressed. (All other key shortcuts, when you press them, prompt you as expected.)

**Comment by wheals** [comment]
Interestingly, this reproduces on webtiles as well, but not console.

**Comment by pooka109** [comment]
After some gdb tracing, I've found out that, in prompt.cc:PromptMenu::process_key(), it's falling through to menu.cc:Menu::process_key(), which is running the key value through get_command() in menu.cc:2004, and interpreting "?" as CMD_MENU_HELP and "!" as CMD_MENU_CYCLE_MODE.
