### ISSUE TITLE
Bug: Equipping a hand cannon as a Coglin crashes the game.

### ISSUE THREAD

**Issue by ClemGG** [crawl/crawl#3616]
**PLATFORM and OS or BROWSER:**
Webtiles, Windows 10, Firefox

**DCSS VERSION AND GAME INFORMATION:**
Version: Dungeon Crawl Stone Soup 0.32-a0-558-g233958a4c4

**DESCRIPTION:**
Obtained a randart hand cannon through a acquirement scroll on D:4.
Went back to D:3 to equip it.
Equipping a hand cannon as a Coglin crashes the game.

**EXTRA FILES:**
Crash log : https://crawl.xtahua.com/crawl/morgue/Konar/crash-Konar-20240301-082203.txt

**Comment by T-Minutiae** [comment]
I got the same problem on a Barachi. See morgue file below.

[crash-Heoxam-20240301-101547.txt](https://github.com/crawl/crawl/files/14459052/crash-Heoxam-20240301-101547.txt)

**Comment by pooka109** [comment]
Should be fixed as of 4c7f4391e0ca127e62af09178e4375e6edf7bbae.
