### ISSUE TITLE
Crash when cursing equipment with Ashenzari

### ISSUE THREAD

**Issue by Flugkiller** [crawl/crawl#3618]
**PLATFORM and OS or BROWSER:**
Webtiles, Google Chrome

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-585-gef4fe23122

**DESCRIPTION:**
Got a curse of introspection+companions from Ashenzari, selected my spear to curse, and the game crashed.

**EXTRA FILES:**
https://underhound.eu/crawl/morgue/Flugkiller/crash-Flugkiller-20240302-081355.txt

**Comment by wheals** [comment]
Fixed by DO as WizardIke mentioned
