### ISSUE TITLE
Liches can eat pizzas

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3635]
**PLATFORM and OS or BROWSER:**

webtiles

**DCSS VERSION AND GAME INFORMATION:**

Version: 0.32-a0-423-g123bbc5

**DESCRIPTION:**

While in lich form, I walked onto a food cache and ate a pizza.

**EXTRA FILES:**

![Screenshot (1357)](https://github.com/crawl/crawl/assets/26264063/b0e7a1f0-1a04-4184-8e3e-438b7b99c548)

**Comment by crystalsolenoid** [comment]
Ooh, can vegetarian species eat meat and carnivorous species eat fruit right now, too? Whoever ends up looking at this might want to check for that at the same time.

**Comment by pooka109** [comment]
Player species are accounted for; player forms are not.

**Comment by wheals** [comment]
Done in 4d5e64a
