### ISSUE TITLE
Sticky flames are unintuitive.

### ISSUE THREAD

**Issue by dambrosyo** [crawl/crawl#3680]
The reworking of sticky flames in 0.31 made the sticky flame status more powerful. However, the mechanics are deeply unintuitive in some ways.

In particular, if a person in real life is on fire, the official advice is for that person to not run around, but to stand in place and roll around to put out the fires more quickly: https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/fire/if-a-fire-starts.html .

> If your clothes catch on fire:
> Stop what you’re doing. Drop to the ground and cover your face if you can. Roll over and over or back and forth until the flames go out. **Running will only make the fire burn faster.** 

The mechanics in DCSS makes the fire go out quicker if the player runs, and not if the player waits in place not attacking or casting spells. This makes the current mechanics deeply unintuitive (and also indirectly gives some less than good IRL advice). Another roguelike, CDDA, makes the character put out fire on the character if the character waits in place not taking any other actions.

The simplest rework would be to let waiting (not attacking, not casting spells, just waiting in place) also put out the sticky flames more quickly, at least for the player. Monsters could be said to be too focused on killing the player to put out any fires on them while standing in place. The description could be "you roll around in place to put out the flames more quickly" when waiting in place while on fire.

**Comment by dambrosyo** [comment]
CC @DracoOmega .

**Comment by DracoOmega** [comment]
Regardless of whether this reflects good fire safety practice in real life, there are no plans to change the current mechanics in this way. (There is now even an additional reminder regarding movement when the player gets sticky flamed.)

If it helps, think of it not as trying to stop your cloak from burning, but to shake off the magical napalm that has gotten stuck to you. That was certainly part of the original intent.
