### ISSUE TITLE
Spellforged Servitor can't cast Permafrost Eruption

### ISSUE THREAD

**Issue by rredelmeier** [crawl/crawl#3690]
**PLATFORM and OS or BROWSER:**
Webtiles **DCSS VERSION AND GAME INFORMATION:**
0.32-a0-732-ga344392067

**DESCRIPTION:**
Spellforged Servitor cannot cast the new spell Permafrost Eruption. (Alternatively, it can, it's just not prioritized appropriately -- stone arrow was taking precedence). I lack the ?Amnesia to test further but can't see a reason the spell would be Servitor-excluded.

**Comment by PleasingFungus** [comment]
This is a known TODO. Apologies for the wait. :)

**Comment by pooka109** [comment]
This should be fixed as of 31df86b944a8383963a1f18e4919b6bad24e790e.
