### ISSUE TITLE
Bad randart staff name

### ISSUE THREAD

**Issue by NormalPerson7** [crawl/crawl#3691]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-g1d96ad09

**DESCRIPTION:**
"The stafffire of the Thirsty Allies" - Seems like a bugged name to me. See image

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/37064413/0ef700cd-690a-42ed-8926-9c35abc87bd3)

**Comment by PleasingFungus** [comment]
Fixed in 95338c156ce86d7b4b3cb89f98aa10beac2d877e, thanks!
