### ISSUE TITLE
log tells felid they can wear dragon scales

### ISSUE THREAD

**Issue by cfcfcfcfcfcfcfcfcfcf** [crawl/crawl#3721]
*PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.31.0-32-g396128a36d

**DESCRIPTION:**
 The steam dragon scales are intact enough to wear.
felid cannot wear, despite them being intact

**EXTRA FILES:**

**Comment by PleasingFungus** [comment]
No one said they were intact enough for *you* to wear. :)
