### ISSUE TITLE
grey draconian breath weapon has <liquified>

### ISSUE THREAD

**Issue by cfcfcfcfcfcfcfcfcfcf** [crawl/crawl#3726]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-818-gb728d0252e

**DESCRIPTION:**
A thick layer of gritty mud. <liquefied>

**EXTRA FILES:**
![image_2024-03-24_135933320](https://github.com/crawl/crawl/assets/78773087/dc6e8f5d-4a24-4240-a210-938ef063be41)

**Comment by pooka109** [comment]
Should be fixed in current trunk.
