### ISSUE TITLE
Crash when resuming game

### ISSUE THREAD

**Issue by wferguss** [crawl/crawl#3728]
**PLATFORM and OS or BROWSER:**
webtiles" on CAO 
Using Chrome bowser: Version 122.0.6261.111 (Official Build) (64-bit)
Linux oregon 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**DCSS VERSION AND GAME INFORMATION:**
Command line: /usr/games/crawl-git-b728d0252e -name wwf -rc /dgldir/rcfiles/crawl-git/wwf.rc -macro /dgldir/rcfiles/crawl-git/wwf.macro -morgue /dgldir/ttyrec/wwf/ -webtiles-socket /crawl-master/webserver/sockets/wwf:2024-03-25.01:45:05.sock -await-connection

**DESCRIPTION:**
The game crashes when I select my game to play from the main menu of CAO.
There seems to be no way to issue a command before it crashes. I cannot even Quit the game.
It does not crash immediately but it takes about 5 minutes.
The only thing that is displayed is the "stats" and then only the titles. No numeric or text data is present.
[crash-wwf-20240325-014512.txt](https://github.com/crawl/crawl/files/14737868/crash-wwf-20240325-014512.txt)

**EXTRA FILES:**
Crashlog is attached.
No screenshot is attached.
I cannot ssh into CAO with my username and password.

**Comment by wferguss** [comment]
Oh. I believe that my coglin did have rings on.
Your explanation makes sense.
Is there a way to delete this game so that I can play the latest DSSC?

**Comment by wheals** [comment]
Should be fixed in trunk, just wait till CAO updates to 0.32-a0-861-g165e151e72 or later and your game will load.

**Comment by wferguss** [comment]
I can now play normally when I resume my game.
Thanks everyone who helped.
