### ISSUE TITLE
Butterflies Move While Asleep

### ISSUE THREAD

**Issue by tr2424** [crawl/crawl#3731]
**PLATFORM and OS or BROWSER:**
local tiles, macos

**DCSS VERSION AND GAME INFORMATION:**
0.31.0

**DESCRIPTION:**
I've noticed this for some time. Sometimes butterflies will fly around and have "Zzzz" on them. Not taking about the scroll, these are ones that exist in the game, around shrines, etc. This may not be a bug at all, usually they "wake up" after moving a bit. But figured I'd log it just in case. If intended, or the way it is... please close and ignore me thanks! To reproduce I guess use a character w/a lot of stealth; that's when it occurs the most.

**Comment by wheals** [comment]
If you examine them closely, you'll see that they're sleepwalking! Butterflies do that in Crawl sometimes.
