### ISSUE TITLE
Felid Unable to Memorise Piledriver

### ISSUE THREAD

**Issue by Picklenugget1** [crawl/crawl#3737]
**PLATFORM and OS or BROWSER:**

CXC 

**DCSS VERSION AND GAME INFORMATION:**

0.32-a0-859-gb0a091d592

**DESCRIPTION:**

I just made a felid warper to try out the new spells, but to my disappointment it's unusable. It shows up in the dump as unusable, and when I try to find it ingame it says I can't memorise it because there's nothing nearby I can slingshot, as shown in the screenshot. However, when I move close to a monster the message goes away, but I'm still not able to memorize it.

**EXTRA FILES:**

![Screenshot 2024-03-27 10 52 44 AM](https://github.com/crawl/crawl/assets/113951792/da1d11b7-6ae3-4bfc-83b9-d76ac8c766fa)

**Comment by pooka109** [comment]
Should be fixed now.
