### ISSUE TITLE
Player Ghost Gell's Gravitas Crash

### ISSUE THREAD

**Issue by T-Minutiae** [crawl/crawl#3740]
PLATFORM and OS or BROWSER:
Local tiles, Windows 10 64-bit

DCSS VERSION AND GAME INFORMATION:
0.32-a0-868-g153ae1a8d6

DESCRIPTION:
A player ghost tried to cast the removed Gell's Gravitas spell, causing the game to crash.
From the crash file below: "ERROR in 'mon-cast.cc' at line 1789: Unknown monster spell 'Gell's Gravitas' cast by Ceyvaan's ghost".

EXTRA FILES:
[crash-Gaon-20240328-190735.txt](https://github.com/crawl/crawl/files/14793863/crash-Gaon-20240328-190735.txt)

**Comment by DracoOmega** [comment]
Should be fixed by f73ac7332549464a353c0b0cfd7cd54f0ec21239
