### ISSUE TITLE
The word "barding" is used incorrectly in DCSS

### ISSUE THREAD

**Issue by powerbf** [crawl/crawl#3748]
In DCSS, the word barding is used to mean the piece of armour that covers the hindquarters of nagas and armataurs
(and previously, palentongas and centaurs).

This is taken from the word for horse armour, but it's kind of a misnomer because barding refers to the entire suit of horse armour, not just the back part. The specific piece of the barding that protects the horse's hindquarters is called the croupiere (because croup means hindquarters/rump). It's also called croupiere bacul or crupper.

https://en.wikipedia.org/wiki/Barding

So, the item in DCSS should be called a croupiere, not barding.

**Comment by powerbf** [comment]
After sleeping on it, I think this may be too nitpicky, but I'll let the devs decide whether to close it or not.

**Comment by WizardIke** [comment]
The in game description says it's for the midsections of nagas and armataurs, and doesn't specifically mention the hindquarters. Also, I can clearly see the peytral in the equipped player sprite.

**Comment by powerbf** [comment]
Oh, you're right: "Armour for the scaly midsections of nagas and armataurs."
