### ISSUE TITLE
+12 demon trident

### ISSUE THREAD

**Issue by cfcfcfcfcfcfcfcfcfcf** [crawl/crawl#3754]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.31.0-32-g396128a36d

**DESCRIPTION:**
a merfolk impaler had a normal, non-artefact +12 demon trident, despite weapons only being enchantable up to +9 as a non-artefact

**EXTRA FILES:**
https://pastebin.com/wJVpXGg4

**Comment by NormalPerson7** [comment]
This isn't a bug. You can very occasionally find over-enchanted weapons, up to +12. This is most common with Killer Klowns' clubs in Zot. Consider it a rare and lucky moment!

**Comment by cfcfcfcfcfcfcfcfcfcf** [comment]
the wiki does not have this information
