### ISSUE TITLE
Talons damage on mutation screen is wrong when wearing boots

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#3779]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-995-gb4a59205af 

**DESCRIPTION:**
With talons 1 and boots, the base damage is displayed on the mutation screen as 5. The correct value is 7 (which is displayed when not wearing boots).

**Comment by pooka109** [comment]
This is not a bug. If you're wearing boots, your talons aren't usable unless you have talons 3 (which disallows wearing boots), so the extra damage from talons doesn't apply. The same logic applies to the hooves mutation.

**Comment by CrawlOdds** [comment]
This doesn't seem right to me - yes, boots suppress talons, but that doesn't seem a good reason for showing the wrong talon damage on the mutation screen when wearing boots (if it showed 0 this might make sense, though the suppressed value of 7 still seems better to me).

The reason this happens (I believe) is that AuxKick::get_damage in melee-attack.cc defaults to the damage of a (level 0/3) tentacle spike.

**Comment by pooka109** [comment]
After some thought, showing the suppressed attack value does seem better, especially since the mutation description already mentions that wearing boots cuts it off.
