### ISSUE TITLE
Barding doesn't show as currently unavailable when boots are merged

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3788]
**PLATFORM and OS or BROWSER:**

webtiles

**DCSS VERSION AND GAME INFORMATION:**

Version: 0.32-a0-1028-gf613fa2

**DESCRIPTION:**

When boots are melded by a form (e.g. statue form) the % screen says "(no barding)" instead of "(barding currently unavailable)".
There is also an equal button when examining barding in your inventory, although you can't actually equip it.

**EXTRA FILES:**

![Screenshot (1569)](https://github.com/crawl/crawl/assets/26264063/a793feb1-964d-4a1c-85b2-29db2b03ae1f)

**Comment by pooka109** [comment]
Bardings should now be displayed as unavailable under those circumstances as of current trunk.

As for the issue with the equip button, I don't use much of the mouse interface, but it seems to work on my end (with the fix applied, anyway). If it still doesn't work on yours, would you please let me know? Thanks.

**Comment by WizardIke** [comment]
I checked and other armour such as boots also has a (w)ear option when you can't wear it (although clicking just tells you you can't wear it). For some reason I thought it was just barding that showed it and it needed fixing because it was inconsistent.

**Comment by pooka109** [comment]
Good to know.
