### ISSUE TITLE
Hellfire Mortar - Game Crash

### ISSUE THREAD

**Issue by GoSagan** [crawl/crawl#3798]
**PLATFORM and OS or BROWSER:**S
CBRO web tiles, google chrome.

**DCSS VERSION AND GAME INFORMATION:**trunk

**DESCRIPTION:**
When casting hellfire mortar, if I hit select before aiming, the default is to target myself, at which point the game crashes.
**EXTRA FILES:**

**Comment by DracoOmega** [comment]
Should be fixed by 5b11573b90773a02b9c5fe2b70320fa5a4726082
