### ISSUE TITLE
Orc followers not dismissed properly when offscreen/not on same floor

### ISSUE THREAD

**Issue by EnfysPranc** [crawl/crawl#3814]
**PLATFORM and OS or BROWSER:**
Platform: Unix
Webtiles
Firefox

**DCSS VERSION AND GAME INFORMATION:**
Server: underhound.eu
Username: Zigma
Version: Dungeon Crawl Stone Soup 0.32-a0-1151-g7caecd69e6

**DESCRIPTION:**
An orc follower was dismissed while on a different floor, when the "Recall Apostles" ability was used later, four orcs were recalled instead of three. When the extra orc dies, it crashes the game.

**EXTRA FILES:**
Crash log: https://underhound.eu/crawl/morgue/Zigma/crash-Zigma-20240513-164746.txt
Morgue file pre-crash: https://underhound.eu/crawl/morgue/Zigma/Zigma.txt

![Screenshot 2024-05-13 180747](https://github.com/crawl/crawl/assets/122648496/48089fc3-c2fe-4f17-bbb7-5cf813dcac37)
![Screenshot 2024-05-13 180819](https://github.com/crawl/crawl/assets/122648496/a6ccf1d4-1d39-46e3-a190-fec6371ae360)

**Comment by DracoOmega** [comment]
This should be fixed by bcb4e34c79d6d1fbb2646269242129f791aed1e5
