### ISSUE TITLE
beogh has spell x2

### ISSUE THREAD

**Issue by cfcfcfcfcfcfcfcfcfcf** [crawl/crawl#3818]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-1175-gca21d12091

**DESCRIPTION:**
an apostle had the same spell listed twice in ^, but it appears to be normal via x v

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/78773087/74e75890-c881-4590-bc44-b423b1ee30de)

**Comment by DracoOmega** [comment]
Should have been fixed by 5a71cb29dfd65ed39e
