### ISSUE TITLE
Hellfire Mortar is displaying a lot of spellpower when it shouldn't

### ISSUE THREAD

**Issue by Flugkiller** [crawl/crawl#3820]
**PLATFORM and OS or BROWSER:**
Webtiles, Google Chrome

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-1185-ge5b5818aa0

**DESCRIPTION:**
The displayed spellpower of Hellfire Mortar seems rather high, see the character dump below. My character has 15 spellcasting, 15 fire magic, 14.5 earth magic, 32 int, one earth enhancer and one fire enhancer, yet the spellpower for Hellfire Mortar is displayed as being at 100%. If the max spellpower of this spell is supposed to be 200, that seems implausible. In contrast, the spellpower for Starburst is at 52%. If the spellpower for Hellfire Mortar is displayed correctly, it would then mean that one extra fire enhancer would bump Starburst up to 100%, which is absurd.

**EXTRA FILES:**
[bqtNDZBe.txt](https://github.com/crawl/crawl/files/15341682/bqtNDZBe.txt)
https://pastebin.com/bqtNDZBe

**Comment by NormalPerson7** [comment]
What's going on here is that while Hellfire Mortar is supposed to have a power cap of 200, `spell_to_zap` links it to `ZAP_HELLFIRE_MORTAR_DIG` which has a power cap of 100, and the default behaviour is to use the lesser of a spell's power cap and its corresponding zap's power cap. So Hellfire Mortar currently has a power cap of 100 - this is not just a display bug. I am looking into the best way to fix it.

**Comment by pooka109** [comment]
This should be fixed as of 30aeb729f79261c09dd60d8b3248537c93c634f7.
