### ISSUE TITLE
Haunt summons more than 8 mobs

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3827]
![image](https://github.com/crawl/crawl/assets/82269729/bec87c1b-dc10-4083-90f6-6550063f4d4a)

**Comment by NormalPerson7** [comment]
This is fine; when the summon cap is exceeded, the oldest summons will expire on the following turn, not immediately.

**Comment by projectNoob** [comment]
> This is fine; when the summon cap is exceeded, the oldest summons will expire on the following turn, not immediately.

I had realized that, but it felt strange as other summonings disappear immediately.

**Comment by NormalPerson7** [comment]
Okay, yes, you have a good point.

**Comment by DracoOmega** [comment]
This should be fixed by 5a289ac79d06e3d860b38cf112af88c69fa9a189
