### ISSUE TITLE
coglin hands

### ISSUE THREAD

**Issue by cfcfcfcfcfcfcfcfcfcf** [crawl/crawl#3841]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-1316-gbd61dd866b

**DESCRIPTION:**
coglins do not have hands, they have graspers

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/78773087/273c1154-c94d-4d93-afe4-8ed48c762522)

**Comment by NormalPerson7** [comment]
Perhaps this should just say "custom made by you".

**Comment by pooka109** [comment]
They have graspers in their exo-suit, but the exo-suit seems to be primarily for dual-wielding weapons, not constructing gizmos; they could still use their hands to construct gizmos.

**Comment by DracoOmega** [comment]
Just because they're not holding weapons in combat with their hands doesn't mean they don't actually *have* hands. In fact, I think the flavor is fairly clear that the reason they're not using them in combat is because they're preoccupied operating the exo-frame. (Ijyb has hands, after all)
