### ISSUE TITLE
Maggie refers to herself as Margery

### ISSUE THREAD

**Issue by ZillyBean** [crawl/crawl#3845]
Version: 0.31.0, local tiles

I ran into Maggie and she said this. (Assuming it's not intended.)

![maggie text](https://github.com/crawl/crawl/assets/122182898/5536b60c-6e13-49b6-b50f-8177ecc8bafb)

**Comment by pooka109** [comment]
This has been fixed in trunk as of cfddb08e57f2679e3c1e26f1784b37bccafcd4af.
