### ISSUE TITLE
'Ran out of altars for temple' on a fresh D:1 start, turn 0. (Seed attached.)

### ISSUE THREAD

**Issue by Vajrapani** [crawl/crawl#3846]
**Platform :** Webtiles (Xtahua)
**Browser :** Firefox 126.0.1 (64-bit)
**DCSS Version :** 0.32-a0-1318-g632b080833
**Seed :** 9863101266137518467
As seen in the log directly after starting the game.
![image](https://github.com/crawl/crawl/assets/35668582/9e5f923d-e188-4ffb-b735-a41b5d241892)

**Comment by Vajrapani** [comment]
Updated with Seed for the game : 9863101266137518467

**Comment by AlejandorLazaro** [comment]
Hit this issue as well on the following seed today on SDL Tiles 0.31.0 (Aug 2, 2024): 7372195435161540223

**Comment by SamanthaTovah** [comment]
reproduced this bug with the seed and version given. issue seems to be that temple vault regret_index_temple_chain_breaker is tagged with temple_altars_18 but actually has 20 altars.

issue fixed when the vault is given the appropriate temple_altars_20 tag.

will create a PR to fix this. there are probably other temple vaults with the same issue.
