### ISSUE TITLE
Jivya Bug

### ISSUE THREAD

**Issue by Skular7** [crawl/crawl#3851]
**PLATFORM and OS or BROWSER:**
Browser, Online

**DCSS VERSION AND GAME INFORMATION:**
Latest Trunk version

**DESCRIPTION:**
Jivya Bug, Cannot switch to the God and I'm currently worshipping Kiku. I tried two different Jivya altars with no luck.

**EXTRA FILES:**
![Jivya_Bug](https://github.com/crawl/crawl/assets/171612928/e980f211-93a6-48dc-9b29-c7c0d012e3b7)

**Comment by jjjingleheimer** [comment]
I just got the same message when trying to pray at an Ignis altar. Maybe it has something to do with the "uncommon" altars? (ie. Jiyva, Beogh, Ignis, Lugonu)
![ignis altar bug](https://github.com/crawl/crawl/assets/141385023/a6721bd2-1522-499e-8fe3-23133c122d05)

**Comment by elliottbernstein** [comment]
I hit this issue too trying to convert to Jiyva; waiting for a fix before i continue my current trunk game. thank you!

**Comment by Skular7** [comment]
> I just got the same message when trying to pray at an Ignis altar. Maybe it has something to do with the "uncommon" altars? (ie. Jiyva, Beogh, Ignis, Lugonu) ![ignis altar bug](https://private-user-images.githubusercontent.com/141385023/336309808-a6721bd2-1522-499e-8fe3-23133c122d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODgzNzgsIm5iZiI6MTcxNzU4ODA3OCwicGF0aCI6Ii8xNDEzODUwMjMvMzM2MzA5ODA4LWE2NzIxYmQyLTE1MjItNDk5ZS04ZmUzLTIzMTMzYzEyMmQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxMTQ3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmE3MjQxMjE2YTE2MGRmZWM5YTFkMmExMTlkM2YyMDZkNGZiM2UwNWMwNTcyNjE2MzA5ZGYyZjdhYjM4MzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6f1QTS8xF0NghESNStF8NTOOY1gBNDl3EQ37PoWWOKo)

That's so odd.... I had a feeling it was uncommon things otherwise it would have been found faster. Trunk was updated but still unable to pray at the altar. I'm not giving up this epic FeSu run.

**Comment by elliottbernstein** [comment]
Bug is still happening in today's build, but the person who made the changes I pointed to above is checking things out.

**Comment by NormalPerson7** [comment]
Should be fixed now. Once the server you play on updates to the latest trunk version, you should be good to go. The issue was Webtiles specific, and I forgot that Webtiles behaves differently for UI things so I didn't test it. Oh well, so it goes.

(This issue can be closed.)

**Comment by PleasingFungus** [comment]
Thanks for reporting!
