### ISSUE TITLE
Right clicking on a skill doesn't describe it when it is level 27

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3872]
**PLATFORM and OS or BROWSER:**

local tiles

**DCSS VERSION AND GAME INFORMATION:**

Version: 0.32-a0-1074-g4fd57f6e19

**DESCRIPTION:**

Pressing m to open the skill menu and them right clicking a skill with a base value of 27 closes the menu instead of describing the skill

**EXTRA FILES:**

**Comment by kleiner-fisch** [comment]
### Question about intended behavior
I am unsure what the intended behavior should be, whether actually anything _should_ be done differently.

When choosing which skills to train (before pressing `?`), only non-mastered skills are clickable. Being clickable coincides with having a hoover-over effect. If we change this, we either create a button that is right-clickable but has no hoover over effect, or we create a button with hoover over effect that is not left-clickable.

In my opinion it is fine to stay the way it is. What do you think @WizardIke ?

### Description of current behavior
version 0.33-a0-311-g228c53f3ca (local tiles).

Hovering over a non-mastered skill will highlight the skill. Left clicking enables training the skill, while right-clicking will give a description. Left-clocking a mastered (golden) skill does nothing, while right-clicking closes the skill menu.
![image](https://github.com/user-attachments/assets/2207ab1e-36ea-4aa4-9d6f-8e60e46eb619)

After pressing `?` in the skill menu, you are presented with different options. Here all skills behave the same (mastered and non-mastered). Hoovering over any skill will highlight it, and left-clicking gives a description of the skill, and right-cklicking does the same.
![image](https://github.com/user-attachments/assets/122a0ef9-6a4b-4eaa-98e7-da388135541b)

**Comment by WizardIke** [comment]
Now that you've laid out the options. I can see than there isn't really a better option.
You can't really highlight the maxed out skills as this would be weird when using the arrow keys and allowing right clicking but not highlighting the skill isn't really any less weird than the current way things work.
