### ISSUE TITLE
Game Crashed 

### ISSUE THREAD

**Issue by bobross419** [crawl/crawl#3881]
**PLATFORM and OS or BROWSER:**
cbro web tiles, macOS/safari

**DCSS VERSION AND GAME INFORMATION:**
Version: Dungeon Crawl Stone Soup 0.32-a0-1508-g6630b05a1f
Platform: unix
Bits: 64
Game mode: normal
Tiles: online

Seed: 11154460223471640881, deterministic pregen: 1
Version history:
Game started: 0.32-a0-1483-gdbccd6685e
0.32-a0-1508-g6630b05a1f

**DESCRIPTION:**
I don't even remember what I was doing, couple bad guys on the screen over lava.  Game crashed and the output was so verbose I figured ya'll would want it.  You can close if this isn't helpful.  

**EXTRA FILES:**
https://cbro.berotato.org/morgue/MrSquiggles/crash-MrSquiggles-20240621-214234.txt
https://cbro.berotato.org/saves/MrSquiggles-crawl-git-6630b05a1f-240621-2200.tar.bz2

**Comment by DracoOmega** [comment]
Should have been fixed by de231d1551cd15a5aca1167de8eec6fefe7956ec
