### ISSUE TITLE
Eviscerate but do no damage

### ISSUE THREAD

**Issue by jejorda2** [crawl/crawl#3890]
**PLATFORM and OS or BROWSER:**
Dungeon Crawl Stone Soup 0.32-a0-1581-gfdff619988 (Console/Webtiles)

**DCSS VERSION AND GAME INFORMATION:**
CBR2 
https://cbro.berotato.org/saves/jejorda2-crawl-git-fdff619988-240628-0008.tar.bz2

**DESCRIPTION:**
I'm seeing lots of combat messages along the lines of:
The orc eviscerates you but does no damage.
Your +1 spectral war axe eviscerates the orc priest but does no damage.

It doesn't make sense to cut organs out without doing damage.
Can the threshold between hit and eviscerate be adjusted to change all these to "hit but does not damage?"

Thanks!

**Comment by DracoOmega** [comment]
This was a very brief messaging bug, introduced by f798c56413617fcd46cedd42b840ec46834aed85 and should have been fixed by e2cddfa179b1458cd9d0b49c6ac67b67bb2c0126
