### ISSUE TITLE
Starburst requiring me to harvest soul to be able to cast it

### ISSUE THREAD

**Issue by salomoncle** [crawl/crawl#3892]
**PLATFORM and OS or BROWSER:webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-1591-ga9aa173657

**DESCRIPTION:**
Playing as a Deep Elf of Vehumet. At some point Vehumet gave me the knowledge of starburst which I instantly took. Though when trying to cast it I get prompted with: "You must harvest more living souls to recharge this spell."
Unless this has been changed very recently I don't think you should need to harvest souls to cast this spell

**EXTRA FILES:**
![Screenshot 2024-06-28 at 16 32 02](https://github.com/crawl/crawl/assets/19990833/7f416af0-18dc-489d-b55f-148d947fff19)

**Comment by pooka109** [comment]
This should be fixed as of 94106ed5a18e508b7ebe125109b0311cbeeccf04.
