### ISSUE TITLE
You must harvest more living souls to cast this spell when attempting to cast Starburst

### ISSUE THREAD

**Issue by Decarabia** [crawl/crawl#3893]
**PLATFORM and OS or BROWSER:**
chrome webtiles

**DCSS VERSION AND GAME INFORMATION:**
 Dungeon Crawl Stone Soup version 0.32-a0-1591-ga9aa173

**DESCRIPTION:**
There no longer seems to be a way to cast starburst. This doesn't appear to be a documented change.

**EXTRA FILES:**
https://crawl.akrasiac.org/rawdata/PowerSlave/PowerSlave.txt
![Screenshot 2024-06-28 113428](https://github.com/crawl/crawl/assets/7276431/14760470-690e-46d1-bfe2-d37633eb5a6d)

**Comment by pooka109** [comment]
This should be fixed as of https://github.com/crawl/crawl/commit/94106ed5a18e508b7ebe125109b0311cbeeccf04.
