### ISSUE TITLE
Necromancer background description still mentions Necrotise

### ISSUE THREAD

**Issue by jlwoodwa** [crawl/crawl#3894]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-1591-ga9aa173

**DESCRIPTION:**
The background description for Necromancer says that they start with Necrotise. It should say Soul Splinter instead.

**Comment by pooka109** [comment]
Fixed in trunk as of b744659e0326313cbda90657df794db1acbabf80.
