### ISSUE TITLE
Kills by apostle's foxfire count as yours

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3896]
**PLATFORM and OS or BROWSER:**
webtiles, CBR2

**DCSS VERSION AND GAME INFORMATION:**
Trunk

**DESCRIPTION:**
My apostle conjured some foxfire. They hit the enemy, and it said 'You kill the xxx'.

**EXTRA FILES:**
![image](https://github.com/crawl/crawl/assets/82269729/c84cac25-9d20-486d-abbb-d0aee7bcc8c5)

**Comment by DracoOmega** [comment]
Should be fixed by 193dd4b
