### ISSUE TITLE
Image of staff of Earth did not change when cursed

### ISSUE THREAD

**Issue by PotatoGolem** [crawl/crawl#3912]
Local tiles.

version 0.31.0

When I curse my Staff of Earth the image of it does not change in the display. However when I look at inventory, the image of the staff has changed, and is purple.

**Comment by PotatoGolem** [comment]
I now see this also happens with staff of conjurations. Same version of game.

**Comment by kleiner-fisch** [comment]
Could not reproduce this in  version 0.33-a0-311-g228c53f3ca (local tiles).
Both cursed staffs change their symbol (in inventory and as it is shown on the character).

Seems fixed?

**Comment by DracoOmega** [comment]
Seems likely to have been the same issue fixed by 0f6f1dd4b9273ad70c2c0f737dad5444d255bb93
