### ISSUE TITLE
Reporting this again

### ISSUE THREAD

**Issue by HumanDestiny** [crawl/crawl#3915]
**PLATFORM and OS or BROWSER:**

**DCSS VERSION AND GAME INFORMATION:**

**DESCRIPTION:**

**EXTRA FILES:**

**Comment by HumanDestiny** [comment]
Pand. Rainbow room crash. I have a stream this time that I'll link with a time stamp. Stream is good for 7 days.

https://www.twitch.tv/videos/2193907528

Time stamp is 1 hour 34 minutes

**Comment by HumanDestiny** [comment]
Reported this bug about 5 months ago...

**Comment by Implojin** [comment]
The provided link here is dead, with no information about what your bug may or may not have been. Closing.
