### ISSUE TITLE
Tukima's Dance can no longer be used

### ISSUE THREAD

**Issue by Doucebaguette** [crawl/crawl#3917]
**PLATFORM and OS or BROWSER:**
Chrome

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-1718-g281234c535

**DESCRIPTION:**
Every time I try to use the spell "Tukima's Dance", I get the message "You cannot cast this spell because you cannot coerce anything to obey you". To reproduce, use any enchanter (more than one spriggan were used to test the case), get to unlocking "Tukima's Dance" and try to use the spell when facing your first weapon wielding orc.

**Comment by pooka109** [comment]
I can't reproduce this; Tukima's Dance works as it should on my end, although I'm not worshipping any god when I try casting it.

Are you worshipping Okawaru when you try casting it? Okawaru's "no allies" conduct applies to the dancing weapons from Tukima's Dance, and that will keep it from working.

**Comment by Doucebaguette** [comment]
That is correct, sorry It was my bad.

**Comment by pooka109** [comment]
No problem.
