### ISSUE TITLE
Teleport closet in cheibrodos_frozen_isle

### ISSUE THREAD

**Issue by Flugkiller** [crawl/crawl#3927]
**PLATFORM and OS or BROWSER:**
webtiles, Google Chrome

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-1752-gb744d034b2

**DESCRIPTION:**
Although extremely unlikely to happen in an actual game, it is possible to be permanently trapped on the island in cheibrodos_frozen_isle, if you were to run out means of crossing deep water/digging/teleporting/blinking etc. . See image attached below. 

**EXTRA FILES:**
https://crawl.xtahua.com/crawl/morgue/Flugkiller/morgue-Flugkiller-20240720-001753.txt
![chrome_2024-07-20_02-10-08](https://github.com/user-attachments/assets/02b7291f-7480-4de9-8784-426e389a9f1a)

**Comment by regret-index** [comment]
Fixed in 3bae827.
