### ISSUE TITLE
Brom's boulder behaves very strangely when switching floors

### ISSUE THREAD

**Issue by radio-gra** [crawl/crawl#3931]
**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup version 0.31.0-32-g396128a36d (console) @ CUE / underhound.eu 

**DESCRIPTION:**
Cast boulder, leave the floor, wait any amount of time on the new floor. When you return, the boulder will still exist, even though it should have expired. Additionally, it may be in a different state or have a different trajectory every time.

**EXTRA FILES:**
Screen recording: https://github.com/user-attachments/assets/555be887-aaec-496b-8aad-fb63b783b69a

**Comment by DracoOmega** [comment]
Should have been fixed by 6911597
