### ISSUE TITLE
[Coglin] When only a single one-handed weapon is equipped, clicking other one-handed weapons switches the primary equipped weapon instead of wielding it in the available offhand slot

### ISSUE THREAD

**Issue by AlejandorLazaro** [crawl/crawl#3943]
**PLATFORM and OS or BROWSER:**
* macOS Sonoma 14.5 (23F79)
* Local SDL Tiles

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-1904-ga9c1aa24dc

**DESCRIPTION:**
When playing coglin, if the player has only a single one-handed weapon equipped, clicking another weapon swaps the main-hand weapon to it instead of equipping it in the off-hand slot.

**NOTE:** This was tested in tiles and *only* occurs when clicking the weapon manually in the inventory view. This *did not* reproduce and was even fixed with the 'e'quip menu, which allows the player to properly equip a weapon into the off-hand if it is empty.

**EXTRA FILES:**
Video showing the bug in action:
https://github.com/user-attachments/assets/8afd5361-e379-4603-a119-fd768c673763

__\*\*ADDENDUM\*\*:__
This also caused me to unintentionally destroy my main cursed weapon from Ashenzari, effectively sabotaging my playthrough due to unequipping the wrong thing and not providing a warning.
<img width="749" alt="Screenshot 2024-07-31 at 11 46 35 PM" src="https://github.com/user-attachments/assets/1db696ea-44ca-46e4-b303-dcbdae317fa1">

**Comment by WizardIke** [comment]
I don't think the game tells you anywhere but its ctrl left click to equip in your offhand

**Comment by AlejandorLazaro** [comment]
Oof, that'd be great to know and have mentioned somewhere.

**Comment by AlejandorLazaro** [comment]
Yeah... this also doesn't warn at all when switching webs for Ashenzari. This could really sour someone's day with a punishing behavior for a simple misclick.

**Comment by AlejandorLazaro** [comment]
Looks like @DracoOmega is dealing with this here! 8529b04c429318c8a91007c0de9c99998a4c6ad7

Thanks! 😄

**Comment by AlejandorLazaro** [comment]
Oops, going ahead and closing this out.
