### ISSUE TITLE
Error relating to bazaar generation

### ISSUE THREAD

**Issue by Filljug** [crawl/crawl#3961]
**PLATFORM and OS or BROWSER:**
<webtiles>

**DCSS VERSION AND GAME INFORMATION:**
<0.32-a0-2013-ge579cb0a31>

**DESCRIPTION:**
<Immediately on entering Lair I received the following message:
`Fatal lua error: /crawl-master/crawl-git-e579cb0a31/data/dat/des/portals/bazaar.des:366: Couldn't find a map for normal bazaar
 Builder VETO on fatal lua error: D:13: Vault placement failure for 'bazaar_wrapper'. /crawl-master/crawl-git-e579cb0a31/data/dat/des/portals/bazaar.des:366: Couldn't find a map for normal bazaar`
I haven't yet explored to find out if a bazaar has been generated.>

**EXTRA FILES:**
<screenshot:
[image](https://github.com/user-attachments/assets/12b3e2e5-ab02-4922-90d5-eb97f321f6b1)
>

**Comment by regret-index** [comment]
Fixed by c0d1bbe.
