### ISSUE TITLE
Unknown monster spell crash

### ISSUE THREAD

**Issue by LightDoom** [crawl/crawl#3962]
**PLATFORM and OS or BROWSER:**
"local tiles"

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.32-a0-2014-gc0d1bbeec4 (SDL Tiles)

**DESCRIPTION:**
The game crashed when a ghost casted a spell

**EXTRA FILES:**
[crash_rep_save.zip](https://github.com/user-attachments/files/16514747/crash_rep_save.zip)

Error code: ERROR in 'mon-cast.cc' at line 2058: Unknown monster spell 'Gell's Gravitas' cast by Ceyvaan's ghost

**Comment by DracoOmega** [comment]
This should hopefully finally be fixed by 1eb867f
