### ISSUE TITLE
Crash with Magnavolt and Shadow Tempest in Cocytus

### ISSUE THREAD

**Issue by IntricateGwyn** [crawl/crawl#3963]
**PLATFORM and OS or BROWSER:**
"webtiles" "Firefox"

**DCSS VERSION AND GAME INFORMATION:**
"0.32-a0-2015-g0644d94"

**DESCRIPTION:**
In Cocytus 2, casting Magnavolt multiple times against multiple enemies. On the final cast before the crash, Magnavolt struck multiple enemies, and the Shadow from Dithmenos cast Shadow Tempest. The game crashed either before Shadow Tempest resolved, or immediately after. The enemies present were Elemental Wellsprings and their summoned Water Elementals, and some Simulacra. This has happened twice, both times with the same circumstances.

**EXTRA FILES:**
Crash Logs:
https://crawl.akrasiac.org/rawdata/IntricateGwyn/crash-IntricateGwyn-20240806-201104.txt
https://crawl.akrasiac.org/rawdata/IntricateGwyn/crash-IntricateGwyn-20240806-145230.txt

**Comment by DracoOmega** [comment]
Should have been fixed by b1c0d4f7e422a91c509
