### ISSUE TITLE
Draconian wings cosmetic bug

### ISSUE THREAD

**Issue by kuniqsX** [crawl/crawl#3973]
Version: trunk 
Dungeon Crawl Stone Soup version 0.32-a0-2080-gfe854bf2fb (webtiles) 

Problem: gained wings mutation from potion on pale draconian. Removed it, but the "wings" on the paperdoll were still on. After saving and reloading, the paperdoll correctly doesn't have wings anymore.

**Comment by AlejandorLazaro** [comment]
Reproduced and verified issue on trunk 0.33-a0-6-gb2e620de6b (SDL Tiles).

<img width="172" alt="Screenshot 2024-08-23 at 5 55 50 PM" src="https://github.com/user-attachments/assets/8979a596-d56d-4068-bedb-61f3d3796169">
<img width="561" alt="Screenshot 2024-08-23 at 5 56 03 PM" src="https://github.com/user-attachments/assets/c466e1af-02ff-49e6-aa7f-d09b94a1fc53">
<img width="561" alt="Screenshot 2024-08-23 at 5 56 17 PM" src="https://github.com/user-attachments/assets/060153bf-ad63-4f2b-955f-85ff753c6de9">

Of note, the character select screen also shows the incorrect wing status until after loading the character without the BIG_WINGS mutation.

<img width="468" alt="Screenshot 2024-08-23 at 5 57 27 PM" src="https://github.com/user-attachments/assets/bc69c187-b0c1-45bf-8709-3ff738132bd9">
