### ISSUE TITLE
Most recent trunk update on webtiles has broken the game for me. Crashes upon attempting to load.

### ISSUE THREAD

**Issue by gardentea** [crawl/crawl#3977]
ASSERT(!invalid_monster_type(mi.type)) in 'tags.cc' at line 6223 failed.

Version: Dungeon Crawl Stone Soup 0.32-a0-2093-gb660852
Platform: unix
Bits: 64
Game mode: normal
Tiles: online

Seed: 5153078768283612827, deterministic pregen: 1
Version history:
Game started: 0.32-a0-2077-gc9a0f24
0.32-a0-2083-gaa93178

Command line: /usr/games/crawl-git-b660852781 -name Velsharoon -rc /dgldir/rcfiles/crawl-git/Velsharoon.rc -macro /dgldir/rcfiles/crawl-git/Velsharoon.macro -morgue /dgldir/ttyrec/Velsharoon/ -webtiles-socket /crawl-master/webserver/sockets/Velsharoon:2024-08-13.13:46:30.sock -await-connection

RC options:
restart_after_game = false

Crash caused by signal #6: Aborted

Obtained 16 stack frames.
/usr/games/crawl-git-b660852781(_Z17write_stack_traceP8_IO_FILE+0x23) [0x76f013]: write_stack_trace(_IO_FILE*)
/usr/games/crawl-git-b660852781(_Z13do_crash_dumpv+0x3ca) [0x778ada]: do_crash_dump()
/usr/games/crawl-git-b660852781(_Z20crash_signal_handleri+0x74) [0x76f264]: crash_signal_handler(int)
/lib/libc.so.6(+0x324f0) [0x7ff1d19304f0]: 
/lib/libpthread.so.0(raise+0x2b) [0x7ff1d1c93efb]: 
/usr/games/crawl-git-b660852781() [0x778199]
/usr/games/crawl-git-b660852781() [0x7784b7]
/usr/games/crawl-git-b660852781(_Z17unmarshallMapCellR6readerR8map_cell+0x119f) [0xd19eff]: unmarshallMapCell(reader&, map_cell&)
/usr/games/crawl-git-b660852781() [0xd1e977]
/usr/games/crawl-git-b660852781(_Z8tag_readR6reader8tag_type+0xac8) [0xd21738]: tag_read(reader&, tag_type)
/usr/games/crawl-git-b660852781() [0x849264]
/usr/games/crawl-git-b660852781(_Z10load_level20dungeon_feature_type14load_mode_typeRK8level_id+0x157b) [0x8545fb]: load_level(dungeon_feature_type, load_mode_type, level_id const&)
/usr/games/crawl-git-b660852781(_Z12startup_stepv+0xc03) [0xcebe73]: startup_step()
/usr/games/crawl-git-b660852781(main+0x339) [0x6b02d9]: 
/lib/libc.so.6(__libc_start_main+0xfd) [0x7ff1d191cead]: 
/usr/games/crawl-git-b660852781() [0x6b15d9]

gdb not executable.

Compilation info:
<<<<<<<<<<<
Compiled with GCC 4.7.2
Build platform: x86_64-linux-gnu
Platform: x86_64-linux-gnu
CFLAGS: -O2 -pipe -DUSE_TILE -DUSE_TILE_WEB -Wall -Wformat-security -Wundef -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-type-limits -Wno-uninitialized -Wno-array-bounds -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -isystem /usr/include/lua5.1 -isystem /usr/local/include -g -DWIZARD -DASSERTS -DREGEX_PCRE -DCLUA_BINDINGS -DDGAMELAUNCH -DSAVE_DIR_PATH="/crawl-master/crawl-git-b660852781/saves" -DSHARED_DIR_PATH="/crawl-master/crawl-git/saves" -DDATA_DIR_PATH="/crawl-master/crawl-git-b660852781/data/" -DWEB_DIR_PATH="/crawl-master/crawl-git-b660852781/data/web/" -isystem /usr/include/ncursesw
LDFLAGS: -rdynamic -O2 
>>>>>>>>>>>

Place info:
branch = 23, depth = 1

Level id: Pan
Level build method = ABSENT, level layout type  = ABSENT, absdepth0 = 24

>>>>>>>>>>>>>>>>>>>>>>

Version history:
Game started: 0.32-a0-2077-gc9a0f24
0.32-a0-2083-gaa93178

Game state:

mouse_enabled: 0, waiting_for_command: 0, terminal_resized: 0
io_inited: 1, need_save: 1, saving_game: 0, updating_scores: 0:
seen_hups: 0, map_stat_gen: 0, type: 1, arena_suspended: 0

prev_cmd = CMD_NO_CMD
repeat_cmd = CMD_NO_CMD

Player:
{{{{{{{{{{{
Name:    [Velsharoon]
Species: Demonspawn
Job:     Air Elementalist

HP: 2/179; mods: 0/0
MP: 6/37; mod: 0
Stats: 16 (16) 25 (25) 16 (16)
Position: (41, 28), god: Vehumet (6), turn_is_over: 0, banished: 0
Recursive crash.

**Comment by gardentea** [comment]
Closed why?

**Comment by gammafunk** [comment]
The commit linked above that closed this issue should have fixed this bug. I've started a rebuild on CAO, but it will take 20-30 minutes to complete. After that rebuild finishes and when you resume your game, it should load and play normally. If it's not fixed 30 minutes from now, let us know in this issue. Thanks!
