### ISSUE TITLE
Dith shadow and Hep ancestor are not immune to fulsome fusillade

### ISSUE THREAD

**Issue by acrobat3** [crawl/crawl#3985]
PLATFORM and OS or BROWSER:
local tiles

DCSS VERSION AND GAME INFORMATION:
0.32-a0-2149-g8529b04c42 (latest trunk)

DESCRIPTION:

Dith shadow and Hep ancestor are immune to fulsome fusillade's damage but not immune to its debuff.

![1](https://github.com/user-attachments/assets/9eb57c37-3c27-4c6e-901d-f0766d26f284)

![2](https://github.com/user-attachments/assets/eb5305d4-b14e-4796-8dec-7a5c2adf9ddf)

![1](https://github.com/user-attachments/assets/363d9848-fc5e-4f34-83a9-1fd7a94e05b3)

![2](https://github.com/user-attachments/assets/6b9da5a3-cf56-4593-bad7-32295bc2bf07)

**Comment by AlejandorLazaro** [comment]
My attempt at fixing this was to add a `god_protects(mon, true)` check in `_do_fusillade_hit` before applying flavors.

Seems to have worked:

1. Shadow appears next to two monsters non-adjacent to player
<img width="862" alt="Screenshot 2024-08-23 at 5 13 26 PM" src="https://github.com/user-attachments/assets/d50375fe-90ae-4e73-9179-b4a5e3eaf168">

2. Fulsome Fullisade hits and the overlapping clouds strike the shadow
<img width="845" alt="Screenshot 2024-08-23 at 5 13 40 PM" src="https://github.com/user-attachments/assets/1f1c3ed3-23ef-4dbe-8988-8879333944d6">

3.  Shadow comes out unaffected while other monsters still are
<img width="850" alt="Screenshot 2024-08-23 at 5 14 43 PM" src="https://github.com/user-attachments/assets/3ed0f087-028c-4bd0-b0fb-3da765cabcc9">

```
Enter Wizard Command (? - help): 
Cast which spell? 
You conjure up an array of volatile reagents!
Flasks of reagents rain from above! Your shadow avoids your attack.
The unstable reaction engulfs the daeva!!
The daeva is lightly wounded.
The unstable reaction engulfs the angel!!
The angel is lightly wounded.
The unstable reaction engulfs the angel!!
The angel is lightly wounded.
The angel twists and deforms.
The unstable reaction engulfs the seraph!
The seraph is lightly wounded.
The seraph twists and deforms. The noxious sulphur engulfs the angel! The angel
partially resists.
The angel is poisoned.
The angel is lightly wounded.

     #.
     ..
     #.##
      ..#
      ..#
..#############
.....#..††..#..
     #.<†...#
     #†..†..#
    .#†@AA..#..
  #.##..A..A###
 ..  #....A@#.
#.  #########.#
#             #


You can see a seraph (misshapen, ally target), a daeva (summoned, sheltered), 3
angels and a friendly shadow.
```
