### ISSUE TITLE
Spellbooks marked as useless while worshipping Okawaru do not give you spells after you abandon him.

### ISSUE THREAD

**Issue by kuniqsX** [crawl/crawl#3994]
Dungeon Crawl Stone Soup version 0.33-a0-5-g34d56c8fa2 (webtiles)
- Playing as formicid gladiator of Okawaru.
- Abandon Okawaru for TSO
- Abandon TSO for Cheibriados
Problem: spellbooks which had spells forbidden by Okawaru (i.e. Animate Dead, Death Channel) did not give me those spells when I was no longer a follower of Okawaru. They give the "Unfortunately, you learn nothing new" message as with books containing spells you already know.
Those spells are effectively forbidden to me in that game.

**Comment by NormalPerson7** [comment]
Steps to reproduce this, in case others wish to investigate:
* Worship Okawaru
* Pick up a book containing a "useless" Summonings/Necromancy spell. Doing so fails to add the spell to your library.
* Abandon Okawaru
* Now whatever you do, it's not possible to add said spell to your library.
