### ISSUE TITLE
Found the shattered Dungeon gem at the end of Depths

### ISSUE THREAD

**Issue by WizardIke** [crawl/crawl#3999]
**PLATFORM and OS or BROWSER:**

webtiles

**DCSS VERSION AND GAME INFORMATION:**

Version: 0.33-a0-35-g516f9d4
Game seed: 5266597994275990087

**DESCRIPTION:**

After running out of time to get the gems on both the Dungeon and Depths, I found a shattered Dungeon gem at the end of Depths where you would usually find the Depths gem if you got there in less turns.

Related issue #3692 

**EXTRA FILES:**

Morgue: https://crawl.project357.org/morgue/Wizard1ke/morgue-Wizard1ke-20240829-014929.txt
![Screenshot (1917)](https://github.com/user-attachments/assets/ca5ddebf-1975-4c70-b9a2-5b8b18fec50f)

![Screenshot (1918)](https://github.com/user-attachments/assets/8dc7d0ec-1c4d-4d52-b090-89691c0f51d6)

**Comment by AlejandorLazaro** [comment]
Looks like this may have been potentially fixed with the latest changes here: 

https://github.com/crawl/crawl/commit/92cb95d158aeed92f9f7adec82a05d66482d8205
