### ISSUE TITLE
Coglin SpellMotor is activated by actions other than casting spells

### ISSUE THREAD

**Issue by Vitna-1** [crawl/crawl#4003]
**PLATFORM and OS or BROWSER:**
macOS Sonoma 14.6.1

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.32.0 (Console)

**DESCRIPTION:**

SpellMotor activates when using some evocables next to an enemy. The description of SpellMotor, "Your spells cost less MP as you Rev up. Whenever you cast a spell, you make a melee attack against a random enemy in range.", implies it should only go off when you cast spells. I did some testing in wizmode with the evocables I could think of and here are my findings.

| Evocable  | Triggers SpellMotor |
| ------------- | ------------- |
| Staff of Olgreb  | Yes  |
| Orb of Dispater  | Yes  |
| Scarf of Invisibility  | No  |
| Blink (on artifacts)  | No  |
| Phial of Floods  | No  |
| Lightning Rod  | Yes  |
| Tin of Tremorstones | No  |
| Condenser Vane  | No  |
| Phantom Mirror  | No  |
| Horn of Geryon  | No  |
| Box of Beasts  | No  |
| Sack of Spiders  | No  |
| Figurine of a Ziggurat   | No  |
| Wand of Acid  | Yes  |
| Wand of Charming  | Yes  |
| Wand of Digging  | Yes  |
| Wand of Flame  | Yes  |
| Wand of Iceblast  | Yes  |
| Wand of Light  | Yes  |
| Wand of Mindburst  | Yes  |
| Wand of Paralysis  | Yes  |
| Wand of Polymorph  | Yes  |
| Wand of Roots  | Yes  |
| Wand of Quicksilver  | Yes  |

**EXTRA FILES:**
No extra files

**Comment by AlejandorLazaro** [comment]
Looking at the code, I think it's missing a simple check to ensure it was a spell and not a wand that triggers the effect.

```c++
// Earlier in spl-util.cc
    if (evoked_wand)
        surge_power_wand(wand_mp_cost());
    else if (actual_spell)
        surge_power(_spell_enhancement(spell));

// ...

// Right above the code without the check, Dithmenos shadow spells do check for an actual spell

// ...
        if (will_have_passive(passive_t::shadow_spells) && actual_spell)
            dithmenos_shadow_spell(spell);
        _spellcasting_side_effects(spell, god, !actual_spell);

        if (you.wearing_ego(EQ_GIZMO, SPGIZMO_SPELLMOTOR))  // <-- let's add "&& actual_spell" here
            coglin_spellmotor_attack();

        return spret::success;
    }
```

**Comment by DracoOmega** [comment]
Thanks for catching this! Should be fixed now.
