### ISSUE TITLE
Fusillade can weaken orbs of destruction

### ISSUE THREAD

**Issue by CrawlOdds** [crawl/crawl#4010]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32

**DESCRIPTION:**
When caught in two blasts of fusillade, orbs of destruction can get bad status effects like weakness

**Comment by AlejandorLazaro** [comment]
Looks like a consequence of certain "projectiles" being monsters.

I saw we steal the same logic that fixed gravitamborine affecting Orbs of Destruction in 1545d69ba7441d9da8dacb47cd3ad2747bdd7d71 and add a `&& !mons_is_projectile(*mon)` check.

**Comment by AlejandorLazaro** [comment]
And now I've got deep into the weeds and I'm now wondering if we should *ever* enchant a projectile-type monster...

If not, we can just do an early return for OOD's and the like in `apply_enchantment_to_monster` and things will "just work"™️
