### ISSUE TITLE
Game sometimes crashes when you attack with chaotic "rift" or "punk"

### ISSUE THREAD

**Issue by nimuck** [crawl/crawl#4014]
Platform: local tiles (offline)
OS: windows
DCSS version: 0.32.0

Description:
Game sometimes crashes when using “rift” or “punk” with chaos brand added, which can be obtained from Xom's bazaar trip.
Found this bug while testing unrand weapons with chaos brand added with repeated trips to xom's bazaar in wizmode.
Other unrands seem to be fine. (though unrand armors and some unrand weapons are not choas branded at all)
![chaotic_unrand_crash](https://github.com/user-attachments/assets/1de84383-30bf-47e1-964b-ae03e87e060f)

Crashlog:
[crash-nimuck-20240906-235846.txt](https://github.com/user-attachments/files/16920762/crash-nimuck-20240906-235846.txt) (punk)
[crash-nimuck-20240907-000027.txt](https://github.com/user-attachments/files/16920763/crash-nimuck-20240907-000027.txt) (rift)

Saves:
Sorry I deleted saves after testing, but maybe it's easy to replicate; just create it and attack anything :D

**Comment by regret-index** [comment]
Fixed in 9fb28c6. Thank you for reporting this bug.
