### ISSUE TITLE
Ran out of altars for temple! x3

### ISSUE THREAD

**Issue by WonderSableye** [crawl/crawl#4017]
https://crawl.akrasiac.org/rawdata/Neopolis/morgue-Neopolis-20240908-222601.txt

Started the game (on akrasiac), got this error, figured I'd just end so I could dump the seed right away

**Comment by code2828** [comment]
Possible duplicate of #3846, which itself duplicates #2810, which is solved by a very recent commit 9043e79ccf94ef3de237063b8d41ffdf65ef55ff (actually only a couple of hours before this issue is posted).
