### ISSUE TITLE
inhibited regeneration weirdness near invisible monsters 

### ISSUE THREAD

**Issue by crystalsolenoid** [crawl/crawl#4018]
**PLATFORM and OS or BROWSER:**

Webtiles

**DCSS VERSION AND GAME INFORMATION:**

0.32-a0-2226-g9043e79ccf

**DESCRIPTION:**

I have the Inhibited Regeneration mutation. No monsters appeared to be around, but the -regen status was active. Trying to rest resulted in the message "You start waiting." and no time passing. It turned out that there was an invisible monster present.

I reproduced this in trunk wizmode:
- Reduce HP or MP to less than full (it still happens at full HP)
- Give self Inhibited Regeneration
- Spawn a shadow wraith
- Check that -regen status appears, and that there is no sensed monster tile
- Press 5
- Observe the "You start resting." message and lack of turn count change

Autoexplore does not get interrupted.

I'm not sure what the intended behavior would be. Should the -regen status get applied? Should there be a more descriptive failure message?

Without the mutation, resting will proceed until the monster hurts you or gets a "sensed monster" tile.

**EXTRA FILES:**

![Screenshot from 2024-09-10 16-54-53](https://github.com/user-attachments/assets/43fb5437-6ea1-4075-b3dd-fcd10eb0cd07)

**Comment by kleiner-fisch** [comment]
I would think it should be treated similarly to Ghost Moths draining gaze. That is, you are negatively affected and get a message indicating so, without knowing the location of the monster: `You feel the presence of a monster inhibiting your regeneration.`

Regarding resting and autoexplore I would imitate the behavior from when a Ghost Moth is present.

**Comment by kleiner-fisch** [comment]
What I wrote was wrong/does not make sense, I guess. 

When you rest, and a Ghost Moths watches you, then you rest one turn, and get the message `You feel you are being watched by something`.

Still, I think as you suggested: there should be a more descriptive failure message.

**Comment by Implojin** [comment]
Thank you for the report! This should now be fixed as of b65ea80194.
