### ISSUE TITLE
Crash on Abyss 7 when entering portal leading further down.

### ISSUE THREAD

**Issue by RihaChri** [crawl/crawl#4020]
**PLATFORM and OS or BROWSER:**
Observed with firefox but seems to occur on other browsers as well for other people ( I was just the spectator. The crash happened for the playing person as well)

**DCSS VERSION AND GAME INFORMATION:**
dcss-0.32

**DESCRIPTION:**
If you are in the Abyss on level 7, when you find and enter a gate leading further down the abyss the game will crash.

**EXTRA FILES:**
Unfortunately I cannot provide the morgue file as I was just a spectator.
-->

**Comment by shadowrider38** [comment]
I believe I was the one playing this game, dunno if it's helpful but here is the morgue and a picture of the instance:
https://crawl.akrasiac.org/rawdata/ShadowRider38/morgue-ShadowRider38-20240911-102638.txt
![image](https://github.com/user-attachments/assets/8056ad62-af74-4a65-bf73-8c7da8255a83)

**Comment by regret-index** [comment]
Handled in 460ee30. Thank you two for reporting this bug.

**Comment by RihaChri** [comment]
Hello shadowrider38,

I apologyze for reporting so late. This is some kind of trash email address actually.
Thank you for providing the image and the morgue.

I saw that you also added it to the bug yourself already, thank you very much.

 

I see that the ticket is now closed anyway so whatever information the devs needed, it was seemingly enough to fix :)

 

I wish you a nice day and many more glorious victories like the one I witnessed.

 
 

Gesendet: Freitag, 13. September 2024 um 23:21 Uhr
Von: "shadowrider38" ***@***.***>
An: "crawl/crawl" ***@***.***>
Cc: "RihaChri" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [crawl/crawl] Crash on Abyss 7 when entering portal leading further down. (Issue #4020)


 

I believe I was the one playing this game, dunno if it's helpful but here is the morgue and a picture of the instance:
https://crawl.akrasiac.org/rawdata/ShadowRider38/morgue-ShadowRider38-20240911-102638.txt
image.png (view on web)
