### ISSUE TITLE
An extra nearby monster got pulled into Okawaru's Arena by duel

### ISSUE THREAD

**Issue by NormalPerson7** [crawl/crawl#4023]
0.32.0 CXC (once again, not the latest version of 0.32 as the server has not been updated beyond the release commit).

Dueled an alligator in Swamp:3 while next to two alligators and a swamp worm. Alligator appeared in Arena in normal place, swamp worm ended up in Duel adjacent to me. See attached chardump from 1 turn after entering Duel.

[Buggy duel chardump.txt](https://github.com/user-attachments/files/16984572/Buggy.duel.chardump.txt)

**Comment by NormalPerson7** [comment]
Another example of this, by screenshot. I was constricted by the jellyfish when I used Duel.
![image](https://github.com/user-attachments/assets/104cc513-9992-423e-bb6d-a93caa484b21)

**Comment by NormalPerson7** [comment]
I believe this is fixed in 2e8f5e9. From my own experience I understand how hard this bug was to pin down!

**Comment by DracoOmega** [comment]
Yes, hopefully this is fixed now.
