### ISSUE TITLE
Coglins can invent unusable gizmos

### ISSUE THREAD

**Issue by AdamPG** [crawl/crawl#4025]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32

**DESCRIPTION:**
Coglins can invent Rampage artefacts while worshipping Cheibriados. This makes the gizmo unusable. This behaviour should be made consistent with acquirement mechanics, where the item is guaranteed to be usable.

**EXTRA FILES:**
https://media.discordapp.net/attachments/317641873709596693/1284219680373866629/image.png?ex=66e5d647&is=66e484c7&hm=444f8476258582e9628fb4f93b1d51a12a9ea9c35acf103f36838b2d1309860b&=&format=webp&quality=lossless

**Comment by regret-index** [comment]
This was fixed in ad5dd90.
