### ISSUE TITLE
Frederik Servitor casts Iron shot instead of Bombard.

### ISSUE THREAD

**Issue by Broken27** [crawl/crawl#4031]
PLATFORM and OS or BROWSER:
Webtiles 0.32

Description:
Frederik changed spells from Iron shot to Bombard in 0.32, but his servitor apparently didn't - this should be changed for consistency.

Extra files:
You can see an example of this happening here:

https://cbro.berotato.org/morgue/Dazliare/morgue-Dazliare-20240909-064235.txt

" Killed from afar by a spellforged servitor (76 damage)
             ... with an iron shot
             ... summoned by Frederick"

**Comment by NormalPerson7** [comment]
The name of Bombard's projectile is, perhaps confusingly, also "an iron shot", and it is the projectile name that appears in the death message. Frederick's servitor casts Bombard.
