### ISSUE TITLE
Pointless runed door/broken vault

### ISSUE THREAD

**Issue by MIC132** [crawl/crawl#4040]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.33-a0-114-g4d60b030d2

**DESCRIPTION:**
Encountered runed door that didn't actually cut-off the vault and monsters had other ways to escape.

**EXTRA FILES:**
![Screenshot 2024-09-19 112945](https://github.com/user-attachments/assets/11856184-654d-4fee-aae7-048a4f5c1e75)

**Comment by paginaweb123** [comment]
maybe this will help
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive
