### ISSUE TITLE
Serpent Talisman disappeared, but still in serpent form

### ISSUE THREAD

**Issue by trevorhackman** [crawl/crawl#4061]
**PLATFORM and OS or BROWSER:**

I'm on browser, google chrome, using webtiles.

**DCSS VERSION AND GAME INFORMATION:**

0.32.1

**DESCRIPTION:**

I found a serpent talisman and am in serpent form. Through some combination of events, I'm not sure what, my serpent talisman has disappeared and is not shown in my inventory anymore. Nor is it shown anywhere when I Ctrl+f and search for talisman.

**EXTRA FILES:**

![chrome_1QS5pKMB5e](https://github.com/user-attachments/assets/93cff543-ca0c-46a1-813e-37a7bbb9e1ac)
![chrome_xcqDLDsjMO](https://github.com/user-attachments/assets/76d6b7ed-45a0-4c75-993a-9a65b42a0ec6)
![image](https://github.com/user-attachments/assets/b3f0c954-826e-4a91-ab53-85d35d41d4f4)

**Comment by regret-index** [comment]
Without any save or seed data or log, it's incredibly difficult to even begin to guess what happened here.

Could you have dropped the serpent talisman inside a portal? Leaving such behind (to make room for other picked-up items, for example) makes it inaccessible afterwards.

**Comment by trevorhackman** [comment]
I figured out partially what happened. Maurice the Thief stole the Serpent Talisman. Is this expected? 

I don't know why he didn't drop it after I killed him. Since I lost the Serpent Talisman I became stuck in the serpent form, which was weird, until I found and used another talisman.
