### ISSUE TITLE
Felids can escape Collapse by dying

### ISSUE THREAD

**Issue by caryoscelus** [crawl/crawl#4066]
**PLATFORM and OS or BROWSER:**
local console / nixos

**DCSS VERSION AND GAME INFORMATION:**
0.32, 0.33-a0-151-g9ec8a70d

**DESCRIPTION:**
get felid character to collapse from 0 strength, die and collapse status is gone despite strength still lacking. haven't checked other zero stat states, but i suppose they will have the same issue

**Comment by kleiner-fisch** [comment]
I can reproduce this, and will look into this.

Seems stat-zero is only checked on stat changes. 

I think on reviving stat-zero should be checked.
