### ISSUE TITLE
Makhleb description is not working

### ISSUE THREAD

**Issue by Colgateinuntap** [crawl/crawl#4068]
**PLATFORM and OS or BROWSER:**
< webtiles LibreWolf 130.0-3 >

**DCSS VERSION AND GAME INFORMATION:**
<0.33-a0-163-g6f3bd40977>

**DESCRIPTION:**
<I wanted to check Makhleb's description so I pressed ?/gm as it usually works, but this time I got what shows in screenshot instead of Makhleb's description.>

**EXTRA FILES:**
<
![makh](https://github.com/user-attachments/assets/03468510-b6a1-4730-af1a-5f936aab7ff2)
>

**Comment by NormalPerson7** [comment]
If this occurs when trying to worship Makhleb (I haven't tested) it will prevent worship, which isn't good

**Comment by Colgateinuntap** [comment]
In this game I was already worshipping Makhleb. Just wanted to check what are all of its granted abilities, since it recently got reworked and I did not necessarily remember everything right.

**Comment by NormalPerson7** [comment]
For future reference you can also use the ^ key to see info about your current god.
