### ISSUE TITLE
Unfortunately your game crashed

### ISSUE THREAD

**Issue by Colgateinuntap** [crawl/crawl#4071]
**PLATFORM and OS or BROWSER:**
<webtiles LibreWolf 130.0-3 >

**DCSS VERSION AND GAME INFORMATION:**
<0.33-a0-194-g07b0ac27cd>

**DESCRIPTION:**
<I destroyed one of those exploding enemies at Swamp, game crashed and I got message "Unfortunately your game crashed.

range check error (27000 / 702)">

**EXTRA FILES:**
<https://underhound.eu/crawl/morgue/Colgate/crash-Colgate-20241003-090035.txt >

**Comment by Colgateinuntap** [comment]
It happened again https://underhound.eu/crawl/morgue/Colgate/crash-Colgate-20241003-111417.txt

**Comment by DracoOmega** [comment]
This should already have been fixed by 30d083e yesterday, but some servers haven't caught up yet.
