### ISSUE TITLE
Google Play Android build needs updating to 0.32.1

### ISSUE THREAD

**Issue by gammafunk** [crawl/crawl#4074]
**PLATFORM and OS or BROWSER:**
Android

**DCSS VERSION AND GAME INFORMATION:**
0.32.1

**DESCRIPTION:**
The [Google Play](https://play.google.com/store/apps/details?id=org.develz.crawl) version of DCSS needs updating to [0.32.1](https://github.com/crawl/crawl/releases/tag/0.32.1), an important bugfix release.

@robertxgray can you please update this build whenever convenient? Let me know if you need anything further, and thanks very much for producing the Android build.

**Comment by robertxgray** [comment]
Sorry for the delay. I'm starting to build the new version right now.

**Comment by robertxgray** [comment]
Done. I sent updates to Google Play and Fdroid. They should be available to download very soon.

Not Android related, but I also sent an update to Flathub.
