### ISSUE TITLE
MCC Crash on Eldritch Tentacle

### ISSUE THREAD

**Issue by bobross419** [crawl/crawl#4079]
**PLATFORM and OS or BROWSER:**
Tiles: online
Browser: Safari 15.4

**DCSS VERSION AND GAME INFORMATION:**
Version: Dungeon Crawl Stone Soup 0.33-a0-218-g443864507a
Platform: unix
Bits: 64
Game mode: normal

**DESCRIPTION:**
Cast MCC when there was just a tentacle on screen.  Not even sure where it came from.  Game stuck on the blue kill flash then gave me the trash dump.

Error: ASSERT(mons.type != MONS_NO_MONSTER) in 'mon-death.cc' at line 3121 failed.

**EXTRA FILES:**
https://cbro.berotato.org/morgue/MrSquiggles/crash-MrSquiggles-20241007-131433.txt

**Comment by DracoOmega** [comment]
Should have been fixed by 1d54a0429a5dc586a8db880267bc43fe9d50139b
