### ISSUE TITLE
Confusion ranged attack wierdness

### ISSUE THREAD

**Issue by RypoFalem** [crawl/crawl#4091]
When confused, ranged attacks fire without prompt un-aimed, to a random tile. Rarely, this will result in the player hitting themself. I believe a random tile in a 13x13 grid centered on the player is picked so there's a 1/169 chance for the confused player to attack themselves. https://github.com/crawl/crawl/blob/0bf80241f61738d45f53e6ec1f28369529ea693e/crawl-ref/source/throw.cc#L622

This is very surprising because of how rare it is. Years of prior experience may teach the player that this isn't possible for confused attacks to hurt themselves. There's an asymmetry where confused melee attacks can't cause the player to attack themselves which reinforces that lesson. There's also no prompt for the action that may directly result in harm to the player which is unusual for crawl.

This comes up after particleface shot himself while confused with Sniper resulting in an unexpected large chunk of health lost. This is *very* funny but that's not a great moment to learn that this mechanic exists :P

The chance to shoot at the player tile should probably be removed. 

If it's desirable to keep that chance then the chance should probably be increased so players learn about it. Alternatively, there could be a prompt to warn the player. The prompt would rarely occur and firing at a completely random tile is probably almost always a mistake anyway so I don't think it will be bothersome.

**Comment by NormalPerson7** [comment]
Also bizarre how it picks a 13x13 grid even though LOS is (usually) 15x15.

**Comment by RypoFalem** [comment]
Also I don't mind doing some implementation and testing myself, I just want to make sure that I am working on something that is desirable first!
