### ISSUE TITLE
Gell's Gravitas?

### ISSUE THREAD

**Issue by mchen7332** [crawl/crawl#4095]
**PLATFORM and OS or BROWSER:**

**DCSS VERSION AND GAME INFORMATION:**

**DESCRIPTION:**

**EXTRA FILES:**

**Comment by NormalPerson7** [comment]
Hi, can you provide some details of the bug you're reporting?

**Comment by mchen7332** [comment]
I swore I wrote down all the details, but essentially I found a book in a shop that contained a spell called gell's gravitas. The description of the spell said to not cast it and to file a bug report.

**Comment by NormalPerson7** [comment]
This was fixed in 44df65d. Unfortunately this didn't make it into the 0.32.1 release (though it could still perhaps be ported to the `stone_soup-0.32` branch for the online servers). It will be fixed in trunk games on the online servers.

**Comment by DracoOmega** [comment]
As mentioned, this is already fixed.
