### ISSUE TITLE
permafrost eruption does not give frozen status

### ISSUE THREAD

**Issue by cfcfcfcfcfcfcfcfcfcf** [crawl/crawl#4098]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32.1-1-g848d7226f3

**DESCRIPTION:**
permafrost eruption says:
```Casting: Permafrost Eruption (dangerous; 1% risk of failure)
Press: ? - help, Q - select action, (/) - cycle
Dir - look around, f - activate
Bitter cold erupts, blasting rock from the ceiling!
The mass of rock hits Xtahua!
Xtahua is moderately wounded.
Piercing cold boils outward!
The piercing cold hits Xtahua!!! Xtahua is frozen!
Xtahua is heavily wounded.
```
but: xtahua does not have the frozen status

**EXTRA FILES:**
![image](https://github.com/user-attachments/assets/11134a0f-2488-4708-8d17-71ca4743feec)
![image](https://github.com/user-attachments/assets/f40c7a64-37f1-4b59-8ff1-86f519320910)

**Comment by NormalPerson7** [comment]
"[creature] is frozen" is the text that is displayed when a creature with cold vulnerability (i.e. rC-) is hit with cold damage. The equivalent for fire is "[creature] is burned terribly/[creature] melts".

Nevertheless, I agree that this is potentially confusing and something to look at, so thanks for the report.
