### ISSUE TITLE
Kiku's capstone gift (receive forbidden knowledge) not working as intended? 

### ISSUE THREAD

**Issue by DocSulfur** [crawl/crawl#4128]
PLATFORM and OS or BROWSER:
Webtiles, google chrome
Version: 130.0.6723.117 (64 bit)

DCSS VERSION AND GAME INFORMATION: Version: 0.33-a0-311-g6419177204
Server: CXC
Username: DocSulfur 

DESCRIPTION:
After reaching max piety with kikubaaqudgha I choose to receive the Necronomicon but I got only two spells in my library, infestation and haunt. If I'm not mistaken kiku should grant also death's door, Borgjnor revivification and rimeblight. 

EXTRA FILES:
Morgue file: https://crawl.xtahua.com/crawl/morgue/DocSulfur/DocSulfur.txt (note that this morgue was generated much later after the gift was received).

**Comment by WizardIke** [comment]
Unfortunately, vampires are "too dead" to learn death's door and Borgjnor revivification. Kiku's gift also isn't the same as the Necronomicon anymore as infestation isn't in the Necronomicon.

**Comment by DocSulfur** [comment]
I see, I thought that when being in alive status vampires could use those spells, but ultimately they are undead beings so it makes sense that those spells are unusable to them, better to close this I think. Thanks fir the reply and sorry for the blunder.
