### ISSUE TITLE
finisher does not loose a low keen

### ISSUE THREAD

**Issue by cfcfcfcfcfcfcfcfcfcf** [crawl/crawl#4140]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.32.1-4-gec8d4c38a4

**DESCRIPTION:**
"The blade looses a low keen as it cuts through the air."
however,  no sound is made:
![Screenshot 2024-11-18 8 38 35 AM](https://github.com/user-attachments/assets/5b6b9e95-b424-4e45-a9ca-cd5143bcead5)

**EXTRA FILES:**

**Comment by DracoOmega** [comment]
I don't think that description was intended to imply it makes additional mechanical noise whenever it attacks. Presumably many weapons logically make some degree of noise when swung, in the same way that footsteps on stone would also make noise (but do not and should not do so mechanically.)

I don't think anything would be improved by special-casing the weapon to generate noise when attacking empty spaces (and damaging monsters with a weapon already generates considerably more)
