### ISSUE TITLE
dcss bug report

### ISSUE THREAD

**Issue by EscapistDaydreamer** [crawl/crawl#4142]
**PLATFORM and OS or BROWSER:**
PC Windows 10

**DCSS VERSION AND GAME INFORMATION:**
0.32.1

**DESCRIPTION:**
Im playing Naga shapeshifter, when i go into beast form my barding melts into my body. But if i unequip the barding
before transforming, i can equip it while in beast form and beneficiate from the AC bonus. Idk whats intended, if you can
or if you cannot have a barding equipped while in beast form, but both are possible in current version it seems.

**EXTRA FILES:**
![bardingunmelded](https://github.com/user-attachments/assets/4c1482ae-edbf-486f-a351-ebbb14ab3bb7)
![bardingmelded](https://github.com/user-attachments/assets/c81d78da-dc56-480a-abc2-c3c5cc78b76a)

**Comment by Implojin** [comment]
This should be fixed in 7c3642a, thanks for reporting it!
