### ISSUE TITLE
Segfault when entering Trove

### ISSUE THREAD

**Issue by chikinn** [crawl/crawl#4157]
**PLATFORM and OS or BROWSER:**
console, arch linux

**DCSS VERSION AND GAME INFORMATION:**
0.32.1

**DESCRIPTION:**
I paid the entrance fee to a trove.  level was already cleared, no other entities in sight.  then `Crash caused by signal #11: Segmentation fault`

**EXTRA FILES:**
[Voniub.zip](https://github.com/user-attachments/files/18012068/Voniub.zip)
[crash-Voniub-20241204-092426.txt](https://github.com/user-attachments/files/18012069/crash-Voniub-20241204-092426.txt)

**Comment by chikinn** [comment]
![2024-12-04--1733333514_948x1033_scrot](https://github.com/user-attachments/assets/bd57f548-f1e4-4b7c-b907-a525732033af)

**Comment by heftig** [comment]
Seems to be fixed in 0.32.1-2, which would make this related to #4152.

**Comment by chikinn** [comment]
confirmed fixed.  thanks for looking!
