### ISSUE TITLE
Strange attack delay for double sword

### ISSUE THREAD

**Issue by barthasanyi** [crawl/crawl#4165]
**PLATFORM and OS or BROWSER:** 

Google Chrome on Linux, Version 130.0.6723.91 

**DCSS VERSION AND GAME INFORMATION:**

https://crawl.xtahua.com/
Dungeon Crawl Stone Soup 0.33-a0-549-g2ebf7937d9 (Console/Webtiles)

**DESCRIPTION:**

I have a character with Long blades 20, and a double sword. Despite the sword's description saying that the min. delay is 0.7 reached at skill level 16, my attack delay is still 0.8.

`This weapon's minimum attack delay (0.7) is reached at skill level 16. `
`    Your skill: 20.0`
`    Current attack delay: 0.8.`

I have attacked with it, and the game reported in the "Time" display that 0.8 aut passed. 

The attack delay seems to be fine with other weapons.

**EXTRA FILES:**
[sanka.txt](https://github.com/user-attachments/files/18063709/sanka.txt)

**Comment by DracoOmega** [comment]
This is likely due to the attack speed reduction caused by the shield you are wearing, and not any weirdness related to the weapon itself.
