### ISSUE TITLE
Trying to read armor descriptions causes an error

### ISSUE THREAD

**Issue by EggmanEpic** [crawl/crawl#4167]
**PLATFORM and OS or BROWSER:**
 Chrome Version 130.0.6723.126 

**DCSS VERSION AND GAME INFORMATION:**
 Game version 0.33-a0-554-g008097b4cb 

**DESCRIPTION:**
Viewing any armor leads to the error pictured
![image](https://github.com/user-attachments/assets/bd512e78-0d43-41f8-a3fa-719941f5e8b2)

Trying to view an armor in the lookup leads to an error that looks like this
![image](https://github.com/user-attachments/assets/50818197-8175-4d43-99ec-c90f99216ded)

**EXTRA FILES:**
 Morgue (https://cbro.berotato.org/morgue/hattop/morgue-hattop-20241211-170315.txt)

**Comment by regret-index** [comment]
Fixed by 4374b4c and 4bf1a7f.
