### ISSUE TITLE
Xom gifts Box of Beasts in a game with Sack of Spiders

### ISSUE THREAD

**Issue by ahyangyi** [crawl/crawl#4175]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
game started: 0.33-a0-565-ge59816b
transferred to: 0.33-a0-566-gaf1b155

**DESCRIPTION:**
As title.

Note that as a player I personally find this behavior somewhat in theme with Xom's random and unexpected behavior. I'd be glad to be told that this is actually working as intended.

However, the current CrawlWiki nowhere mentions this, so I suspect this is actually a bug.

**EXTRA FILES:**
(https://crawl.akrasiac.org/saves/ahyangyi2-crawl-git-af1b155deb-241214-1429.tar.bz2)

**Comment by regret-index** [comment]
Feature, not a bug. Neither the wiki nor the learndb are comprehensive or perfect recordings of in-game developer intent or game behaviour. Link back to this issue if this comes up again.

**Comment by ahyangyi** [comment]
I will edit the wiki.
