### ISSUE TITLE
black-on-black text with default options

### ISSUE THREAD

**Issue by adlerd** [crawl/crawl#469]
Version: 0.19.4-5-g38cae0c
Platform: Console, via the OS X .app release.

With the default options (blank .rc file), some text is rendered in black-on-black.

I assume this is fallout of the darkgray-on-black decision from e35ada97; however, I'm not sure the current behavior is as intended because the text becomes unreadable black-on-black **even with default values for all bright color assumptions**. As evidence for this view, when I allow my terminal to interpret "bright as bold" (without telling crawl about it), the text becomes _readable_ darkgray-on-black — presumably thanks to "best_effort_brighten_foreground". That also shows that my terminal settings have no trouble rendering darkgray-on-black so it's not a simple instance of broken color support.

No experiment I could think of disproved my notion that crawl really, truly was attempting to render black-on-black with nothing but the 'bold' bit to distinguish them, despite 'bold_brightens_foreground' being its default value of 'false'.

Screenshot without 'bright for bold' in terminal options:
![image](https://cloud.githubusercontent.com/assets/2301999/23206752/b92393a6-f8a3-11e6-9877-ebb759ca49cc.png)

Screenshot with 'bright for bold' in terminal options, and a distinct light green color as darkgray:
![image](https://cloud.githubusercontent.com/assets/2301999/23206845/0648ab4e-f8a4-11e6-9225-00aad67a8bbd.png)

Yes, there's a workaround of always choosing 'bright for bold', but presumably there's no workaround on terminals without this option.

**Comment by neilmoore** [comment]
In current trunk (which will become 0.20) the defaults have changed so that that text will be blue on black unless you change a setting in Crawl.

The options `bold_brightens_foreground` and so on are not present in 0.19.
