### ISSUE TITLE
Generate on-demand Abyss stairs next to the player, not on top of

### ISSUE THREAD

**Issue by alexjurkiewicz** [crawl/crawl#483]
When the Abyss generates stairs up or down (due to the player killing monsters) they currently generate below the player. It would probably look cooler if they generated next to the player. Bit of a risk the player would be teleported before they could use the teleport, but random Abyss teleports are not *that* common.

**Comment by rawlins** [comment]
I'm going to close this -- in some scenarios I've seen with a char that really, really needed an abyss exit to generate from kills (e.g. a qazlal char in abyss 5) stairs not under the character wouldn't have done much good because of too many monsters.
