### ISSUE TITLE
MUT_NECRO_ENHANCER has no implementation

### ISSUE THREAD

**Issue by mgdelmonte** [crawl/crawl#520]
**PLATFORM:** all
**VERSION:** current (0.20+)
**DESCRIPTION:**
Examining the code, the MUT_NECRO_ENHANCER mutation has no implementation, other than stating that the mummy is "in touch with death."  So your mummy is in touch with death, but it doesn't actually change anything in the game.

**Comment by alexjurkiewicz** [comment]
The implementation is in:
https://github.com/crawl/crawl/blob/171fa7aa94bda3722a5ee8d9362f1bd6d0299696/crawl-ref/source/player.cc#L1687

**Comment by rawlins** [comment]
alexjurkiewicz got it, closing.  There's a bunch of mutations like this that are checked indirectly somewhere in the source code but don't don't necessarily have a single specialized block of code associated with them; `git grep` can be a useful tool for finding them if you're working at the command line.

**Comment by mgdelmonte** [comment]
ugh, my bad, dunno how I missed that
