### ISSUE TITLE
beam targeting seems broken

### ISSUE THREAD

**Issue by mgdelmonte** [crawl/crawl#625]
On local tiles, v0.21.a0-366-g9170151.  Beam targeting is blocked by monsters but not by solid walls.

If a wall DOESN'T block a beam, then a monster shouldn't either.  See screenshots:

Wall doesn't block:

![right](https://user-images.githubusercontent.com/2027885/31773962-596facbc-b4b2-11e7-81b6-67e45937c5d3.png)

Monster does block:

![wrong](https://user-images.githubusercontent.com/2027885/31773967-5b8b071c-b4b2-11e7-92d8-41151ae49228.png)

Makes no sense, and makes using fireball unpredictable.

Looking through the code, the "find_ray" area seems unnecessarily overcomplicated.

**Comment by rawlins** [comment]
I'm not an expert on beam code so someone may respond with a more definitive answer, but I think if you look at the beam paths for bolt spells you'll find that this makes a lot more sense, and works in the player's favor in that case. Basically the path through the monster is the normal one, but the beam can go "around" a solid feature in a bunch of circumstances that actually allow extra targeting for bolt / single target spells.

If we were to change this to make things more consistent, at least given my read on the current behavior, what we'd have to do is drop cases where beams exceptionally go around walls, not allow the beam to go around a monster too. Right now I don't think that would be a good change overall. Having fireball / area spells obey a different set of cases than bolt / single target spells also seems problematic.

**Comment by simon1tan** [comment]
Initially, I agreed with OP but thinking more about it, if it was a cloud-based spell (and it looks like you are casting a cloud and not a beam), it should wrap around the wall. A beam would go straight. Logically, it looks like it shouldn't hit that spot but if the line of vision shows it, then you can hit it and I don't have a problem with that.

**Comment by rawlins** [comment]
I'm going to close this up; I think my earlier reasoning is still correct and no change is needed (any change that address this would either be inconsistent/a nerf for bolt spells or a nerf to fireball-like-spells).
