### ISSUE TITLE
Compilation of console fails because of missing "-ltinfo" flag

### ISSUE THREAD

**Issue by data-flux** [crawl/crawl#660]
I'm on CentOS 7 and when I try to compile the console version, it throws an error when linking ncurses.

I found that this is fixed by adding "-ltinfo" to the Makefile, as I found in [this patch for entirely different software](https://moc.daper.net/node/1469) when googling my error message.

I'm not entirely sure what the best way to implement this would be, because I think it might fail with the -ltinfo flag on systems that don't have the split into ncurses and tinfo, so I can't make a pull request.

I can simply amend my Makefile every time I update, but I thought I'd mention it here.

**Comment by rawlins** [comment]
This seems to be a CentOS specific thing, I found discussion in the dev channels from other users as well. For now I guess the recommended solution is to manually add:

    EXTRA_LIBS += -ltinfo

somewhere early in `Makefile`. Ideally we would be able to detect this and add it automatically (and we would probably accept a patch that did so) but the build process isn't tailored towards autodetecting super-specific build issues like this (e.g. no autoconf).

**Comment by rawlins** [comment]
Absent any followup from a centos contributor, I'm going to go ahead and close this -- the solution will still show up in searches and we'd still accept a PR that tried to autodetect centos and add this flag.
