### ISSUE TITLE
ctrl-q doesn't display "are you sure?" message in webtiles

### ISSUE THREAD

**Issue by mikegogulski** [crawl/crawl#662]
I've noticed this in trunk webtiles across a few commits. Pressing ^Q to quit the game should be displaying something like "are you sure?" with a box where one needs to type "yes" to actually quit. The message does not appear, but the box does, and one can quit normally provided one knows to type "yes".

**Comment by rawlins** [comment]
Could you post a screenshot by any chance, along with your browser details?  For reference, here's what it looks like in firefox, so maybe a line is somehow getting cut off?

![screenshot 2017-12-11 11 43 43](https://user-images.githubusercontent.com/6290753/33842502-b721fbd2-de68-11e7-8963-7ae36a5e4e81.png)

**Comment by mikegogulski** [comment]
My apologies, error between keyboard and chair. I created a new account to test, since I'm in the middle of a game, and the problem didn't occur. I check out my rc file, though, and found this:

msc := message_colour

# Muted - unnecessary
[...]
msc += mute:Confirm with

So it was just getting muted by this rcfile I copied from someone. False alarm.

**Comment by rawlins** [comment]
Ok, thanks for the update.  I suspect that was intended to be the following, which I see some people use:

    msc = mute:Confirm with \. or Enter, or press \? or \* to list all spells\.

**Comment by mikegogulski** [comment]
super helpful, thanks much!
