### ISSUE TITLE
weird display bug/glitches in Shoals

### ISSUE THREAD

**Issue by mikegogulski** [crawl/crawl#680]
webtiles version 0.21-a0-584-g185da8e
Chromium Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)

Exploring Shoals 3, I found a teleport trap, but didn't step on it. At that point, I could no longer see my character icon tile at all. I took a step or two, and noticed the display not rendering certain tiles at all. Likewise, I don't see the trap icon. When my allies walk in the black squares, they appear, but the background tiles do not show up. I walked around and through the black squares closest to me after this. A few of them disappeared and background tiles took their places, seemingly without cause, and the bar of black tiles to the south of me also got painted with proper tiles. To my southeast in the screenshot you can also see several tiles that are in LOS but shaded in grey for some reason. Some of these resolved due to tidal movement. The teleport trap eventually appeared, on a full-black background. Moving out and then back into LOS of the wrongly-shaded tiles caused them to render properly, but some of the black tiles remained.

Spooky!

Screenshot:
![ee](https://user-images.githubusercontent.com/118625/34241036-df5160b4-e612-11e7-82e7-bc277b4ad167.png)

Chardump: https://pastebin.com/5yxKt8YK

**Comment by mikegogulski** [comment]
Another instance, in a different game, but also in Shoals. Not entirely sure what was the action immediately before things started going weird, since I was o-tabbing madly.

Screenshot:
![ee](https://user-images.githubusercontent.com/118625/34362519-c1db9822-ea74-11e7-9d91-c5fb7f8a243e.png)

Chardump: https://pastebin.com/ChAp9bTJ

**Comment by mikegogulski** [comment]
BTW, these are on CAO.

**Comment by mikegogulski** [comment]
For the second instance, at least, leaving the level and coming back clears the glitches.

**Comment by aidanholm** [comment]
This is probably the same as https://crawl.develz.org/mantis/view.php?id=11283 --- if you manage to reproduce the issue, please try to obtain a save backup using the instructions at https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup

**Comment by mikegogulski** [comment]
Could be the same issue, certainly looks related.

Noted about save backups, and will try to keep that in mind for future reporting.

Is it preferred to open issues on Mantis rather than here?

**Comment by aidanholm** [comment]
Yes; if you do manage to get a save, it'd probably be best to post it there if you have a mantis account.

**Comment by mikegogulski** [comment]
Will do. Looks like I made an account on mantis back in 2014, so I'm all set. No Shoals in my current game, so we'll see when this recurs.

**Comment by ebering** [comment]
I wonder if this is related to 11657, fixed in a036e81 

If possible can you report if you've seen this after Jan 7 2019 on cao?

**Comment by ebering** [comment]
Seeing no further follow up I think we did indeed fix this one. Please re-open if I am wrong.
