### ISSUE TITLE
Ctrl-O window obscures UI

### ISSUE THREAD

**Issue by mikegogulski** [crawl/crawl#684]
webtiles (might be in other UIs too), trunk

Pressing Ctrl-O brings up the dungeon overview and level annotations. Unlike seemingly all other command which pop up a modal window, this one causes the rest of the UI to be hidden. This can be somewhat annoying when figuring out where one wants to go next, as things like your current XL, HP, location, etc., are not visible.

Apologies if this has been submitted before and rejected as a request.

**Comment by aidanholm** [comment]
This is a known issue: I'm currently working on an overhaul of the UI internals and this (and other similar issues) should be fixed when that's done.

**Comment by mikegogulski** [comment]
Awesome!

**Comment by aidanholm** [comment]
Fixed at b46e3d778be9; thanks for reporting!
