### ISSUE TITLE
Borgnjor's Vile Clutch does not target through allies

### ISSUE THREAD

**Issue by RBrandon** [crawl/crawl#686]
**PLATFORM:**
Webtiles

**VERSION:**
0.21-a0-641-geef9d7f

**DESCRIPTION:**
Zombie hands is smite-targeted, but does not seem to be aware of it. Trying to target normally (i.e. with z) with an ally in between the player and the target results in a 'You can't see any susceptible monsters within range! (Use Z to cast anyway.)' message, with some exceptions. These exceptions seem to occur when you could aim a fireball at the target (aiming around the ally.) in these cases the targeter is placed directly on the monster.

Using Z from behind an ally targets the monster as expected. It does not, however, account for its radius at the edge of its range when targeting.

**Comment by wheals** [comment]
I can't reproduce this; see the attached screenshot 
![image](https://user-images.githubusercontent.com/6370042/35486897-d1b92466-0442-11e8-81c7-9634f3a9b8c7.png)

**Comment by rawlins** [comment]
(This got fixed in 002c4683ae4d4c83f5412.)
