### ISSUE TITLE
Macro assignment does not escape angle brackets correctly.

### ISSUE THREAD

**Issue by G3Kappa** [crawl/crawl#687]
**PLATFORM:**
*Verified on both Tiles and Console on Windows.*

**VERSION:**
*This bug has been dormant for several versions, and I noticed it a couple versions ago. Currently on 0.21-a0-641-geef9d7f.*

**DESCRIPTION:**
*When you assign a new macro, angle brackets are not escaped correctly and end up messing with the XML tags used for colored text.*

**EXAMPLE**: https://i.imgur.com/nZxJK3R.png

**HOW TO REPRODUCE**:
Try to assign any key to the default upstairs key (`<`).

- CTRL+D
- m or M
- *any key*
- *any text that contains an opening angle bracket*

I can work on this myself, if it's not a problem. I've never contributed to this repo otherwise.

**Comment by G3Kappa** [comment]
I think that the exception should be added to [this](https://github.com/crawl/crawl/blob/806c6c2d46fd1913647813594df069373c3f9b3b/crawl-ref/source/macro.cc#L282) function or right before it gets called [here](https://github.com/crawl/crawl/blob/806c6c2d46fd1913647813594df069373c3f9b3b/crawl-ref/source/macro.cc#L993).

**Comment by aidanholm** [comment]
Fixes welcome! Relevant code is `vtostr()` in macro.cc. `replace_all(foo, "<", "<<");` should be sufficient escaping. Only some of the calls to `vtostr()` should be modified, not `vtostr()` itself.
