### ISSUE TITLE
Strange drunky movement with numpad keys (numlock on)

### ISSUE THREAD

**Issue by Fixer-007** [crawl/crawl#694]
In 0.20.x (local tiles, win7) using numpad with and without numlock had same effect - one turn walk.
In 0.21.0 when numlock is ON (it is usually), player often moves multiple turns in a sometimes strange, drunk & random way, somewhat similar to shift-walking but with random hard-to-predict movement, after attacking enemies it may perform several walks, it often skips entrances in temple, or some stuff, very hard to aim into door from the middle of the room or catch potion/scroll (i had few ridiculous moments already). When numlock off - player moves per 1 turn.

Gif demo/numlock on:
![numlock-on](https://user-images.githubusercontent.com/16494741/34803206-b136c91c-f67a-11e7-8688-47fa2c837044.gif)

Numlock off with shift walk:
![numlock-off-shift-move](https://user-images.githubusercontent.com/16494741/34803221-c5bcf4c4-f67a-11e7-9b72-426e5a2009fa.gif)

**Comment by rawlins** [comment]
Closing this as a dup of the mantis version: https://crawl.develz.org/mantis/view.php?id=11337

Thanks for the gifs though, they are helpful.

**Comment by Fixer-007** [comment]
Seems like a known bug, dupe of https://crawl.develz.org/mantis/view.php?id=11337

Feel free to close it.
