### ISSUE TITLE
Crash when blinking away a cleaving attacker

### ISSUE THREAD

**Issue by amalloy** [crawl/crawl#718]
**VERSION:**
0.22-a0-265-g0d8bc90

To reproduce: 

- Give the player a long blade of distortion, and an allied monster (eg a training dummy). 
- Give a monster an axe
- Get the monster to attack the player while cleaving onto the allied monster

Eventually, the player's riposte will trigger, activating distortion to blink away the attacker. But the attacker cleaves the allied monster anyway, even though it is no longer adjacent, and then an assertion is triggered, because a monster is attacking something it cannot reach.

Example crashlog: http://crawl.berotato.org/crawl/morgue/cellescent/crash-cellescent-20180308-020454.txt

**Comment by jnooner** [comment]
Hello there!  I believe that I may have a bug fix that prevents the occurrence of what you are reporting here.

If you pull the code from:
https://github.com/jnooner/crawl

And if you run the test on the branch:
alcon-cleave-bugfix

Based on my tests... without this fix; the bug you describe above *will* trigger.  With this fix... the bug will not trigger.

**Comment by amalloy** [comment]
Fixed by #798
