### ISSUE TITLE
Keyboard letter area not working properly on linux tiles version

### ISSUE THREAD

**Issue by q8f13** [crawl/crawl#814]
**PLATFORM:**
Gallium OS(Ubuntu 16.04 based) on a chromebook pixel 2013
Xfce4
local tiles

**VERSION:**
0.21 from package repository (instruction [here](https://crawl.develz.org/download.htm)

**DESCRIPTION:**
Letter area (a-z) not working in game.
I also found the letter keys only work when pressing left-alt key.
IME is english (Asian IME not activated)
I never touched any config file.
Only tiles version affected. ASCII version works fine.
**This happens all the time.**

**Comment by Wizp** [comment]
0.22 tiles version works fine on ubuntu 16.04 lts. Try to update.

**Comment by rawlins** [comment]
Did updating help? If not it's presumably specific to gallium or this device (which we don't have a lot of experience with).

**Comment by q8f13** [comment]
0.23.2 works fine
