### ISSUE TITLE
Potion of experience interface is broken

### ISSUE THREAD

**Issue by abstrakct** [crawl/crawl#817]
**PLATFORM:** webtiles - underground.eu - trunk/git version

**VERSION:** 0.22-a0-748-g283c1ef38e

**DESCRIPTION:**
I drank a potion of experience. Then an empty ui box (i.e. only the frame) popped up, while this happened in the message log:

> You feel more experienced!
> Training target 4.0 for Charms reached!
> Your Charms skill increases to level 4!

And I got a force more because I have a force more for skill increases, so after pressing enter the empty ui box turned into the normal popup where I could select which skills to increase. But when I marked skills, the number that showed how much a skill would increase stayed the same as what the skill currently was! So I tried to mark the skills I wanted to increase (Necromancy and Earth), and pressed enter, and got this:

> You have reached level 16!
> You feel clever.

The skills I had selected got no increase, but it looks like the skills I was training before I quaffed the pot of exp (Charms, Axes, Dodging) got increased.

**Comment by rawlins** [comment]
Sorry for the slow reply to this issue, but this was fixed in f02a5016e20, 06a55de886e39fe1d, and   ac08f70f71dc0
