### ISSUE TITLE
Windows not appearing in level map interface

### ISSUE THREAD

**Issue by maadneet** [crawl/crawl#818]
**PLATFORM:** webtiles, CAO

**VERSION:** 0.22-a0-755-g5fb6194

**DESCRIPTION:**
While in level map (after pressing `Shift-X`), after pressing `?` no window appears. Pressing keys (e.g. vi keys for movement) appears to do nothing. Trying to exit the level map from here returns movement controls to normal. Using `v` to examine from the level map does the same thing.

**Comment by rawlins** [comment]
I believe this is fixed now, not sure of a specific commit, but there were a bunch of fixes to the help popup back in Jul-Aug for related things, and it is working fine for me now. (Reopen if I'm wrong!)
