### ISSUE TITLE
LICENSE file missing from official source tarballs

### ISSUE THREAD

**Issue by akien-mga** [crawl/crawl#834]
**PLATFORM:**
Source tarball.

**VERSION:**
0.22.0-nodeps tarball: https://crawl.develz.org/release/0.22/stone_soup-0.22.0-nodeps.tar.xz

**DESCRIPTION:**
The `LICENSE` file is not included in the above-linked source tarball. It used to be in `crawl-ref/license.txt` and was included in the tarball as `docs/license.txt`, but I guess the script used to generate the tarball was not adapted after 91872347.

**Comment by rawlins** [comment]
This was fixed in  6561e4c and c95c2c7, just forgot to close it -- thanks for reporting!
