### ISSUE TITLE
Empty white map boxes on first run

### ISSUE THREAD

**Issue by vatterspun** [crawl/crawl#843]
**PLATFORM:**
Win7-32bit, under VirtualBox

**VERSION:**

**DESCRIPTION:**
1. Download Windows ZIP file
2. Launch
3. Get texture wall error message, hit escape to move past it

![2018-08-19 10_37_41-dungeon crawl stone soup 0 22 0](https://user-images.githubusercontent.com/1289134/44310647-52dad200-a39f-11e8-822c-ec17885268d3.png)

Defect: Map had odd white squares

![2018-08-19 10_59_20-dungeon crawl stone soup 0 22 0](https://user-images.githubusercontent.com/1289134/44310627-2f178c00-a39f-11e8-97bc-e5ac82fd5e0f.png)

I realize the texture error message is probably related to the white boxes issue and this might be a unfixable VirtualBox issue

**Comment by rawlins** [comment]
Yes, this is a known issue with virtualbox -- its graphics driver has an extremely low texture size limit by modern standards, and even adjusting the amount of graphics memory won't affect it; some of our textures are just too big.  I will attempt to fix this sooner or later, but it's technically a bit complicated, and at this point only impacts virtualbox specifically (for instances of this bug on non-virtual hardware, it can usually be resolved simply by updating graphics drivers, and as far as we know other VMs are ok too).

Closing this in favor of the open mantis issue: https://crawl.develz.org/mantis/view.php?id=11378

**Comment by vatterspun** [comment]
> this is a known issue with virtualbox

Understood, thanks for the reply
