### ISSUE TITLE
The spacing between the letters does not seem to match.

### ISSUE THREAD

**Issue by sesangsokuro** [crawl/crawl#885]
When reporting a bug, please include the following:

**PLATFORM:**
window local ( Not tile )
also fine.*

**VERSION:**
0.21

**DESCRIPTION:**
I changed the font to Korean to make Korean version.
The spacing between the letters does not seem to match.
The characters overlap.
Which part need to be modified so that it prints [normally?](url
![k-002](https://user-images.githubusercontent.com/6899756/47776315-7aea9800-dd35-11e8-8d7e-6cc83e16efeb.png)
)

**Comment by rawlins** [comment]
Thanks for the report; in console this may reflect some issue to do with ncurses, wide character support and windows. Can you suggest a minimal way for one of us (who aren't familiar with Korean) to replicate the problem (e.g. if you have a diff that changes the main menu text)? What specific font are you using?

**Comment by sesangsokuro** [comment]
코드상의 변화는 없습니다. 단지

make -j7  PROPORTIONAL_FONT=./nanumgothiccoding.ttf  \
MONOSPACED_FONT=./nanumgothiccoding.ttf 


There is no code change. This is just the build command.

I will attach the relevant fonts.

[fonts.zip](https://github.com/crawl/crawl/files/2545844/fonts.zip)

Fonts that may be included in the game.

Fonts include some Korean, English, and Chinese characters.

**Comment by smopucilowski** [comment]
Recommend instead to just use [Googles' Noto font](https://www.google.com/get/noto/help/cjk/) for CJK support.

**Comment by sesangsokuro** [comment]
I applied it to the Google noto font, but it's still broken

**Comment by geekosaur** [comment]
This behavior will depend on the terminal, not the crawl program. And there is no way to query the terminal to find out how it treats CJK characters; if it chooses to use two character cells, it will do so and crawl will not know and can't find out.
