### ISSUE TITLE
cant build with new function

### ISSUE THREAD

**Issue by sesangsokuro** [crawl/crawl#890]
When reporting a bug, please include the following:

**PLATFORM:**
webtiles, ubuntu 16.04

**VERSION:**
0.20

**DESCRIPTION:**

I created a new fork to make the i18n feature automatically adaptable for every update.

There are several goals here.

Since the word order may be different for each language, you must be able to change the order in which the following parameters are applied in the formatting string

In addition, the formatting string alone will tell you which sentence structure the sentence is and what the parameter points to.

I created a function that satisfies this using va_list.

It works as follows.

( the function's name is 'format'. )

  
printf( format("{01 : attacker }(은)는 {00 : monster }를 { 2 : to do }했다.\n", "코볼트", "당신", "공격") ); 
// TRANSLATE("kobold"), TRANSLATE("you"), TRANSLATE("attack")
// Meaning of Korean string
printf( format("{01 : attacker } {2 : todo }ed { 0 : to do }. \n", "kobold", "you", "attack") );

>> console output <<
당신(은)는 코볼트를 공격했다.
you attacked kobold.

This makes it possible to change the order of Korean and English to different languages ​​and change the formatting string, without changing the parameter order.

Open the i18n-format.cc file and uncomment the commented main function, and

run following command

gcc -o a.out i18n-format.h i18n-format.cc && ./a.out

You can see the console output above.

----

The problem occurred when applying the monster death message processing part under 

 if (death_message)
 
in the mon-death.cc file as follows.

2247                     mprf(MSGCH_MONSTER_DAMAGE, MDAM_DEAD,
2248                         format("당신은 {0:monster}을(를) {1:killtype}!", mons.name(DESC_PLAIN).c_str(),
2249                          exploded                        ? "터뜨렸다" :
2250                          wounded_damaged(targ_holy)      ? "박살내버렸다"
2251                                                          : "죽였다"));

I also added '#include "i18n-format.h"' at the top of the file, adding i18n-format.cc to the mon-death.d file and adding i18n-format.o or i18n-format.h . However, no compile error occurs, and a link error occurs.

---- error msg

    CXX version.o
    LINK crawl
mon-death.o:mon-death.cc:function monster_die(monster&, killer_type, int, bool, bool, bool): error: undefined reference to '_format(char*, unsigned long, ...)'
collect2: error: ld returned 1 exit status
Makefile:1473: recipe for target 'crawl' failed
make: *** [crawl] Error 1

---

For the web tile version, the build script looks like this:
If you run it without the format function, it is normally buildable and executable.

make clean && make -j7 WEBTILES=y USE_DGAMELAUNCH=y

---

I just want to add a function and apply it to the part.

I do not know why this is an error. The result of Googleing is only about using the library and not using the -l option at build time. However, I did not use the new library and I could not find similar questions.

**Comment by sesangsokuro** [comment]
https://github.com/ReviveCrawl/crawl/commit/1ab7c8bd897e42bf4f4221e872b9390aea945d4b

2018년 11월 3일 (토) 오전 5:08에 Stenella <notifications@github.com>님이 작성:

**Comment by sesangsokuro** [comment]
https://github.com/ReviveCrawl/crawl/commit/1ab7c8bd897e42bf4f4221e872b9390aea945d4b

Here

**Comment by rawlins** [comment]
Did you add `i18n-format.o` to Makefile.obj as well? I don't see it in the diff. That's where the object file list comes from, it isn't calculated automatically.

**Comment by sesangsokuro** [comment]
Thank you rawlins. 

Listen to your answer
I added i18n-format.o to the OBJECTS entry in the Makefile.obj file and built it.

https://github.com/ReviveCrawl/crawl/commit/441bbebc51477c96af6be831fb32ab93afca8460

But

error: undefined reference to '_format (char *, unsigned long, ...)'): error: undefined reference to '_format (char *, unsigned long, ...)
collect2: error: ld returned 1 exit status
Makefile: 1473: recipe for target 'crawl' failed
make: *** [crawl] Error 1


The same error occurs.

The build command is as follows

make clean && make -j7 WEBTILES = y USE_DGAMELAUNCH = y

**Comment by rawlins** [comment]
@sesangsokuro that change adds it to `GLTILES_OBJECTS`, which will only be used when building local tiles. I think you want to add it to `WEBTILES_OBJECTS`, or more likely, just `OBJECTS` on line 262.

**Comment by sesangsokuro** [comment]
I've rebuilt it the way you say.
Oh My God..
You added me to a strange place.

I thought you added it to OBJECTS, but it was not.

I added it to OBJECTS and it works normally.

Now it's time to do something else to change the formatting string.

Is it OK to close the issue in this case? I am actually the first person to write a github issue myself.


I almost missed it.

Thank you rawlins!

**Comment by rawlins** [comment]
Great, I'm glad that worked. Closing the issue now makes sense, I'll go ahead and do that.
