### ISSUE TITLE
Crash if you have a typo in Arena mode

### ISSUE THREAD

**Issue by ghost** [crawl/crawl#891]
**PLATFORM:**
Only tested it using local tiles on Windows. 

**VERSION:**
0.22.1

**DESCRIPTION:**
If you mistype something in Arena mode, it displays the message:

>Fatal error:
>Expected arena monster spec "xxx v yyy", but got "test"
>Hit any key to exit, ctrl-p for the full log.

Then exits the program, instead of going back to arena mode.

**Comment by The-Fireplace** [comment]
I've tested this on local tiles for Linux, with the same results.

**Comment by rawlins** [comment]
These issues should be fixed as of https://github.com/crawl/crawl/commit/33f6f7b652e4, which makes a number of improvements to error reporting in arena.
