### ISSUE TITLE
Shift+Left Click sometimes equips weapon instead of dropping it

### ISSUE THREAD

**Issue by The-Fireplace** [crawl/crawl#898]
When reporting a bug, please include the following:

**PLATFORM:**
Local tiles, tested on Linux

**VERSION:**
0.22.1

**DESCRIPTION:**
When you have a weapon in the inventory that you want to drop, Shift+Left Clicking it sometimes equips it instead of dropping it. I can't find any specific way to reproduce this behavior, except that when the issue starts to occur, it continues to occur until you save the game and load it again. If I do find a specific way to reproduce it, I'll comment to let you know.

**Comment by G3Kappa** [comment]
I had this happen too for at least a month if not a bit more. At first I thought that shift-dropping was removed but then, as you said, I started working again for seemingly no reason.

**Comment by dessaya** [comment]
I think the bug is affected by pressing Alt+Tab: it starts to happen after you switched windows with Alt+Tab and it is "fixed" by pressing Alt+Tab with no other open windows to switch to.

**Comment by The-Fireplace** [comment]
That's definitely a possibility, I'll try that when I get a chance and see
if that's the cause.

**Comment by rawlins** [comment]
At some point last year I spent a bunch of time trying to replicate this and didn't succeed, though it may be windows-specific (I was testing on mac). So this is basically still waiting on a means of replicating.

**Comment by The-Fireplace** [comment]
I recall trying it and being unable to find a way to consistently replicate it, but it did happen from time to time.
