### ISSUE TITLE
console: Selection no longer highlighted in species selection

### ISSUE THREAD

**Issue by medusacle** [crawl/crawl#902]
- platform: console, Ubuntu Linux 18.04, alacritty terminal, TERM=xterm-256color
- version: bisected to commit 722f094350a02f56a3ba88af34287cdf44767881

The current selection in the species selection screen is no longer highlighted, which is inconvenient !

before:
![before](https://user-images.githubusercontent.com/43048142/48659941-89d18a00-ea59-11e8-9480-2b56656ac942.png)

after:
![after](https://user-images.githubusercontent.com/43048142/48659917-031cad00-ea59-11e8-86f9-b0ae029f715d.png)

**Comment by amalloy** [comment]
Thanks for the report and for bisecting it down to a specific commit. I was able to reproduce and can confirm that reverting that commit fixes the issue. I'll talk with @rawlins to work out a fix that gets console back into shape without breaking webtiles again.

**Comment by MarvinPA** [comment]
Should be fixed in df024910cac5, thanks for reporting.
