### ISSUE TITLE
CTRL+F: "a runed scarf" Information Leak

### ISSUE THREAD

**Issue by Rydian** [crawl/crawl#933]
**PLATFORM:** webtiles (akrasiac.org)

**VERSION:** 0.23-a0-650-ga4d50d4

**DESCRIPTION:** While doing a CTRL+F to search for "rf" (was searching for fire resist sources), a runed scarf I saw in a vault shows up as one of the results.  The search result lets me know that it's a scarf of elements (opposed to one of the other egos), without having to actually identify it or even obtain it (never entered the vault).  Searching for "fire re" shows other things but not the scarf.

**SCREENSHOTS:** Shows for "rf": https://i.imgur.com/XyAam5X.png
Does not show up for "fire re": https://i.imgur.com/NB5BzZp.png

**Comment by ebering** [comment]
Stash search operates via string matching "sca**rf**" has **rf** as a substring. Since the scarf does not show up when searching for "fire re" there is no information leak.
