### ISSUE TITLE
Architectural proposal: unified methodology for effects such as holy word and torment

### ISSUE THREAD

**Issue by 1Hyena** [crawl/crawl#953]
Within the context of https://github.com/crawl/crawl/pull/941, when resolving bug 11821, I had to use duplicate code for the penance checks of the torment scroll and melee attacks with the Sceptre of Torment.

The code that needs to be duplicated for the most part is given below:

```C++
else if (weapon
         && is_unrandom_artefact(*weapon, UNRAND_TORMENT)
         && you.can_see(*defender))
{
    bool penance = false;
    bool friendly_fire = false;
    const coord_def& where = attacker->pos();

    for (radius_iterator ri(where, LOS_SOLID); ri; ++ri)
    {
        const monster_info* m = env.map_knowledge(*ri).monsterinfo();
        monster* mons = monster_at(*ri);

        if (!m || !mons || mons->res_torment())
            continue;

        if (!friendly_fire
            && mons_att_wont_attack(m->attitude)
            && !mons_is_projectile(m->type))
        {
            friendly_fire = true;
        }

        if (!penance)
        {
            string adj, suffix;
            bad_attack(mons, adj, suffix, penance, where);
        }

        if (penance && friendly_fire)
            break;
    }

    if (friendly_fire && !yesno("Some of your allies may get hurt"
                                " - continue anyway?", true, 'n'))
    {
        canned_msg(MSG_OK);
        cancel_attack = true;
        return false;
    }

    if (penance && !yesno("This action could place you under penance"
                          " - continue anyway?", false, 'n'))
    {
        canned_msg(MSG_OK);
        cancel_attack = true;
        return false;
    }
}
```

Since there are similarities between the holy word and the torment effects they should be wrapped into a unifying function that is able to handle friendly fire and penance checks.

Example code following the proposed architectural changes is given below:

```C++
else if (weapon
         && is_unrandom_artefact(*weapon, UNRAND_TORMENT)
         && you.can_see(*defender))
{
    const coord_def& where = attacker->pos();
    std::set<FX> implications = cause_effect(where, {FX::TORMENT, FX::SIM},
                                             attacker, defender);

    if (implications.count(FX::FRIENDLY_FIRE)) {
        if (!yesno("Some of your allies may get hurt"
                   " - continue anyway?", true, 'n'))
        {
            canned_msg(MSG_OK);
            cancel_attack = true;
            return false;
        }
    }

    if (implications.count(FX::PENANCE)) {
        if (!yesno("This action could place you under penance"
                   " - continue anyway?", false, 'n'))
        {
            canned_msg(MSG_OK);
            cancel_attack = true;
            return false;
        }
    }

    // If we wanted to actually cause this effect, we would call this function:
    // cause_effect(where, {FX::TORMENT}, attacker, defender);
    // Notice that flags  no longer include FX::SIM, so it's serious business.
}
```

I would do it with `enum class`, sample code below:

```C++
enum class FX {
    SIM,
    TORMENT,
    HOLY_WORD,
    PENANCE,
    FRIENDLY_FIRE
};
```

An example declaration for the `cause_effect` function is given below:

```C++
std::set<FX> cause_effect(const coord_def& where, std::set<FX> flags, actor* attacker =nullptr, actor* defender =nullptr);

// Attacker and defender default to nullptr which would indicate that there is none. For example,
// if attacker is nullptr then the effect could be something as natural as a cave-in. The defender
// parameter is questionable and could be reserved for future use-cases. Perhaps if the effect is
// targeted to a specific actor rather than a field of view.
```

With this architecture it would be trivial to combine multiple effects into one. For example we could cause holy word and torment with the same function call:

```C++
cause_effect(where, {FX::TORMENT, FX::HOLY_WORD});
```

Or in a more realistic scenario at some future time we might have natural effects that could be combined like this:

```C++
cause_effect(where, {FX::HEAVY_RAIN, FX::THUNDER, FX::EARTHQUAKE, FX::CAVE_IN}, player);
```

In case we also provided `FX::SIM` flag, the above function would just check the consequences of all the above effects without causing any real damage. This makes it trivial to bust a prompt for the player asking whether they wish to continue under a threat of potential penance or friendly fire.

That said, let me know what you think. If these improvements are acceptable then I would have no problem implementing these and posting a pull request.

**Comment by ebering** [comment]
I agree that there needs to be a refactor, but I think it would be better to use the functions `trace_los_attack_spell` and `fire_los_attack_spell` for torment and holy word, as they already exist and do this sort of thing. As a pair `trace` corresponds to `FX::SIM` and `fire` actually doing it.

**Comment by ebering** [comment]
After digging into those tracers, the `stop_attack_prompt` function already handles this unified methodology; in the referenced commit I refactored your patch to take advantage of it. Thanks for suggesting the improvement.

**Comment by 1Hyena** [comment]
@ebering ah nice you are using a lambda for that :+1: 
I agree, if you already have such framework in place then it's definitely better to utilize this
