### ISSUE TITLE
Seed stability tracking

### ISSUE THREAD

**Issue by rawlins** [crawl/crawl#981]
This issue is for tracking obscure or complicated seed stability issues that don't have an immediate fix. Please don't post other kinds of bugs here - feel free to open a new issue and reference this one, or to open a mantis issue. To add a report, give an exact version number (as much as possible), a seed, any extra conditions, and how it plays out. If you aren't able to run the stability test, or it is an issue across systems (e.g. mac vs windows), just reporting as much as you know is fine, and I will try to replicate it.

~~Seed 316313470, ver 0.24-a0-84-g25a2d9f (which is pretty much 0.23.0).~~ This involved a vault (`pandoras_box_mu`) that used `acquire`, so I think it was fixed by 60e86920ebe896.

~~Seed 840311440, version not very precisely recorded but somewhere around 0.23.0.~~ This also involved a vault (`grunt_profane_loot`) that used `acquire any`, and is fixed as of 60e86920ebe896.

**Seed 5313719195296785585**, https://crawl.develz.org/mantis/view.php?id=11884. The issue turns out to be a different double-to-int conversion that lua 5.1 uses on 32-bit non-SSE2 builds. (SpecificalIy, `layout_rooms` calls `join_the_dots` with fractional values.) have fixed this for any build that uses contribs, by requiring SSE2 (this is good for other reasons too), but it is still possible to trigger this problem on 32 bit linux builds if they use system liblua.a rather than contribs (I have replicated it in a docker container). I'm not sure what the solution is yet. It would be easy to fix this particular seed, but the scope of the problem may be larger.

~~Seed 18127138284784505733, 0.23.1 (probably a lot of seeds)~~. User rc settings to do with explore were impacting the way pathfinding in connectivity checks happened, leading to different level generation behavior. Fixed in 56e1b8fd0ee2.

**Comment by rawlins** [comment]
Example report (for something that is now fixed):

**Seed 840311440**, version not very precisely recorded but somewhere around 0.23.0: If vault_catalog.lua is run in the context of the entire `make test` suite with this seed in place of the random seed, runs diverge in depths:

```
Runs diverge for seed 840311440 on level Depths:3!
Run 1: grunt_profane_halls [grunt_profane_temple_dis, grunt_profane_temple_coc, grunt_profane_temple_tar, grunt_profane_temple_geh, grunt_profane_loot], hell_entry and pan_entry
Run 2: grunt_profane_halls [grunt_profane_temple_dis, grunt_profane_temple_coc, grunt_profane_temple_tar, grunt_profane_temple_geh, grunt_profane_loot], serial_shops, pan_entry and hell_entry
```

I was not able to replicate this when reducing the number of tests run in any way (or even the fixed seed test), suggesting there is some long-term global state not getting cleared for tests. For obvious reasons, not testable in-game. Sample travis run: https://travis-ci.org/rawlins/crawl/jobs/489291518

**Comment by Djent-** [comment]
Hi Rawlins, I was going to post this as a separate issue, but since it directly relates to your seed stability commit, I'll post it as a comment here.

When reporting a bug, please include the following:

**PLATFORM:**
ARM webtiles

**VERSION:**
https://github.com/crawl/crawl/commit/3d66cf40a65a3843061e5a6d1106f9fa5d2b0bdb

**DESCRIPTION:**
ARM g++ doesn't recognize options for x86 instruction set math [(related SO answer)](https://stackoverflow.com/questions/44967149/arm-hisiv300-linux-g-error-unrecognized-command-line-option-msse)

I use my Raspberry Pi as a local crawl server, so this is a breaking change. Count me as "coming out of the woodwork", but without a "very old device".
```
    CXX ability.o
    CXX abyss.o
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-mfpmath=sse’
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-mfpmath=sse’
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-msse2’
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-msse2’
Makefile:1575: recipe for target 'ability.o' failed
make: *** [ability.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:1575: recipe for target 'abyss.o' failed
make: *** [abyss.o] Error 1
```
Please do not use this to request features, unless you are one of Crawl's
developers.

Thanks!

**Comment by rawlins** [comment]
@Djent- Thanks for the report; I'm actually going to convert it to a separate issue.

**Comment by rawlins** [comment]
No longer using this, so I'm going to close it for now.
