### ISSUE TITLE
ARM compilation with -msse2

### ISSUE THREAD

**Issue by rawlins** [crawl/crawl#992]
_Originally posted by @Djent- in https://github.com/crawl/crawl/issues/981#issuecomment-466783649_

When reporting a bug, please include the following:

**PLATFORM:**
ARM webtiles

**VERSION:**
https://github.com/crawl/crawl/commit/3d66cf40a65a3843061e5a6d1106f9fa5d2b0bdb

**DESCRIPTION:**
ARM g++ doesn't recognize options for x86 instruction set math [(related SO answer)](https://stackoverflow.com/questions/44967149/arm-hisiv300-linux-g-error-unrecognized-command-line-option-msse)

I use my Raspberry Pi as a local crawl server, so this is a breaking change. Count me as "coming out of the woodwork", but without a "very old device".
```
    CXX ability.o
    CXX abyss.o
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-mfpmath=sse’
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-mfpmath=sse’
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-msse2’
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-msse2’
Makefile:1575: recipe for target 'ability.o' failed
make: *** [ability.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:1575: recipe for target 'abyss.o' failed
make: *** [abyss.o] Error 1
```

Thanks!

**Comment by rawlins** [comment]
@Djent- just a quick followup - how exactly are you building (what make command)? Is this via cross-compiling, or building on the Raspberry Pi?

**Comment by Djent-** [comment]
@rawlins 
```
git clone https://github.com/crawl/crawl --single-branch --depth 1 --branch master
cd crawl/crawl-ref/source
git submodule update --init
make WEBTILES=y -j 2
```
This is part of a [script](https://github.com/Djent-/Djent-.github.io/blob/master/blog/posts/resources/downloadmake-uni.sh) I made for managing my local server

**Comment by Djent-** [comment]
And I am compiling on the Pi itself, using arm-linux-gnueabihf-g++-6

**Comment by rawlins** [comment]
Our build infrastructure is not really set up to do things like detect architecture, so what I did is just add a variable you can set at the command line when calling `make`, in https://github.com/crawl/crawl/commit/fc1eed5d34c6ec5942309776f806e12eb0ccc867. Basically, replace the make command with:

    make WEBTILES=y NOSSE=y -j 2

This should be fine with the forks you are building too (they'll just ignore it unless they merge these seeding changes).

**Comment by Djent-** [comment]
Hi rawlins, it's compiling fine now with NOSSE, thanks!

**Comment by rawlins** [comment]
Ok, great, I will close this up then. Thanks for the report.
