### ISSUE TITLE
non-implied use of SSE is harmful everywhere

### ISSUE THREAD

**Issue by kilobyte** [crawl/crawl#996]
I've just had 0.23.1 fail to build everywhere except for amd64 and x32 — plus i386 where it builds when emulated on an amd64 host but fails on actual hardware.

The culprit is 3d66cf40a65a3843061e5a6d1106f9fa5d2b0bdb.  Could you please name **one** architecture where force-enabling SSE would be a fix?
 * on amd64 and x32 it's already implied by arch baseline
 * on i386 it causes a SIGILL (unless wastefully running on modern hardware, but especially with the cost of Meltdown and Spectre mitigations, that's a very bad idea)
 * on all other archs — including for example all laptops I own, and the desktop I'm typing these words on, it fails to build

**Comment by rawlins** [comment]
> Could you please name one architecture where force-enabling SSE would be a fix?

Cross-compiled win32 builds, as described in the linked commit message; see also ##crawl-dev-20190217.lg. Alternative solutions for dealing with the somewhat crazy thing lua is doing are of course welcome.

Can you please describe exactly what hardware it is failing to build on? The only previous report was ARM.

**Comment by kilobyte** [comment]
Debian's buildds ([→current state](https://buildd.debian.org/status/package.php?p=crawl&suite=unstable)) but same happens on eg. the machine I'm on right now.  All working hardware in the room with me is either armhf or arm64.

**Comment by vhk28457** [comment]
3d66cf4 had helped me to figure out the reason of different dungeon layouts generation on Windows and [unofficial Android version](https://github.com/michaelbarlow7/dungeon-crawl-android) (I know that devteam not in charge of this port nevertheless they put the link to it among other official download links).
As it is described in commit message, Android uses [generic implementation of `lua_number2int`](https://github.com/crawl/crawl-lua/blob/881acfc2d9217f122147fbb5b21b2b141c4300c3/src/luaconf.h#L580-L581). So 0.23.0 without this commit generates different layout on PC and Android starting from D2 and 0.23.1 produces the same layout on both platforms at least up to D5 (I had no time to verify it further, but it looks like everything's fine).

**Comment by kilobyte** [comment]
Yeah, it's a matter of producing a different result vs not working at all.

So let's compare the set of affected people:
 * Linux/BSD/...:
    * amd64, x32: SSE in arch baseline, all is fine with or without that commit
    * i386: may or may not crash.
      Hardware-wise:
      * Pentium 3 and earlier, AMD/whatever equivalents: must not use SSE2
      * early-mid Pentium 4, some rare early Atoms (AFAIK used only in some phones and tablets): SSE2 works
      * late Pentium 4 and everything later: strongly advised to use amd64 instead
    * any other architectures (most popular ones being arm64 and armhf): no SSE (and I guess you're not interested in talk about NEON or whatever)
 * Windows:
    * win64: the ABI really really sucks.  For this reason, a good part of programs are still built for win32
    * win32: no security support for any processors without SSE2 (WinXP and Vista EOLed, Win7 had a bug in a security update in March 2018 that Microsoft decided not to fix, dropping support)

Thus, if you lack the tuits for a proper fix, forced SSE2 on win32 would be an acceptable solution, bad anywhere else.  If using floating point can't be easily fixed or avoided, I'd propose using the generic implementation on i386 non-Windows: those on ancient hardware will have the game usable, those who use i386 on modern hardware have already decided they don't want performance.

**Comment by rawlins** [comment]
I think that what I'm going to do (which I might not have time to do immediately, but will do sometime soon) is (i) revert that commit, (ii) just fix the stupid lua issue in the contrib version of lua (since that is what is used to build win32 anyways), and (iii) introduce a test of rounding behavior so that anyone using a version with different rounding behavior sees a warning message when they start a seeded game.  Really the only case where I know there can be a seeding issue doing it this way is i386 builds that use system lua 5.1 (at some point I verified this in a 32 bit ubuntu container).

**Comment by rawlins** [comment]
Resolved in 9dfec57 and c15b636.
